KOGITO-5878 Research DataIndex Gateway API usage
apache/incubator-kie-kogito-apps pull request #1025
Opened 2021-09-19 15:49 UTC by bxf12315

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-09-26 13:31 UTC, bxf12315 commented
Jenkins retest this

2021-09-26 13:34 UTC, bxf12315 commented
Jenkins retest this

2021-10-01 04:49 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/server/server.js
> +    },
Hey Xiaofeng, I was going through the new mutation code and everything looks great!. I would do a small change in the mock server . For abort process we could directly get the mocked data from `./MockData/graphql` and then we can mutate the `state` to `'ABORTED'`. So this would change its state and when the user refreshes the page , the processes for which the Abort has been successfully performed will be removed from the 'ACTIVE' filter.
Also we can force - fail a few instances and do a `throw new Error('message')` on them to simulate some error.

here is some example code that I tried .. hope it helps

```
  const failedAbortInstances = ['8035b580-6ae4-4aa8-9ec0-e18e19809e0b2', '8035b580-6ae4-4aa8-9ec0-e18e19809e0b3']
      const data = graphData.ProcessInstanceData.filter(data => {
        return data.id === args['id'];
      });
      if (failedAbortInstances.includes(data[0].id)) {
        throw new Error('404 error - Failed to abort process Instances')
      } else {
        data[0].state = 'ABORTED';
      }
```
let me know if you need any clarification here

2021-10-11 06:23 UTC, bxf12315 commented on ui-packages/packages/management-console-webapp/server/server.js
> +    },
It's looking good, but every instance has 3 actions, "skip,retrigger,aborted", I think mutationRest.js includes all of them.

2021-10-11 06:42 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/server/server.js
> +    },
so the idea is to change the `state` in the mocked process instances, only then the table would move the 'ABORTED' process instances to the correct state. Otherwise if you abort the process instances , it would not remove these instances from `ACTIVE` or 'ERROR' state, also the bulk actions are not showing the error properly unsless we do the `throw new error`. Please let me know if it is not clear :)

2021-10-11 06:43 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/server/server.js
> +    },
you could also take a look at the previous implementation of Abort(Rest). We would modify the state of the mocked process instances ( `MockData/graphql.js` )

2021-10-14 05:43 UTC, bxf12315 commented on ui-packages/packages/management-console-webapp/server/server.js
> +    },
ok I see.

2021-10-14 06:00 UTC, bxf12315 commented on ui-packages/packages/management-console-webapp/server/server.js
> +    },
updated

2021-10-25 14:16 UTC, pefernan commented on ui-packages/packages/consoles-common/src/graphql/graphql.schema.json
> +            "name": "Hiring",
@bxf12315 I see references to the hiring example (HiringArgument, Candidate...) we should get rid of this before merging

2021-10-25 14:17 UTC, pefernan commented on ui-packages/packages/consoles-common/src/graphql/types.tsx
> +  export type Candidate = {
Same here, we should get rid of the hiring examples types

2021-10-25 14:20 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/apis/apis.tsx
> +    client
This is sweet!!

2021-10-25 14:25 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/apis/apis.tsx
> +import { ApolloClient } from 'apollo-client';
we also need this changes on the runtime-tools-webap

2021-10-25 14:39 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/apis/apis.tsx
> -  processInstance: ProcessInstance
for simplicity I'd move this logic into the ProcessListQueries class, we don't have to pass the client all the time.

2021-11-10 12:52 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/server/server.js
> +        return processInstance[0].abort;
Hey Xiaofeng, I think we still need to enhance this a bit. We should be mutating the mock graphql data directly( `kogito-apps/ui-packages/packages/management-console-webapp/server/MockData/graphql.js `) so that we really change the state to `Aborted`. Otherwise what happens is even if we abort any instance, the instance will not change the state to `Aborted` and this will lead to misleading results in the mock server.  Let me know if you need any help in this :) .

2021-11-10 12:57 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/apis/apis.tsx
> +import { ApolloClient } from 'apollo-client';
@bxf12315 please look at the apis.tsx in *runtime-tools-webap*, we may need apis and queries there too

2021-11-11 07:25 UTC, bxf12315 commented on ui-packages/packages/management-console-webapp/server/server.js
> +        return processInstance[0].abort;
"processInstance[0].state = 'ABORTED';", it's set state to aborted. and you can see the change.

2021-11-15 13:02 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/server/server.js
> +        return processInstance[0].abort;
but the state is changed in the `mutationRestData` so it does not really abort an instance in the mock server. Here is what you can do to understand it better -
1. Start management console in dev mode and try to abort a process or multiple processes  (Active instances).
2. Refresh and change the filter state to 'Aborted'
3. You can see that the process's state would not change to Aborted and they wont appear under the filter.

2021-11-15 13:48 UTC, bxf12315 commented on ui-packages/packages/management-console-webapp/server/server.js
> +        return processInstance[0].abort;
ok, we also want to change status of process instance data from graphql.js.

2021-11-15 13:50 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/server/server.js
> +        return processInstance[0].abort;
Exactly!!

2021-11-16 07:58 UTC, bxf12315 commented on ui-packages/packages/management-console-webapp/server/server.js
> +        return processInstance[0].abort;
Done

2021-11-30 20:39 UTC, pefernan requested changes
Please do some cleanup!

It seems to work fine in dev mode but I couldn't make it work properly using the docker images of data-index. I'd try to research a bit what's going on.

2021-11-30 20:39 UTC, pefernan commented on ui-packages/packages/runtime-tools-dev-ui-webapp/src/channel/ProcessList/ProcessListGatewayApi.ts
> +    alert('PrcessListgatewayapi');
we may cleanup this!

2021-11-30 20:39 UTC, pefernan commented on ui-packages/packages/runtime-tools-dev-ui-webapp/src/channel/ProcessList/ProcessListQueries.ts
> +    alert('PrcessListQueries');
this too

2021-12-07 11:05 UTC, cristianonicolai requested changes

2021-12-07 11:05 UTC, cristianonicolai commented on data-index/data-index-service/data-index-service-common/src/main/java/org/kie/kogito/index/graphql/GraphQLSchemaManager.java
> +        return dataIndexApiExecutor.updateProcessInstanceVariables(getServiceUrl(processInstance.getEndpoint(), processInstance.getProcessId()), processInstance, env.getArgument("processInstanceVaria
@bxf12315 we need to handle this on a separated JIRA for data index alone.

2021-12-07 12:37 UTC, bxf12315 commented on data-index/data-index-service/data-index-service-common/src/main/java/org/kie/kogito/index/graphql/GraphQLSchemaManager.java
> +        return dataIndexApiExecutor.updateProcessInstanceVariables(getServiceUrl(processInstance.getEndpoint(), processInstance.getProcessId()), processInstance, env.getArgument("processInstanceVaria
ok

2023-02-09 08:34 UTC, domhanak commented
Closing as stale, please reopen if relevant. Thanks!

2023-02-09 08:34 UTC, closed without merging