first commit with working LarsPath and LassoLarsIC implementations
apache/incubator-kie-kogito-apps pull request #1098
Opened 2021-11-09 10:36 UTC by RobGeada

https://issues.redhat.com/browse/FAI-660

To regularize SHAP in large-model, low-sample situations we need LARSPath and LassoLarsIC regularization
implementations. This PR implements:

* The LARSPath algorithm
* LassoLARS with Akaike/Bayesian Information Criteria

Which are all necessary for to allow our SHAP Kernel Explainer to have feature-parity with the official Python version

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-11-09 10:41 UTC, RobGeada commented
jenkins retest this please?

2021-11-09 10:54 UTC, RobGeada commented
jenkins retest this pretty please?

2021-11-10 14:10 UTC, RobGeada commented
jenkins retest this

2021-11-18 10:05 UTC, RobGeada commented
jenkins retest this please!

2021-11-19 09:54 UTC, RobGeada commented
jenkins retest this pleeeease

2021-11-19 14:11 UTC, RobGeada commented
jenkins retest this

2021-12-02 14:24 UTC, ruivieira approved these changes
@RobGeada LGTM, nice job!
I've left some minor comments.

2021-12-02 14:24 UTC, ruivieira commented on ui-packages/packages/trusty/src/components/Molecules/CounterfactualOutcomeEdit/tests/CounterfactualOutcomeEdit.test.tsx
> -import React from 'react';
@RobGeada Are the `tsx` files part of this commit?

2021-12-02 14:24 UTC, ruivieira commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LarsPath.java
> +        // initialize the data carrier that will contain all intermediate results from the algorithm
Perhaps assert `X` and `y` have compatible dimensions here and throw explanatory exception (instead of an exception inside `LarsPathDataCarrier`)

2021-12-02 14:24 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LassoLarsICTest.java
> +    RealMatrix X2 = MatrixUtils.createRealMatrix(new double[][] { { 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1. },
`RealMatrix X2 = MatrixUtils.createRealMatrix(20, 20).scalarAdd(1.0);` should have the same effect.

2021-12-02 14:24 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LassoLarsICTest.java
> +    RealVector cCorrect2 = MatrixUtils.createRealVector(new double[] { 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
In fact, something like

```java
int DIM = 20;
RealMatrix X2 = MatrixUtils.createRealMatrix(DIM, DIM).scalarAdd(1.0);
RealVector cCorrect2 MatrixUtils.createRealVector(new double[DIM])
```

2021-12-02 14:24 UTC, ruivieira commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LassoLarsIC.java
> +        RealVector criterion = mse.mapMultiply(nSamples).mapDivide(sigma2 + epsilon64).add(dof.mapMultiply(K));
Just as an FYI, I notice that the latest Least Angle reference implementation estimates the criterion by calculating the LL using an OLS fitted to the data to get the noise variance.

2021-12-02 14:35 UTC, manstis commented on ui-packages/packages/trusty/src/components/Molecules/CounterfactualOutcomeEdit/tests/CounterfactualOutcomeEdit.test.tsx
> -import React from 'react';
I hope not!

2021-12-02 14:51 UTC, ruivieira requested changes
Hi @RobGeada if you could just check the `tsx` files in this commit (being deleted). Thank you!

2021-12-06 14:44 UTC, RobGeada commented on ui-packages/packages/trusty/src/components/Molecules/CounterfactualOutcomeEdit/tests/CounterfactualOutcomeEdit.test.tsx
> -import React from 'react';
Yeah, I definitely didn't mean to touch those, don't know how that happened. Might've been something that IntelliJ did automatically, I'll sort that out.

2021-12-06 14:46 UTC, RobGeada commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LassoLarsICTest.java
> +    RealVector cCorrect2 = MatrixUtils.createRealVector(new double[] { 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
Yeah, I automatically generated these test cases from Python, didn't think about how you'd actually write them properly. Again, I'll sort it out.

2021-12-10 11:57 UTC, RobGeada commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LassoLarsIC.java
> +        RealVector criterion = mse.mapMultiply(nSamples).mapDivide(sigma2 + epsilon64).add(dof.mapMultiply(K));
Oh, thanks for flagging that. It's mark as a to-do in https://issues.redhat.com/browse/FAI-690

2021-12-13 09:17 UTC, ruivieira approved these changes
LGTM, thanks @RobGeada!

2021-12-13 11:49 UTC, manstis approved these changes

2021-12-13 11:49 UTC, merged