[DO NOT MERGE] KOGITO-7168: Create SWF Dev UI module
apache/incubator-kie-kogito-apps pull request #1364
Opened 2022-05-31 22:29 UTC by paulovmr

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] mandrel</b>

</details>

2022-06-07 08:27 UTC, pefernan commented on swf-quarkus-extension-parent/swf-quarkus-extension-deployment/src/main/java/org/kie/kogito/swf/tools/deployment/ServerlessWorkflowQuarkusExtensionProcessor.java
> +    private static final String FEATURE = "runtime-tools-quarkus-extension";
Should we use this id?

2022-06-07 08:55 UTC, pefernan requested changes
@paulovmr great! My only doubt is that if we we want to keep using the same extension name as the previous runtime tools extension?

2022-06-07 08:55 UTC, pefernan commented on swf-quarkus-extension-parent/swf-quarkus-extension/src/main/resources/META-INF/quarkus-extension.yaml
> +name: Kogito Runtime Tools
Should we use same name for both extensions¿

2022-06-07 15:02 UTC, paulovmr commented on swf-quarkus-extension-parent/swf-quarkus-extension-deployment/src/main/java/org/kie/kogito/swf/tools/deployment/ServerlessWorkflowQuarkusExtensionProcessor.java
> +    private static final String FEATURE = "runtime-tools-quarkus-extension";
Fixed!

2022-06-07 15:02 UTC, paulovmr commented on swf-quarkus-extension-parent/swf-quarkus-extension/src/main/resources/META-INF/quarkus-extension.yaml
> +name: Kogito Runtime Tools
Fixed!

2022-06-07 18:54 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#134` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/134/display/redirect

**Test results:**
- PASSED: 137
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-07T18:48:20.887Z] [INFO] <br/>[2022-06-07T18:48:20.887Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ ruleunit-springboot-example ---<br/>[2022-06-07T18:48:20.887Z] [INFO] Surefire report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/surefire-reports<br/>[2022-06-07T18:48:20.887Z] [INFO] <br/>[2022-06-07T18:48:20.887Z] [INFO] -------------------------------------------------------<br/>[2022-06-07T18:48:20.887Z] [INFO]  T E S T S<br/>[2022-06-07T18:48:20.887Z] [INFO] -------------------------------------------------------<br/>[2022-06-07T18:48:20.887Z] [INFO] Running org.kie.kogito.decisiontable.springboot.ruleunit.RestQueryTest<br/>[2022-06-07T18:48:25.758Z] 14:48:20.512 [main] INFO  o.s.t.c.s.AbstractTestContextBootstrapper.buildDefaultMergedContextConfiguration:305 - Neither @ContextConfiguration nor @ContextHierarchy found for test class [org.kie.kogito.decisiontable.springboot.ruleunit.RestQueryTest], using SpringBootContextLoader<br/>[2022-06-07T18:48:25.758Z] 14:48:20.518 [main] INFO  o.s.t.c.s.AbstractContextLoader.generateDefaultLocations:264 - Could not detect default resource locations for test class [org.kie.kogito.decisiontable.springboot.ruleunit.RestQueryTest]: no resource found for suffixes {-context.xml, Context.groovy}.<br/>[2022-06-07T18:48:25.758Z] 14:48:20.643 [main] INFO  o.s.t.c.s.AbstractTestContextBootstrapper.getDefaultTestExecutionListenerClassNames:245 - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]<br/>[2022-06-07T18:48:25.758Z] 14:48:20.653 [main] INFO  o.s.t.c.s.AbstractTestContextBootstrapper.getTestExecutionListeners:174 - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@56303b57, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@4b2a01d4, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@8692d67, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@78f5c518, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@2f48b3d2, org.springframework.test.context.support.DirtiesContextTestExecutionListener@34f7234e, org.springframework.test.context.event.EventPublishingTestExecutionListener@753432a2, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@23bff419, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@4983159f, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@44e3a2b2, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@101639ae, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@4c550889, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@1d2bd371]<br/>[2022-06-07T18:48:25.758Z] <br/>[2022-06-07T18:48:25.758Z]   .   ____          _            __ _ _<br/>[2022-06-07T18:48:25.758Z]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \<br/>[2022-06-07T18:48:25.758Z] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \<br/>[2022-06-07T18:48:25.758Z]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )<br/>[2022-06-07T18:48:25.758Z]   '  |____| .__|_| |_|_| |_\__, | / / / /<br/>[2022-06-07T18:48:25.758Z]  =========|_|==============|___/=/_/_/_/<br/>[2022-06-07T18:48:25.758Z]  :: Spring Boot ::                (v2.6.6)<br/>[2022-06-07T18:48:25.758Z] <br/>[2022-06-07T18:48:25.758Z] 14:48:20.948 [main] INFO  o.s.boot.StartupInfoLogger.logStarting:55 - Starting RestQueryTest using Java 11.0.14.1 on rhos-01-kie-psi-rhel7-xlarge-950 with PID 19802 (started by jenkins in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/kogito-springboot-examples/ruleunit-springboot-example)<br/>[2022-06-07T18:48:25.758Z] 14:48:20.950 [main] INFO  o.s.boot.SpringApplication.logStartupProfileInfo:640 - No active profile set, falling back to 1 default profile: "default"<br/>[2022-06-07T18:48:25.758Z] 14:48:22.285 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer.initialize:108 - Tomcat initialized with port(s): 0 (http)<br/>[2022-06-07T18:48:25.758Z] 14:48:22.294 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Initializing ProtocolHandler ["http-nio-0.0.0.0-auto-1"]<br/>[2022-06-07T18:48:25.758Z] 14:48:22.294 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Starting service [Tomcat]<br/>[2022-06-07T18:48:25.758Z] 14:48:22.295 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Starting Servlet engine: [Apache Tomcat/9.0.60]<br/>[2022-06-07T18:48:25.758Z] 14:48:22.387 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Initializing Spring embedded WebApplicationContext<br/>[2022-06-07T18:48:25.758Z] 14:48:22.388 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext.prepareWebApplicationContext:290 - Root WebApplicationContext: initialization completed in 1177 ms<br/>[2022-06-07T18:48:25.758Z] 14:48:24.249 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver.<init>:58 - Exposing 1 endpoint(s) beneath base path '/actuator'<br/>[2022-06-07T18:48:25.759Z] 14:48:24.447 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Starting ProtocolHandler ["http-nio-0.0.0.0-auto-1"]<br/>[2022-06-07T18:48:25.759Z] 14:48:24.463 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer.start:220 - Tomcat started on port(s): 35942 (http) with context path ''<br/>[2022-06-07T18:48:25.759Z] 14:48:24.478 [main] INFO  o.s.boot.StartupInfoLogger.logStarted:61 - Started RestQueryTest in 3.794 seconds (JVM running for 4.654)<br/>[2022-06-07T18:48:27.158Z] 14:48:25.513 [http-nio-0.0.0.0-auto-1-exec-1] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Initializing Spring DispatcherServlet 'dispatcherServlet'<br/>[2022-06-07T18:48:27.158Z] 14:48:25.514 [http-nio-0.0.0.0-auto-1-exec-1] INFO  o.s.web.servlet.FrameworkServlet.initServletBean:525 - Initializing Servlet 'dispatcherServlet'<br/>[2022-06-07T18:48:27.158Z] 14:48:25.515 [...]

2022-06-07 19:37 UTC, paulovmr commented
jenkins rerun kogito-examples

2022-06-07 20:13 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#135` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/135/display/redirect

**Test results:**
- PASSED: 2738
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/135/testReport/org.kie.kogito.taskassigning.service/SolverExecutorTest/stopWithSolverStarted/">org.kie.kogito.taskassigning.service.SolverExecutorTest.stopWithSolverStarted</a></summary>
java.util.concurrent.TimeoutException: stopWithSolverStarted() timed out after 50 seconds<br/>	at org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)<br/>	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:59)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)<br/>	S [...]

2022-06-08 10:00 UTC, pefernan approved these changes

2022-06-08 15:24 UTC, merged