[WIP]Kogito 7604 svg preview
apache/incubator-kie-kogito-apps pull request #1451
Opened 2022-09-01 07:29 UTC by AjayJagan

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] mandrel</b>

</details>

2022-09-01 08:17 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#306` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/306/display/redirect

**Test results:**
- PASSED: 1862
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-01T08:17:14.431Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-01T08:17:14.431Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-01T08:17:14.431Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-01T08:17:14.431Z] [INFO] <br/>[2022-09-01T08:17:14.431Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-01T08:17:14.431Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-01T08:17:14.431Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-01T08:17:14.431Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-01T08:17:14.431Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-01T08:17:14.431Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-01T08:17:14.431Z] [INFO] <br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.437 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.038 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.037 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.036 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.275 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.607 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.237 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.089 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.592 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.192 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 22.673 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 30.192 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 15.818 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.350 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 46.459 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.033 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.325 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.507 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.276 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.247 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.022 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:27 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:31 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:23 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:22 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:27 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.024 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.101 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.875 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 14.437 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.458 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.662 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 13.264 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.909 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.023 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 11.505 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:34 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:28 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:51 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:59 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:46 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:48 min]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 50.888 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.115 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  8.726 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.028 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.025 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.983 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.021 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.272 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 26.338 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 38.016 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.158 s]<br/>[2022-09-01T08:17:14.431Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-27 05:49 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#384` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/384/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-27T05:49:28.039Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-27T05:49:28.039Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-27T05:49:28.039Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-27T05:49:28.039Z] [INFO] <br/>[2022-09-27T05:49:28.039Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T05:49:28.039Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-27T05:49:28.039Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-27T05:49:28.039Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T05:49:28.040Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T05:49:28.040Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-27T05:49:28.040Z] [INFO] <br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.667 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.043 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.039 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.037 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.366 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.581 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.354 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.033 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  2.036 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.513 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 21.783 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 32.867 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 15.644 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.421 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 47.931 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.038 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.300 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.521 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.760 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.320 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.030 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:28 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:29 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:22 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:20 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:22 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.021 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.020 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.063 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.710 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 13.532 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.218 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [  9.987 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 12.554 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.747 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.026 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.747 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:27 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:24 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:44 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:54 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:41 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:20 min]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 55.999 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.006 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  7.691 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.019 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.018 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.916 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.029 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.233 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 24.824 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 36.765 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.191 s]<br/>[2022-09-27T05:49:28.040Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-27 07:21 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#385` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/385/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-27T07:21:14.264Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-27T07:21:14.264Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-27T07:21:14.264Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-27T07:21:14.264Z] [INFO] <br/>[2022-09-27T07:21:14.264Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T07:21:14.264Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-27T07:21:14.264Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-27T07:21:14.264Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T07:21:14.264Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T07:21:14.264Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-27T07:21:14.264Z] [INFO] <br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.755 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.042 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.042 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.041 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.441 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.884 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 15.658 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.042 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.712 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.543 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 23.634 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 34.085 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 17.258 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.609 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 48.943 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.037 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.467 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.724 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.827 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.267 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.025 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:31 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:33 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:26 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:23 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:26 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.045 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.024 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.174 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.930 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 14.232 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.378 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.136 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 13.635 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 39.476 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.026 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 10.906 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:31 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:27 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:49 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:06 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:46 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [04:38 min]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 54.324 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.025 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.193 s]<br/>[2022-09-27T07:21:14.264Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  8.118 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.022 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.021 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.957 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.023 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.234 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 25.642 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 37.888 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.189 s]<br/>[2022-09-27T07:21:14.265Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-27 08:09 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#386` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/386/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-27T08:09:37.294Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-27T08:09:37.294Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-27T08:09:37.294Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-27T08:09:37.294Z] [INFO] <br/>[2022-09-27T08:09:37.294Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T08:09:37.294Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-27T08:09:37.294Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-27T08:09:37.294Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T08:09:37.294Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-27T08:09:37.294Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-27T08:09:37.294Z] [INFO] <br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.580 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.042 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.039 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.040 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.330 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.613 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.262 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.038 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.553 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.659 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 22.408 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 31.610 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 16.018 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.217 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 46.461 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.031 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.172 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.618 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 14.860 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.271 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.025 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:27 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:30 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:23 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:20 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:24 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.022 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.113 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.815 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 13.640 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.309 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.449 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 13.185 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.514 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 10.189 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:29 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:27 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:48 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:02 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:44 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [04:22 min]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 54.417 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.050 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  7.558 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.025 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.022 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.952 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.273 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 25.311 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 40.052 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.162 s]<br/>[2022-09-27T08:09:37.294Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-27 08:20 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#381` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/381/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.6:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.ow2.asm:asm:jar:9.3:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.3:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  +- org.ow2.asm:asm-tree:jar:9.3:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  |  \- org.ow2.asm:asm-analysis:jar:9.3:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  \- org.jboss:jandex:jar:2.4.3.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  +- io.quarkus:quarkus-junit5-properties:jar:2.12.2.Final:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-09-27T08:20:12.187Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.12.2.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.12.2.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.12.2.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.1.0.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.12.2.Final:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-27T08:20:12.187Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-27T08:20:12.187Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-27T08:20:12.187Z] [INFO] <br/>[2022-09-27T08:20:12.187Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-27T08:20:12.187Z [...]

2022-09-28 17:18 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#396` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/396/display/redirect

**Test results:**
- PASSED: 205
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-28T17:17:49.895Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-28T17:17:49.895Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-28T17:17:49.895Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-28T17:17:49.895Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-28T17:17:49.895Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [95/95]<br/>[2022-09-28T17:17:49.895Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2022-09-28T17:17:49.895Z] [INFO] Number of files to be formatted: 0<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-09-28T17:17:49.895Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-09-28T17:17:49.895Z] [INFO]         Already Sorted: 0<br/>[2022-09-28T17:17:49.895Z] [INFO]         Needed Sorting: 0<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] Skipping packaging of the test-jar<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] No tests to run.<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] No tests to run.<br/>[2022-09-28T17:17:49.895Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2022-09-28T17:17:49.895Z] [INFO] <br/>[2022-09-28T17:17:49.895Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:17:49.895Z]  [...]

2022-09-28 17:20 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#397` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/397/display/redirect

**Test results:**
- PASSED: 205
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-28T17:20:12.507Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-09-28T17:20:12.507Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-28T17:20:12.508Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-28T17:20:12.508Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-28T17:20:12.508Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-28T17:20:12.508Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-28T17:20:12.508Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-28T17:20:12.508Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-28T17:20:12.508Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-28T17:20:12.508Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [95/95]<br/>[2022-09-28T17:20:12.508Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2022-09-28T17:20:12.508Z] [INFO] Number of files to be formatted: 0<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-09-28T17:20:12.508Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-09-28T17:20:12.508Z] [INFO]         Already Sorted: 0<br/>[2022-09-28T17:20:12.508Z] [INFO]         Needed Sorting: 0<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] Skipping packaging of the test-jar<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] No tests to run.<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] No tests to run.<br/>[2022-09-28T17:20:12.508Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2022-09-28T17:20:12.508Z] [INFO] <br/>[2022-09-28T17:20:12.508Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:20:12.508Z]  [...]

2022-09-28 17:30 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#399` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/399/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-28T17:30:00.490Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-28T17:30:00.490Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-28T17:30:00.490Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-28T17:30:00.490Z] [INFO] <br/>[2022-09-28T17:30:00.490Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T17:30:00.490Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-28T17:30:00.490Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-28T17:30:00.490Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T17:30:00.490Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T17:30:00.490Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-28T17:30:00.490Z] [INFO] <br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.442 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.038 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.039 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.039 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.340 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.644 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.837 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.096 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.794 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.536 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 23.245 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 32.521 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 15.903 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.600 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 48.269 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.035 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.231 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.686 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.480 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.304 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.025 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:33 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:33 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:25 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:23 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:26 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.028 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.024 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.046 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.642 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 13.858 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.353 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.254 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 13.206 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.818 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.027 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.865 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:26 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:19 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:42 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:55 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:38 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [04:19 min]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 48.973 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.024 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.181 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  7.631 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.024 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.022 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.993 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.021 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.237 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 25.479 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 36.181 s]<br/>[2022-09-28T17:30:00.490Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.153 s]<br/>[2022-09-28T17:30:00.491Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-28 17:37 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#400` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/400/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-28T17:36:46.006Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-28T17:36:46.006Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-28T17:36:46.006Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-28T17:36:46.006Z] [INFO] <br/>[2022-09-28T17:36:46.006Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T17:36:46.006Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-28T17:36:46.006Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-28T17:36:46.006Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T17:36:46.006Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T17:36:46.006Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-28T17:36:46.006Z] [INFO] <br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.507 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.046 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.040 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.039 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.397 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.612 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.736 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.042 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.810 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.880 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 22.672 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 31.891 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 16.228 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.479 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 47.390 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.032 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.426 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.741 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.661 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.264 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.024 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:30 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:32 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:24 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:23 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:24 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.023 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.060 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.662 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 14.013 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.458 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.460 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 13.249 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 38.400 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.022 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.841 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:28 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:21 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:44 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:57 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:41 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:50 min]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 49.976 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.058 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  7.389 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.021 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.022 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.164 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.227 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 25.602 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 37.586 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.187 s]<br/>[2022-09-28T17:36:46.006Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-28 17:54 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#398` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/398/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-28T17:54:17.671Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-28T17:54:17.671Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-28T17:54:17.671Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-28T17:54:17.671Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-28T17:54:17.671Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-28T17:54:17.671Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-28T17:54:17.671Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-28T17:54:17.671Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-28T17:54:17.671Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-28T17:54:17.672Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-28T17:54:17.672Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-28T17:54:17.672Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-28T17:54:17.672Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-28T17:54:17.672Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-28T17:54:17.672Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [95/95]<br/>[2022-09-28T17:54:17.672Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2022-09-28T17:54:17.672Z] [INFO] Number of files to be formatted: 0<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-09-28T17:54:17.672Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-09-28T17:54:17.672Z] [INFO]         Already Sorted: 0<br/>[2022-09-28T17:54:17.672Z] [INFO]         Needed Sorting: 0<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] Skipping packaging of the test-jar<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] No tests to run.<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] No tests to run.<br/>[2022-09-28T17:54:17.672Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2022-09-28T17:54:17.672Z] [INFO] <br/>[2022-09-28T17:54:17.672Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serverless-workflow-examples ---<br/>[2022-09-28T17:54:17.672Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullreq [...]

2022-09-28 18:07 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#401` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/401/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-28T18:07:11.726Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-28T18:07:11.726Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-28T18:07:11.726Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-28T18:07:11.726Z] [INFO] <br/>[2022-09-28T18:07:11.726Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T18:07:11.726Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-28T18:07:11.726Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-28T18:07:11.726Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T18:07:11.726Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-28T18:07:11.726Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-28T18:07:11.726Z] [INFO] <br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.529 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.043 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.040 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.040 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.430 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.750 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.640 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.040 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.620 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.563 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 22.763 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 31.902 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 16.199 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.425 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 47.627 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.036 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.169 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.702 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.251 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.283 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.023 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:29 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:32 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:23 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:21 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:24 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.027 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.024 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.099 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.703 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 13.911 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.486 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.203 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 12.999 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.435 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.028 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.707 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:25 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:23 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:44 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:54 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:39 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [04:29 min]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 50.014 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.023 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.127 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  8.398 s]<br/>[2022-09-28T18:07:11.726Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.028 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.025 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.034 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.024 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.250 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 25.757 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 37.665 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.169 s]<br/>[2022-09-28T18:07:11.727Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-30 11:16 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#413` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/413/display/redirect

**Test results:**
- PASSED: 205
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-30T11:16:11.090Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-09-30T11:16:11.090Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-30T11:16:11.090Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-30T11:16:11.090Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-30T11:16:11.090Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-30T11:16:11.090Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [95/95]<br/>[2022-09-30T11:16:11.090Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2022-09-30T11:16:11.090Z] [INFO] Number of files to be formatted: 0<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-09-30T11:16:11.090Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-09-30T11:16:11.090Z] [INFO]         Already Sorted: 0<br/>[2022-09-30T11:16:11.090Z] [INFO]         Needed Sorting: 0<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] Skipping packaging of the test-jar<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] No tests to run.<br/>[2022-09-30T11:16:11.090Z] [INFO] <br/>[2022-09-30T11:16:11.090Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:16:11.090Z] [INFO] No tests to run.<br/>[2022-09-30T11:16:11.090Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-09-30T11:16:11 [...]

2022-09-30 11:28 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#416` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/416/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-30T11:28:12.426Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-30T11:28:12.426Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-30T11:28:12.426Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-30T11:28:12.426Z] [INFO] <br/>[2022-09-30T11:28:12.426Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T11:28:12.426Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-30T11:28:12.426Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-30T11:28:12.426Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T11:28:12.426Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T11:28:12.426Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-30T11:28:12.426Z] [INFO] <br/>[2022-09-30T11:28:12.426Z] [INFO] Kogito Apps ........................................ SUCCESS [  3.005 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.041 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.038 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.043 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.326 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  4.084 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.561 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.044 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.671 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.966 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 22.163 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 33.935 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 15.939 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.569 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 49.947 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.033 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.300 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.447 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 15.039 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.263 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.023 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:32 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:32 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:24 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:25 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:25 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.033 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.050 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.633 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 14.204 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.516 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.416 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 12.893 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 40.697 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.824 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:27 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:21 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:44 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:04 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:41 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:23 min]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 56.936 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.024 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.063 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  8.288 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.022 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.985 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.259 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 24.129 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 37.593 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.162 s]<br/>[2022-09-30T11:28:12.427Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-30 11:49 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#414` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/414/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-30T11:49:45.304Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-09-30T11:49:45.304Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-09-30T11:49:45.304Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-09-30T11:49:45.305Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-30T11:49:45.305Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-30T11:49:45.305Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-30T11:49:45.305Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-30T11:49:45.305Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [95/95]<br/>[2022-09-30T11:49:45.305Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2022-09-30T11:49:45.305Z] [INFO] Number of files to be formatted: 0<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-09-30T11:49:45.305Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-09-30T11:49:45.305Z] [INFO]         Already Sorted: 0<br/>[2022-09-30T11:49:45.305Z] [INFO]         Needed Sorting: 0<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] Skipping packaging of the test-jar<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] No tests to run.<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-09-30T11:49:45.305Z] [INFO] No tests to run.<br/>[2022-09-30T11:49:45.305Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-09-30T11:49:45.305Z] [INFO] <br/>[2022-09-30T11:49:45.305Z] [INFO] --- maven-failsafe-plugin:3. [...]

2022-09-30 12:01 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#417` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/417/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-30T12:00:43.659Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-30T12:00:43.659Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-30T12:00:43.659Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-30T12:00:43.659Z] [INFO] <br/>[2022-09-30T12:00:43.659Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T12:00:43.659Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-30T12:00:43.659Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-30T12:00:43.659Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T12:00:43.659Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T12:00:43.659Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-30T12:00:43.659Z] [INFO] <br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.674 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.046 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.042 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.043 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.465 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  4.023 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 15.456 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.040 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.657 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 13.200 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 23.842 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 33.837 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 17.449 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.500 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 49.563 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.035 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.432 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.659 s]<br/>[2022-09-30T12:00:43.659Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 16.114 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.303 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.033 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:31 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:34 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:24 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:21 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:25 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.027 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  0.998 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.559 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 13.869 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.431 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 10.338 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 13.485 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.528 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.662 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:28 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:21 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:44 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:56 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:41 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:37 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:01 min]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.025 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  8.654 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.022 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.018 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.020 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.264 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 26.233 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 39.305 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.155 s]<br/>[2022-09-30T12:00:43.660Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-30 18:37 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#418` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/418/display/redirect

**Test results:**
- PASSED: 205
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-30T18:37:07.278Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-09-30T18:37:07.278Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-30T18:37:07.278Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-30T18:37:07.278Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-30T18:37:07.278Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-30T18:37:07.278Z] [INFO] <br/>[2022-09-30T18:37:07.278Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2022-09-30T18:37:07.278Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [95/95]<br/>[2022-09-30T18:37:07.278Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2022-09-30T18:37:07.278Z] [INFO] <br/>[2022-09-30T18:37:07.278Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.278Z] [INFO] <br/>[2022-09-30T18:37:07.278Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.278Z] [INFO] <br/>[2022-09-30T18:37:07.278Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.278Z] [INFO] <br/>[2022-09-30T18:37:07.278Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.278Z] [INFO] <br/>[2022-09-30T18:37:07.278Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2022-09-30T18:37:07.279Z] [INFO] Number of files to be formatted: 0<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-09-30T18:37:07.279Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-09-30T18:37:07.279Z] [INFO]         Already Sorted: 0<br/>[2022-09-30T18:37:07.279Z] [INFO]         Needed Sorting: 0<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] Skipping packaging of the test-jar<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] No tests to run.<br/>[2022-09-30T18:37:07.279Z] [INFO] <br/>[2022-09-30T18:37:07.279Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-09-30T18:37:07.279Z] [INFO] No tests to run.<br/>[2022-09-30T18:37:07.279Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-09-30T18:37:07 [...]

2022-09-30 18:51 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#421` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/421/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-30T18:50:46.742Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-30T18:50:46.742Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-30T18:50:46.742Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-30T18:50:46.742Z] [INFO] <br/>[2022-09-30T18:50:46.742Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T18:50:46.742Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-30T18:50:46.742Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-30T18:50:46.742Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T18:50:46.742Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-30T18:50:46.742Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-30T18:50:46.742Z] [INFO] <br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.672 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.046 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.045 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.050 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.380 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.934 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 15.624 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.039 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.918 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 13.565 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 24.226 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 34.782 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 17.901 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.536 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 50.325 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.036 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.669 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.789 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 16.381 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.278 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.027 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:48 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:36 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:28 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:26 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:30 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.028 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.026 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.132 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.759 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 14.802 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.553 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 11.525 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 14.159 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 43.823 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.028 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 10.413 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:31 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:32 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:52 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:13 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:45 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:36 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:00 min]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.027 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.107 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  8.549 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.023 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.038 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.112 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.221 s]<br/>[2022-09-30T18:50:46.742Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 26.448 s]<br/>[2022-09-30T18:50:46.743Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 40.300 s]<br/>[2022-09-30T18:50:46.743Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.196 s]<br/>[2022-09-30T18:50:46.743Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-10-13 16:06 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#467` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/467/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
using credential kie-ci<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.37.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision 6fad5af39091b715f785920d9bb33bb8dba10606 (origin/main)<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 6fad5af39091b715f785920d9bb33bb8dba10606 # timeout=10<br/>Commit message: "Update Jenkinsfile.tools.update-dependency-version (#654)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-13T16:05:34.011Z] Timeout set to expire in 3 hr 30 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-10-13T16:05:34.104Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-1581<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-13T16:05:36.351Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-13T16:05:36.413Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-13T16:05:36.997Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:05:37.035Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-13T16:05:37.347Z] + df -h<br/>[2022-10-13T16:05:37.347Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-13T16:05:37.347Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-13T16:05:37.347Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-13T16:05:37.347Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-13T16:05:37.347Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-13T16:05:37.347Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-13T16:05:37.347Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-13T16:05:37.369Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-13T16:05:37.654Z] + du -h -d1 /home/jenkins<br/>[2022-10-13T16:05:37.654Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-13T16:05:37.654Z] 0	/home/jenkins/go<br/>[2022-10-13T16:05:37.654Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-13T16:05:37.654Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-13T16:05:37.654Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-13T16:05:37.654Z] 8.0K	/home/jenkins/.config<br/>[2022-10-13T16:05:37.654Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-13T16:05:37.654Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-13T16:05:37.654Z] 32M	/home/jenkins/remoting<br/>[2022-10-13T16:05:37.654Z] 0	/home/jenkins/.cache<br/>[2022-10-13T16:05:37.654Z] 3.1M	/home/jenkins/workspace<br/>[2022-10-13T16:05:37.654Z] 0	/home/jenkins/.pki<br/>[2022-10-13T16:05:37.654Z] 100M	/home/jenkins/tools<br/>[2022-10-13T16:05:37.654Z] 0	/home/jenkins/caches<br/>[2022-10-13T16:05:37.654Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-13T16:05:37.676Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-13T16:05:37.958Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-13T16:05:37.958Z] 3.1M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-13T16:05:37.958Z] 3.1M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-13T16:05:37.958Z] 3.1M	/home/jenkins/workspace/KIE<br/>[2022-10-13T16:05:37.958Z] 3.1M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:05:38.285Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-13T16:05:38.528Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-13T16:05:38.816Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-13T16:05:43.012Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-13T16:05:43.012Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-13T16:05:43.012Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-13T16:05:43.012Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-13T16:05:43.012Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:05:43.012Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-13T16:05:43.012Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-13T16:05:43.012Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-13T16:05:43.012Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-13T16:05:43.012Z] npm WARN <br/>[2022-10-13T16:05:43.012Z] npm WARN Could not resolve dependency:<br/>[2022-10-13T16:05:43.012Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-13T16:05:43.012Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-13T16:05:43.012Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-13T16:05:43.012Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:05:48.266Z] <br/>[2022-10-13T16:05:48.266Z] added 111 packages, and audited 112 packages in 9s<br/>[2022-10-13T16:05:48.266Z] <br/>[2022-10-13T16:05:48.266Z] 5 packages are looking for funding<br/>[2022-10-13T16:05:48.266Z]   run `npm fund` for details<br/>[2022-10-13T16:05:48.266Z] <br/>[2022-10-13T16:05:48.266Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipel [...]

2022-10-13 16:06 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#466` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/466/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
 > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision 6fad5af39091b715f785920d9bb33bb8dba10606 (origin/main)<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 6fad5af39091b715f785920d9bb33bb8dba10606 # timeout=10<br/>Commit message: "Update Jenkinsfile.tools.update-dependency-version (#654)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-13T16:06:04.140Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-10-13T16:06:04.229Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-1582<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-13T16:06:06.472Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-13T16:06:06.554Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-13T16:06:07.074Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:07.106Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-13T16:06:07.389Z] + df -h<br/>[2022-10-13T16:06:07.389Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-13T16:06:07.389Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-13T16:06:07.389Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-13T16:06:07.389Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-13T16:06:07.389Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-13T16:06:07.389Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-13T16:06:07.389Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-13T16:06:07.410Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-13T16:06:07.692Z] + du -h -d1 /home/jenkins<br/>[2022-10-13T16:06:07.692Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-13T16:06:07.692Z] 0	/home/jenkins/go<br/>[2022-10-13T16:06:07.692Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-13T16:06:07.693Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-13T16:06:07.693Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-13T16:06:07.693Z] 8.0K	/home/jenkins/.config<br/>[2022-10-13T16:06:07.693Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-13T16:06:07.693Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-13T16:06:07.693Z] 32M	/home/jenkins/remoting<br/>[2022-10-13T16:06:07.693Z] 0	/home/jenkins/.cache<br/>[2022-10-13T16:06:07.693Z] 3.1M	/home/jenkins/workspace<br/>[2022-10-13T16:06:07.693Z] 0	/home/jenkins/.pki<br/>[2022-10-13T16:06:07.693Z] 100M	/home/jenkins/tools<br/>[2022-10-13T16:06:07.693Z] 0	/home/jenkins/caches<br/>[2022-10-13T16:06:07.693Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-13T16:06:07.715Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-13T16:06:08.000Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-13T16:06:08.000Z] 3.1M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-13T16:06:08.000Z] 3.1M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-13T16:06:08.000Z] 3.1M	/home/jenkins/workspace/KIE<br/>[2022-10-13T16:06:08.000Z] 3.1M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:08.337Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-13T16:06:08.530Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-13T16:06:08.816Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-13T16:06:09.380Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-13T16:06:09.380Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-13T16:06:09.380Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-13T16:06:09.380Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-13T16:06:09.380Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:06:09.380Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-13T16:06:09.380Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-13T16:06:09.380Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-13T16:06:09.380Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-13T16:06:09.380Z] npm WARN <br/>[2022-10-13T16:06:09.380Z] npm WARN Could not resolve dependency:<br/>[2022-10-13T16:06:09.380Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-13T16:06:09.380Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-13T16:06:09.380Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-13T16:06:09.380Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:06:12.652Z] <br/>[2022-10-13T16:06:12.652Z] added 111 packages, and audited 112 packages in 3s<br/>[2022-10-13T16:06:12.652Z] <br/>[2022-10-13T16:06:12.652Z] 5 packages are looking for funding<br/>[2022-10-13T16:06:12.652Z]   run `npm fund` for details<br/>[2022-10-13T16:06:12.652Z] <br/>[2022-10-13T16:06:12.652Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:13.061Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream<br/>[Pipeline] configFileProvider<br/>[2022-10-13T16:06:13.076Z] provisioning config files...<br/>[2022-10-13T16:06:13.085Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples@tmp/config7822 [...]

2022-10-13 16:07 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#467` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/467/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-13T16:06:35.482Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.37.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 6fad5af39091b715f785920d9bb33bb8dba10606 # timeout=10<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-13T16:06:36.105Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-13T16:06:36.132Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-13T16:06:36.554Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:36.588Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-13T16:06:36.870Z] + df -h<br/>[2022-10-13T16:06:36.870Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-13T16:06:36.870Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-13T16:06:36.871Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-13T16:06:36.871Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-13T16:06:36.871Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-13T16:06:36.871Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-13T16:06:36.871Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-13T16:06:36.894Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-13T16:06:37.173Z] + du -h -d1 /home/jenkins<br/>[2022-10-13T16:06:37.174Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-13T16:06:37.174Z] 0	/home/jenkins/go<br/>[2022-10-13T16:06:37.174Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-13T16:06:37.174Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-13T16:06:37.174Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-13T16:06:37.174Z] 8.0K	/home/jenkins/.config<br/>[2022-10-13T16:06:37.174Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-13T16:06:37.174Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-13T16:06:37.174Z] 32M	/home/jenkins/remoting<br/>[2022-10-13T16:06:37.174Z] 0	/home/jenkins/.cache<br/>[2022-10-13T16:06:37.174Z] 3.1M	/home/jenkins/workspace<br/>[2022-10-13T16:06:37.174Z] 0	/home/jenkins/.pki<br/>[2022-10-13T16:06:37.174Z] 139M	/home/jenkins/tools<br/>[2022-10-13T16:06:37.174Z] 0	/home/jenkins/caches<br/>[2022-10-13T16:06:37.174Z] 27M	/home/jenkins/.npm<br/>[2022-10-13T16:06:37.174Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-13T16:06:37.193Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-13T16:06:37.474Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-13T16:06:37.475Z] 3.1M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-13T16:06:37.475Z] 3.1M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-13T16:06:37.475Z] 3.1M	/home/jenkins/workspace/KIE<br/>[2022-10-13T16:06:37.475Z] 3.1M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:37.791Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-13T16:06:37.893Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-13T16:06:38.177Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-13T16:06:38.744Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-13T16:06:38.744Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-13T16:06:38.744Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-13T16:06:38.744Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-13T16:06:38.744Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:06:38.744Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-13T16:06:38.744Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-13T16:06:38.744Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-13T16:06:38.744Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-13T16:06:38.744Z] npm WARN <br/>[2022-10-13T16:06:38.744Z] npm WARN Could not resolve dependency:<br/>[2022-10-13T16:06:38.744Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-13T16:06:38.744Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-13T16:06:38.744Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-13T16:06:38.744Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:06:40.107Z] <br/>[2022-10-13T16:06:40.107Z] changed 111 packages, and audited 112 packages in 2s<br/>[2022-10-13T16:06:40.107Z] <br/>[2022-10-13T16:06:40.107Z] 5 packages are looking for funding<br/>[2022-10-13T16:06:40.107Z]   run `npm fund` for details<br/>[2022-10-13T16:06:40.107Z] <br/>[2022-10-13T16:06:40.107Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:40.510Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream<br/>[Pipeline] configFileProvider<br/>[2022-10-13T16:06:40.527Z] provisioning config files...<br/>[2022-10-13T16:06:40.531Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/ [...]

2022-10-13 16:07 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#468` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/468/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
using credential kie-ci<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.37.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision 6fad5af39091b715f785920d9bb33bb8dba10606 (origin/main)<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 6fad5af39091b715f785920d9bb33bb8dba10606 # timeout=10<br/>Commit message: "Update Jenkinsfile.tools.update-dependency-version (#654)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-13T16:06:34.298Z] Timeout set to expire in 3 hr 30 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-10-13T16:06:34.383Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-1583<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-13T16:06:36.506Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-13T16:06:36.573Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-13T16:06:37.087Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:37.119Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-13T16:06:37.400Z] + df -h<br/>[2022-10-13T16:06:37.401Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-13T16:06:37.401Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-13T16:06:37.401Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-13T16:06:37.401Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-13T16:06:37.401Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-13T16:06:37.401Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-13T16:06:37.401Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-13T16:06:37.421Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-13T16:06:37.704Z] + du -h -d1 /home/jenkins<br/>[2022-10-13T16:06:37.704Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-13T16:06:37.704Z] 0	/home/jenkins/go<br/>[2022-10-13T16:06:37.704Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-13T16:06:37.704Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-13T16:06:37.704Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-13T16:06:37.704Z] 8.0K	/home/jenkins/.config<br/>[2022-10-13T16:06:37.704Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-13T16:06:37.704Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-13T16:06:37.704Z] 32M	/home/jenkins/remoting<br/>[2022-10-13T16:06:37.704Z] 0	/home/jenkins/.cache<br/>[2022-10-13T16:06:37.704Z] 3.1M	/home/jenkins/workspace<br/>[2022-10-13T16:06:37.704Z] 0	/home/jenkins/.pki<br/>[2022-10-13T16:06:37.704Z] 100M	/home/jenkins/tools<br/>[2022-10-13T16:06:37.704Z] 0	/home/jenkins/caches<br/>[2022-10-13T16:06:37.704Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-13T16:06:37.725Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-13T16:06:38.008Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-13T16:06:38.009Z] 3.1M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-13T16:06:38.009Z] 3.1M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-13T16:06:38.009Z] 3.1M	/home/jenkins/workspace/KIE<br/>[2022-10-13T16:06:38.009Z] 3.1M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-13T16:06:38.326Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-13T16:06:38.423Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-13T16:06:38.712Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-13T16:06:39.640Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-13T16:06:39.640Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-13T16:06:39.640Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-13T16:06:39.640Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-13T16:06:39.640Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:06:39.640Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-13T16:06:39.640Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-13T16:06:39.640Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-13T16:06:39.640Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-13T16:06:39.640Z] npm WARN <br/>[2022-10-13T16:06:39.640Z] npm WARN Could not resolve dependency:<br/>[2022-10-13T16:06:39.640Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-13T16:06:39.640Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-13T16:06:39.640Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-13T16:06:39.640Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-13T16:06:42.156Z] <br/>[2022-10-13T16:06:42.156Z] added 111 packages, and audited 112 packages in 3s<br/>[2022-10-13T16:06:42.156Z] <br/>[2022-10-13T16:06:42.156Z] 5 packages are looking for funding<br/>[2022-10-13T16:06:42.156Z]   run `npm fund` for details<br/>[2022-10-13T16:06:42.156Z] <br/>[2022-10-13T16:06:42.156Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipel [...]

2022-10-13 17:40 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#469` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/469/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-13T17:30:58.307Z] [INFO] |     |  |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     |  \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     |     \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- org.drools:drools-drl-quarkus-util-deployment:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- org.kie:kie-memory-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  \- org.drools:drools-util:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- org.kie:kie-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-drl-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-drl-extensions:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-wiring-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  |  \- org.drools:drools-wiring-static:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-drl-ast:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-kiesession:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.drools:drools-ecj:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.kie:kie-internal:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.kie:kie-util-xml:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  +- org.kie:kie-util-maven-support:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  +- org.drools:drools-ruleunits-impl:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- org.drools:drools-model-codegen:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- org.drools:drools-model-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     |  \- org.drools:drools-canonical-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     +- org.drools:drools-mvel-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |     \- org.drools:drools-mvel-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- io.cloudevents:cloudevents-core:jar:2.3.0:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- io.quarkus:quarkus-resteasy-reactive-spi-deployment:jar:2.13.2.Final:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- io.quarkus:quarkus-vertx-http-deployment-spi:jar:2.13.2.Final:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- org.drools:drools-io:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |     \- org.assertj:assertj-core:jar:3.22.0:test<br/>[2022-10-13T17:30:58.307Z] [INFO] +- io.quarkus:quarkus-undertow-deployment:jar:2.13.2.Final:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  +- io.quarkus.http:quarkus-http-servlet:jar:4.1.9:compile<br/>[2022-10-13T17:30:58.307Z] [INFO] |  |  \- io.quarkus.http:quarkus-http-core:jar:4.1.9:compile<br/>[2022 [...]

2022-10-14 06:35 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#471` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/471/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-14T06:25:24.021Z] [INFO] |     |  |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-10-14T06:25:24.021Z] [INFO] |     |  \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-10-14T06:25:24.021Z] [INFO] |     |     \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-10-14T06:25:24.021Z] [INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-10-14T06:25:24.021Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- org.drools:drools-drl-quarkus-util-deployment:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- org.kie:kie-memory-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  \- org.drools:drools-util:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- org.kie:kie-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-drl-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-drl-extensions:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-wiring-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  |  \- org.drools:drools-wiring-static:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-drl-ast:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-kiesession:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.drools:drools-ecj:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.kie:kie-internal:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.kie:kie-util-xml:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  +- org.kie:kie-util-maven-support:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  +- org.drools:drools-ruleunits-impl:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- org.drools:drools-model-codegen:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- org.drools:drools-model-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     |  \- org.drools:drools-canonical-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     +- org.drools:drools-mvel-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |     \- org.drools:drools-mvel-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- io.cloudevents:cloudevents-core:jar:2.3.0:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- io.quarkus:quarkus-resteasy-reactive-spi-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- io.quarkus:quarkus-vertx-http-deployment-spi:jar:2.13.2.Final:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- org.drools:drools-io:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |     \- org.assertj:assertj-core:jar:3.22.0:test<br/>[2022-10-14T06:25:24.022Z] [INFO] +- io.quarkus:quarkus-undertow-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  +- io.quarkus.http:quarkus-http-servlet:jar:4.1.9:compile<br/>[2022-10-14T06:25:24.022Z] [INFO] |  |  \- io.quarkus.http:quarkus-http-core:jar:4.1.9:compile<br/>[2022 [...]

2022-10-14 06:37 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#473` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/473/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-14T06:27:19.151Z] [INFO] |     |  |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |     |  \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |     |     \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  +- org.drools:drools-drl-quarkus-util-deployment:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- org.kie:kie-memory-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  \- org.drools:drools-util:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     +- org.kie:kie-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-drl-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-drl-extensions:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-wiring-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  |  \- org.drools:drools-wiring-static:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-drl-ast:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-kiesession:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.drools:drools-ecj:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.kie:kie-internal:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.kie:kie-util-xml:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  +- org.kie:kie-util-maven-support:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  +- org.drools:drools-ruleunits-impl:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.151Z] [INFO] |  |  \- org.drools:drools-model-codegen:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |     +- org.drools:drools-model-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |     |  \- org.drools:drools-canonical-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |     +- org.drools:drools-mvel-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |     \- org.drools:drools-mvel-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |  \- io.cloudevents:cloudevents-core:jar:2.3.0:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  +- io.quarkus:quarkus-resteasy-reactive-spi-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |  \- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  +- io.quarkus:quarkus-vertx-http-deployment-spi:jar:2.13.2.Final:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |  \- org.drools:drools-io:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |  \- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |     \- org.assertj:assertj-core:jar:3.22.0:test<br/>[2022-10-14T06:27:19.152Z] [INFO] +- io.quarkus:quarkus-undertow-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  +- io.quarkus.http:quarkus-http-servlet:jar:4.1.9:compile<br/>[2022-10-14T06:27:19.152Z] [INFO] |  |  \- io.quarkus.http:quarkus-http-core:jar:4.1.9:compile<br/>[2022 [...]

2022-10-14 06:39 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#472` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/472/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-14T06:28:33.056Z] [INFO] |     |  |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |     |  \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |     |     \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  +- org.drools:drools-drl-quarkus-util-deployment:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- org.kie:kie-memory-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  \- org.drools:drools-util:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     +- org.kie:kie-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-drl-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-drl-extensions:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-wiring-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  |  \- org.drools:drools-wiring-static:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-drl-ast:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-kiesession:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.drools:drools-ecj:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.kie:kie-internal:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.kie:kie-util-xml:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  +- org.kie:kie-util-maven-support:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  +- org.drools:drools-ruleunits-impl:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |  \- org.drools:drools-model-codegen:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.056Z] [INFO] |  |     +- org.drools:drools-model-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |     |  \- org.drools:drools-canonical-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |     +- org.drools:drools-mvel-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |     \- org.drools:drools-mvel-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |  \- io.cloudevents:cloudevents-core:jar:2.3.0:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  +- io.quarkus:quarkus-resteasy-reactive-spi-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |  \- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  +- io.quarkus:quarkus-vertx-http-deployment-spi:jar:2.13.2.Final:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |  \- org.drools:drools-io:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |  \- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |     \- org.assertj:assertj-core:jar:3.22.0:test<br/>[2022-10-14T06:28:33.057Z] [INFO] +- io.quarkus:quarkus-undertow-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  +- io.quarkus.http:quarkus-http-servlet:jar:4.1.9:compile<br/>[2022-10-14T06:28:33.057Z] [INFO] |  |  \- io.quarkus.http:quarkus-http-core:jar:4.1.9:compile<br/>[2022 [...]

2022-10-14 07:36 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#474` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/474/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-14T07:26:36.874Z] [INFO] |     |  |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     |  \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     |     \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- org.drools:drools-drl-quarkus-util-deployment:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- org.kie:kie-memory-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  \- org.drools:drools-util:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- org.kie:kie-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-drl-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-drl-extensions:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-wiring-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  |  \- org.drools:drools-wiring-static:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-drl-ast:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-kiesession:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.drools:drools-ecj:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.kie:kie-internal:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.kie:kie-util-xml:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  +- org.kie:kie-util-maven-support:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  +- org.drools:drools-ruleunits-impl:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- org.drools:drools-model-codegen:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- org.drools:drools-model-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     |  \- org.drools:drools-canonical-model:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     +- org.drools:drools-mvel-parser:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |     \- org.drools:drools-mvel-compiler:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- io.cloudevents:cloudevents-core:jar:2.3.0:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- io.quarkus:quarkus-resteasy-reactive-spi-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- io.quarkus:quarkus-vertx-http-deployment-spi:jar:2.13.2.Final:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- org.drools:drools-io:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.30.0-SNAPSHOT:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |     \- org.assertj:assertj-core:jar:3.22.0:test<br/>[2022-10-14T07:26:36.874Z] [INFO] +- io.quarkus:quarkus-undertow-deployment:jar:2.13.2.Final:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  +- io.quarkus.http:quarkus-http-servlet:jar:4.1.9:compile<br/>[2022-10-14T07:26:36.874Z] [INFO] |  |  \- io.quarkus.http:quarkus-http-core:jar:4.1.9:compile<br/>[2022 [...]

2022-10-17 09:39 UTC, pefernan requested changes
@AjayJagan great work again! There's a missing header on a file but that should have an easy fix.

I noticed that the monaco editor doesn't show the syntax highlighting, so I'm afraid that the combined editor is missing some config related to the language service... @paulovmr wdyt?

2022-10-17 09:39 UTC, pefernan commented on ui-packages/packages/consoles-common/src/graphql/types.tsx
> -/*
missing licencse

2022-10-18 14:06 UTC, AjayJagan commented on ui-packages/packages/consoles-common/src/graphql/types.tsx
> -/*
added the headers. Fixed the syntax highlighting issue as well :)

2022-10-18 15:03 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#481` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/481/display/redirect

**Test results:**
- PASSED: 251
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/481/testReport/org.kie.kogito.examples.hr/DepartmentTest/testDepartmentUK/">org.kie.kogito.examples.hr.DepartmentTest.testDepartmentUK</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:hr::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:714)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:785)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)<br/>	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)<br/>	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatform [...]

2022-10-19 04:59 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#482` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/482/display/redirect

**Test results:**
- PASSED: 229
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/482/testReport/org.kie.kogito.examples.hr/DepartmentTest/testDepartmentUK/">org.kie.kogito.examples.hr.DepartmentTest.testDepartmentUK</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:hr::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:714)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:785)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)<br/>	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)<br/>	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatform [...]

2022-10-19 06:35 UTC, AjayJagan commented
Jenkins rerun kogito-examples tests

2022-10-19 07:39 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#483` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/483/display/redirect

**Test results:**
- PASSED: 251
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/483/testReport/org.kie.kogito.examples.hr/DepartmentTest/testDepartmentUK/">org.kie.kogito.examples.hr.DepartmentTest.testDepartmentUK</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:hr::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:714)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:785)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)<br/>	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)<br/>	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatform [...]

2022-10-19 14:19 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#486` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/486/display/redirect

**Test results:**
- PASSED: 238
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/486/testReport/org.kie.kogito.examples.hr/DepartmentTest/testDepartmentUK/">org.kie.kogito.examples.hr.DepartmentTest.testDepartmentUK</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:hr::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:714)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:785)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)<br/>	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)<br/>	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatform [...]

2022-10-20 14:47 UTC, paulovmr commented
Jenkins run kogito-examples tests

2022-10-20 14:50 UTC, jstastny-cz commented on ui-packages/yarn.lock
> -"@kogito-tooling/envelope-bus@0.11.0":
Some of kogito-tooling deps stayed here (not replaced by kie-tools scoped packages), could you verify why is that?

2022-10-20 15:09 UTC, AjayJagan commented on ui-packages/yarn.lock
> -"@kogito-tooling/envelope-bus@0.11.0":
I think trusty uses ` "@kogito-tooling/kie-editors-standalone": "^0.10.0"` , as a result those deps are still present.

2022-10-20 15:22 UTC, pefernan commented on ui-packages/yarn.lock
> -"@kogito-tooling/envelope-bus@0.11.0":
@jstastny-cz well checking `package.json` files look we still depend on the old `@kogito-tooling` stuff. I think we could schedule a module upgrade at some point.

2022-10-20 15:25 UTC, pefernan commented on ui-packages/yarn.lock
> -"@kogito-tooling/envelope-bus@0.11.0":
@paulovmr ^

2022-10-20 15:43 UTC, pefernan approved these changes

2022-10-20 16:30 UTC, paulovmr commented on ui-packages/yarn.lock
> -"@kogito-tooling/envelope-bus@0.11.0":
Yeah it is probably because trusty has some old dependencies.

2022-10-20 16:30 UTC, paulovmr approved these changes

2022-10-25 05:41 UTC, jstastny-cz approved these changes

2022-10-25 12:42 UTC, merged