KOGITO-7605: [SWF Dev UI] Allow workflows to be started based on form schema
apache/incubator-kie-kogito-apps pull request #1458
Opened 2022-09-12 18:05 UTC by AjayJagan

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] mandrel</b>

</details>

2022-09-13 06:30 UTC, jstastny-cz commented
It seems coverage reporting is fixed after #1457 , please see if you can improve test coverage of these changes in here.

2022-09-14 05:56 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#351` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/351/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-14T05:56:16.194Z] [INFO] Total time:  0.055 s<br/>[2022-09-14T05:56:16.194Z] [INFO] Finished at: 2022-09-14T01:56:15-04:00<br/>[2022-09-14T05:56:16.194Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-14T05:56:16.194Z] [WARNING] The requested profile "sonarcloud-analysis" could not be activated because it does not exist.<br/>[2022-09-14T05:56:16.194Z] [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps). Please verify you invoked Maven from the correct directory. -> [Help 1]<br/>[2022-09-14T05:56:16.194Z] org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps). Please verify you invoked Maven from the correct directory.<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:85)<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2022-09-14T05:56:16.194Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2022-09-14T05:56:16.194Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2022-09-14T05:56:16.194Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2022-09-14T05:56:16.194Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2022-09-14T05:56:16.194Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-09-14T05:56:16.194Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2022-09-14T05:56:16.194Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2022-09-14T05:56:16.194Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2022-09-14T05:56:16.194Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2022-09-14T05:56:16.194Z] [ERROR] <br/>[2022-09-14T05:56:16.194Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.<br/>[2022-09-14T05:56:16.194Z] [ERROR] <br/>[2022-09-14T05:56:16.194Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:<br/>[2022-09-14T05:56:16.194Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException<br/>[2022-09-14T05:56:16.194Z] + test 1 -eq 0<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-09-14T05:56:17.024Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/351/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-09-14 05:56 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#352` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/352/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-14T05:56:25.534Z] [INFO] Total time:  0.053 s<br/>[2022-09-14T05:56:25.534Z] [INFO] Finished at: 2022-09-14T01:56:24-04:00<br/>[2022-09-14T05:56:25.534Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-14T05:56:25.534Z] [WARNING] The requested profile "sonarcloud-analysis" could not be activated because it does not exist.<br/>[2022-09-14T05:56:25.534Z] [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps). Please verify you invoked Maven from the correct directory. -> [Help 1]<br/>[2022-09-14T05:56:25.534Z] org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps). Please verify you invoked Maven from the correct directory.<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:85)<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2022-09-14T05:56:25.534Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2022-09-14T05:56:25.534Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2022-09-14T05:56:25.534Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2022-09-14T05:56:25.534Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2022-09-14T05:56:25.534Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-09-14T05:56:25.534Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2022-09-14T05:56:25.534Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2022-09-14T05:56:25.534Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2022-09-14T05:56:25.534Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2022-09-14T05:56:25.534Z] [ERROR] <br/>[2022-09-14T05:56:25.534Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.<br/>[2022-09-14T05:56:25.534Z] [ERROR] <br/>[2022-09-14T05:56:25.534Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:<br/>[2022-09-14T05:56:25.534Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException<br/>[2022-09-14T05:56:25.534Z] + test 1 -eq 0<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-09-14T05:56:26.371Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/352/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-09-14 05:57 UTC, jstastny-cz commented
jenkins rerun kogito-apps tests

2022-09-14 10:32 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#355` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/355/display/redirect

**Test results:**
- PASSED: 1914
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/355/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

2022-09-14 14:39 UTC, pefernan commented on ui-packages/packages/components-common/src/components/utils/FormActionsUtils.tsx
> +        action.actionType === ActionType.SUBMIT && onSubmitForm && onSubmitForm();
@AjayJagan please check with the `actionType` const declared at https://github.com/kiegroup/kogito-apps/pull/1458/files#diff-89f58cc3dbde3dd65131eb25822649b48ed3161da4d4d753026952a9af49a960R68 since the `actionType` field is optional in the `FormAction` interface

2022-09-14 14:55 UTC, pefernan commented on ui-packages/packages/task-form/src/envelope/components/TaskFormRenderer/TaskFormRenderer.tsx
> +          actionType: ActionType.SUBMIT
We could leave this empty since `submit` is the default type

2022-09-14 15:42 UTC, pefernan requested changes
@AjayJagan great job, just fix that minor issue regarding the button type and we are done

2022-09-14 17:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#357` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/357/display/redirect

**Test results:**
- PASSED: 1864
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-14T17:48:16.173Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-14T17:48:16.173Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-14T17:48:16.173Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-14T17:48:16.173Z] [INFO] <br/>[2022-09-14T17:48:16.173Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-14T17:48:16.173Z] [INFO] Skipping Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment<br/>[2022-09-14T17:48:16.173Z] [INFO] This project has been banned from the build due to previous failures.<br/>[2022-09-14T17:48:16.173Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-14T17:48:16.173Z] [INFO] ------------------------------------------------------------------------<br/>[2022-09-14T17:48:16.173Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:<br/>[2022-09-14T17:48:16.173Z] [INFO] <br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.474 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.038 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.036 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.036 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.178 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  3.497 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 14.042 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Parent ....... SUCCESS [  0.037 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Runtime ...... SUCCESS [  1.660 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Deployment ... SUCCESS [ 12.516 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Quarkus :: PostgreSQL :: In-memory :: Integration Tests SUCCESS [ 21.795 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 30.495 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 15.511 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.223 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 46.150 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.034 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  3.127 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  3.408 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 14.514 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.273 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.023 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:26 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:30 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:21 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:19 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:22 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.023 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.020 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  0.998 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.735 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 12.854 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.248 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [  9.503 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 12.183 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 37.385 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.023 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.669 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:26 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:17 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [01:43 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [02:52 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:38 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:21 min]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 55.891 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.020 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  1.933 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  7.447 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.023 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.791 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.241 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 23.556 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 35.999 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.149 s]<br/>[2022-09-14T17:48:16.173Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ..... [...]

2022-09-15 08:34 UTC, pefernan approved these changes
+1 thanks @AjayJagan

2022-09-15 16:47 UTC, pefernan commented
@AjayJagan @paulovmr please don't merge, found an issue while testing that I'd like to verify tomorrow morning.

2022-09-16 11:14 UTC, pefernan commented
@AjayJagan @paulovmr ok to merge for me

2022-09-20 12:28 UTC, paulovmr approved these changes

2022-09-20 12:29 UTC, paulovmr commented
Jenkins rerun kogito-examples tests

2022-09-20 16:43 UTC, paulovmr commented
Jenkins rerun kogito-examples tests

2022-09-21 17:41 UTC, merged