KOGITO-8303: fix CloudEvent form in DevUi
apache/incubator-kie-kogito-apps pull request #1592
Opened 2023-01-17 17:11 UTC by pefernan

Many thanks for submitting your Pull Request :heart:! 

Enhancing the Dev UI Cloud Event Form to allow filling all the required data to trigger CE. Also improved the WorkflowForm component to display a CodeEditor when no schema is available instead of showing a CE form.

There are some testing instructions here: https://github.com/pefernan/kogito-examples/blob/KOGITO-8303-test/serverless-workflow-examples/serverless-workflow-consuming-events-over-http-quarkus/README_test.md

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] mandrel</b>

- for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] mandrel-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-01-17 18:23 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#659` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/659/display/redirect

**Test results:**
- PASSED: 1912
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/659/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.157 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [01:01 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.034 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  5.406 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.609 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 24.234 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.257 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.024 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:02 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [01:59 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [01:46 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [01:43 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [01:45 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.062 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.059 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.271 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.639 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 20.949 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.499 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 16.842 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.116 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 53.749 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.632 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.024 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.278 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:44 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:41 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:10 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:41 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:04 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  0.441 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.257 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.022 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.664 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.395 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 43.121 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.020 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.270 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.399 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 31.895 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.037 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.267 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.386 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SUCCESS [ 33.157 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.022 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.192 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.358 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 31.582 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [04:19 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:02 min]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.229 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.631 s]<br/>[2023-01-17T18:23:02.581Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [ [...]

2023-01-23 17:19 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#678` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/678/display/redirect

**Test results:**
- PASSED: 1971
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/678/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

2023-01-24 12:36 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#159` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/159/display/redirect

**Test results:**
- PASSED: 75
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/159/testReport/org.kie.kogito.examples/AnnotationsAndDescriptionsTest/testAnnotations(String,_String)[1]/">org.kie.kogito.examples.AnnotationsAndDescriptionsTest.testAnnotations(String, String)[1]</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor#setupKubernetesDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:119)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:829)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.lambda$startKubernetes$7(DevServicesKubernetesProcessor.java:227)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.startKubernetes(DevServicesKubernetesProcessor.java:241)<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:109)<br/> ... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 17 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at com.dajudge.kindcontainer.ApiServerContainer.containerIsStarting(ApiServerContainer.java:142)<br/> at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:692)<br/> at com.dajudge.kindcontainer.KubernetesContainer.containerIsStarting(KubernetesContainer.java:151)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:474)<br/> ... 19 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 24 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 25 more<br/>Caused by: com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"cannot join network of a non running container: 08580233b036adc94d41fc6c2bfe749826c6c6f1a8889333fcaea5c7c51ae986"}<br/><br/> at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:245)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)<br/> ... 27 more<br/>
</details>

2023-01-24 18:17 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#163` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/163/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
 > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c990bebb99c215a256eba4082334621ccff59691 # timeout=10<br/>Commit message: "KOGITO-8090 GHA Maven cache exclude kie artifacts (#765)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-01-24T18:14:00.223Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2023-01-24T18:14:00.314Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-954<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-24T18:14:02.797Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-01-24T18:14:02.860Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-01-24T18:14:03.398Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-01-24T18:14:03.432Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-01-24T18:14:03.711Z] + df -h<br/>[2023-01-24T18:14:03.712Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-01-24T18:14:03.712Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-01-24T18:14:03.712Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-01-24T18:14:03.712Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2023-01-24T18:14:03.712Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-01-24T18:14:03.712Z] /dev/vda1        80G   20G   61G  25% /<br/>[2023-01-24T18:14:03.712Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-01-24T18:14:03.732Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-01-24T18:14:04.012Z] + du -h -d1 /home/jenkins<br/>[2023-01-24T18:14:04.012Z] 4.0K	/home/jenkins/.ssh<br/>[2023-01-24T18:14:04.012Z] 0	/home/jenkins/go<br/>[2023-01-24T18:14:04.012Z] 8.0K	/home/jenkins/.vnc<br/>[2023-01-24T18:14:04.012Z] 8.0K	/home/jenkins/.m2<br/>[2023-01-24T18:14:04.012Z] 2.2G	/home/jenkins/git-repos<br/>[2023-01-24T18:14:04.012Z] 4.0K	/home/jenkins/.config<br/>[2023-01-24T18:14:04.267Z] 131M	/home/jenkins/virtenvs<br/>[2023-01-24T18:14:04.267Z] 4.0K	/home/jenkins/.cekit<br/>[2023-01-24T18:14:04.267Z] 32M	/home/jenkins/remoting<br/>[2023-01-24T18:14:04.267Z] 0	/home/jenkins/.cache<br/>[2023-01-24T18:14:04.267Z] 3.5M	/home/jenkins/workspace<br/>[2023-01-24T18:14:04.267Z] 0	/home/jenkins/.pki<br/>[2023-01-24T18:14:04.267Z] 100M	/home/jenkins/tools<br/>[2023-01-24T18:14:04.267Z] 0	/home/jenkins/caches<br/>[2023-01-24T18:14:04.267Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2023-01-24T18:14:04.293Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2023-01-24T18:14:04.579Z] + du -h -d3 /home/jenkins/workspace<br/>[2023-01-24T18:14:04.579Z] 3.5M	/home/jenkins/workspace/KIE/kogito/main<br/>[2023-01-24T18:14:04.579Z] 3.5M	/home/jenkins/workspace/KIE/kogito<br/>[2023-01-24T18:14:04.579Z] 3.5M	/home/jenkins/workspace/KIE<br/>[2023-01-24T18:14:04.579Z] 3.5M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-01-24T18:14:04.915Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2023-01-24T18:14:05.032Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2023-01-24T18:14:05.323Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-24T18:14:06.249Z] npm WARN ERESOLVE overriding peer dependency<br/>[2023-01-24T18:14:06.249Z] npm WARN Found: @octokit/core@2.5.4<br/>[2023-01-24T18:14:06.249Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2023-01-24T18:14:06.249Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2023-01-24T18:14:06.249Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2023-01-24T18:14:06.249Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2023-01-24T18:14:06.249Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2023-01-24T18:14:06.249Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2023-01-24T18:14:06.249Z] npm WARN <br/>[2023-01-24T18:14:06.249Z] npm WARN Could not resolve dependency:<br/>[2023-01-24T18:14:06.249Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2023-01-24T18:14:06.249Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2023-01-24T18:14:06.249Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2023-01-24T18:14:06.249Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2023-01-24T18:14:09.508Z] <br/>[2023-01-24T18:14:09.508Z] added 110 packages, and audited 111 packages in 4s<br/>[2023-01-24T18:14:09.508Z] <br/>[2023-01-24T18:14:09.508Z] 5 packages are looking for funding<br/>[2023-01-24T18:14:09.508Z]   run `npm fund` for details<br/>[2023-01-24T18:14:09.508Z] <br/>[2023-01-24T18:14:09.508Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to when conditional<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to when conditional<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-01-24T18:14:10.068Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-01-24T18:14:10.080Z] provisioning config files...<br/>[2023-01-24T18:14:10.087Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-sprin [...]

2023-01-24 18:33 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#162` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/162/display/redirect

**Test results:**
- PASSED: 128
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/162/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 32811] should be listening)<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 32811] should be listening)<br/>
</details>

2023-01-24 22:05 UTC, paulovmr requested changes

2023-01-24 22:05 UTC, paulovmr commented on ui-packages/packages/runtime-tools-dev-ui-webapp/src/channel/apis/tests/apis.test.tsx
> +describe('triiger cloud events serction', () => {
```suggestion
describe('trigger cloud events section', () => {
```

2023-01-24 22:05 UTC, paulovmr commented on ui-packages/packages/runtime-tools-dev-ui-webapp/src/channel/apis/tests/apis.test.tsx
> +  it('trigger cloud event start - with businesskey', async () => {
```suggestion
  it('trigger cloud event start - with business key', async () => {
```

2023-01-24 22:05 UTC, paulovmr commented on ui-packages/packages/runtime-tools-dev-ui-webapp/src/components/containers/ProcessListContainer/ProcessListContainer.tsx
> +import {CloudEventPageSource} from "../../pages/CloudEventFormPage/CloudEventFormPage";
```suggestion
import { CloudEventPageSource } from "../../pages/CloudEventFormPage/CloudEventFormPage";
```

2023-01-25 19:58 UTC, paulovmr approved these changes

2023-01-26 09:56 UTC, AjayJagan approved these changes
Thanks Pere :)

2023-02-06 12:59 UTC, domhanak commented on ui-packages/packages/cloud-event-form/src/embedded/EmbeddedCloudEventForm.tsx
> +            window.postMessage(message, '*', transfer);
@paulovmr @AjayJagan are we ok with this?

2023-02-06 12:59 UTC, domhanak commented
@paulovmr @AjayJagan LGTM, tested the example and it worked well. Check the comment from sonarcloud analysis, I need reply before I approve

2023-02-06 13:25 UTC, paulovmr commented on ui-packages/packages/cloud-event-form/src/embedded/EmbeddedCloudEventForm.tsx
> +            window.postMessage(message, '*', transfer);
I believe this could be changed to `window.postMessage(message, window.location.origin, transfer);` to prevent this alert. Needs verification.

2023-02-06 13:28 UTC, AjayJagan commented
There seems to be 1 issue with the `Math.random()` as well so the I found a suggestion in StackOverflow: https://stackoverflow.com/questions/62036514/make-sure-that-using-this-pseudorandom-number-generator-is-safe-here

2023-02-06 13:33 UTC, domhanak commented on kogito-quarkus-serverless-workflow-devui-parent/kogito-quarkus-serverless-workflow-devui-deployment/src/main/java/org/kie/kogito/swf/tools/deployment/DevConsoleProcessor.java
> +                .route("/q/dev/org.kie.kogito.kogito-quarkus-serverless-workflow-devui/*")
nitpick: make this a constant

2023-02-08 17:19 UTC, paulovmr commented
@domhanak Unfortunately we can't use the `window.location.origin` because the component is in an iframe, so it is `null`. All other envelope components do the same thing using `*`, so I suggest we keep the way it is and investigate if there is a better way in another task. I extracted the constant you suggested.

2023-02-08 18:55 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#712` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/712/display/redirect

**Test results:**
- PASSED: 2026
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/712/testReport/org.kie.kogito.taskassigning.service/SolverExecutorTest/stopWithSolverStarted/">org.kie.kogito.taskassigning.service.SolverExecutorTest.stopWithSolverStarted</a></summary>
java.util.concurrent.TimeoutException: stopWithSolverStarted() timed out after 80 seconds<br/>	at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)<br/>	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:58)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)<br/>	at org.apache.maven.sur [...]

2023-02-08 20:20 UTC, paulovmr commented
Jenkins rerun kogito-apps tests

2023-02-09 06:05 UTC, domhanak approved these changes
@paulovmr Thanks for the clarificaton.

2023-02-09 13:31 UTC, merged