KOGITO-7426:  [SWF Dev UI] Pnpm migration
apache/incubator-kie-kogito-apps pull request #1706
Opened 2023-04-26 12:17 UTC by Sara4994

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-04-26 12:18 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#357` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/357/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
 > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/> > git rev-list --no-walk c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh8948643950548270112.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.downstream.kogito-springboot-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.downstream.kogito-springboot-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh15538149614781528904.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>Commit message: "[BXMSPROD-2020] withKerberos: added retry mechanism (#272)"<br/> > git rev-list --no-walk 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-2410 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-04-26T12:17:54.246Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-04-26T12:17:55.346Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-04-26T12:17:55.378Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-04-26T12:17:56.385Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-04-26T12:17:56.468Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-04-26T12:17:56.748Z] + df -h<br/>[2023-04-26T12:17:56.749Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-04-26T12:17:56.749Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-04-26T12:17:56.749Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-04-26T12:17:56.749Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2023-04-26T12:17:56.749Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-04-26T12:17:56.749Z] /dev/vda1        80G   22G   59G  27% /<br/>[2023-04-26T12:17:56.749Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-04-26T12:17:56.779Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023 [...]

2023-04-26 12:18 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#346` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/346/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/> > git rev-list --no-walk c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh4855302289177552571.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.downstream.serverless-workflow-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.downstream.serverless-workflow-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh6081013043019640909.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>Commit message: "[BXMSPROD-2020] withKerberos: added retry mechanism (#272)"<br/> > git rev-list --no-walk 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-2423 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-04-26T12:17:54.158Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-04-26T12:17:55.243Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-04-26T12:17:55.280Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-04-26T12:17:56.347Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-04-26T12:17:56.387Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-04-26T12:17:56.745Z] + df -h<br/>[2023-04-26T12:17:56.745Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-04-26T12:17:56.745Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-04-26T12:17:56.745Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-04-26T12:17:56.745Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2023-04-26T12:17:56.745Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-04-26T12:17:56.745Z] /dev/vda1        80G   20G   61G  25% /<br/>[2023-04-26T12:17:56.745Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[2023-04-26T12:17:56.745Z] tmpfs           1.6G     0  1.6G   0% [...]

2023-04-26 12:19 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#343` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-quarkus-examples/343/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/> > git rev-list --no-walk c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh15299158127564729075.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.downstream.kogito-quarkus-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.downstream.kogito-quarkus-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh7849301819247936936.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>Commit message: "[BXMSPROD-2020] withKerberos: added retry mechanism (#272)"<br/> > git rev-list --no-walk 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!built-in’<br/>Running on rhos-01-kie-psi-rhel7-xlarge-2377 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-04-26T12:18:40.456Z] Timeout set to expire in 3 hr 0 min<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-04-26T12:18:41.545Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-04-26T12:18:41.574Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-04-26T12:18:42.565Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-04-26T12:18:42.650Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-04-26T12:18:42.944Z] + df -h<br/>[2023-04-26T12:18:42.945Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-04-26T12:18:42.945Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-04-26T12:18:42.945Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-04-26T12:18:42.945Z] tmpfs           7.8G   25M  7.8G   1% /run<br/>[2023-04-26T12:18:42.945Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-04-26T12:18:42.945Z] /dev/vda1        80G   26G   55G  33% /<br/>[2023-04-26T12:18:42.945Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-04-26T12:18:42.975Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-04-26T12:18:43.345Z] + du -h -d1 /home/jenkins<br/>[2023-04-26T12:18:43.345Z] 4.0K	/home/jenkins/.ssh<br/>[2023-04-26T12:18:43.345Z] 0	/home/ [...]

2023-04-26 12:19 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#887` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/887/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
The recommended git tool is: NONE<br/>using credential kie-ci3<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/> > git rev-list --no-walk c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh10849869349677862458.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh7295376138379003149.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>Commit message: "[BXMSPROD-2020] withKerberos: added retry mechanism (#272)"<br/> > git rev-list --no-walk 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!built-in’<br/>Running on rhos-01-kie-psi-rhel7-xlarge-2410 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 (origin/main)<br/>Commit message: "Quarkus 3: Correct environment variables (#947)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f c0bb2b034a3a7826665916be3c4ba82ec7ec71d9 # timeout=10<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-04-26T12:18:51.644Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-04-26T12:18:53.043Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-04-26T12:18:53.073Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-04-26T12:18:54.262Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-04-26T12:18:54.354Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-04-26T12:18:54.646Z] + df -h<br/>[2023-04-26T12:18:54.646Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-04-26T12:18:54.646Z] devtmpfs        7.8G     0  7.8G  [...]

2023-04-26 13:26 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#888` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/888/display/redirect

**Test results:**
- PASSED: 2106
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 21.853 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 45.427 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.974 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.042 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.139 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:39 min]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:34 min]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:01 min]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:21 min]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:58 min]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.021 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  0.764 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.322 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.327 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.522 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 43.303 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.021 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.345 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.570 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 34.743 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.368 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.517 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.023 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.266 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  5.822 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.283 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.484 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 31.838 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 51.004 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.018 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.131 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.159 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.225 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.611 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 45.461 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.152 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.730 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.478 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.220 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:47 min]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.578 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 26.392 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 30.167 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Task Assigning ...................... SUCCESS [  0.020 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Task Assigning Core ................. SUCCESS [ 19.585 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Task Assigning Process Service Client SUCCESS [ 20.701 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Task Assigning :: Integration API ... SUCCESS [  0.175 s]<br/>[2023-04-26T13:26:09.703Z] [INFO] Kogito Apps :: Task Assigning :: User Service ...... S [...]

2023-04-26 13:27 UTC, Sara4994 commented
Closed previous [PR](https://github.com/kiegroup/kogito-apps/pull/1690) and opened this new PR.

2023-04-26 16:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#892` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/892/display/redirect

**Test results:**
- PASSED: 2106
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.023 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.099 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 23.114 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 31.230 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 21.757 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.053 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.026 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.419 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.026 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.412 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 20.931 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.025 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:25 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:02 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:03 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:10 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 55.591 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.341 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:03 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:07 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [03:48 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:49 min]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.032 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [  9.225 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [ 38.271 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.024 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.984 s]<br/>[2023-04-26T16:48:20.604Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-04-26T16:48:20.604Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-26T16:48:20.604Z] [INFO] BUILD FAILURE<br/>[2023-04-26T16:48:20.604Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-26T16:48:20.604Z] [INFO] Total time:  01:03 h<br/>[2023-04-26T16:48:20.604Z] [INFO] Finished at: 2023-04-26T12:48:19-04:00<br/>[2023-04-26T16:48:20.604Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-26T16:48:20.604Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.16.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-04-26T16:48:20.604Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-26T16:48:20.604Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-26T16:48:20.604Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-26T16:48: [...]

2023-04-26 18:10 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#893` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/893/display/redirect

**Test results:**
- PASSED: 2106
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.022 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.105 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 25.297 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 34.799 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 23.744 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.029 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.030 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.509 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.030 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.526 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 23.678 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.039 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:35 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:20 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:21 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:22 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:08 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.035 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.396 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:18 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:28 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [05:22 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [02:22 min]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.040 s]<br/>[2023-04-26T18:10:33.753Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [ 12.208 s]<br/>[2023-04-26T18:10:33.754Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [ 53.419 s]<br/>[2023-04-26T18:10:33.754Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.038 s]<br/>[2023-04-26T18:10:33.754Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  8.187 s]<br/>[2023-04-26T18:10:33.754Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-04-26T18:10:33.754Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-26T18:10:33.754Z] [INFO] BUILD FAILURE<br/>[2023-04-26T18:10:33.754Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-26T18:10:33.754Z] [INFO] Total time:  01:06 h<br/>[2023-04-26T18:10:33.754Z] [INFO] Finished at: 2023-04-26T14:10:32-04:00<br/>[2023-04-26T18:10:33.754Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-26T18:10:33.754Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.21.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-04-26T18:10:33.754Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-26T18:10:33.754Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-26T18:10:33.754Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-26T18:10: [...]

2023-04-28 14:25 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#897` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/897/display/redirect

**Test results:**
- PASSED: 2108
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/897/testReport/org.kie.kogito.jobs.service.management/JobServiceInstanceManagerTest/heartbeatLeader/">org.kie.kogito.jobs.service.management.JobServiceInstanceManagerTest.heartbeatLeader</a></summary>
org.mockito.exceptions.verification.TooManyActualInvocations: <br/><br/>repository.heartbeat(<br/>    JobServiceManagementInfo[id=null, lastHeartbeat=2023-04-28T13:27:54.798Z, token=d376e9d3-ae6e-45f5-a644-d48c8aab70b0]<br/>);<br/>Wanted 1 time:<br/>-> at org.kie.kogito.jobs.service.management.JobServiceInstanceManagerTest.heartbeatLeader(JobServiceInstanceManagerTest.java:142)<br/>But was 2 times:<br/>-> at org.kie.kogito.jobs.service.management.JobServiceInstanceManager.heartbeat(JobServiceInstanceManager.java:187)<br/>-> at org.kie.kogito.jobs.service.management.JobServiceInstanceManager.heartbeat(JobServiceInstanceManager.java:187)<br/><br/><br/>	at org.kie.kogito.jobs.service.management.JobServiceInstanceManagerTest.heartbeatLeader(JobServiceInstanceManagerTest.java:142)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at or [...]

2023-05-02 11:50 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#899` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/899/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Checking out git https://github.com/kiegroup/kogito-pipelines.git into /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92 to read .ci/jenkins/Jenkinsfile.buildchain<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision ebe2db489a17f79dedc59797fcc0462a8a3a5e21 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f ebe2db489a17f79dedc59797fcc0462a8a3a5e21 # timeout=10<br/>Commit message: "Quarkus 3: Disable automatic PR check (#950)"<br/> > git rev-list --no-walk ebe2db489a17f79dedc59797fcc0462a8a3a5e21 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh14020566834932765220.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh6568434597213009272.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>Commit message: "[BXMSPROD-2020] withKerberos: added retry mechanism (#272)"<br/> > git rev-list --no-walk 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-984 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision ebe2db489a17f79dedc59797fcc0462a8a3a5e21 (origin/main)<br/>Commit message: "Quarkus 3: Disable automatic PR check (#950)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-05-02T11:48:08.892Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f ebe2db489a17f79dedc59797fcc0462a8a3a5e21 # timeout=10<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-05-02T11:48:09.553Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-05-02T11:48:09.583Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-05-02T11:48:10.040Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-05-02T11:48:10.076Z] [INFO] space left on the machine<br/>[Pipeline] sh<br [...]

2023-05-02 12:41 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#898` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/898/display/redirect

**Test results:**
- PASSED: 2109
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.020 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.095 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.550 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 30.324 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.691 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.023 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.026 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.407 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.028 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.437 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.262 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.025 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:25 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:04 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:06 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:14 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:00 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.029 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.368 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:05 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:08 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:03 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.028 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [  9.137 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [ 39.139 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.021 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.967 s]<br/>[2023-05-02T12:41:35.115Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-02T12:41:35.115Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T12:41:35.115Z] [INFO] BUILD FAILURE<br/>[2023-05-02T12:41:35.115Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T12:41:35.115Z] [INFO] Total time:  01:02 h<br/>[2023-05-02T12:41:35.115Z] [INFO] Finished at: 2023-05-02T08:41:34-04:00<br/>[2023-05-02T12:41:35.115Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T12:41:35.115Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.17.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-02T12:41:35.115Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-02T12:41:35.115Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-02T12:41:35.115Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-02T12:41: [...]

2023-05-02 17:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#900` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/900/display/redirect

**Test results:**
- PASSED: 2109
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.020 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.095 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.294 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 30.106 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.775 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.020 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.036 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.392 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.025 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.426 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.858 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:19 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:03 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [01:58 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:09 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 56.651 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.352 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:04 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:07 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:00 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:53 min]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.024 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [  8.384 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [ 38.486 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.022 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.725 s]<br/>[2023-05-02T17:48:05.525Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-02T17:48:05.525Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T17:48:05.525Z] [INFO] BUILD FAILURE<br/>[2023-05-02T17:48:05.525Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T17:48:05.525Z] [INFO] Total time:  59:38 min<br/>[2023-05-02T17:48:05.525Z] [INFO] Finished at: 2023-05-02T13:48:05-04:00<br/>[2023-05-02T17:48:05.525Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T17:48:05.525Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.24.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-02T17:48:05.525Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-02T17:48:05.525Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-02T17:48:05.525Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-02T17:4 [...]

2023-05-02 17:57 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#901` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/901/display/redirect

**Test results:**
- PASSED: 2109
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.026 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.090 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 23.557 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 31.451 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 22.919 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.025 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.056 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.440 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.031 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.454 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.976 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.025 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:31 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:08 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:09 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:12 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 58.462 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.056 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.328 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:09 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:12 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:12 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:57 min]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.028 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [  9.208 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [ 41.017 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.050 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  6.105 s]<br/>[2023-05-02T17:57:42.651Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-02T17:57:42.651Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T17:57:42.651Z] [INFO] BUILD FAILURE<br/>[2023-05-02T17:57:42.651Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T17:57:42.651Z] [INFO] Total time:  01:02 h<br/>[2023-05-02T17:57:42.651Z] [INFO] Finished at: 2023-05-02T13:57:42-04:00<br/>[2023-05-02T17:57:42.651Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T17:57:42.651Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.17.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-02T17:57:42.651Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-02T17:57:42.651Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-02T17:57:42.651Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-02T17:57: [...]

2023-05-02 19:00 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#902` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/902/display/redirect

**Test results:**
- PASSED: 2109
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.022 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.094 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.074 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.880 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.983 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.021 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.022 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.372 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.025 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.424 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.894 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:21 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:02 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [01:56 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:08 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 56.536 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.031 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.342 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:03 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:08 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:00 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:53 min]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.025 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [  8.402 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [ 39.850 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.021 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.832 s]<br/>[2023-05-02T19:00:27.260Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-02T19:00:27.260Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T19:00:27.260Z] [INFO] BUILD FAILURE<br/>[2023-05-02T19:00:27.260Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T19:00:27.260Z] [INFO] Total time:  01:00 h<br/>[2023-05-02T19:00:27.260Z] [INFO] Finished at: 2023-05-02T15:00:27-04:00<br/>[2023-05-02T19:00:27.260Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-02T19:00:27.260Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.23.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-02T19:00:27.260Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-02T19:00:27.260Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-02T19:00:27.260Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-02T19:00: [...]

2023-05-15 07:59 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#917` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/917/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 29.786 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.020 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.070 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 21.434 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.071 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.030 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.021 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.022 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.367 s]<br/>[2023-05-15T07:58:53.878Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.022 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.425 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.675 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:21 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:56 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:52 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:47 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:26 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.024 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.297 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:01 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:05 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [03:55 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:54 min]<br/>[2023-05-15T07:58:53.879Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.025 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.537 s]<br/>[2023-05-15T07:58:53.879Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-15T07:58:53.879Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-15T07:58:53.879Z] [INFO] BUILD FAILURE<br/>[2023-05-15T07:58:53.879Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-15T07:58:53.879Z] [INFO] Total time:  01:01 h<br/>[2023-05-15T07:58:53.879Z] [INFO] Finished at: 2023-05-15T03:58:53-04:00<br/>[2023-05-15T07:58:53.879Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-15T07:58:53.879Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.17.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-15T07:58:53.879Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-15T07:58:53.879Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-15T07:58:53.879Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-15T07:58:53.879Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-15T07:58:53.879Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-15T07:58:53.8 [...]

2023-05-17 19:30 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#920` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/920/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 31.747 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.021 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.077 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 21.860 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 30.360 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.532 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.020 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.021 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.402 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.026 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.414 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.835 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:51 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:05 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [03:05 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:51 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:27 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.025 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.294 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:09 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:08 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:08 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [02:01 min]<br/>[2023-05-17T19:30:36.826Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.021 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.562 s]<br/>[2023-05-17T19:30:36.826Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-17T19:30:36.826Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-17T19:30:36.826Z] [INFO] BUILD FAILURE<br/>[2023-05-17T19:30:36.826Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-17T19:30:36.826Z] [INFO] Total time:  01:04 h<br/>[2023-05-17T19:30:36.826Z] [INFO] Finished at: 2023-05-17T15:30:36-04:00<br/>[2023-05-17T19:30:36.826Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-17T19:30:36.826Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.21.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-17T19:30:36.826Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-17T19:30:36.826Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-17T19:30:36.826Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-17T19:30:36.826Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-17T19:30:36.826Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-17T19:30:36.8 [...]

2023-05-18 08:16 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#921` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/921/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 32.212 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.023 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.065 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 21.651 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 28.822 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.694 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.020 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.022 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.339 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.023 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.407 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.760 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.024 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:34 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:06 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [03:06 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:48 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:28 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.302 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:06 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:09 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:12 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-05-18T08:16:22.895Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.021 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.771 s]<br/>[2023-05-18T08:16:22.895Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-18T08:16:22.895Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-18T08:16:22.895Z] [INFO] BUILD FAILURE<br/>[2023-05-18T08:16:22.895Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-18T08:16:22.895Z] [INFO] Total time:  01:04 h<br/>[2023-05-18T08:16:22.895Z] [INFO] Finished at: 2023-05-18T04:16:21-04:00<br/>[2023-05-18T08:16:22.895Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-18T08:16:22.895Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.20.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-18T08:16:22.895Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-18T08:16:22.895Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-18T08:16:22.896Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-18T08:16:22.896Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-18T08:16:22.896Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-18T08:16:22.8 [...]

2023-05-18 11:55 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#384` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/384/display/redirect

**Test results:**
- PASSED: 79
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/384/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/>
</details>

2023-05-18 12:34 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#924` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/924/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 32.560 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.020 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.068 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.185 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.260 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.348 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.019 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.022 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.390 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.024 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.417 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.596 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.021 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:29 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:02 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [03:00 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:51 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:28 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.299 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:07 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:09 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:10 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-05-18T12:34:44.605Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.024 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.606 s]<br/>[2023-05-18T12:34:44.605Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-18T12:34:44.605Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-18T12:34:44.605Z] [INFO] BUILD FAILURE<br/>[2023-05-18T12:34:44.605Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-18T12:34:44.605Z] [INFO] Total time:  01:03 h<br/>[2023-05-18T12:34:44.605Z] [INFO] Finished at: 2023-05-18T08:34:44-04:00<br/>[2023-05-18T12:34:44.605Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-18T12:34:44.605Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.17.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-18T12:34:44.605Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-18T12:34:44.605Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-18T12:34:44.605Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-18T12:34:44.605Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-18T12:34:44.605Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-18T12:34:44.6 [...]

2023-05-19 09:46 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#927` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/927/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 32.596 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.021 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.074 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.080 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.146 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.720 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.022 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.025 s]<br/>[2023-05-19T09:45:48.216Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.462 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.023 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.438 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.792 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.021 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:29 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:01 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:58 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:49 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:28 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.026 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.276 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:05 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [03:56 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [06:21 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:57 min]<br/>[2023-05-19T09:45:48.217Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.026 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.705 s]<br/>[2023-05-19T09:45:48.217Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-19T09:45:48.217Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T09:45:48.217Z] [INFO] BUILD FAILURE<br/>[2023-05-19T09:45:48.217Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T09:45:48.217Z] [INFO] Total time:  01:08 h<br/>[2023-05-19T09:45:48.217Z] [INFO] Finished at: 2023-05-19T05:45:47-04:00<br/>[2023-05-19T09:45:48.217Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T09:45:48.217Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.20.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-19T09:45:48.217Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-19T09:45:48.217Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-19T09:45:48.217Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-19T09:45:48.217Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-19T09:45:48.217Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-19T09:45:48.2 [...]

2023-05-19 10:43 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#928` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/928/display/redirect

**Test results:**
- PASSED: 1609
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/928/testReport/org.kie.kogito.persistence.infinispan.cache/InfinispanStorageIT/testGet/">org.kie.kogito.persistence.infinispan.cache.InfinispanStorageIT.testGet</a></summary>
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException<br/>Caused by: java.lang.reflect.InvocationTargetException<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.testcontainers.quarkus.InfinispanQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.testcontainers.quarkus.InfinispanQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=infinispan/server:14.0.6.Final, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@9c519cc)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: infinispan/server:14.0.6.Final<br/>Caused by: java.lang.InterruptedException<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-19T10:43:18.529Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 31.398 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.029 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.094 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.635 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 30.522 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 21.250 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.049 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.026 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.430 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.028 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.438 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.313 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.026 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:34 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:04 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [03:08 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:51 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:29 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.028 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.311 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:06 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:10 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:05 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:56 min]<br/>[2023-05-19T10:43:18.530Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.023 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.521 s]<br/>[2023-05-19T10:43:18.530Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-19T10:43:18.530Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T10:43:18.530Z] [INFO] BUILD FAILURE<br/>[2023-05-19T10:43:18.530Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T10:43:18.530Z] [INFO] Total time:  01:10 h<br/>[2023-05-19T10:43:18.530Z] [INFO] Finished at: 2023-05-19T06:43:17-04:00<br/>[2023-05-19T10:43:18.530Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T10:43:18.530Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.20.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-19T10:43:18.530Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-19T10:43:18.530Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-19T10:43:18.530Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-19T10:43:18.530Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-19T10:43:18.530Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-19T10:43:18.530Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-19T10:43:18.530Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java: [...]

2023-05-19 11:02 UTC, AjayJagan approved these changes
Tested all functionality and everything works!!! Thanks @Sara4994

2023-05-19 11:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#929` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/929/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 32.123 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.047 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.067 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 21.817 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.699 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.569 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.019 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.020 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.346 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.047 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.412 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.473 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.020 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:31 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:03 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [03:05 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:52 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:29 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.025 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.283 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:05 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:08 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:01 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-05-19T11:47:05.409Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.028 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  5.552 s]<br/>[2023-05-19T11:47:05.409Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-19T11:47:05.409Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T11:47:05.409Z] [INFO] BUILD FAILURE<br/>[2023-05-19T11:47:05.409Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T11:47:05.409Z] [INFO] Total time:  01:04 h<br/>[2023-05-19T11:47:05.409Z] [INFO] Finished at: 2023-05-19T07:47:04-04:00<br/>[2023-05-19T11:47:05.409Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T11:47:05.409Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.25.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.21.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-19T11:47:05.409Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-19T11:47:05.409Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-19T11:47:05.409Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-19T11:47:05.409Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-19T11:47:05.409Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-19T11:47:05.4 [...]

2023-05-19 11:56 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#930` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/930/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 32.678 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.021 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.068 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 21.714 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.534 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.923 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.020 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.021 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.391 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.024 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.407 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.771 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.040 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:24 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:00 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:56 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:49 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:27 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.273 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:03 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:07 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:02 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-05-19T11:56:37.771Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.021 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  6.112 s]<br/>[2023-05-19T11:56:37.771Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-19T11:56:37.771Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T11:56:37.771Z] [INFO] BUILD FAILURE<br/>[2023-05-19T11:56:37.771Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T11:56:37.771Z] [INFO] Total time:  01:02 h<br/>[2023-05-19T11:56:37.771Z] [INFO] Finished at: 2023-05-19T07:56:36-04:00<br/>[2023-05-19T11:56:37.771Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-19T11:56:37.771Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz: Connect to registry.npmjs.org:443 [registry.npmjs.org/104.16.17.35, registry.npmjs.org/104.16.16.35, registry.npmjs.org/104.16.22.35, registry.npmjs.org/104.16.27.35, registry.npmjs.org/104.16.21.35, registry.npmjs.org/104.16.20.35, registry.npmjs.org/104.16.24.35, registry.npmjs.org/104.16.18.35, registry.npmjs.org/104.16.19.35, registry.npmjs.org/104.16.23.35, registry.npmjs.org/104.16.26.35, registry.npmjs.org/104.16.25.35] failed: Connection refused (Connection refused) -> [Help 1]<br/>[2023-05-19T11:56:37.771Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-pnpm (install-node-and-pnpm) on project kogito-apps-ui-packages: Could not download pnpm: Could not download https://registry.npmjs.org/pnpm/-/pnpm-7.26.3.tgz<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-19T11:56:37.771Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-19T11:56:37.771Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-19T11:56:37.771Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-19T11:56:37.771Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-19T11:56:37.7 [...]

2023-05-19 19:14 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#931` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/931/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.365 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  4.929 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 19.694 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 45.273 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 24.288 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.303 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 52.730 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.036 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  5.318 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.426 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 23.775 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.261 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.066 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.102 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.024 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  1.977 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.023 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  6.580 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 19.978 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.025 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.565 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.537 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:28 min]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:35 min]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [02:41 min]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:16 min]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:16 min]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.023 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.020 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  5.681 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.449 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.021 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.019 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.136 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.555 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 21.726 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.539 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.122 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.176 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 47.833 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.782 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-05-19T19:14:37.490Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.112 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:40 min]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:38 min]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:05 min]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:29 min]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:00 min]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.019 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.080 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.338 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.020 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.318 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.443 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 41.693 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.020 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.311 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.490 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 33.900 s]<br/>[2023-05-19T19:14:37.491Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.020 s]<b [...]

2023-05-20 18:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#933` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/933/display/redirect

**Test results:**
- PASSED: 1616
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/933/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleKafkaIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].comments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.440 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.179 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 20.776 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 47.058 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 24.980 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.586 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 57.254 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.039 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  4.987 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.478 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 24.202 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.262 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.025 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.146 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.024 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  2.060 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.023 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  6.838 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 20.612 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.025 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.381 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.674 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:35 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:34 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [02:43 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:21 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:20 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.030 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.021 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  6.442 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.379 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.022 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.020 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.142 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.605 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.249 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.374 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.195 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.836 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 53.665 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.812 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.019 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.287 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:43 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:46 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:07 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:55 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:01 min]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.021 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.481 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.317 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.319 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.482 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 48.561 s]<br/>[2023-05-20T18:47:13.665Z] [INFO] Kogito Apps :: Kogito Addons Quar [...]

2023-05-21 06:29 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#934` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/934/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.381 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.029 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 20.115 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 47.592 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 25.702 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.376 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [ 59.660 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.043 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  5.310 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.688 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 24.692 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.264 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.025 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.229 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.026 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  2.117 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.026 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  6.862 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 20.843 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.023 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.507 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.679 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:33 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:39 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [02:45 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:21 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:20 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.023 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.022 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  5.610 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.468 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.021 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.061 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.136 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.552 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.212 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.271 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.697 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.778 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 55.763 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.317 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.276 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:46 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:50 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:11 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:53 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:05 min]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.757 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.329 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.022 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.330 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.488 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 49.198 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.040 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.315 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.459 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 35.568 s]<br/>[2023-05-21T06:29:27.970Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.022 s]<b [...]

2023-05-22 11:02 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#938` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/938/display/redirect

**Test results:**
- PASSED: 1616
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/938/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.247 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  4.907 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 20.908 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [01:03 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 26.045 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.574 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [01:01 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.035 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  4.998 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.528 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 24.417 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.289 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.027 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.146 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.025 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  1.975 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.024 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  6.589 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 20.309 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.025 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.694 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.638 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:39 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:41 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [02:48 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:24 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:24 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.031 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.025 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  5.990 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.687 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.024 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.202 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.674 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 23.470 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.450 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 18.664 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.469 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 56.070 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.056 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.657 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:49 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:58 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:15 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:59 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:07 min]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.023 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.729 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.345 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.032 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.390 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.652 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 52.312 s]<br/>[2023-05-22T11:02:02.993Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Inde [...]

2023-05-22 16:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#948` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/948/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.219 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.001 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 20.822 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 48.908 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 26.461 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.322 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [01:01 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.036 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  5.360 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.253 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 23.791 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.251 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.025 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.047 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.024 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  1.961 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.024 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  6.601 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 19.926 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.025 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.481 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.502 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:33 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:42 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [02:46 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:17 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:23 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.024 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.021 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  6.183 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.409 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.021 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.020 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.124 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.532 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.150 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.401 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 18.488 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.958 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 59.836 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.808 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.022 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.232 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:45 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:48 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:08 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:03 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:05 min]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.021 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.021 s]<br/>[2023-05-22T16:48:17.457Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.674 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.353 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.038 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.423 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.462 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 49.184 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.041 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.387 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.493 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.218 s]<br/>[2023-05-22T16:48:17.458Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<b [...]

2023-05-23 09:00 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#952` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/952/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.259 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.151 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 21.214 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 49.777 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 28.694 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.341 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [01:03 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.040 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  5.487 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.336 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 24.860 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.284 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.027 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.262 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.024 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  2.114 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.025 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  6.924 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 20.639 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.027 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.510 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.601 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:38 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:46 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [02:53 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:31 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:32 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.029 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.028 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  6.394 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.900 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.025 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.027 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.338 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.865 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 24.401 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.837 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 18.787 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 24.093 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [01:03 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.887 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.024 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 15.133 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:53 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [03:13 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:24 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:19 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:16 min]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.022 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.022 s]<br/>[2023-05-23T08:59:49.274Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.778 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.358 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.022 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.364 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.585 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 52.082 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.039 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.379 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.676 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 36.882 s]<br/>[2023-05-23T08:59:49.275Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.030 s]<b [...]

2023-05-23 09:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#957` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/957/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:47:17.872Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.367 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.020 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.020 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.132 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.716 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.457 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.111 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.686 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.994 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [01:00 min]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.991 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.031 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.326 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:48 min]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:53 min]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:08 min]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:53 min]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:03 min]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.018 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.630 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.399 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.021 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.438 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.453 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 43.413 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.021 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.314 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.442 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 33.339 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.426 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.484 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.019 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.390 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.308 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.364 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.433 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 31.196 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 55.199 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.065 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.361 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.021 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.985 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.248 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.923 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 48.498 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.198 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.691 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.792 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.088 s]<br/>[2023-05-23T09:47:17.872Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-23 12:58 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#960` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/960/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T12:58:17.241Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.475 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.022 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.165 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.543 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.609 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.045 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.595 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.792 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 58.810 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.909 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.509 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:46 min]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:53 min]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:11 min]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:19 min]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:06 min]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.411 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.327 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.018 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.345 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.438 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 48.520 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.040 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.307 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.529 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.933 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.020 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.446 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.634 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.020 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.334 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  5.995 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.041 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.337 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.522 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 32.435 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:00 min]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.020 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.032 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.991 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.019 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.961 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.206 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.349 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 50.187 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.155 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.650 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.616 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.027 s]<br/>[2023-05-23T12:58:17.241Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-23 14:19 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#962` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/962/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T14:19:35.705Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.693 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.028 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.025 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.247 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.689 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.715 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.156 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.402 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.520 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 56.966 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.962 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.019 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.247 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:48 min]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:48 min]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:12 min]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:02 min]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:04 min]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.027 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.023 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.658 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.322 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.335 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.448 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 47.543 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.028 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.358 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.449 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 34.783 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.417 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.577 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.021 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.545 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.440 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.292 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.434 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 32.315 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:00 min]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.194 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.497 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.018 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.027 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2023-05-23T14:19:35.705Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.224 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 35.392 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 49.220 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.142 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.746 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.501 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.085 s]<br/>[2023-05-23T14:19:35.706Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-23 18:27 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#431` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/431/display/redirect

**Test results:**
- PASSED: 125
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/431/testReport/org.kie.kogito.examples.springboot/GrafanaDockerComposeIT/___/">org.kie.kogito.examples.springboot.GrafanaDockerComposeIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: --compatibility up -d<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/431/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: --compatibility up -d kafka mongodb connect sidecar kogito<br/>
</details>

2023-05-23 18:53 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#432` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/432/display/redirect

**Test results:**
- PASSED: 125
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/432/testReport/org.kie.kogito.examples.springboot/GrafanaDockerComposeIT/___/">org.kie.kogito.examples.springboot.GrafanaDockerComposeIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: --compatibility up -d<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/432/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: --compatibility up -d kafka mongodb connect sidecar kogito<br/>
</details>

2023-05-23 19:09 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#965` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/965/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T19:09:35.243Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.296 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.021 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.121 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.596 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.396 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.041 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.505 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.500 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 55.101 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.850 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.019 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.389 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:43 min]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:42 min]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:05 min]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:52 min]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:05 min]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.019 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.517 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.353 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.020 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.315 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.429 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 45.978 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.066 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.318 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.442 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.457 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.562 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.627 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.021 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.298 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.655 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.318 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.486 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 29.697 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 54.643 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.074 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 11.009 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.078 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.202 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.537 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 47.976 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.153 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.486 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.407 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.112 s]<br/>[2023-05-23T19:09:35.243Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-23 19:38 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#966` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/966/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T19:37:57.284Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.692 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.023 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.155 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.542 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.366 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.050 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.286 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.577 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 54.423 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.743 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 13.867 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:42 min]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:41 min]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:06 min]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:50 min]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:03 min]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.496 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.325 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.362 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.654 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 43.725 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.036 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.304 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.440 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 34.448 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.409 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.471 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.019 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.317 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.270 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.019 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.285 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.475 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.950 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 55.649 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.020 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.045 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.037 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.019 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.018 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.971 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.202 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.537 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 46.574 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.145 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.634 s]<br/>[2023-05-23T19:37:57.284Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.602 s]<br/>[2023-05-23T19:37:57.285Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.066 s]<br/>[2023-05-23T19:37:57.285Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-24 07:30 UTC, domhanak commented
@Sara4994 I ll check when we get green builds, are those related or not? I see docker failures in springboot examples.

2023-05-24 10:04 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#439` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/439/display/redirect

**Test results:**
- PASSED: 125
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/439/testReport/org.kie.kogito.examples.springboot/GrafanaDockerComposeIT/___/">org.kie.kogito.examples.springboot.GrafanaDockerComposeIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: --compatibility up -d<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/439/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 18 whilst running command: --compatibility up -d kafka mongodb connect sidecar kogito<br/>
</details>

2023-05-24 10:54 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#971` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/971/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-24T10:54:10.504Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.452 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.025 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.149 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.586 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.499 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.028 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.373 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.289 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 54.272 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.966 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 13.731 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:42 min]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:48 min]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:07 min]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:59 min]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:03 min]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.022 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.022 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.496 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.321 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.020 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.372 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.622 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 46.849 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.036 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.311 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.435 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.429 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.448 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.504 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.022 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.306 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.162 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.021 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.308 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.417 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.655 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 56.943 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.024 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.313 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.512 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.021 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.282 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.021 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.217 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.311 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 47.772 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.201 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.789 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.630 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.086 s]<br/>[2023-05-24T10:54:10.504Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-24 12:14 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#972` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/972/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-24T12:14:15.394Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.285 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.023 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.067 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.111 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.591 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 21.858 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.096 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.554 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.240 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 54.820 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.328 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.019 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 13.931 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:43 min]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:44 min]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:06 min]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:03 min]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:04 min]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.022 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.200 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.304 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.352 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.554 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 43.706 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.020 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.296 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.427 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.600 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.020 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.350 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.447 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.017 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.340 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.686 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.265 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.389 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.108 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 57.218 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-05-24T12:14:15.394Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  2.986 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.422 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.132 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.020 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.209 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 35.404 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 47.588 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.145 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.574 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.641 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.146 s]<br/>[2023-05-24T12:14:15.395Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-25 11:13 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#981` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/981/display/redirect

**Test results:**
- PASSED: 1616
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/981/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:37 min]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.022 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.019 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.166 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.581 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.047 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.436 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 18.052 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.355 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 58.119 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.461 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.296 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:51 min]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:55 min]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:11 min]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:57 min]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:02 min]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.025 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.018 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.762 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.322 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.308 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.428 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 46.531 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.040 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.301 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.434 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 33.318 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.457 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.599 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.020 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.145 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  5.982 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.298 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.389 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.594 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 53.852 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.220 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.582 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.036 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.926 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.219 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 32.913 s]<br/>[2023-05-25T11:13:32.720Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 49.9 [...]

2023-05-25 12:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#985` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/985/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-25T12:45:47.704Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-25T12:45:47.704Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-25T12:45:47.705Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-25T12:45:47.705Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-25T12:45:47.705Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-25T12:45:47.705Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-25T12:45:47.705Z] Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task<br/>[2023-05-25T12:45:47.705Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:100)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-25T12:45:47.705Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-25T12:45:47.705Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-25T12:45:47.705Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-25T12:45:47.705Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-25T12:45:47.705Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-25T12:45:47.705Z] Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'pnpm install --fetch-retry-mintimeout=50000 --fetch-retries=10 --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed.<br/>[2023-05-25T12:45:47.705Z]     at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute (NodeTaskExecutor.java:63)<br/>[2023-05-25T12:45:47.705Z]     at com.github.eirslett.maven.plugins.frontend.mojo.PnpmMojo.execute (PnpmMojo.java:62)<br/>[2023-05-25T12:45:47.705Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-25T12:45:47.705Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-25T1 [...]

2023-05-25 18:34 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#988` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/988/display/redirect

**Test results:**
- PASSED: 1617
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:30 min]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.022 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.157 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.625 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.683 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.390 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.569 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 22.983 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 57.740 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.818 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.079 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:45 min]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:47 min]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:06 min]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:51 min]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:05 min]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.021 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.440 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.323 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.021 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.375 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.592 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 44.604 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.038 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.340 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.557 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.238 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.022 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.446 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.584 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.019 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.317 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.155 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.021 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.321 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.411 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 32.392 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 54.642 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.042 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.387 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.018 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.152 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.208 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.244 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 47.892 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.151 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.687 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.613 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.132 s]<br/>[2023-05-25T18:33:45.828Z] [INFO] Kogito Apps :: Trusty Service Common ............... S [...]

2023-05-29 12:51 UTC, mbiarnes commented
Jenkins retest kogito-apps

2023-05-29 12:53 UTC, mbiarnes commented
Jenkins retest kogito-apps tests

2023-05-29 12:55 UTC, mbiarnes commented
Jenkins rerun kogito-apps tests

2023-05-29 13:03 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1004` was: **ABORTED**
Possible explanation: Most probably a timeout, please review


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1004/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-drl-parser:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-drl-extensions:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-wiring-api:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-core:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  |  +- org.drools:drools-wiring-static:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  |  +- org.drools:drools-io:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  |  \- commons-codec:commons-codec:jar:1.15:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-drl-ast:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-kiesession:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.kie:kie-memory-compiler:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-ecj:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.kie:kie-util-xml:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.kie:kie-util-maven-support:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  \- org.antlr:antlr-runtime:jar:3.5.2:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] +- org.drools:drools-ruleunits-impl:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] +- org.drools:drools-model-codegen:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-util:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-codegen-common:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-model-compiler:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  |  \- org.drools:drools-canonical-model:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  +- org.drools:drools-mvel-parser:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] |  \- org.drools:drools-mvel-compiler:jar:8.40.0-SNAPSHOT:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] \- org.slf4j:slf4j-api:jar:1.7.36:compile<br/>[2023-05-29T13:03:18.779Z] [INFO] <br/>[2023-05-29T13:03:18.779Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ kogito-drools ---<br/>[2023-05-29T13:03:18.779Z] [INFO] <br/>[2023-05-29T13:03:18.779Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ kogito-drools ---<br/>[2023-05-29T13:03:18.779Z] [INFO] <br/>[2023-05-29T13:03:18.779Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ kogito-drools ---<br/>[2023-05-29T13:03:18.779Z] [INFO] <br/>[2023-05-29T13:03:18.779Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ kogito-drools ---<br/>[2023-05-29T13:03:18.779Z] [INFO] <br/>[2023-05-29T13:03:18.779Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- formatter-maven-plugin:2.13.0:format (default) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Formatting is skipped<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- impsort-maven-plugin:1.8.0:sort (default) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Skipping execution of impsort-maven-plugin<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-29T13:03:19.034Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-runtimes/drools/kogito-drools/src/main/resources<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Changes detected - recompiling the module!<br/>[2023-05-29T13:03:19.034Z] [INFO] Compiling 10 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-runtimes/drools/kogito-drools/target/classes<br/>[2023-05-29T13:03:19.034Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-runtimes/drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/unit/AbstractRuleUnits.java:[52,58] unchecked cast<br/>[2023-05-29T13:03:19.034Z]   required: org.drools.ruleunits.api.RuleUnit<T><br/>[2023-05-29T13:03:19.034Z]   found:    org.drools.ruleunits.api.RuleUnit<capture#1 of ? extends org.drools.ruleunits.api.RuleUnitData><br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-29T13:03:19.034Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-runtimes/drools/kogito-drools/src/test/resources<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] No sources to compile<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Tests are skipped.<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-runtimes/drools/kogito-drools/target/kogito-drools-2.0.0-SNAPSHOT.jar<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Skipping packaging of the test-jar<br/>[2023-05-29T13:03:19.034Z] [INFO] <br/>[2023-05-29T13:03:19.034Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ kogito-drools ---<br/>[2023-05-29T13:03:19.034Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-runtimes/drools/kogito-drools/target/kogito-drools-2.0.0-SNAPSHOT-sources.jar<br/>[2023-05-29T13:03:19.03 [...]

2023-05-29 13:38 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1005` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1005/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-29T13:36:34.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-29T13:36:34.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-29T13:36:34.222Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-29T13:36:34.222Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-29T13:36:34.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-29T13:36:34.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-29T13:36:34.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-29T13:36:34.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-29T13:36:34.222Z] Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task<br/>[2023-05-29T13:36:34.222Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:100)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-29T13:36:34.222Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-29T13:36:34.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-29T13:36:34.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-29T13:36:34.222Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-29T13:36:34.222Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-29T13:36:34.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-29T13:36:34.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-29T13:36:34.223Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-29T13:36:34.223Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-29T13:36:34.223Z] Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'pnpm install --fetch-retry-mintimeout=50000 --fetch-retries=10 --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed.<br/>[2023-05-29T13:36:34.223Z]     at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute (NodeTaskExecutor.java:63)<br/>[2023-05-29T13:36:34.223Z]     at com.github.eirslett.maven.plugins.frontend.mojo.PnpmMojo.execute (PnpmMojo.java:62)<br/>[2023-05-29T13:36:34.223Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-29T13:36:34.223Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-29 [...]

2023-05-29 16:02 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1006` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1006/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.022 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.381 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.022 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.422 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [  1.492 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.021 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [01:11 min]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [ 20.306 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [ 46.710 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [ 20.238 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 17.562 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.021 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.251 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [ 11.560 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot FAILURE [  6.406 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [ 20.739 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [ 11.104 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.019 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  4.782 s]<br/>[2023-05-29T16:00:33.930Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-29T16:00:33.930Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-29T16:00:33.930Z] [INFO] BUILD FAILURE<br/>[2023-05-29T16:00:33.930Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-29T16:00:33.930Z] [INFO] Total time:  22:13 min<br/>[2023-05-29T16:00:33.930Z] [INFO] Finished at: 2023-05-29T12:00:32-04:00<br/>[2023-05-29T16:00:33.930Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-29T16:00:33.930Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm build) on project kogito-apps-ui-packages: Failed to run task: 'pnpm run build:prod --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]<br/>[2023-05-29T16:00:33.930Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm build) on project kogito-apps-ui-packages: Failed to run task<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-29T16:00:33.930Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-29T16:00:33.930Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-29T16:00:33.930Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-29T16:00:33.930Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-29T16:00:33.930Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-29T16:00:33.930Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-29T16:00:33.930Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-29T16:00:33.930Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-29T16:00:33.930Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-29T16:00:33.930Z] Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task<br/>[2023-05-29T16:00:33.930Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:100)<br/>[2023-05-29T16:00:33.931Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-29T16:00:33.931Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-29T16:00:33.931Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-29T16:00:33.931Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-29T16:00:33.931Z]     at o [...]

2023-05-30 11:37 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1012` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1012/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-30T11:36:15.631Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-30T11:36:15.631Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-30T11:36:15.631Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-30T11:36:15.631Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-30T11:36:15.631Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-30T11:36:15.631Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-30T11:36:15.631Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-30T11:36:15.631Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-30T11:36:15.631Z] Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task<br/>[2023-05-30T11:36:15.631Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:100)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-30T11:36:15.631Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-30T11:36:15.632Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-30T11:36:15.632Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-30T11:36:15.632Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-30T11:36:15.632Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-30T11:36:15.632Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-30T11:36:15.632Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-30T11:36:15.632Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-30T11:36:15.632Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-30T11:36:15.632Z] Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm run build:prod --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed.<br/>[2023-05-30T11:36:15.632Z]     at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute (NodeTaskExecutor.java:63)<br/>[2023-05-30T11:36:15.632Z]     at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute (NpmMojo.java:62)<br/>[2023-05-30T11:36:15.632Z]     at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-30T11:36:15.632Z]     at org.apache.maven.lifecy [...]

2023-05-30 11:39 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1008` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1008/display/redirect

**Test results:**
- PASSED: 1623
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1008/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:38 min]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.025 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.221 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.809 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 23.367 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.539 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 18.428 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.279 s]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [01:07 min]<br/>[2023-05-30T11:39:34.047Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.181 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.022 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.818 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:50 min]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:49 min]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:17 min]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [11:28 min]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:09 min]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.025 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.021 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  6.018 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.407 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.023 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.517 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.552 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 45.688 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.064 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.290 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.501 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 33.213 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.437 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.494 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.044 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.264 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.589 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.297 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.390 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 31.045 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 58.832 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.230 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 12.419 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.024 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.021 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.149 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.020 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.242 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.933 s]<br/>[2023-05-30T11:39:34.048Z] [INFO] Kogito Apps :: Explainability Service Rest . [...]

2023-05-30 14:43 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1013` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1013/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:27 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.073 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  4.987 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 16.909 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.066 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.057 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  4.810 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.045 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.417 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 50.076 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [01:19 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.575 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  7.666 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  5.541 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  5.720 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [02:51 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 50.567 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 39.814 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 46.291 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.064 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.243 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 31.426 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 42.345 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 29.623 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.048 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.051 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.732 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.044 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.696 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 29.430 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.068 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [04:11 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:37 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [03:36 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [02:12 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:52 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.091 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.946 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:35 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:38 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [06:15 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [02:53 min]<br/>[2023-05-30T14:40:25.028Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.474 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [ 12.615 s]<br/>[2023-05-30T14:40:25.028Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-05-30T14:40:25.028Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-30T14:40:25.028Z] [INFO] BUILD FAILURE<br/>[2023-05-30T14:40:25.028Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-30T14:40:25.028Z] [INFO] Total time:  01:37 h<br/>[2023-05-30T14:40:25.028Z] [INFO] Finished at: 2023-05-30T10:40:25-04:00<br/>[2023-05-30T14:40:25.028Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-30T14:40:25.028Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (pnpm build) on project kogito-apps-ui-packages: Failed to run task: 'npm run build:prod --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]<br/>[2023-05-30T14:40:25.028Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (pnpm build) on project kogito-apps-ui-packages: Failed to run task<br/>[2023-05-30T14:40:25.028Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-05-30T14:40:25.028Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-30T14:40:25.028Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-30T14:40:25.028Z]     at org.apache.maven [...]

2023-05-31 10:28 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1020` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1020/display/redirect

**Test results:**
- PASSED: 1624
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.024 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.022 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.202 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.619 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.861 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.163 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.506 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.028 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 58.581 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.824 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.026 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.757 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:46 min]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:49 min]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:10 min]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:00 min]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:09 min]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.023 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.675 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.356 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.020 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.337 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.449 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 43.333 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.045 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.352 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.512 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 34.271 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.445 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.511 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.021 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.446 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.428 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.291 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.405 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.064 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 57.692 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.263 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.701 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.022 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.021 s]<br/>[2023-05-31T10:28:20.251Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.085 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.225 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.609 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 49.721 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.165 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.676 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.714 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.282 s]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [02:00 min]<br/>[2023-05-31T10:28:20.252Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... [...]

2023-05-31 11:15 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1022` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1022/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-31T11:14:08.147Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-05-31T11:14:08.147Z] [INFO] Number of files to be formatted: 2<br/>[2023-05-31T11:14:08.147Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-05-31T11:14:08.147Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-05-31T11:14:08.147Z] [INFO] Skipped:                         2 file(s)<br/>[2023-05-31T11:14:08.147Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-05-31T11:14:08.147Z] [INFO] Approximate time taken:          0s<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] Processed 2 files in 00:00.010 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T11:14:08.147Z] [INFO] Copying 6 resources<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T11:14:08.147Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/../../ui-packages/packages/runtime-tools-dev-ui-webapp/dist<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T11:14:08.147Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/../../ui-packages/packages/runtime-tools-dev-ui-webapp/dist/resources<br/>[2023-05-31T11:14:08.147Z] [INFO] <br/>[2023-05-31T11:14:08.147Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:08.147Z] [INFO] Changes detected - recompiling the module!<br/>[2023-05-31T11:14:08.147Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-05-31T11:14:09.069Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[67,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-05-31T11:14:09.069Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[71,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-05-31T11:14:09.069Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[71,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-05-31T11:14:09.069Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[81,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-05-31T11:14:09.069Z] [INFO] <br/>[2023-05-31T11:14:09.069Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T11:14:09.069Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T11:14:09.069Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-05-31T11:14:09.069Z] [INFO] <br/>[2023-05-31T11:14:09.069Z] [INFO] --- mav [...]

2023-05-31 12:51 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1024` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1024/display/redirect

**Test results:**
- PASSED: 1624
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.031 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.024 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.176 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.672 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 23.512 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.718 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 19.799 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.558 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [01:01 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.780 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.026 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 15.808 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:51 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:59 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:15 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:12 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:07 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.026 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.883 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.400 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.023 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.434 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.466 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 44.424 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.021 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.325 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.505 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 35.015 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.023 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.459 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.615 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.022 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  5.704 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [  6.337 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.023 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.331 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.545 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 31.882 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:00 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.112 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 10.729 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.021 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.021 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.271 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.021 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.219 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 35.138 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 51.103 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.166 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.800 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.591 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.241 s]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [02:02 min]<br/>[2023-05-31T12:51:19.449Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... [...]

2023-05-31 12:58 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1025` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1025/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-31T12:57:22.149Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-05-31T12:57:22.149Z] [INFO] Number of files to be formatted: 2<br/>[2023-05-31T12:57:22.149Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-05-31T12:57:22.149Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-05-31T12:57:22.149Z] [INFO] Skipped:                         2 file(s)<br/>[2023-05-31T12:57:22.149Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-05-31T12:57:22.149Z] [INFO] Approximate time taken:          0s<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T12:57:22.149Z] [INFO] Copying 6 resources<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T12:57:22.149Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/../../ui-packages/packages/runtime-tools-dev-ui-webapp/dist<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T12:57:22.149Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/../../ui-packages/packages/runtime-tools-dev-ui-webapp/dist/resources<br/>[2023-05-31T12:57:22.149Z] [INFO] <br/>[2023-05-31T12:57:22.149Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.149Z] [INFO] Changes detected - recompiling the module!<br/>[2023-05-31T12:57:22.149Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-05-31T12:57:22.708Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[67,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-05-31T12:57:22.708Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[71,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-05-31T12:57:22.708Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[71,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-05-31T12:57:22.708Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[81,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-05-31T12:57:22.708Z] [INFO] <br/>[2023-05-31T12:57:22.708Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T12:57:22.708Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T12:57:22.709Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-05-31T12:57:22.709Z] [INFO] <br/>[2023-05-31T12:57:22.709Z] [INFO] --- mav [...]

2023-05-31 13:17 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1026` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1026/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (npn build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-05-31T13:17:18.441Z] + cd bc/kiegroup_kogito-apps/ui-packages<br/>[2023-05-31T13:17:18.441Z] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/durable-aa44c67d/script.sh: line 1: cd: bc/kiegroup_kogito-apps/ui-packages: No such file or directory<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-05-31T13:17:19.555Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1026/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-05-31 14:49 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1027` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1027/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-31T14:48:01.455Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] <br/>[2023-05-31T14:48:01.455Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-05-31T14:48:01.455Z] [INFO] <br/>[2023-05-31T14:48:01.455Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] Processed 2 files in 00:00.020 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-05-31T14:48:01.455Z] [INFO] <br/>[2023-05-31T14:48:01.455Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T14:48:01.455Z] [INFO] Copying 6 resources<br/>[2023-05-31T14:48:01.455Z] [INFO] <br/>[2023-05-31T14:48:01.455Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T14:48:01.455Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/../../ui-packages/packages/runtime-tools-dev-ui-webapp/dist<br/>[2023-05-31T14:48:01.455Z] [INFO] <br/>[2023-05-31T14:48:01.455Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T14:48:01.455Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/../../ui-packages/packages/runtime-tools-dev-ui-webapp/dist/resources<br/>[2023-05-31T14:48:01.455Z] [INFO] <br/>[2023-05-31T14:48:01.455Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:01.455Z] [INFO] Changes detected - recompiling the module!<br/>[2023-05-31T14:48:01.455Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-05-31T14:48:02.378Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[67,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-05-31T14:48:02.378Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[71,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-05-31T14:48:02.378Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[71,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-05-31T14:48:02.378Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[81,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-05-31T14:48:02.378Z] [INFO] <br/>[2023-05-31T14:48:02.378Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:02.378Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-05-31T14:48:02.378Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-05-31T14:48:02.378Z] [INFO] <br/>[2023-05-31T14:48:02.378Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:02.378Z] [INFO] No sources to compile<br/>[2023-05-31T14:48:02.378Z] [INFO] <br/>[2023-05-31T14:48:02.378Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:02.378Z] [INFO] No tests to run.<br/>[2023-05-31T14:48:02.378Z] [INFO] <br/>[2023-05-31T14:48:02.378Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:02.378Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/runtime-tools-quarkus-extension-deployment-2.0.0-SNAPSHOT.jar<br/>[2023-05-31T14:48:02.378Z] [INFO] <br/>[2023-05-31T14:48:02.378Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:02.378Z] [INFO] Skipping packaging of the test-jar<br/>[2023-05-31T14:48:02.378Z] [INFO] <br/>[2023-05-31T14:48:02.378Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-05-31T14:48:02.378Z] [INFO] Building jar: / [...]

2023-06-01 14:11 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1041` was: **ABORTED**
Possible explanation: Most probably a timeout, please review


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1041/display/redirect

**Test results:**
- PASSED: 1393
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-01T14:11:12.377Z] [INFO] |  +- org.kie.kogito:trusty-storage-common:jar:2.0.0-SNAPSHOT:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  \- org.kie.kogito:persistence-commons-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  +- io.quarkus:quarkus-smallrye-health:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  +- io.smallrye:smallrye-health:jar:3.3.1:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  |  \- io.smallrye:smallrye-health-api:jar:3.3.1:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  +- io.smallrye:smallrye-health-provided-checks:jar:3.3.1:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  \- io.quarkus:quarkus-jsonp:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |     \- org.glassfish:jakarta.json:jar:1.1.6:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  +- org.kie.kogito:kogito-addons-tracing-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  +- io.cloudevents:cloudevents-json-jackson:jar:2.3.0:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.36:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  \- io.quarkus:quarkus-oidc:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     +- io.quarkus:quarkus-security:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     +- io.quarkus:quarkus-oidc-common:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.30.1:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  \- io.vertx:vertx-web-client:jar:4.3.7:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  \- io.quarkus:quarkus-smallrye-jwt-build:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |     \- io.smallrye:smallrye-jwt-build:jar:3.6.0:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     \- io.smallrye:smallrye-jwt:jar:3.6.0:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |        +- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:jar:1.2:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |        +- org.bitbucket.b_c:jose4j:jar:0.9.2:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |        \- io.smallrye:smallrye-jwt-common:jar:3.6.0:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] +- org.kie.kogito:trusty-storage-infinispan:jar:2.0.0-SNAPSHOT:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |  \- org.kie.kogito:persistence-commons-infinispan:jar:2.0.0-SNAPSHOT:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     +- io.quarkus:quarkus-infinispan-client:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- io.quarkus:quarkus-elytron-security-common:jar:2.16.7.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  |  \- org.wildfly.security:wildfly-elytron-x500-cert:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  |     +- org.wildfly.security:wildfly-elytron-x500-cert-util:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  |     \- org.apache.sshd:sshd-common:jar:2.9.2:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  +- org.wildfly.security:wildfly-elytron-provider-util:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  \- org.wildfly.security:wildfly-elytron-password-impl:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- org.wildfly.security:wildfly-elytron-sasl-plain:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  \- org.wildfly.security:wildfly-elytron-permission:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.wildfly.security:wildfly-elytron-sasl:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  \- org.wildfly.security:wildfly-elytron-ssl:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  \- org.wildfly.security:wildfly-elytron-mechanism:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |     \- org.wildfly.security:wildfly-elytron-http:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- org.wildfly.security:wildfly-elytron-sasl-digest:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.wildfly.security:wildfly-elytron-mechanism-digest:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  \- org.wildfly.security:wildfly-elytron-util:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- org.wildfly.security:wildfly-elytron-sasl-external:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- org.wildfly.security:wildfly-elytron-sasl-oauth2:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  \- org.wildfly.security:wildfly-elytron-mechanism-oauth2:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- org.wildfly.security:wildfly-elytron-sasl-scram:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  \- org.wildfly.security:wildfly-elytron-mechanism-scram:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  +- org.infinispan:infinispan-client-hotrod:jar:14.0.6.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.infinispan:infinispan-commons:jar:14.0.6.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.wildfly.security:wildfly-elytron-sasl-gs2:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  +- org.wildfly.security:wildfly-elytron-mechanism-gssapi:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  |  \- org.wildfly.security:wildfly-elytron-security-manager-action:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- org.wildfly.security:wildfly-elytron-sasl-gssapi:jar:1.20.3.Final:compile<br/>[2023-06-01T14:11:12.377Z] [INFO] |     |  |  +- io.reactivex.rxjava3:rxjava:jar:3.1.4:compile<br/>[2023-06 [...]

2023-06-01 15:21 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1043` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1043/display/redirect

**Test results:**
- PASSED: 1624
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.196 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 21.161 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 48.128 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 26.864 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.310 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [01:03 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.042 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  5.236 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.850 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 24.935 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.294 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.028 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.335 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.027 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  2.107 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.029 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  7.000 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 20.992 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.029 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  7.154 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.697 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:31 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [03:04 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:45 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.024 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.022 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  5.804 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.810 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:51 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:34 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.024 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.021 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.235 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.636 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 22.828 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.664 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 17.660 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 23.693 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 55.692 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.212 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.023 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.859 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:50 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:48 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:07 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:57 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:04 min]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  5.592 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.311 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.029 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.394 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.552 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 42.869 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.047 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.331 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.549 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 35.050 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.045 s]<br/>[2023-06-01T15:21:14.083Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SU [...]

2023-06-01 15:27 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1044` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1044/display/redirect

**Test results:**
- PASSED: 1613
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1044/testReport/org.kie.kogito.index.service.messaging/OracleMessagingKafkaConsumerIT/testProcessInstanceEvent/">org.kie.kogito.index.service.messaging.OracleMessagingKafkaConsumerIT.testProcessInstanceEvent</a></summary>
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException<br/>Caused by: java.lang.reflect.InvocationTargetException<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.testcontainers.quarkus.OracleSqlQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.testcontainers.quarkus.OracleSqlQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Started.*'<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1044/testReport/org.kie.kogito.index.service/KeycloakPostgreSqlIndexingServiceIT/testUnauthorizedUserAccess/">org.kie.kogito.index.service.KeycloakPostgreSqlIndexingServiceIT.testUnauthorizedUserAccess</a></summary>
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException<br/>Caused by: java.lang.reflect.InvocationTargetException<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.testcontainers.quarkus.PostgreSqlQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.testcontainers.quarkus.PostgreSqlQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Started.*'<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-01T15:26:57.621Z] [INFO] <br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps ........................................ SUCCESS [  2.940 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.054 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.067 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.047 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  2.842 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.402 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 21.085 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 48.428 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 26.108 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  5.749 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons Oracle .......... SUCCESS [01:08 min]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: Parent SUCCESS [  0.182 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: API SUCCESS [  6.165 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL base SUCCESS [  5.499 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Persistence Commons :: Reporting :: PostgreSQL (Generic) SUCCESS [ 25.469 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: DB Scripts Collection Multi Repo .... SUCCESS [  0.446 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.031 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Internal :: API ..... SUCCESS [  3.194 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Jobs Recipients ..... SUCCESS [  0.029 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Recipient Common Http SUCCESS [  2.026 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Parent SUCCESS [  0.028 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Runtime SUCCESS [  7.041 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Http Recipient - Deployment SUCCESS [ 20.956 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Parent SUCCESS [  0.027 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Runtime SUCCESS [  6.160 s]<br/>[2023-06-01T15:26:57.621Z] [INFO] Kogito Apps :: Jobs Service :: Job Sink Recipient - Deployment SUCCESS [  3.732 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [02:30 min]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Jobs Service :: PostgreSQL .......... SUCCESS [03:07 min]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Jobs Service :: In-memory ........... SUCCESS [02:39 min]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Jobs :: Addons ...................... SUCCESS [  0.091 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Jobs Service Embedded Quarkus Addon - Parent ....... SUCCESS [  0.087 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Jobs Service Embedded Quarkus Addon - Runtime ...... SUCCESS [  8.155 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Jobs Service Embedded Quarkus Addon - Deployment ... SUCCESS [  4.711 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [02:59 min]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:34 min]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.045 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.105 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  1.381 s]<br/>[2023-06-01T15:26:57.622Z] [INFO] Kogito Apps :: Data Ind [...]

2023-06-02 09:59 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1051` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1051/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-02T09:56:48.175Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-02T09:56:48.175Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-02T09:56:48.175Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-02T09:56:48.175Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-02T09:56:48.175Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-02T09:56:48.175Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-02T09:56:48.175Z] [INFO] Approximate time taken:          0s<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] Processed 2 files in 00:00.007 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-02T09:56:48.175Z] [INFO] Copying 6 resources<br/>[2023-06-02T09:56:48.175Z] [INFO] <br/>[2023-06-02T09:56:48.175Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:48.175Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-02T09:56:48.430Z] [INFO] Copying 4084 resources<br/>[2023-06-02T09:56:51.686Z] [INFO] <br/>[2023-06-02T09:56:51.686Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:51.686Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-02T09:56:51.686Z] [INFO] Copying 2 resources<br/>[2023-06-02T09:56:51.686Z] [INFO] <br/>[2023-06-02T09:56:51.686Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:51.686Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-02T09:56:51.941Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-02T09:56:52.500Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-02T09:56:52.501Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-02T09:56:52.501Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-02T09:56:52.501Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-02T09:56:52.501Z] [INFO] <br/>[2023-06-02T09:56:52.501Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:52.501Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-02T09:56:52.501Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-02T09:56:52.501Z] [INFO] <br/>[2023-06-02T09:56:52.501Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:52.501Z] [INFO] No sources to compile<br/>[2023-06-02T09:56:52.501Z] [INFO] <br/>[2023-06-02T09:56:52.501Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-02T09:56:52.501Z] [INFO] No tests to run.<br/>[2023-06-02T09:56:52.501Z] [INFO] <br/>[2023-06-02T09:56:52.501Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-05 07:42 UTC, Ginxo commented
Jenkins run kogito-apps rhel8-tests

2023-06-05 07:47 UTC, kie-ci3 commented
**(tests rhel8) - kogito-apps job** `#1` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/kogito-apps.tests.kogito-apps.rhel8/1/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-06-05T07:47:49.560Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-06-05T07:47:50.801Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/kogito-apps.tests.kogito-apps.rhel8/1/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-06-05 07:51 UTC, Ginxo commented
Jenkins run kogito-apps rhel8-tests

2023-06-05 07:55 UTC, kie-ci3 commented
**(tests rhel8) - kogito-apps job** `#2` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/kogito-apps.tests.kogito-apps.rhel8/2/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
GitHub pull request #1706 of commit 271087d87fb9ecadddabd5c4dca318cebe80377b, has merge conflicts.<br/>Setting status of 271087d87fb9ecadddabd5c4dca318cebe80377b to PENDING with url https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/kogito-apps.tests.kogito-apps.rhel8/2/display/redirect and message: 'Build started.'<br/>Using context: (build) kogito-apps-rhel8<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh1572067555550268944.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision ad968e479904594f9f10e6b2baa6971baab3492d<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/custom/jobs/emingora/jobs/kogito-apps.tests.kogito-apps.rhel8/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/custom/jobs/emingora/jobs/kogito-apps.tests.kogito-apps.rhel8/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh7280514059576586431.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision ad968e479904594f9f10e6b2baa6971baab3492d (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f ad968e479904594f9f10e6b2baa6971baab3492d # timeout=10<br/>Commit message: "KOGITO-8455: added Release Notes creation methods (#275)"<br/>First time build. Skipping changelog.<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>‘rhos-d-kie-rhel8-large-osbs-docker-3243’ is offline<br/>Running on rhos-d-kie-rhel8-large-osbs-docker-3246 in /home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-06-05T07:54:13.493Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2023-06-05T07:54:13.581Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-d-kie-rhel8-large-osbs-docker-3246<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-06-05T07:54:16.171Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-06-05T07:54:16.297Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-06-05T07:54:16.842Z] Running in /home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-06-05T07:54:16.872Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-06-05T07:54:17.160Z] + df -h<br/>[2023-06-05T07:54:17.161Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-06-05T07:54:17.161Z] devtmpfs        3.8G     0  3.8G   0% /dev<br/>[2023-06-05T07:54:17.161Z] tmpfs           3.8G     0  3.8G   0% /dev/shm<br/>[2023-06-05T07:54:17.161Z] tmpfs           3.8G   17M  3.8G   1% /run<br/>[2023-06-05T07:54:17.161Z] tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup<br/>[2023-06-05T07:54:17.161Z] /dev/vda3        60G   22G   39G  36% /<br/>[2023-06-05T07:54:17.161Z] /dev/vda2       100M  5.8M   95M   6% /boot/efi<br/>[2023-06-05T07:54:17.161Z] tmpfs           770M     0  770M   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-06-05T07:54:17.185Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-06-05T07:54:17.481Z] + du -h -d1 /home/jenkins<br/>[2023-06-05T07:54:17.481Z] 4.0K	/home/jenkins/.ssh<br/>[2023-06-05T07:54:17.481Z] 0	/home/jenkins/go<br/>[2023-06-05T07:54:17.481Z] 8.0K	/home/jenkins/.vnc<br/>[2023-06-05T07:54:17.481Z] 8.0K	/home/jenkins/.m2<br/>[2023-06-05T07:54:17.481Z] 2.2G	/home/jenkins/git-repos<br/>[2023-06-05T07:54:17.481Z] 8.0K	/home/jenkins/.config<br/>[2023-06-05T07:54:17.481Z] 134M	/home/jenkins/virtenvs<br/>[2023-06-05T07:54:17.481Z] 4.0K	/home/jenkins/.cekit<br/>[2023-06-05T07:54:17.481Z] 26M	/home/jenkins/remoting<br/>[2023-06-05T07:54:17.481Z] 0	/home/jenkins/.cache<br/>[2023-06-05T07:54:17.481Z] 100M	/home/jenkins/tools<br/>[2023-06-05T07:54:17.481Z] 0	/home/jenkins/caches<br/>[2023-06-05T07:54:17.481Z] 24K	/home/jenkins/workspace<br/>[2023-06-05T07:54:17.481Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2023-06-05T07:54:17.504Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2023-06-05T07:54:17.791Z] + du -h -d3 /home/jenkins/workspace<br/>[2023-06-05T07:54:17.791Z] 16K	/home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8<br/>[2023-06-05T07:54:17.791Z] 8.0K	/home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8@tmp<br/>[2023-06-05T07:54:17.791Z] 24K	/home/jenkins/workspace/custom/emingora<br/>[2023-06-05T07:54:17.791Z] 24K	/home/jenkins/workspace/custom<br/>[2023-06-05T07:54:17.791Z] 24K	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] wit [...]

2023-06-05 09:43 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1062` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1062/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.027 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.894 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.024 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.248 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.537 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 46.770 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.137 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.604 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.339 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  3.942 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:56 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 31.320 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [01:04 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 29.094 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.019 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.069 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.013 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.609 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.387 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.020 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.020 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.335 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.020 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.411 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.478 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:19 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:02 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:56 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:45 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:25 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.024 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.268 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:14 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:07 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:12 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:57 min]<br/>[2023-06-05T09:41:20.966Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.021 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  4.641 s]<br/>[2023-06-05T09:41:20.966Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-06-05T09:41:20.966Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-05T09:41:20.966Z] [INFO] BUILD FAILURE<br/>[2023-06-05T09:41:20.966Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-05T09:41:20.966Z] [INFO] Total time:  01:05 h<br/>[2023-06-05T09:41:20.966Z] [INFO] Finished at: 2023-06-05T05:41:20-04:00<br/>[2023-06-05T09:41:20.966Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-05T09:41:20.967Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm install) on project kogito-apps-ui-packages: Failed to run task: 'pnpm install --fetch-retry-mintimeout=50000 --fetch-retries=10 --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]<br/>[2023-06-05T09:41:20.967Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm install) on project kogito-apps-ui-packages: Failed to run task<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-06-05T09:41:20.967Z]     at org.apache.maven.lifecycl [...]

2023-06-05 10:13 UTC, kie-ci3 commented
**(tests rhel8) - kogito-apps job** `#4` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/kogito-apps.tests.kogito-apps.rhel8/4/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-05T10:11:32.017Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.3:test<br/>[2023-06-05T10:11:32.017Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.3:test<br/>[2023-06-05T10:11:32.017Z] [INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test<br/>[2023-06-05T10:11:32.017Z] [INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.2:test<br/>[2023-06-05T10:11:32.017Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  \- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.16.7.Final:test<br/>[2023-06-05T10:11:32.018Z] [INFO] |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2023-06-05T10:11:32.018Z] [INFO] |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2023-06-05T10:11:32.018Z] [INFO] |  \- org.awaitility:awaitility:jar:4.2.0:test<br/>[2023-06-05T10:11:32.018Z] [INFO] \- org.kie.kogito:kogito-apps-ui-packages:pom:2.0.0-SNAPSHOT:compile<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-05T10:11:32.018Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-05T10:11:32.018Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-05T10:11:32.018Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-05T10:11:32.018Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-05T10:11:32.018Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-05T10:11:32.018Z] [INFO] Approximate time taken:          0s<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.018Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-05T10:11:32.018Z] [INFO] <br/>[2023-06-05T10:11:32.018Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.271Z] [INFO] Processed 2 files in 00:00.004 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-05T10:11:32.271Z] [INFO] <br/>[2023-06-05T10:11:32.271Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.271Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-05T10:11:32.271Z] [INFO] Copying 6 resources<br/>[2023-06-05T10:11:32.271Z] [INFO] <br/>[2023-06-05T10:11:32.271Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:32.271Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-05T10:11:32.271Z] [INFO] Copying 4084 resources<br/>[2023-06-05T10:11:34.778Z] [INFO] <br/>[2023-06-05T10:11:34.778Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:34.778Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-05T10:11:34.778Z] [INFO] Copying 2 resources<br/>[2023-06-05T10:11:34.778Z] [INFO] <br/>[2023-06-05T10:11:34.778Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-05T10:11:34.778Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-05T10:11:34.779Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-exte [...]

2023-06-07 10:58 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1084` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1084/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.018 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.835 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.197 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 32.776 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 46.155 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.144 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.424 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.503 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  3.849 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:56 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.141 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 26.327 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 31.112 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.019 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.066 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.385 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.753 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.305 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.022 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.023 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.354 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.038 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.482 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.015 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.019 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:20 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:59 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:51 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:45 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:26 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.026 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.272 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:02 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:07 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:01 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-06-07T10:56:33.995Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.022 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  4.273 s]<br/>[2023-06-07T10:56:33.995Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-06-07T10:56:33.995Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-07T10:56:33.995Z] [INFO] BUILD FAILURE<br/>[2023-06-07T10:56:33.995Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-07T10:56:33.995Z] [INFO] Total time:  01:04 h<br/>[2023-06-07T10:56:33.995Z] [INFO] Finished at: 2023-06-07T06:56:32-04:00<br/>[2023-06-07T10:56:33.995Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-07T10:56:33.995Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm install) on project kogito-apps-ui-packages: Failed to run task: 'pnpm install --fetch-retry-mintimeout=50000 --fetch-retries=10 --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]<br/>[2023-06-07T10:56:33.995Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm install) on project kogito-apps-ui-packages: Failed to run task<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-06-07T10:56:33.995Z]     at org.apache.maven.lifecycl [...]

2023-06-07 11:22 UTC, kie-ci3 commented
**(tests rhel8) - kogito-apps job** `#25` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/emingora/job/kogito-apps.tests.kogito-apps.rhel8/25/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.3:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.3:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.2:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  \- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.16.7.Final:test<br/>[2023-06-07T11:20:49.473Z] [INFO] |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2023-06-07T11:20:49.473Z] [INFO] |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2023-06-07T11:20:49.473Z] [INFO] |  \- org.awaitility:awaitility:jar:4.2.0:test<br/>[2023-06-07T11:20:49.473Z] [INFO] \- org.kie.kogito:kogito-apps-ui-packages:pom:2.0.0-SNAPSHOT:compile<br/>[2023-06-07T11:20:49.473Z] [INFO] <br/>[2023-06-07T11:20:49.473Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.473Z] [INFO] <br/>[2023-06-07T11:20:49.473Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.473Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.474Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.474Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.474Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-07T11:20:49.474Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-07T11:20:49.474Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-07T11:20:49.474Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-07T11:20:49.474Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-07T11:20:49.474Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-07T11:20:49.474Z] [INFO] Approximate time taken:          0s<br/>[2023-06-07T11:20:49.474Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.474Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-07T11:20:49.474Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.474Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.474Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-07T11:20:49.474Z] [INFO] <br/>[2023-06-07T11:20:49.474Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.728Z] [INFO] Processed 2 files in 00:00.016 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-07T11:20:49.728Z] [INFO] <br/>[2023-06-07T11:20:49.728Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.728Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T11:20:49.728Z] [INFO] Copying 6 resources<br/>[2023-06-07T11:20:49.728Z] [INFO] <br/>[2023-06-07T11:20:49.728Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:49.728Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T11:20:49.728Z] [INFO] Copying 4085 resources<br/>[2023-06-07T11:20:52.233Z] [INFO] <br/>[2023-06-07T11:20:52.233Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:52.233Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T11:20:52.233Z] [INFO] Copying 2 resources<br/>[2023-06-07T11:20:52.233Z] [INFO] <br/>[2023-06-07T11:20:52.233Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T11:20:52.233Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-07T11:20:52.233Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/custom/emingora/kogito-apps.tests.kogito-apps.rhel8/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-ex [...]

2023-06-07 15:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1085` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1085/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-07T15:45:15.898Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:15.898Z] [INFO] <br/>[2023-06-07T15:45:15.898Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:15.898Z] [INFO] <br/>[2023-06-07T15:45:15.898Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:15.898Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-07T15:45:15.898Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-07T15:45:15.898Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-07T15:45:15.898Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-07T15:45:15.898Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-07T15:45:15.898Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-07T15:45:15.898Z] [INFO] Approximate time taken:          0s<br/>[2023-06-07T15:45:15.898Z] [INFO] <br/>[2023-06-07T15:45:15.898Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:15.898Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-07T15:45:15.898Z] [INFO] <br/>[2023-06-07T15:45:15.898Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:15.898Z] [INFO] <br/>[2023-06-07T15:45:15.898Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:15.898Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-07T15:45:15.898Z] [INFO] <br/>[2023-06-07T15:45:15.898Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:16.153Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-07T15:45:16.153Z] [INFO] <br/>[2023-06-07T15:45:16.153Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:16.153Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T15:45:16.153Z] [INFO] Copying 6 resources<br/>[2023-06-07T15:45:16.153Z] [INFO] <br/>[2023-06-07T15:45:16.153Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:16.153Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T15:45:16.407Z] [INFO] Copying 4085 resources<br/>[2023-06-07T15:45:20.560Z] [INFO] <br/>[2023-06-07T15:45:20.560Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:20.560Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T15:45:20.560Z] [INFO] Copying 2 resources<br/>[2023-06-07T15:45:20.560Z] [INFO] <br/>[2023-06-07T15:45:20.560Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:20.560Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-07T15:45:20.560Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-07T15:45:20.815Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-07T15:45:20.815Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-07T15:45:20.815Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-07T15:45:20.815Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-07T15:45:20.815Z] [INFO] <br/>[2023-06-07T15:45:20.815Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:20.815Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-07T15:45:20.815Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-07T15:45:20.815Z] [INFO] <br/>[2023-06-07T15:45:20.815Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:20.815Z] [INFO] No sources to compile<br/>[2023-06-07T15:45:20.815Z] [INFO] <br/>[2023-06-07T15:45:20.815Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-07T15:45:20.815Z] [INFO] No tests to run.<br/>[2023-06-07T15:45:20.815Z] [INFO] <br/>[2023-06-07T15:45:20.815Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-07 18:01 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1086` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1086/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.019 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.048 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.909 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.018 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.198 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 32.951 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 46.892 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.162 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.409 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.445 s]<br/>[2023-06-07T17:59:42.081Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.047 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:58 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.564 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 26.982 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 30.329 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.019 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.068 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.944 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 28.811 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.717 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.021 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.022 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.391 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.023 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.396 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.083 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.031 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [03:23 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:00 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:55 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:47 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:29 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.045 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.305 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:03 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:09 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:06 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:56 min]<br/>[2023-06-07T17:59:42.082Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.024 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  4.315 s]<br/>[2023-06-07T17:59:42.082Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-06-07T17:59:42.082Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-07T17:59:42.082Z] [INFO] BUILD FAILURE<br/>[2023-06-07T17:59:42.082Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-07T17:59:42.082Z] [INFO] Total time:  01:04 h<br/>[2023-06-07T17:59:42.082Z] [INFO] Finished at: 2023-06-07T13:59:41-04:00<br/>[2023-06-07T17:59:42.082Z] [INFO] ------------------------------------------------------------------------<br/>[2023-06-07T17:59:42.082Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm install) on project kogito-apps-ui-packages: Failed to run task: 'pnpm install --fetch-retry-mintimeout=50000 --fetch-retries=10 --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]<br/>[2023-06-07T17:59:42.082Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm install) on project kogito-apps-ui-packages: Failed to run task<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-06-07T17:59:42.082Z]     at org.apache.maven.lifecycl [...]

2023-06-08 06:33 UTC, domhanak commented
@Sara4994 what's the status please? :)

2023-06-08 07:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1091` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1091/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Started by user Tristan<br/>Replayed #1085<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh11475041631775414804.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 353366e5edc4da983049c360133ec846ac50a3ce<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh15296137678786643525.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 353366e5edc4da983049c360133ec846ac50a3ce (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 353366e5edc4da983049c360133ec846ac50a3ce # timeout=10<br/>Commit message: "KOGITO-9275 Jenkins: Switch jobs to use RHEL8 (#276)"<br/> > git rev-list --no-walk 353366e5edc4da983049c360133ec846ac50a3ce # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel8&&docker&&kie-mem16g&&!built-in’<br/>Running on rhos-01-kie-rhel8-xlarge-docker-448 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.3'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision b6c1cb71b32e15fd0817c1192ea9c87ea39721d9 (origin/main)<br/>Commit message: "Quarkus 3: Restrict UI build memory (#984)"<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f b6c1cb71b32e15fd0817c1192ea9c87ea39721d9 # timeout=10<br/> > git rev-list --no-walk b6c1cb71b32e15fd0817c1192ea9c87ea39721d9 # timeout=10<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-06-08T07:46:27.749Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2023-06-08T07:46:27.836Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-rhel8-xlarge-docker-448<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-06-08T07:46:30.097Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-06-08T07:46:30.176Z] Archiving artifacts<br/>[Pipeline] withCredentials<br/>[2023-06-08T07:46:30.349Z] Masking supported pattern matches of $CYPRESS_BINARY_URL<br/>[Pipeline] {<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-06-08T07:46:30.814Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-06-08T07:46:30.847Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-06-08T07:46:31.130Z] + df -h<br/>[2023-06-08T07:46:31.131Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-06-08T07:46:31.131Z] devtmpfs        7.7G     0  7.7G   0% /dev<br/>[2023-06-08T07:46:31.131Z] tmpfs           7.7G     0  7.7G   0% /dev/shm<br/>[2023-06-08T07:46:31.131Z] tmpfs           7.7G   17M  7.7G   1% /run<br/>[2023-06-08T07:46:31.131Z] tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup<br/>[2023-06-08T07:46:31.131Z] /dev/vda3        80G   22G   59G  28% /<br/>[2023-06-08T07:46:31.131Z] /dev/vda2       100M  5.8M   95M   6% /boot/efi<br/>[2023-06-08T07:46:31.131Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-06-08T07:46:31.152Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-06-08T07:46:31.431Z] + du -h -d1 /home/jenkins<br/>[2023-06-08T07:46:31.432Z] 4.0K	/home/jenkins/.ssh<br/>[2023-06-08T07:46:31.432Z] 0	/home/jenkins/go<br/>[2023-06-08T07:46:31.432Z] 8.0K	/home/jenkins/.vnc<br/>[2023-06-08T07:46:31.432Z] 8.0K	/home/jenkins/.m2<br/>[2023-06-08T07:46:31.432Z] 2.2G	 [...]

2023-06-08 09:47 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1093` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1093/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-08T09:45:52.802Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-08T09:45:52.802Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-08T09:45:52.802Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-08T09:45:52.802Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-08T09:45:52.802Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-08T09:45:52.802Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-08T09:45:52.802Z] [INFO] Approximate time taken:          0s<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T09:45:52.802Z] [INFO] Copying 6 resources<br/>[2023-06-08T09:45:52.802Z] [INFO] <br/>[2023-06-08T09:45:52.802Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:52.802Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T09:45:53.361Z] [INFO] Copying 4085 resources<br/>[2023-06-08T09:45:57.530Z] [INFO] <br/>[2023-06-08T09:45:57.530Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:57.530Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T09:45:57.530Z] [INFO] Copying 2 resources<br/>[2023-06-08T09:45:57.530Z] [INFO] <br/>[2023-06-08T09:45:57.530Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:57.530Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-08T09:45:57.530Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-08T09:45:57.785Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-08T09:45:57.785Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-08T09:45:57.785Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-08T09:45:57.785Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-08T09:45:57.785Z] [INFO] <br/>[2023-06-08T09:45:57.785Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:57.785Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T09:45:57.785Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-08T09:45:57.785Z] [INFO] <br/>[2023-06-08T09:45:57.785Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:57.785Z] [INFO] No sources to compile<br/>[2023-06-08T09:45:57.785Z] [INFO] <br/>[2023-06-08T09:45:57.785Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T09:45:57.785Z] [INFO] No tests to run.<br/>[2023-06-08T09:45:57.785Z] [INFO] <br/>[2023-06-08T09:45:57.785Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-08 11:22 UTC, radtriste commented
jenkins run kogito-apps tests

2023-06-08 13:03 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1095` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1095/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-08T13:01:01.828Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.828Z] [INFO] <br/>[2023-06-08T13:01:01.828Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.828Z] [INFO] <br/>[2023-06-08T13:01:01.828Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.828Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-08T13:01:01.828Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-08T13:01:01.828Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-08T13:01:01.828Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-08T13:01:01.828Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-08T13:01:01.829Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-08T13:01:01.829Z] [INFO] Approximate time taken:          0s<br/>[2023-06-08T13:01:01.829Z] [INFO] <br/>[2023-06-08T13:01:01.829Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.829Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-08T13:01:01.829Z] [INFO] <br/>[2023-06-08T13:01:01.829Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.829Z] [INFO] <br/>[2023-06-08T13:01:01.829Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.829Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-08T13:01:01.829Z] [INFO] <br/>[2023-06-08T13:01:01.829Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.829Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-08T13:01:01.829Z] [INFO] <br/>[2023-06-08T13:01:01.829Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.829Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T13:01:01.829Z] [INFO] Copying 6 resources<br/>[2023-06-08T13:01:01.829Z] [INFO] <br/>[2023-06-08T13:01:01.829Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:01.829Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T13:01:02.083Z] [INFO] Copying 4085 resources<br/>[2023-06-08T13:01:07.340Z] [INFO] <br/>[2023-06-08T13:01:07.340Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:07.340Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T13:01:07.340Z] [INFO] Copying 2 resources<br/>[2023-06-08T13:01:07.340Z] [INFO] <br/>[2023-06-08T13:01:07.340Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:07.340Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-08T13:01:07.340Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-08T13:01:07.340Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-08T13:01:07.340Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-08T13:01:07.340Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-08T13:01:07.340Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-08T13:01:07.340Z] [INFO] <br/>[2023-06-08T13:01:07.340Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:07.340Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-08T13:01:07.340Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-08T13:01:07.340Z] [INFO] <br/>[2023-06-08T13:01:07.340Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:07.340Z] [INFO] No sources to compile<br/>[2023-06-08T13:01:07.340Z] [INFO] <br/>[2023-06-08T13:01:07.340Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-08T13:01:07.340Z] [INFO] No tests to run.<br/>[2023-06-08T13:01:07.340Z] [INFO] <br/>[2023-06-08T13:01:07.340Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-08 13:53 UTC, Sara4994 commented
> @Sara4994 what's the status please? :)

@domhanak I am still working with few other people in find ways to fix the pipeline(we are almost there). Will update you as soon build passes fine.

2023-06-09 12:46 UTC, radtriste commented
jenkins rerun kogito-apps tests

2023-06-09 12:51 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1103` was: **ABORTED**
Possible explanation: Most probably a timeout, please review


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1103/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-09T12:50:59.904Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (no-managed-deps) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- build-helper-maven-plugin:3.0.0:add-source (default) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Source directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/generated-sources/annotations added.<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- build-helper-maven-plugin:3.0.0:parse-version (default) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T12:50:59.904Z] [INFO] Copying 10 resources<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] No sources to compile<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T12:50:59.904Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/src/test/resources<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-09T12:50:59.904Z] [INFO] Compiling 11 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/test-classes<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:50:59.904Z] [INFO] Tests are skipped.<br/>[2023-06-09T12:50:59.904Z] [INFO] <br/>[2023-06-09T12:50:59.904Z] [INFO] --- arch-unit-maven-plugin:2.9.1:arch-test (default) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/kie-pmml-models-scorecard-tests-8.40.0-SNAPSHOT.jar<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/kie-pmml-models-scorecard-tests-8.40.0-SNAPSHOT-sources.jar<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/kie-pmml-models-scorecard-tests-8.40.0-SNAPSHOT-test-sources.jar<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/kie-pmml-models-scorecard-tests-8.40.0-SNAPSHOT-tests.jar<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (default) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [WARNING] artifact org.kie:kie-pmml-models-scorecard-tests:test-jar:tests:8.40.0-SNAPSHOT already attached, replace previous instance<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Tests are skipped.<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Tests are skipped.<br/>[2023-06-09T12:51:00.159Z] [INFO] <br/>[2023-06-09T12:51:00.159Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ kie-pmml-models-scorecard-tests ---<br/>[2023-06-09T12:51:00.159Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/target/kie-pmml-models-scorecard-tests-8.40.0-SNAPSHOT.jar to /home/jenkins/.m2/repository/org/kie/kie-pmml-models-scorecard-tests/8.40.0-SNAPSHOT/kie-pmml-models-scorecard-tests-8.40.0-SNAPSHOT.jar<br/>[2023-06-09T12:51:00.159Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-scorecard/kie-pmml-models-scorecard-tests/pom.xml to /home/jenkins/.m2/repository/org/kie/kie-pmml-models-scorecard-tests/8.40.0-SNAPSHOT/kie-pmml-mo [...]

2023-06-09 14:26 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1104` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1104/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-09T14:24:39.008Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-09T14:24:39.008Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-09T14:24:39.008Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-09T14:24:39.008Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-09T14:24:39.008Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-09T14:24:39.008Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-09T14:24:39.008Z] [INFO] Approximate time taken:          0s<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T14:24:39.008Z] [INFO] Copying 6 resources<br/>[2023-06-09T14:24:39.008Z] [INFO] <br/>[2023-06-09T14:24:39.008Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:39.008Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T14:24:39.262Z] [INFO] Copying 4085 resources<br/>[2023-06-09T14:24:43.420Z] [INFO] <br/>[2023-06-09T14:24:43.420Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:43.420Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T14:24:43.420Z] [INFO] Copying 2 resources<br/>[2023-06-09T14:24:43.420Z] [INFO] <br/>[2023-06-09T14:24:43.420Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:43.674Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-09T14:24:43.674Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-09T14:24:43.928Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-09T14:24:43.928Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-09T14:24:43.928Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-09T14:24:43.928Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-09T14:24:43.928Z] [INFO] <br/>[2023-06-09T14:24:43.928Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:43.928Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T14:24:43.928Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-09T14:24:43.928Z] [INFO] <br/>[2023-06-09T14:24:43.928Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:43.928Z] [INFO] No sources to compile<br/>[2023-06-09T14:24:43.928Z] [INFO] <br/>[2023-06-09T14:24:43.928Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T14:24:43.928Z] [INFO] No tests to run.<br/>[2023-06-09T14:24:43.928Z] [INFO] <br/>[2023-06-09T14:24:43.928Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-09 16:07 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1106` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1106/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-09T16:05:04.287Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-09T16:05:04.287Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-09T16:05:04.287Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-09T16:05:04.287Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-09T16:05:04.287Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-09T16:05:04.287Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-09T16:05:04.287Z] [INFO] Approximate time taken:          0s<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] Processed 2 files in 00:00.004 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T16:05:04.287Z] [INFO] Copying 6 resources<br/>[2023-06-09T16:05:04.287Z] [INFO] <br/>[2023-06-09T16:05:04.287Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:04.287Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T16:05:04.287Z] [INFO] Copying 4085 resources<br/>[2023-06-09T16:05:08.442Z] [INFO] <br/>[2023-06-09T16:05:08.442Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:08.442Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T16:05:08.442Z] [INFO] Copying 2 resources<br/>[2023-06-09T16:05:08.442Z] [INFO] <br/>[2023-06-09T16:05:08.442Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:08.442Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-09T16:05:08.442Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-09T16:05:08.442Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-09T16:05:08.442Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-09T16:05:08.442Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-09T16:05:08.442Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-09T16:05:08.442Z] [INFO] <br/>[2023-06-09T16:05:08.442Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:08.442Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-09T16:05:08.442Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-09T16:05:08.442Z] [INFO] <br/>[2023-06-09T16:05:08.442Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:08.442Z] [INFO] No sources to compile<br/>[2023-06-09T16:05:08.442Z] [INFO] <br/>[2023-06-09T16:05:08.442Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-09T16:05:08.442Z] [INFO] No tests to run.<br/>[2023-06-09T16:05:08.442Z] [INFO] <br/>[2023-06-09T16:05:08.442Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-12 08:16 UTC, radtriste commented
jenkins rerun kogito-apps tests

2023-06-12 10:02 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1114` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1114/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T10:00:17.034Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-12T10:00:17.034Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-12T10:00:17.034Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-12T10:00:17.034Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-12T10:00:17.034Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-12T10:00:17.034Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-12T10:00:17.034Z] [INFO] Approximate time taken:          0s<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] Processed 2 files in 00:00.004 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T10:00:17.034Z] [INFO] Copying 6 resources<br/>[2023-06-12T10:00:17.034Z] [INFO] <br/>[2023-06-12T10:00:17.034Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:17.034Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T10:00:17.288Z] [INFO] Copying 4085 resources<br/>[2023-06-12T10:00:21.438Z] [INFO] <br/>[2023-06-12T10:00:21.438Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:21.438Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T10:00:21.438Z] [INFO] Copying 2 resources<br/>[2023-06-12T10:00:21.438Z] [INFO] <br/>[2023-06-12T10:00:21.438Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:21.438Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-12T10:00:21.438Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-12T10:00:21.693Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-12T10:00:21.693Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-12T10:00:21.693Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-12T10:00:21.693Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-12T10:00:21.693Z] [INFO] <br/>[2023-06-12T10:00:21.693Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:21.693Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T10:00:21.693Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-12T10:00:21.693Z] [INFO] <br/>[2023-06-12T10:00:21.693Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:21.693Z] [INFO] No sources to compile<br/>[2023-06-12T10:00:21.693Z] [INFO] <br/>[2023-06-12T10:00:21.693Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T10:00:21.693Z] [INFO] No tests to run.<br/>[2023-06-12T10:00:21.693Z] [INFO] <br/>[2023-06-12T10:00:21.693Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-12 11:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1117` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1117/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T11:45:54.487Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-06-12T11:45:54.487Z] [INFO] Number of files to be formatted: 2<br/>[2023-06-12T11:45:54.487Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-06-12T11:45:54.487Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-06-12T11:45:54.487Z] [INFO] Skipped:                         2 file(s)<br/>[2023-06-12T11:45:54.487Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-06-12T11:45:54.487Z] [INFO] Approximate time taken:          0s<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] Processed 2 files in 00:00.004 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T11:45:54.487Z] [INFO] Copying 6 resources<br/>[2023-06-12T11:45:54.487Z] [INFO] <br/>[2023-06-12T11:45:54.487Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:45:54.487Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T11:45:54.742Z] [INFO] Copying 4085 resources<br/>[2023-06-12T11:46:01.263Z] [INFO] <br/>[2023-06-12T11:46:01.263Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:46:01.263Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T11:46:01.263Z] [INFO] Copying 2 resources<br/>[2023-06-12T11:46:01.263Z] [INFO] <br/>[2023-06-12T11:46:01.263Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:46:01.263Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-12T11:46:01.263Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-06-12T11:46:01.517Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-12T11:46:01.517Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-06-12T11:46:01.518Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-06-12T11:46:01.518Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-06-12T11:46:01.518Z] [INFO] <br/>[2023-06-12T11:46:01.518Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:46:01.518Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T11:46:01.518Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-06-12T11:46:01.518Z] [INFO] <br/>[2023-06-12T11:46:01.518Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:46:01.518Z] [INFO] No sources to compile<br/>[2023-06-12T11:46:01.518Z] [INFO] <br/>[2023-06-12T11:46:01.518Z] [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-06-12T11:46:01.518Z] [INFO] No tests to run.<br/>[2023-06-12T11:46:01.518Z] [INFO] <br/>[2023-06-12T11:46:01.518Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ runtime [...]

2023-06-12 11:59 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1118` was: **ABORTED**
Possible explanation: Most probably a timeout, please review


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1118/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  \- org.kie:efesto-compilation-manager-api:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  \- org.kie:kie-pmml-commons:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |     +- org.slf4j:slf4j-api:jar:1.7.30:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |     \- org.apache.commons:commons-text:jar:1.10.0:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |        \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] +- org.kie:kie-pmml-evaluator-core:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  +- org.kie:kie-pmml-evaluator-api:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  +- org.drools:drools-core:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.kie:kie-internal:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.kie:kie-util-xml:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.drools:drools-wiring-api:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.drools:drools-base:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  |  \- org.drools:drools-util:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.drools:drools-wiring-static:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  +- org.drools:drools-io:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  |  \- commons-codec:commons-codec:jar:1.15:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  \- org.kie:efesto-runtime-manager-core:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |     \- org.kie:efesto-common-core:jar:8.40.0-SNAPSHOT:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |        \- com.fasterxml.jackson.core:jackson-databind:jar:2.15.2:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |           \- com.fasterxml.jackson.core:jackson-core:jar:2.15.2:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] +- org.assertj:assertj-core:jar:3.23.1:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] |  \- net.bytebuddy:byte-buddy:jar:1.12.18:compile<br/>[2023-06-12T11:59:32.007Z] [INFO] +- org.mockito:mockito-core:jar:4.11.0:test<br/>[2023-06-12T11:59:32.007Z] [INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.19:test<br/>[2023-06-12T11:59:32.007Z] [INFO] |  \- org.objenesis:objenesis:jar:3.3:test<br/>[2023-06-12T11:59:32.007Z] [INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.9.2:test<br/>[2023-06-12T11:59:32.007Z] [INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2023-06-12T11:59:32.007Z] [INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.9.2:test<br/>[2023-06-12T11:59:32.007Z] [INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2023-06-12T11:59:32.007Z] [INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.9.2:test<br/>[2023-06-12T11:59:32.007Z] [INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.9.2:test<br/>[2023-06-12T11:59:32.007Z] [INFO] \- org.junit.jupiter:junit-jupiter-params:jar:5.9.2:test<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (no-duplicate-declared-dependencies) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (ban-blacklisted-dependencies) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (no-managed-deps) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Skipping Rule Enforcement.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- build-helper-maven-plugin:3.0.0:add-source (default) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Source directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/target/generated-sources/annotations added.<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- build-helper-maven-plugin:3.0.0:parse-version (default) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-06-12T11:59:32.007Z] [INFO] Copying 1 resource<br/>[2023-06-12T11:59:32.007Z] [INFO] <br/>[2023-06-12T11:59:32.007Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kie-pmml-models-tree-evaluator ---<br/>[2023-06-12T11:59:32.007Z] [INFO] Changes detected - recompiling the module!<br/>[2023-06-12T11:59:32.007Z] [INFO] Compiling 1 source file to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_drools/kie-pmml-trusty/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/target/classes<br/>[2023-06-12T11:59:32.007Z] [WARNING] unknown enum constant javax.xml.bind.annotation.XmlAccessType.NONE<br/>[2023-06-12T11:59:32.007Z]   reason: class file for javax.xml.bind.annotation.XmlAccessType not found<br/>[2023-06-12T11:59:32.007Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_dr [...]

2023-06-12 12:24 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1119` was: **ABORTED**
Possible explanation: Most probably a timeout, please review


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1119/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,204 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.testcontainers.KogitoGenericContainer:75] (docker-java-stream-1624104122) STDERR: INFO  2023-06-12 12:23:20,204 [shard 0] admin_api_server - admin_server.cc:96 - Started HTTP admin service listening at {{:{host: 0.0.0.0, port: 9644}}}<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,205 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.testcontainers.KogitoGenericContainer:75] (docker-java-stream-1624104122) STDERR: INFO  2023-06-12 12:23:20,204 [shard 0] redpanda::main - application.cc:1013 - Started Pandaproxy listening at {{:{host: 0.0.0.0, port: 8082}}}<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,205 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.testcontainers.KogitoGenericContainer:75] (docker-java-stream-1624104122) STDERR: INFO  2023-06-12 12:23:20,204 [shard 0] redpanda::main - application.cc:1021 - Started Schema Registry listening at {{:{host: 0.0.0.0, port: 8081}}}<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,205 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.testcontainers.KogitoGenericContainer:75] (docker-java-stream-1624104122) STDERR: INFO  2023-06-12 12:23:20,204 [shard 0] redpanda::main - application.cc:1026 - Successfully started Redpanda!<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,205 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.testcontainers.KogitoGenericContainer:75] (docker-java-stream-1624104122) STDERR: INFO  2023-06-12 12:23:20,204 [shard 0] storage - segment.cc:635 - Creating new segment /var/lib/redpanda/data/redpanda/controller/0_0/0-1-v1.log<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,214 eng-jenkins-csb-business-automation INFO  [🐳 [vectorized/redpanda:v21.11.8]:520] (pool-11-thread-1) Container vectorized/redpanda:v21.11.8 started in PT0.700296S<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:20,214 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.testcontainers.KogitoKafkaContainer:70] (pool-11-thread-1) Kafka servers: OUTSIDE://localhost:32845<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:21,459 eng-jenkins-csb-business-automation INFO  [org.infinispan.HOTROD:58] (main) ISPN004108: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:21,701 eng-jenkins-csb-business-automation INFO  [org.infinispan.HOTROD:368] (main) ISPN004021: Infinispan version: Infinispan 'Flying Saucer' 14.0.6.Final<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:21,803 eng-jenkins-csb-business-automation WARN  [org.infinispan.HOTROD:335] (HotRod-client-async-pool-1-1) ISPN004005: Error received from the server: org.infinispan.server.hotrod.CacheNotFoundException: Cache with name 'JOB_DETAILS_V2' not found amongst the configured caches<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:22,015 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:89] (main) SRMSG18229: Configured topics for channel 'kogito-job-service-job-request-events-v2': [kogito-job-service-job-request-events-v2]<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:22,035 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:290] (main) SRMSG18214: Key deserializer omitted, using String as default<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:22,243 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:89] (main) SRMSG18229: Configured topics for channel 'kogito-job-service-job-request-events': [kogito-job-service-job-request-events]<br/>[2023-06-12T12:23:23.570Z] 2023-06-12 08:23:22,255 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:290] (main) SRMSG18214: Key deserializer omitted, using String as default<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,326 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:84] (smallrye-kafka-producer-thread-0) SRMSG18258: Kafka producer kafka-producer-kogito-job-service-job-request-events-emitter, connected to Kafka brokers 'localhost:32845', is configured to write records to 'kogito-job-service-job-request-events'<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,460 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:141] (smallrye-kafka-consumer-thread-0) SRMSG18257: Kafka consumer kogito-jobs-service-v2, connected to Kafka brokers 'localhost:32845', belongs to the 'kogito-jobs-service' consumer group and is configured to poll records from [kogito-job-service-job-request-events-v2]<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,461 eng-jenkins-csb-business-automation INFO  [io.smallrye.reactive.messaging.kafka:141] (smallrye-kafka-consumer-thread-1) SRMSG18257: Kafka consumer kogito-jobs-service, connected to Kafka brokers 'localhost:32845', belongs to the 'kogito-jobs-service' consumer group and is configured to poll records from [kogito-job-service-job-request-events]<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,472 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.jobs.service.management.JobServiceInstanceManager:193] (main) Current Job Service Instance JobServiceManagementInfo[id=kogito-jobs-service-leader, lastHeartbeat=2023-06-12T12:23:22.471Z, token=8a733b17-f690-41e1-9a66-abc0b0766e6e]<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,475 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.jobs.service.management.JobServiceInstanceManager:154] (main) SET Leader JobServiceManagementInfo[id=kogito-jobs-service-leader, lastHeartbeat=2023-06-12T12:23:22.475Z, token=8a733b17-f690-41e1-9a66-abc0b0766e6e]<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,478 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.jobs.service.management.JobServiceInstanceManager:123] (main) Enabled communication for leader instance<br/>[2023-06-12T12:23:23.571Z] 2023-06-12 08:23:22,479 eng-jenkins-csb-business-automation INFO  [org.kie.kogito.jobs.service.management.JobServiceInstanceManager:102] (main) Initial leader check completed<br/>[2023-06-12T12:23:23.571Z] INFO  2023-06-12 12:23:22,658 [shard 0] cluster - topics_frontend.cc:71 - Create topics {{configuration: { topic: {ns: {kafka}, topic: {kogito-job-service-job-request-events-v2}}, partition_count: 1, replication_factor: 1, properties: { compression: {nullopt}, cleanup_policy_bitflags: {nullopt}, compaction_strategy: {nullopt}, retention_bytes: {}, retention_duration_ms: {}, segment_size: {nullopt}, timestamp_type: {nullopt}, recovery_enabled: {nullopt}, shadow_indexing: {nullopt} }}, custom_assignments: {}}}<br/>[2023-06-12T12:23:23.571Z] INFO  2023-06-12 12:23:22,658 [shard 0] cluster - topics_frontend.cc:71 - Create topics {{configuration: { topic: {ns: {kafka}, topic: {kogito-job-service-job-request-events}}, partition_count: 1, replication_factor: 1, properties: { compression: {nullopt}, cleanup_policy_bitflags: {nullopt}, compaction_strategy: {nullopt}, retention_bytes: {}, retention_duration_ms: {}, segment_size: {nullopt}, timestamp_type: {nullopt}, recov [...]

2023-06-12 12:55 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1120` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1120/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:54.406Z] [INFO] packages/management-console-webapp test:it: [1] orderBy args:  { lastUpdate: 'DESC' }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] offset :  0<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] limit :  10<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] result length: 10<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.968Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T12:53:56.969Z] [INFO] packages [...]

2023-06-12 13:28 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1121` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1121/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+executor-graphql-ws@0.0.14_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/graphql-ws@5.12.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+wrap@9.4.2_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/graphql-config@4.5.0_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/graphql-config@4.5.0_graphql@14.3.1/node_modules/graphql-config/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/graphql-request@6.0.0_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+typescript@2.8.8_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+introspection@2.2.3_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+visitor-plugin-common@2.13.8_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+optimize@1.3.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+relay-operation-optimizer@6.5.18_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+relay-operation-optimizer@6.5.18_graphql@14.3.1/node_modules/@graphql-tools/relay-operation-optimizer/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+schema-ast@2.6.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+typescript-react-apollo@3.3.7_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/graphql-tag@2.12.6_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+visitor-plugin-common@2.13.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+plugin-helpers@2.7.2_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@ardatan+relay-compiler@12.0.0_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@ardatan+relay-compiler@12.0.0_graphql@14.3.1/node_modules/@ardatan/relay-compiler/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/responselike@1.0.2/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+utils@8.13.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+typescript-operations@2.5.13_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@wojtekmaj+enzyme-adapter-react-17@0.8.0_enzyme@3.11.0_react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@wojtekmaj+enzyme-adapter-utils@0.2.0/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/babel-jest@25.5.1/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/react-test-renderer@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/babel-preset-current-node-syntax@0.1.4/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/react-shallow-renderer@16.15.0/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/babel-preset-jest@25.5.0/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-import-meta@7.10.4/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-async-generators@7.8.4/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-bigint@7.8.3/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-json-strings@7.8.3/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-logical-assignment-operators@7.10.4/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.526Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-class-properties@7.12.13/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.527Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.6/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.527Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.6/node_modules/@apidevtools/json-schema-ref-parser/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.527Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-nullish-coalescing-operator@7.8.3/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.527Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-numeric-separator@7.10.4/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.527Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-object-rest-spread@7.8.3/node_modules': Directory not empty<br/>[2023-06-12T13:27:22.527Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@babel+plugin-syntax-optional-chaining@7.8.3/node_modules': Directory not empty<br/>[202 [...]

2023-06-12 14:10 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1122` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1122/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T14:10:18.746Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.746Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/apollo-link@1.2.14_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.746Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/react-apollo@3.1.3_apollo-client@2.6.10_graphql@14.3.1_react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.746Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apollo+react-common@3.1.4_apollo-client@2.6.10_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.746Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apollo+react-components@3.1.5_apollo-client@2.6.10_graphql@14.3.1_react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.746Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/react-dom@17.0.2/node_modules/react-dom/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apollo+react-hooks@3.1.5_apollo-client@2.6.10_graphql@14.3.1_react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apollo+react-ssr@3.1.5_apollo-client@2.6.10_graphql@14.3.1_react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/elkjs@0.8.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@apollo+react-hoc@3.1.5_apollo-client@2.6.10_graphql@14.3.1_react-dom@17.0.2/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+add@3.2.3_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+plugin-helpers@3.1.2_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+utils@9.2.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/react-apollo-hooks@0.5.0_apollo-client@2.6.10_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-typed-document-node+core@3.2.0_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+cli@2.16.5_graphql@14.3.1_typescript@4.9.5/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+cli@2.16.5_graphql@14.3.1_typescript@4.9.5/node_modules/@graphql-codegen/cli/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-codegen+core@2.6.8_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+schema@9.0.18_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+merge@8.4.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+apollo-engine-loader@7.3.26_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+code-file-loader@7.3.22_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+git-loader@7.2.21_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+graphql-tag-pluck@7.5.1_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+graphql-tag-pluck@7.5.1_graphql@14.3.1/node_modules/@graphql-tools/graphql-tag-pluck/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+github-loader@7.3.28_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+graphql-file-loader@7.5.17_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+executor-http@0.1.9_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+json-file-loader@7.4.18_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+import@6.7.18_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+load@7.8.14_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+url-loader@7.17.18_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+delegate@9.0.31_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+prisma-loader@7.2.70_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+prisma-loader@7.2.70_graphql@14.3.1/node_modules/@graphql-tools/prisma-loader/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+batch-execute@8.5.19_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+executor@0.0.17_graphql@14.3.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/serve-index@1.9.1/node_modules': Directory not empty<br/>[2023-06-12T14:10:18.747Z] rmdir: failed to remove './ui-packages/node_modules/.pnpm/@graphql-tools+executor-legacy-ws@0.0.11_graphql@14.3.1/node_modules': Directory not empty<br/>[2 [...]

2023-06-12 14:35 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1123` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1123/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:48.492Z] [INFO] packages/management-console-webapp test:it: [1] orderBy args:  { lastUpdate: 'DESC' }<br/>[2023-06-12T14:34:50.408Z] [INFO] packages/management-console-webapp test:it: [1] offset :  0<br/>[2023-06-12T14:34:50.408Z] [INFO] packages/management-console-webapp test:it: [1] limit :  10<br/>[2023-06-12T14:34:50.408Z] [INFO] packages/management-console-webapp test:it: [1] result length: 10<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T14:34:50.983Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T14:34:50.9 [...]

2023-06-12 15:06 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1125` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1125/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:03.156Z] [INFO] packages/management-console-webapp test:it: [1] orderBy args:  { lastUpdate: 'DESC' }<br/>[2023-06-12T15:06:05.042Z] [INFO] packages/management-console-webapp test:it: [1] offset :  0<br/>[2023-06-12T15:06:05.042Z] [INFO] packages/management-console-webapp test:it: [1] limit :  10<br/>[2023-06-12T15:06:05.042Z] [INFO] packages/management-console-webapp test:it: [1] result length: 10<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-12T15:06:05.631Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-12T15:06:05.6 [...]

2023-06-13 07:09 UTC, radtriste commented
jenkins rerun kogito-apps tests

2023-06-13 07:42 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1129` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1129/display/redirect

**Test results:**
- PASSED: 1136
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T07:42:00.657Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-06-13T07:42:00.657Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-06-13T07:42:00.657Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-06-13T07:42:00.657Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-06-13T07:42:00.657Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-06-13T07:42:00.657Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-06-13T07:42:00.657Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-06-13T07:42:00.657Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-06-13T07:42:00.657Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-06-13T07:42:00.657Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-06-13T07:42:00.657Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-06-13T07:42:00.657Z] [ERROR] <br/>[2023-06-13T07:42:00.657Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.<br/>[2023-06-13T07:42:00.657Z] [ERROR] <br/>[2023-06-13T07:42:00.657Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:<br/>[2023-06-13T07:42:00.657Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException<br/>[2023-06-13T07:42:00.657Z] [ERROR] <br/>[2023-06-13T07:42:00.657Z] [ERROR] After correcting the problems, you can resume the build with the command<br/>[2023-06-13T07:42:00.657Z] [ERROR]   mvn <args> -rf :persistence-commons-protobuf<br/>[2023-06-13T07:42:00.657Z] + test 1 -eq 0<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-06-13T07:42:01.463Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1129/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>[2023-06-13T07:42:01.782Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1129/consoleText<br/>[2023-06-13T07:42:01.782Z] + tail -n 50<br/>
</details>

2023-06-13 08:07 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1130` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage  -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1130/display/redirect

**Test results:**
- PASSED: 1136
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T08:07:49.863Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-06-13T08:07:49.863Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-06-13T08:07:49.863Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-06-13T08:07:49.863Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-06-13T08:07:49.863Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-06-13T08:07:49.863Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-06-13T08:07:49.863Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-06-13T08:07:49.863Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-06-13T08:07:49.863Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-06-13T08:07:49.863Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-06-13T08:07:49.863Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-06-13T08:07:49.863Z] [ERROR] <br/>[2023-06-13T08:07:49.863Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.<br/>[2023-06-13T08:07:49.863Z] [ERROR] <br/>[2023-06-13T08:07:49.863Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:<br/>[2023-06-13T08:07:49.863Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException<br/>[2023-06-13T08:07:49.863Z] [ERROR] <br/>[2023-06-13T08:07:49.863Z] [ERROR] After correcting the problems, you can resume the build with the command<br/>[2023-06-13T08:07:49.863Z] [ERROR]   mvn <args> -rf :persistence-commons-protobuf<br/>[2023-06-13T08:07:49.863Z] + test 1 -eq 0<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-06-13T08:07:50.660Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1130/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>[2023-06-13T08:07:50.980Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1130/consoleText<br/>[2023-06-13T08:07:50.980Z] + tail -n 50<br/>
</details>

2023-06-13 08:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1131` was: **ABORTED**
Possible explanation: Most probably a timeout, please review


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1131/display/redirect

**Test results:**
- PASSED: 627
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T08:48:01.931Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2023-06-13T08:48:01.931Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2023-06-13T08:48:01.931Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2023-06-13T08:48:01.931Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2023-06-13T08:48:01.931Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.16.7.Final:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  \- io.smallrye:jandex:jar:3.0.5:compile<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- io.quarkus:quarkus-junit5-properties:jar:2.16.7.Final:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.9.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.20:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] +- org.mockito:mockito-junit-jupiter:jar:4.11.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  \- org.junit.jupiter:junit-jupiter-api:jar:5.9.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |     +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |     +- org.junit.platform:junit-platform-commons:jar:1.9.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |     \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] +- org.mockito:mockito-core:jar:4.11.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- net.bytebuddy:byte-buddy:jar:1.12.18:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.19:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  \- org.objenesis:objenesis:jar:3.3:test<br/>[2023-06-13T08:48:01.932Z] [INFO] +- org.assertj:assertj-core:jar:3.22.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO] +- org.awaitility:awaitility:jar:4.2.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  \- org.hamcrest:hamcrest:jar:2.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] +- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.14:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  +- commons-logging:commons-logging:jar:1.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  \- commons-codec:commons-codec:jar:1.15:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.14:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] +- org.keycloak:keycloak-core:jar:21.0.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- org.keycloak:keycloak-common:jar:21.0.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  |  \- com.sun.activation:jakarta.activation:jar:1.2.1:test<br/>[2023-06-13T08:48:01.932Z] [INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-06-13T08:48:01.932Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-06-13T08:48:01.932Z] [INFO] \- com.github.tomakehurst:wiremock-jre8:jar:2.33.2:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    +- org.eclipse.jetty:jetty-server:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  +- javax.servlet:javax.servlet-api:jar:3.1.0:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  +- org.eclipse.jetty:jetty-http:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  \- org.eclipse.jetty:jetty-io:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    +- org.eclipse.jetty:jetty-servlet:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  +- org.eclipse.jetty:jetty-security:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    +- org.eclipse.jetty:jetty-servlets:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  \- org.eclipse.jetty:jetty-util:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    +- org.eclipse.jetty:jetty-webapp:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  \- org.eclipse.jetty:jetty-xml:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    +- org.eclipse.jetty:jetty-proxy:jar:9.4.46.v20220331:test<br/>[2023-06-13T08:48:01.932Z] [INFO]    |  \- org.eclipse.jetty:jetty-client:jar:9.4.46.v20220331:test<br/>[2023-06 [...]

2023-06-13 09:22 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1133` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1133/display/redirect

**Test results:**
- PASSED: 1136
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T09:22:28.445Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-06-13T09:22:28.445Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-06-13T09:22:28.445Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-06-13T09:22:28.445Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-06-13T09:22:28.445Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-06-13T09:22:28.445Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-06-13T09:22:28.445Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-06-13T09:22:28.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-06-13T09:22:28.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-06-13T09:22:28.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-06-13T09:22:28.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-06-13T09:22:28.445Z] [ERROR] <br/>[2023-06-13T09:22:28.445Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.<br/>[2023-06-13T09:22:28.445Z] [ERROR] <br/>[2023-06-13T09:22:28.445Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:<br/>[2023-06-13T09:22:28.445Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException<br/>[2023-06-13T09:22:28.445Z] [ERROR] <br/>[2023-06-13T09:22:28.445Z] [ERROR] After correcting the problems, you can resume the build with the command<br/>[2023-06-13T09:22:28.445Z] [ERROR]   mvn <args> -rf :persistence-commons-protobuf<br/>[2023-06-13T09:22:28.700Z] + test 1 -eq 0<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Upload artifacts to repository)<br/>Stage "Upload artifacts to repository" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-06-13T09:22:29.535Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1133/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>[2023-06-13T09:22:29.859Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1133/consoleText<br/>[2023-06-13T09:22:29.859Z] + tail -n 50<br/>
</details>

2023-06-13 09:30 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1134` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage -am -pl :kogito-apps-ui-packages
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1134/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.454Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:45.455Z] [INFO] packages/management-console-webapp test:it: [1] orderBy args:  { lastUpdate: 'DESC' }<br/>[2023-06-13T09:28:47.390Z] [INFO] packages/management-console-webapp test:it: [1] offset :  0<br/>[2023-06-13T09:28:47.390Z] [INFO] packages/management-console-webapp test:it: [1] limit :  10<br/>[2023-06-13T09:28:47.390Z] [INFO] packages/management-console-webapp test:it: [1] result length: 10<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1]   state: { in: [ 'ACTIVE' ] }<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1] }<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1] args {<br/>[2023-06-13T09:28:47.953Z] [INFO] packages/management-console-webapp test:it: [1]   parentProcessInstanceId: { isNull: true },<br/>[2023-06-13T09:28:47.95 [...]

2023-06-13 12:28 UTC, radtriste commented
jenkins rerun kogito-apps tests

2023-06-14 08:45 UTC, domhanak approved these changes
LGTM

2023-06-14 16:48 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#550` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/550/display/redirect

**Test results:**
- PASSED: 79
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/550/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/>
</details>

2023-06-14 17:29 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1150` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1150/display/redirect

**Test results:**
- PASSED: 1607
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.247 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.833 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:45 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:49 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:08 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:55 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:00 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  4.763 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.301 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.021 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.357 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.429 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 42.797 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.022 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.282 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.454 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.598 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.373 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.517 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.018 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.757 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [ 14.427 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.021 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.350 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.413 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 41.220 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:02 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.358 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 13.804 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.876 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.026 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.207 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.646 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 47.226 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.192 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.498 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.551 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.018 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:54 min]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.697 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 27.269 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 29.714 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.020 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.070 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.273 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.646 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.984 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.019 s]<br/>[2023-06-14T17:29:17.555Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCC [...]

2023-06-14 18:35 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1153` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1153/display/redirect

**Test results:**
- PASSED: 1607
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  6.150 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.021 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 15.083 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:45 min]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [03:01 min]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:09 min]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [04:13 min]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:04 min]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.020 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.020 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  4.868 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.308 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.022 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.381 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.588 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 42.593 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.021 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.292 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.518 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 33.475 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.027 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.323 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.498 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.020 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.918 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [ 14.232 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.023 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.293 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.541 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.065 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 56.091 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.281 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 13.917 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.826 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.018 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.202 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.098 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 46.669 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.152 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.203 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.371 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  3.928 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:53 min]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.985 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 27.681 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 29.730 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.019 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.074 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.854 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.868 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.120 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.020 s]<br/>[2023-06-14T18:35:40.741Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCC [...]

2023-06-14 19:56 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1155` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1155/display/redirect

**Test results:**
- PASSED: 1607
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.993 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 15.134 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:41 min]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:44 min]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:04 min]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:53 min]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:59 min]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.027 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.021 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  4.927 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.453 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.031 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.299 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.406 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests SUCCESS [ 40.629 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.024 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.338 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.508 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests SUCCESS [ 32.493 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.020 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.320 s]<br/>[2023-06-14T19:56:24.138Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.517 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.019 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  4.387 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [ 11.262 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests SKIPPED<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.020 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.291 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.501 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests SUCCESS [ 30.303 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 55.287 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.035 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  4.114 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 23.931 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.023 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.022 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.877 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.019 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.223 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.372 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 47.381 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.161 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.396 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.447 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  3.921 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:53 min]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.495 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 27.731 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 28.694 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.020 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.074 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.114 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 28.207 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.550 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.023 s]<br/>[2023-06-14T19:56:24.139Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCC [...]

2023-06-24 23:19 UTC, paulovmr requested changes
Hi @Sara4994 , a few things I got during the review, plus inline comments with some questions to make sure all changes were necessary:

1) Some dependencies versions updated in these commits [1](https://github.com/kiegroup/kogito-apps/commit/8ae5a4790f25e7a78adafccd31727be3a9168f73), [2](https://github.com/kiegroup/kogito-apps/commit/68507d741d42fe4254686fc9e1af3a7788644caa) and [3](https://github.com/kiegroup/kogito-apps/commit/a306ea7e7604fa7b38b873ccd289584eda9ffb2d) seems to have been reverted during the conflict resolution. They should be still applied here.

2) About the following files, do they need to be replicated across all packages?
![Screenshot from 2023-06-24 18-32-24](https://github.com/kiegroup/kogito-apps/assets/832830/a1afd87f-0f72-4fa2-8a41-f41f29b2a9a6)

3) Is `patternfly-base` packages still needed?

Thanks!

2023-06-24 23:19 UTC, paulovmr commented on README.md
> +- Install [Pnpm](https://pnpm.io/)
```suggestion
- Install [pnpm](https://pnpm.io/)
```

2023-06-24 23:19 UTC, paulovmr commented on README.md
> +- Install projects dependencies using Pnpm
```suggestion
- Install projects dependencies using pnpm
```

2023-06-24 23:19 UTC, paulovmr commented on README.md
> +- Build with Pnpm:
```suggestion
- Build with pnpm:
```

2023-06-24 23:19 UTC, paulovmr commented on README.md
> +`ui-packages` are managed with [Pnpm Workspaces](https://pnpm.io/workspaces). Dependencies shared between packages are listed in the top-level [`package.json`](./ui-packages/package.json).
```suggestion
`ui-packages` are managed with [pnpm Workspaces](https://pnpm.io/workspaces). Dependencies shared between packages are listed in the top-level [`package.json`](./ui-packages/package.json).
```

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/packages/cloud-event-form/package.json
> +    "build:prod": "pnpm run clean && pnpm run lint && pnpm -r -F @kogito-apps/components-common build:prod && pnpm run build",
```suggestion
    "build:prod": "pnpm run clean && pnpm run lint && pnpm run build",
```

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/packages/components-common/package.json
> +    "@kogito-apps/task-console-shared": "workspace:*",
This dependency didn't exist before, do we need it here for some reason? The task-console-shared already depends on this package, so this creates a circular dependency.

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/packages/common/package.json
> +    "build": "pnpm clean && pnpm run copy:css && tsc -m commonjs -p tsconfig.json ",
```suggestion
    "build": "pnpm clean && tsc -m commonjs -p tsconfig.json && pnpm run copy:css",
```

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/pnpm-workspace.yaml
> +  - 'examples/*'
```suggestion
```

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/packages/management-console/package.json
> -    "test:it": "start-server-and-test 'yarn start:it' 9000 'yarn cypress:run' && echo"
Is this not necessary anymore?

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/packages/process-list/src/envelope/components/ProcessListTable/ProcessListTable.tsx
> +                      columns[cellIndex + 1].toLowerCase(),
Why was this changed?

2023-06-24 23:19 UTC, paulovmr commented on ui-packages/packages/runtime-tools-dev-ui-webapp/webpack.common.js
> +      languages: ['typescript', 'json'],
Why was this changed?

2023-06-27 16:08 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1174` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1174/display/redirect

**Test results:**
- PASSED: 1615
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.431 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 20.885 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  4.797 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 16.069 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 20.342 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 57.717 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.841 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.018 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 14.676 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:46 min]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [04:01 min]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:05 min]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:49 min]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [01:58 min]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.019 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  4.505 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.268 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.314 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.456 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests :: SW SUCCESS [ 23.178 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests :: Process SUCCESS [ 20.248 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.047 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.290 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.385 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests :: SW SUCCESS [ 24.816 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests :: Process SUCCESS [ 22.705 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.018 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.302 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.383 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.017 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.813 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [ 13.699 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 26.507 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.019 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.287 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.361 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 25.922 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 18.884 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 54.080 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.018 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.126 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 13.000 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.018 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.017 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.766 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.022 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.235 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 32.492 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 45.797 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.145 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.276 s]<br/>[2023-06-27T16:08:15.512Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.264 s]<br/>[2023-06-27T16:08:15.512Z [...]

2023-06-27 20:01 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1179` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1706 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1179/display/redirect

**Test results:**
- PASSED: 1615
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.023 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.875 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [01:15 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 30.443 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.023 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.288 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.384 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 29.309 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 20.791 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:00 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.022 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.452 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 14.314 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.022 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.022 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.102 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.024 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.244 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 34.647 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 48.929 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.170 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.523 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.761 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.066 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [02:08 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 34.762 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 29.697 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 30.773 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.030 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.145 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 22.089 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.764 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.369 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.024 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.028 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.480 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.027 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.482 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.653 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.027 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:53 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:04 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:20 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:42 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:28 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.026 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.268 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:03 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:10 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:12 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:59 min]<br/>[2023-06-27T20:00:54.512Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.024 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  4.391 s]<br/>[2023-06-27T20:00:54.512Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SKIPPED<br/>[2023-06-27T20:00:54.512Z] [INFO] -------------------------------------- [...]

2023-06-27 21:13 UTC, paulovmr approved these changes

2023-06-27 21:13 UTC, merged