KOGITO-9122: [SWF Dev UI] Patternfly version upgrades, specific impor…
apache/incubator-kie-kogito-apps pull request #1798
Opened 2023-06-28 08:09 UTC by Sara4994

…ts and removed unused packages

Hello,

Please review this PR which makes following changes,

1) Upgrades Patternfly libraries to below versions:

        "@patternfly/react-code-editor": "4.82.113",
        "@patternfly/react-charts": "^6.94.18",
        "@patternfly/patternfly": "^4.224.2”,
        "@patternfly/react-core": "^4.276.6",
        "@patternfly/react-icons": "^4.93.6",
        "@patternfly/react-table": "^4.112.39",
        "@patternfly/react-styles": "^4.92.6",

2) Includes specific imports to the Patternfly components

3) Removed below un-used packages from the repo:
        Patternfly-base(which is not required anymore as the PF libraries to moved to specific packages)
        Common(Not used for long time, we created Consoles-common and Components-common package out of this)
        Management-console(Old Management console package, which is not in use. Current package Management- 
           console-webapp)
       
4) Upgrades below mentioned kie-tools libraries: (Commit from @AjayJagan)
      "@kie-tools/dashbuilder-client": "^0.29.0",
      "@kie-tools-core/envelope": "0.29.0",
      "@kie-tools-core/envelope-bus": "0.29.0",    
      "@kie-tools-core/editor": "0.29.0",
      "@kie-tools/serverless-workflow-combined-editor": "0.29.0",
      "@kie-tools/serverless-workflow-diagram-editor-assets": "0.29.0",
      "@kie-tools/serverless-workflow-diagram-editor-envelope": "0.29.0",
      "@kie-tools/serverless-workflow-mermaid-viewer": "0.29.0",
      "@kie-tools/serverless-workflow-text-editor": "0.29.0",
      "@kie-tools-core/keyboard-shortcuts": "0.29.0",

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

2023-06-28 09:29 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1182` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1182/display/redirect

**Test results:**
- PASSED: 1615
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.024 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.322 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.390 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.019 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.721 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [02:26 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 30.300 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.025 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.312 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.396 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 28.542 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 20.825 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 58.464 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.535 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 13.664 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.021 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.020 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.808 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.020 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.197 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 33.255 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 48.787 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.158 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.325 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.432 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.000 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [02:01 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 35.279 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 29.246 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 33.362 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.023 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.070 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.716 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 28.019 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.804 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.021 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.025 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.433 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.026 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.355 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 21.681 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.021 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:51 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:02 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:23 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:41 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:26 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.276 s]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:05 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:11 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:07 min]<br/>[2023-06-28T09:29:05.363Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:55 min]<br/>[2023-06-28T09:29 [...]

2023-06-28 10:30 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1184` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1184/display/redirect

**Test results:**
- PASSED: 1615
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.020 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.326 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.433 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.019 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.944 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:12 min]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 31.152 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.022 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.342 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.389 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 31.562 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 24.525 s]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:23 min]<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-28T10:30:25.332Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.142 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  5.775 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 21.759 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.019 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.032 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.197 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.023 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.248 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 35.728 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 45.857 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.196 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.417 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.313 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.198 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:52 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 33.202 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 27.363 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 29.795 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.018 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.076 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.263 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.473 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.249 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.021 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.023 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.328 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.023 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.372 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.404 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:46 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [02:59 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:17 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:40 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:29 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.031 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.268 s]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:02 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:07 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:07 min]<br/>[2023-06-28T10:30:25.333Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:57 min]<br/>[2023-06-28T10:30 [...]

2023-06-28 10:49 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1185` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1185/display/redirect

**Test results:**
- PASSED: 1615
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.022 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.345 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.498 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.021 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.769 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [01:29 min]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 27.786 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.025 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.268 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.382 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 27.184 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 19.742 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 55.409 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.021 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.347 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 12.739 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.020 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.022 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.934 s]<br/>[2023-06-28T10:49:12.279Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.021 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.217 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 32.202 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 46.866 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.242 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.510 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.340 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  3.842 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:55 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 32.564 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 27.637 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 30.950 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.024 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.082 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 20.330 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.214 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 20.230 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.023 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.065 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.375 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.024 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.609 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.026 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.028 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:49 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:01 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:19 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:40 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:25 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.027 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.281 s]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:02 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:10 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:11 min]<br/>[2023-06-28T10:49:12.280Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:56 min]<br/>[2023-06-28T10:49 [...]

2023-06-28 11:02 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1186` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1186/display/redirect

**Test results:**
- PASSED: 1615
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.018 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.376 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.439 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.021 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  3.858 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [03:19 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 32.248 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.030 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.356 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.623 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 30.091 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 23.746 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:37 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.349 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  5.407 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 15.396 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.021 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.024 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  5.169 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.202 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.582 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 42.377 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 48.316 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.171 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.645 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.365 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  4.183 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:58 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [ 34.058 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [ 28.116 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [ 31.962 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.023 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: JIT Executor :: Common .............. SUCCESS [  0.077 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: JIT Executor BPMN ................... SUCCESS [ 21.427 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 27.516 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 19.262 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.022 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.024 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.460 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.025 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.436 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common :: Quarkus SUCCESS [ 22.481 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [  0.022 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Management SUCCESS [02:51 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Messaging SUCCESS [03:01 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: Knative Eventing SUCCESS [02:19 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus :: embedded SUCCESS [01:42 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [01:31 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.024 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.266 s]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:05 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Audit UI  SKIPPED<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:10 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [04:13 min]<br/>[2023-06-28T11:01:59.915Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [02:05 min]<br/>[2023-06-28T11:01 [...]

2023-07-03 15:44 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#601` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/601/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:44:08.544Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T15:44:08.576Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-07-03T15:44:08.592Z] provisioning config files...<br/>[2023-07-03T15:44:08.599Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config125087907593713317tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T15:44:08.641Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:44:08.692Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config125087907593713317tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T15:44:08.715Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T15:44:08.716Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T15:44:08.716Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T15:44:09.007Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T15:44:09.007Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/durable-5153b45a/script.sh ']'<br/>[2023-07-03T15:44:09.007Z] ++ deactivate nondestructive<br/>[2023-07-03T15:44:09.007Z] ++ unset -f pydoc<br/>[2023-07-03T15:44:09.007Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:09.007Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:09.007Z] ++ hash -r<br/>[2023-07-03T15:44:09.007Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:09.007Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T15:44:09.007Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T15:44:09.007Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T15:44:09.007Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T15:44:09.007Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T15:44:09.007Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T15:44:09.007Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:44:09.007Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:44:09.007Z] ++ export PATH<br/>[2023-07-03T15:44:09.007Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:09.007Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:09.007Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T15:44:09.007Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T15:44:09.007Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T15:44:09.007Z] ++ PS1='(swf) '<br/>[2023-07-03T15:44:09.007Z] ++ export PS1<br/>[2023-07-03T15:44:09.007Z] ++ alias pydoc<br/>[2023-07-03T15:44:09.007Z] ++ true<br/>[2023-07-03T15:44:09.007Z] ++ hash -r<br/>[2023-07-03T15:44:09.007Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T15:44:10.892Z] # Executing pre section<br/>[2023-07-03T15:44:10.892Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config125087907593713317tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:44:10.892Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config125087907593713317tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:44:10.892Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T15:44:10.892Z] BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T15:44:10.892Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T15:44:10.892Z] QUARKUS_VERSION=<br/>[2023-07-03T15:44:10.892Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T15:44:10.892Z] ENABLE_DEPLOY=<br/>[2023-07-03T15:44:10.892Z]  <br/>[2023-07-03T15:44:10.892Z] # Execution Plan<br/>[2023-07-03T15:44:10.892Z] [INFO] 4 projects will be executed<br/>[2023-07-03T15:44:10.892Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T15:44:10.892Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:44:10.892Z] [INFO] 	 [before]<br/>[2023-07-03T15:44:10.892Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:44:10.892Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:44:10.892Z] [INFO] 	 [commands]<br/>[2023-07-03T15:44:10.892Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T15:44:10.892Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T15:44:10.892Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:44:10.892Z] [INFO] 	 [before]<br/>[2023-07-03T15:44:10.892Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:44:10.892Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:44:10.892Z] [INFO] 	 [commands]<br/>[2023-07-03T1 [...]

2023-07-03 15:45 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#590` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/590/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:44:45.312Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T15:44:45.337Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-07-03T15:44:45.352Z] provisioning config files...<br/>[2023-07-03T15:44:45.358Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config8399760883590957548tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T15:44:45.397Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:44:45.454Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config8399760883590957548tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T15:44:45.475Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T15:44:45.475Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T15:44:45.475Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T15:44:45.760Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T15:44:45.760Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/durable-6ca3ca87/script.sh ']'<br/>[2023-07-03T15:44:45.760Z] ++ deactivate nondestructive<br/>[2023-07-03T15:44:45.760Z] ++ unset -f pydoc<br/>[2023-07-03T15:44:45.760Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:45.760Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:45.760Z] ++ hash -r<br/>[2023-07-03T15:44:45.760Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:45.760Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T15:44:45.760Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T15:44:45.760Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T15:44:45.760Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T15:44:45.760Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T15:44:45.760Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T15:44:45.760Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:44:45.760Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:44:45.760Z] ++ export PATH<br/>[2023-07-03T15:44:45.760Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:45.760Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:44:45.760Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T15:44:45.760Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T15:44:45.760Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T15:44:45.760Z] ++ PS1='(swf) '<br/>[2023-07-03T15:44:45.760Z] ++ export PS1<br/>[2023-07-03T15:44:45.760Z] ++ alias pydoc<br/>[2023-07-03T15:44:45.760Z] ++ true<br/>[2023-07-03T15:44:45.760Z] ++ hash -r<br/>[2023-07-03T15:44:45.760Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T15:44:47.644Z] # Executing pre section<br/>[2023-07-03T15:44:47.644Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config8399760883590957548tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:44:47.644Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config8399760883590957548tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:44:47.644Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T15:44:47.644Z] BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T15:44:47.644Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T15:44:47.644Z] QUARKUS_VERSION=<br/>[2023-07-03T15:44:47.644Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T15:44:47.644Z] ENABLE_DEPLOY=<br/>[2023-07-03T15:44:47.644Z]  <br/>[2023-07-03T15:44:47.644Z] # Execution Plan<br/>[2023-07-03T15:44:47.644Z] [INFO] 4 projects will be executed<br/>[2023-07-03T15:44:47.644Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T15:44:47.644Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:44:47.644Z] [INFO] 	 [before]<br/>[2023-07-03T15:44:47.644Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:44:47.644Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:44:47.644Z] [INFO] 	 [commands]<br/>[2023-07-03T15:44:47.644Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T15:44:47.644Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T15:44:47.644Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:44:47.644Z] [INFO] 	 [before]<br/>[2023-07-03T15:44:47.644Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:44:47.644Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:44:47.644Z] [INFO] 	 [commands] [...]

2023-07-03 15:45 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1191` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1191/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:45:09.270Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T15:45:09.297Z] BUILD_MVN_OPTS_CURRENT = -Dvalidate-formatting -Prun-code-coverage<br/>[Pipeline] configFileProvider<br/>[2023-07-03T15:45:09.311Z] provisioning config files...<br/>[2023-07-03T15:45:09.315Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config10688045806813972836tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T15:45:09.353Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:45:09.395Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config10688045806813972836tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T15:45:09.415Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T15:45:09.416Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T15:45:09.416Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T15:45:09.682Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T15:45:09.682Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/durable-5fbc582c/script.sh ']'<br/>[2023-07-03T15:45:09.682Z] ++ deactivate nondestructive<br/>[2023-07-03T15:45:09.682Z] ++ unset -f pydoc<br/>[2023-07-03T15:45:09.682Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:09.682Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:09.682Z] ++ hash -r<br/>[2023-07-03T15:45:09.682Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:09.682Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T15:45:09.682Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T15:45:09.682Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T15:45:09.682Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T15:45:09.682Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T15:45:09.682Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T15:45:09.682Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:45:09.682Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:45:09.682Z] ++ export PATH<br/>[2023-07-03T15:45:09.682Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:09.682Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:09.682Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T15:45:09.682Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T15:45:09.682Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T15:45:09.682Z] ++ PS1='(swf) '<br/>[2023-07-03T15:45:09.682Z] ++ export PS1<br/>[2023-07-03T15:45:09.682Z] ++ alias pydoc<br/>[2023-07-03T15:45:09.682Z] ++ true<br/>[2023-07-03T15:45:09.682Z] ++ hash -r<br/>[2023-07-03T15:45:09.682Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T15:45:10.605Z] # Executing pre section<br/>[2023-07-03T15:45:10.605Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config10688045806813972836tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:45:10.605Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config10688045806813972836tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:45:10.605Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage<br/>[2023-07-03T15:45:10.605Z] BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage<br/>[2023-07-03T15:45:10.605Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T15:45:10.605Z] QUARKUS_VERSION=<br/>[2023-07-03T15:45:10.605Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T15:45:10.605Z] ENABLE_DEPLOY=<br/>[2023-07-03T15:45:10.605Z]  <br/>[2023-07-03T15:45:10.605Z] # Execution Plan<br/>[2023-07-03T15:45:10.605Z] [INFO] 3 projects will be executed<br/>[2023-07-03T15:45:10.605Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T15:45:10.605Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:45:10.605Z] [INFO] 	 [before]<br/>[2023-07-03T15:45:10.605Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:45:10.605Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:45:10.605Z] [INFO] 	 [commands]<br/>[2023-07-03T15:45:10.605Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T15:45:10.605Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T15:45:10.605Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:45:10.605Z] [INFO] 	 [before]<br/>[2023-07-03T15:45:10.605Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:45:10.605Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environmen [...]

2023-07-03 15:46 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#584` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-quarkus-examples/584/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:45:25.678Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T15:45:25.711Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-07-03T15:45:25.725Z] provisioning config files...<br/>[2023-07-03T15:45:25.733Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config11039817418577810468tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T15:45:25.770Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T15:45:25.815Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config11039817418577810468tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T15:45:25.836Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T15:45:25.836Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T15:45:25.836Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T15:45:26.121Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T15:45:26.121Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/durable-cf17f7d4/script.sh ']'<br/>[2023-07-03T15:45:26.121Z] ++ deactivate nondestructive<br/>[2023-07-03T15:45:26.121Z] ++ unset -f pydoc<br/>[2023-07-03T15:45:26.121Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:26.121Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:26.121Z] ++ hash -r<br/>[2023-07-03T15:45:26.121Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:26.121Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T15:45:26.121Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T15:45:26.121Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T15:45:26.121Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T15:45:26.121Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T15:45:26.121Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T15:45:26.121Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:45:26.121Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T15:45:26.121Z] ++ export PATH<br/>[2023-07-03T15:45:26.121Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:26.121Z] ++ '[' -z '' ']'<br/>[2023-07-03T15:45:26.121Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T15:45:26.121Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T15:45:26.121Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T15:45:26.121Z] ++ PS1='(swf) '<br/>[2023-07-03T15:45:26.121Z] ++ export PS1<br/>[2023-07-03T15:45:26.121Z] ++ alias pydoc<br/>[2023-07-03T15:45:26.121Z] ++ true<br/>[2023-07-03T15:45:26.121Z] ++ hash -r<br/>[2023-07-03T15:45:26.121Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T15:45:27.482Z] # Executing pre section<br/>[2023-07-03T15:45:27.482Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config11039817418577810468tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:45:27.482Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config11039817418577810468tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T15:45:27.482Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T15:45:27.482Z] BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T15:45:27.482Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T15:45:27.482Z] QUARKUS_VERSION=<br/>[2023-07-03T15:45:27.482Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T15:45:27.482Z] ENABLE_DEPLOY=<br/>[2023-07-03T15:45:27.482Z]  <br/>[2023-07-03T15:45:27.482Z] # Execution Plan<br/>[2023-07-03T15:45:27.482Z] [INFO] 4 projects will be executed<br/>[2023-07-03T15:45:27.482Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T15:45:27.482Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:45:27.482Z] [INFO] 	 [before]<br/>[2023-07-03T15:45:27.482Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:45:27.482Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:45:27.482Z] [INFO] 	 [commands]<br/>[2023-07-03T15:45:27.482Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T15:45:27.482Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T15:45:27.482Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T15:45:27.482Z] [INFO] 	 [before]<br/>[2023-07-03T15:45:27.482Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T15:45:27.482Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T15:45:27.482Z] [INFO] 	 [commands]<br/>[2023-07-03T15:45:27.482Z] [...]

2023-07-03 17:26 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#585` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-quarkus-examples/585/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:26:04.929Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T17:26:04.956Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-07-03T17:26:04.970Z] provisioning config files...<br/>[2023-07-03T17:26:04.976Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config10732940673598627741tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T17:26:05.016Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:26:05.060Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config10732940673598627741tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T17:26:05.081Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T17:26:05.081Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T17:26:05.081Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T17:26:05.370Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T17:26:05.371Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/durable-8ae30327/script.sh ']'<br/>[2023-07-03T17:26:05.371Z] ++ deactivate nondestructive<br/>[2023-07-03T17:26:05.371Z] ++ unset -f pydoc<br/>[2023-07-03T17:26:05.371Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:05.371Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:05.371Z] ++ hash -r<br/>[2023-07-03T17:26:05.371Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:05.371Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T17:26:05.371Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T17:26:05.371Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T17:26:05.371Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T17:26:05.371Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T17:26:05.371Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T17:26:05.371Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:26:05.371Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:26:05.371Z] ++ export PATH<br/>[2023-07-03T17:26:05.371Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:05.371Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:05.371Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T17:26:05.371Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T17:26:05.371Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T17:26:05.371Z] ++ PS1='(swf) '<br/>[2023-07-03T17:26:05.371Z] ++ export PS1<br/>[2023-07-03T17:26:05.371Z] ++ alias pydoc<br/>[2023-07-03T17:26:05.371Z] ++ true<br/>[2023-07-03T17:26:05.371Z] ++ hash -r<br/>[2023-07-03T17:26:05.371Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T17:26:06.732Z] # Executing pre section<br/>[2023-07-03T17:26:06.732Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config10732940673598627741tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:26:06.732Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-quarkus-examples@tmp/config10732940673598627741tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:26:06.732Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T17:26:06.732Z] BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T17:26:06.732Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T17:26:06.732Z] QUARKUS_VERSION=<br/>[2023-07-03T17:26:06.732Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T17:26:06.732Z] ENABLE_DEPLOY=<br/>[2023-07-03T17:26:06.732Z]  <br/>[2023-07-03T17:26:06.732Z] # Execution Plan<br/>[2023-07-03T17:26:06.732Z] [INFO] 4 projects will be executed<br/>[2023-07-03T17:26:06.732Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T17:26:06.732Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:26:06.732Z] [INFO] 	 [before]<br/>[2023-07-03T17:26:06.732Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:26:06.732Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:26:06.732Z] [INFO] 	 [commands]<br/>[2023-07-03T17:26:06.732Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T17:26:06.732Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T17:26:06.732Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:26:06.732Z] [INFO] 	 [before]<br/>[2023-07-03T17:26:06.732Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:26:06.732Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:26:06.732Z] [INFO] 	 [commands]<br/>[2023-07-03T17:26:06.732Z] [...]

2023-07-03 17:27 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#591` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.serverless-workflow-examples/591/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:26:36.897Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T17:26:36.929Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-07-03T17:26:36.949Z] provisioning config files...<br/>[2023-07-03T17:26:36.957Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config15108320210353697938tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T17:26:37.018Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:26:37.084Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config15108320210353697938tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T17:26:37.117Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T17:26:37.118Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T17:26:37.118Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T17:26:37.411Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T17:26:37.411Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/durable-120b7031/script.sh ']'<br/>[2023-07-03T17:26:37.411Z] ++ deactivate nondestructive<br/>[2023-07-03T17:26:37.411Z] ++ unset -f pydoc<br/>[2023-07-03T17:26:37.411Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:37.411Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:37.411Z] ++ hash -r<br/>[2023-07-03T17:26:37.411Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:37.411Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T17:26:37.411Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T17:26:37.411Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T17:26:37.411Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T17:26:37.411Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T17:26:37.411Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T17:26:37.411Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:26:37.411Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:26:37.411Z] ++ export PATH<br/>[2023-07-03T17:26:37.411Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:37.411Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:26:37.411Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T17:26:37.411Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T17:26:37.411Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T17:26:37.411Z] ++ PS1='(swf) '<br/>[2023-07-03T17:26:37.411Z] ++ export PS1<br/>[2023-07-03T17:26:37.411Z] ++ alias pydoc<br/>[2023-07-03T17:26:37.411Z] ++ true<br/>[2023-07-03T17:26:37.411Z] ++ hash -r<br/>[2023-07-03T17:26:37.412Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T17:26:38.778Z] # Executing pre section<br/>[2023-07-03T17:26:38.778Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config15108320210353697938tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:26:38.778Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.serverless-workflow-examples@tmp/config15108320210353697938tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:26:38.778Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T17:26:38.778Z] BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T17:26:38.778Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T17:26:38.778Z] QUARKUS_VERSION=<br/>[2023-07-03T17:26:38.778Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T17:26:38.778Z] ENABLE_DEPLOY=<br/>[2023-07-03T17:26:38.778Z]  <br/>[2023-07-03T17:26:38.778Z] # Execution Plan<br/>[2023-07-03T17:26:38.778Z] [INFO] 4 projects will be executed<br/>[2023-07-03T17:26:38.778Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T17:26:38.778Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:26:38.778Z] [INFO] 	 [before]<br/>[2023-07-03T17:26:38.778Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:26:38.778Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:26:38.778Z] [INFO] 	 [commands]<br/>[2023-07-03T17:26:38.778Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T17:26:38.778Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T17:26:38.778Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:26:38.778Z] [INFO] 	 [before]<br/>[2023-07-03T17:26:38.778Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:26:38.778Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:26:38.778Z] [INFO] 	 [comma [...]

2023-07-03 17:28 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#602` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-springboot-examples/602/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:27:05.119Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T17:27:05.149Z] BUILD_MVN_OPTS_CURRENT = -Pkogito-apps-downstream <br/>[Pipeline] configFileProvider<br/>[2023-07-03T17:27:05.164Z] provisioning config files...<br/>[2023-07-03T17:27:05.168Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config11062599786213494614tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T17:27:05.209Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:27:05.254Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config11062599786213494614tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T17:27:05.276Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T17:27:05.276Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T17:27:05.276Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T17:27:05.542Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T17:27:05.543Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/durable-8e49a151/script.sh ']'<br/>[2023-07-03T17:27:05.543Z] ++ deactivate nondestructive<br/>[2023-07-03T17:27:05.543Z] ++ unset -f pydoc<br/>[2023-07-03T17:27:05.543Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:05.543Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:05.543Z] ++ hash -r<br/>[2023-07-03T17:27:05.543Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:05.543Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T17:27:05.543Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T17:27:05.543Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T17:27:05.543Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T17:27:05.543Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T17:27:05.543Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T17:27:05.543Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:27:05.543Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:27:05.543Z] ++ export PATH<br/>[2023-07-03T17:27:05.543Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:05.543Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:05.543Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T17:27:05.543Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T17:27:05.543Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T17:27:05.543Z] ++ PS1='(swf) '<br/>[2023-07-03T17:27:05.543Z] ++ export PS1<br/>[2023-07-03T17:27:05.543Z] ++ alias pydoc<br/>[2023-07-03T17:27:05.543Z] ++ true<br/>[2023-07-03T17:27:05.543Z] ++ hash -r<br/>[2023-07-03T17:27:05.543Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T17:27:06.904Z] # Executing pre section<br/>[2023-07-03T17:27:06.904Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config11062599786213494614tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:27:06.904Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.downstream.kogito-springboot-examples@tmp/config11062599786213494614tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:27:06.904Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T17:27:06.904Z] BUILD_MVN_OPTS_CURRENT=-Pkogito-apps-downstream<br/>[2023-07-03T17:27:06.904Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T17:27:06.904Z] QUARKUS_VERSION=<br/>[2023-07-03T17:27:06.904Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T17:27:06.904Z] ENABLE_DEPLOY=<br/>[2023-07-03T17:27:06.904Z]  <br/>[2023-07-03T17:27:06.904Z] # Execution Plan<br/>[2023-07-03T17:27:06.904Z] [INFO] 4 projects will be executed<br/>[2023-07-03T17:27:06.904Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T17:27:06.904Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:27:06.904Z] [INFO] 	 [before]<br/>[2023-07-03T17:27:06.904Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:27:06.904Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:27:06.904Z] [INFO] 	 [commands]<br/>[2023-07-03T17:27:06.904Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T17:27:06.904Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T17:27:06.904Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:27:06.904Z] [INFO] 	 [before]<br/>[2023-07-03T17:27:06.904Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:27:06.904Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:27:06.904Z] [INFO] 	 [commands]<br/>[2023 [...]

2023-07-03 17:28 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1192` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1192/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:27:38.041Z] LD_LIBRARY_PATH = /opt/tools/graalvm/lib/server<br/>[Pipeline] echo<br/>[2023-07-03T17:27:38.071Z] BUILD_MVN_OPTS_CURRENT = -Dvalidate-formatting -Prun-code-coverage<br/>[Pipeline] configFileProvider<br/>[2023-07-03T17:27:38.086Z] provisioning config files...<br/>[2023-07-03T17:27:38.093Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config2075892884753285776tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2023-07-03T17:27:38.137Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-07-03T17:27:38.184Z] BUILD_MVN_OPTS =  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config2075892884753285776tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true<br/>[Pipeline] sh<br/>[2023-07-03T17:27:38.205Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2023-07-03T17:27:38.206Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2023-07-03T17:27:38.206Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2023-07-03T17:27:38.495Z] + source /home/jenkins/virtenvs/swf/bin/activate<br/>[2023-07-03T17:27:38.495Z] ++ '[' /home/jenkins/virtenvs/swf/bin/activate = /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/durable-ee3e775d/script.sh ']'<br/>[2023-07-03T17:27:38.495Z] ++ deactivate nondestructive<br/>[2023-07-03T17:27:38.495Z] ++ unset -f pydoc<br/>[2023-07-03T17:27:38.495Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:38.495Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:38.495Z] ++ hash -r<br/>[2023-07-03T17:27:38.495Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:38.495Z] ++ unset VIRTUAL_ENV<br/>[2023-07-03T17:27:38.495Z] ++ '[' '!' nondestructive = nondestructive ']'<br/>[2023-07-03T17:27:38.495Z] ++ VIRTUAL_ENV=/home/jenkins/virtenvs/swf<br/>[2023-07-03T17:27:38.495Z] ++ '[' linux-gnu = cygwin ']'<br/>[2023-07-03T17:27:38.495Z] ++ '[' linux-gnu = msys ']'<br/>[2023-07-03T17:27:38.495Z] ++ export VIRTUAL_ENV<br/>[2023-07-03T17:27:38.495Z] ++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:27:38.495Z] ++ PATH=/home/jenkins/virtenvs/swf/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.9.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/tools/graalvm/bin<br/>[2023-07-03T17:27:38.495Z] ++ export PATH<br/>[2023-07-03T17:27:38.495Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:38.495Z] ++ '[' -z '' ']'<br/>[2023-07-03T17:27:38.495Z] ++ _OLD_VIRTUAL_PS1=<br/>[2023-07-03T17:27:38.495Z] ++ '[' x '!=' x ']'<br/>[2023-07-03T17:27:38.495Z] +++ basename /home/jenkins/virtenvs/swf<br/>[2023-07-03T17:27:38.495Z] ++ PS1='(swf) '<br/>[2023-07-03T17:27:38.495Z] ++ export PS1<br/>[2023-07-03T17:27:38.495Z] ++ alias pydoc<br/>[2023-07-03T17:27:38.495Z] ++ true<br/>[2023-07-03T17:27:38.495Z] ++ hash -r<br/>[2023-07-03T17:27:38.495Z] + build-chain build cross_pr --token **** -f https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -o bc -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout<br/>[2023-07-03T17:27:39.426Z] # Executing pre section<br/>[2023-07-03T17:27:39.426Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config2075892884753285776tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:27:39.426Z] BUILD_MVN_OPTS= -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config2075892884753285776tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2023-07-03T17:27:39.426Z] [command]/usr/bin/echo BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage<br/>[2023-07-03T17:27:39.426Z] BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage<br/>[2023-07-03T17:27:39.426Z] [command]/usr/bin/echo QUARKUS_VERSION=<br/>[2023-07-03T17:27:39.426Z] QUARKUS_VERSION=<br/>[2023-07-03T17:27:39.426Z] [command]/usr/bin/echo ENABLE_DEPLOY=<br/>[2023-07-03T17:27:39.426Z] ENABLE_DEPLOY=<br/>[2023-07-03T17:27:39.426Z]  <br/>[2023-07-03T17:27:39.426Z] # Execution Plan<br/>[2023-07-03T17:27:39.426Z] [INFO] 3 projects will be executed<br/>[2023-07-03T17:27:39.426Z] [INFO] [kiegroup/drools]<br/>[2023-07-03T17:27:39.426Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:27:39.426Z] [INFO] 	 [before]<br/>[2023-07-03T17:27:39.426Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:27:39.426Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/update.sh ${{ env.BUILD_ENVIRONMENT }} ${{ env.BUILD_ENVIRONMENT_OPTIONS_UPSTREAM }}; fi"<br/>[2023-07-03T17:27:39.426Z] [INFO] 	 [commands]<br/>[2023-07-03T17:27:39.426Z] [INFO] 		 mvn dependency:tree clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2023-07-03T17:27:39.426Z] [INFO] [kiegroup/kogito-runtimes]<br/>[2023-07-03T17:27:39.426Z] [INFO] 	 Level type: upstream<br/>[2023-07-03T17:27:39.426Z] [INFO] 	 [before]<br/>[2023-07-03T17:27:39.426Z] [INFO] 		 export INTEGRATION_BRANCH=${{ env.INTEGRATION_BRANCH_UPSTREAM }}<br/>[2023-07-03T17:27:39.426Z] bash -c "if [ ! -z '${{ env.BUILD_ENVIRONMENT }}' ] && [ -f .ci/environments/update.sh ]; then .ci/environments/u [...]

2023-07-05 18:33 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1194` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1194/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-07-05T18:28:41.892Z] [INFO] Number of files to be formatted: 2<br/>[2023-07-05T18:28:41.892Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-07-05T18:28:41.892Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-07-05T18:28:41.892Z] [INFO] Skipped:                         2 file(s)<br/>[2023-07-05T18:28:41.892Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-07-05T18:28:41.892Z] [INFO] Approximate time taken:          0s<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-05T18:28:41.892Z] [INFO] Copying 6 resources<br/>[2023-07-05T18:28:41.892Z] [INFO] <br/>[2023-07-05T18:28:41.892Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:41.892Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-05T18:28:41.892Z] [INFO] Copying 4224 resources<br/>[2023-07-05T18:28:45.148Z] [INFO] <br/>[2023-07-05T18:28:45.148Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:45.148Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-05T18:28:45.148Z] [INFO] Copying 2 resources<br/>[2023-07-05T18:28:45.148Z] [INFO] <br/>[2023-07-05T18:28:45.148Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:45.148Z] [INFO] Changes detected - recompiling the module!<br/>[2023-07-05T18:28:45.148Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-07-05T18:28:45.707Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-05T18:28:45.707Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-05T18:28:45.707Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-07-05T18:28:45.707Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-07-05T18:28:45.707Z] [INFO] <br/>[2023-07-05T18:28:45.707Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:45.707Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-05T18:28:45.707Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-07-05T18:28:45.707Z] [INFO] <br/>[2023-07-05T18:28:45.707Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:45.707Z] [INFO] No sources to compile<br/>[2023-07-05T18:28:45.707Z] [INFO] <br/>[2023-07-05T18:28:45.707Z] [INFO] --- maven-surefire-plugin:3.1.2:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-05T18:28:45.707Z] [INFO] No tests to run.<br/>[2023-07-05T18:28:45.707Z] [INFO] <br/>[2023-07-05T18:28:45.707Z] [INFO] --- maven-jar-plugin:3.1.0:jar [...]

2023-07-06 07:39 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1195` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1195/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-07-06T07:34:07.934Z] [INFO] Number of files to be formatted: 2<br/>[2023-07-06T07:34:07.934Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-07-06T07:34:07.934Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-07-06T07:34:07.934Z] [INFO] Skipped:                         2 file(s)<br/>[2023-07-06T07:34:07.934Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-07-06T07:34:07.934Z] [INFO] Approximate time taken:          0s<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.934Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.934Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-07-06T07:34:07.934Z] [INFO] <br/>[2023-07-06T07:34:07.935Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.935Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T07:34:07.935Z] [INFO] Copying 6 resources<br/>[2023-07-06T07:34:07.935Z] [INFO] <br/>[2023-07-06T07:34:07.935Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:07.935Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T07:34:08.189Z] [INFO] Copying 4224 resources<br/>[2023-07-06T07:34:12.346Z] [INFO] <br/>[2023-07-06T07:34:12.346Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:12.346Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T07:34:12.346Z] [INFO] Copying 2 resources<br/>[2023-07-06T07:34:12.346Z] [INFO] <br/>[2023-07-06T07:34:12.346Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:12.346Z] [INFO] Changes detected - recompiling the module!<br/>[2023-07-06T07:34:12.346Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-07-06T07:34:12.346Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-06T07:34:12.346Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-06T07:34:12.346Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-07-06T07:34:12.346Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-07-06T07:34:12.346Z] [INFO] <br/>[2023-07-06T07:34:12.346Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:12.346Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T07:34:12.346Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-07-06T07:34:12.346Z] [INFO] <br/>[2023-07-06T07:34:12.346Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:12.346Z] [INFO] No sources to compile<br/>[2023-07-06T07:34:12.346Z] [INFO] <br/>[2023-07-06T07:34:12.346Z] [INFO] --- maven-surefire-plugin:3.1.2:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T07:34:12.346Z] [INFO] No tests to run.<br/>[2023-07-06T07:34:12.346Z] [INFO] <br/>[2023-07-06T07:34:12.346Z] [INFO] --- maven-jar-plugin:3.1.0:jar [...]

2023-07-06 08:13 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1196` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1196/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-07-06T08:08:16.771Z] [INFO] Number of files to be formatted: 2<br/>[2023-07-06T08:08:16.771Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-07-06T08:08:16.771Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-07-06T08:08:16.771Z] [INFO] Skipped:                         2 file(s)<br/>[2023-07-06T08:08:16.771Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-07-06T08:08:16.771Z] [INFO] Approximate time taken:          0s<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] Processed 2 files in 00:00.003 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T08:08:16.771Z] [INFO] Copying 6 resources<br/>[2023-07-06T08:08:16.771Z] [INFO] <br/>[2023-07-06T08:08:16.771Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:16.771Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T08:08:17.027Z] [INFO] Copying 4224 resources<br/>[2023-07-06T08:08:21.180Z] [INFO] <br/>[2023-07-06T08:08:21.180Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:21.180Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T08:08:21.180Z] [INFO] Copying 2 resources<br/>[2023-07-06T08:08:21.180Z] [INFO] <br/>[2023-07-06T08:08:21.180Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:21.180Z] [INFO] Changes detected - recompiling the module!<br/>[2023-07-06T08:08:21.180Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-07-06T08:08:21.435Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-06T08:08:21.435Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-06T08:08:21.435Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-07-06T08:08:21.435Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-07-06T08:08:21.435Z] [INFO] <br/>[2023-07-06T08:08:21.435Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:21.435Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T08:08:21.435Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-07-06T08:08:21.435Z] [INFO] <br/>[2023-07-06T08:08:21.435Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:21.435Z] [INFO] No sources to compile<br/>[2023-07-06T08:08:21.435Z] [INFO] <br/>[2023-07-06T08:08:21.435Z] [INFO] --- maven-surefire-plugin:3.1.2:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T08:08:21.435Z] [INFO] No tests to run.<br/>[2023-07-06T08:08:21.435Z] [INFO] <br/>[2023-07-06T08:08:21.435Z] [INFO] --- maven-jar-plugin:3.1.0:jar [...]

2023-07-06 10:40 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1197` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1197/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- formatter-maven-plugin:2.13.0:validate (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.401Z] [INFO] Using 'UTF-8' encoding to format source files.<br/>[2023-07-06T10:35:13.401Z] [INFO] Number of files to be formatted: 2<br/>[2023-07-06T10:35:13.401Z] [INFO] Successfully formatted:          0 file(s)<br/>[2023-07-06T10:35:13.401Z] [INFO] Fail to format:                  0 file(s)<br/>[2023-07-06T10:35:13.401Z] [INFO] Skipped:                         2 file(s)<br/>[2023-07-06T10:35:13.401Z] [INFO] Read only skipped:               0 file(s)<br/>[2023-07-06T10:35:13.401Z] [INFO] Approximate time taken:          0s<br/>[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- maven-checkstyle-plugin:3.1.1:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.401Z] [INFO] You have 0 Checkstyle violations.<br/>[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (jacoco-prepare-agent) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.401Z] [INFO] jacoco.agent.argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/target/jacoco.exec,append=true,excludes=*Lexer:org.kie.kogito.codegen.data.*<br/>[2023-07-06T10:35:13.401Z] [INFO] <br/>[2023-07-06T10:35:13.401Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.656Z] [INFO] Processed 2 files in 00:00.005 (Already Sorted: 2, Needed Sorting: 0)<br/>[2023-07-06T10:35:13.656Z] [INFO] <br/>[2023-07-06T10:35:13.656Z] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.656Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T10:35:13.656Z] [INFO] Copying 6 resources<br/>[2023-07-06T10:35:13.656Z] [INFO] <br/>[2023-07-06T10:35:13.656Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-webapp) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:13.656Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T10:35:13.911Z] [INFO] Copying 4224 resources<br/>[2023-07-06T10:35:18.061Z] [INFO] <br/>[2023-07-06T10:35:18.061Z] [INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-envelope-resources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:18.061Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T10:35:18.061Z] [INFO] Copying 2 resources<br/>[2023-07-06T10:35:18.061Z] [INFO] <br/>[2023-07-06T10:35:18.061Z] [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:18.061Z] [INFO] Changes detected - recompiling the module!<br/>[2023-07-06T10:35:18.061Z] [INFO] Compiling 2 source files to /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes<br/>[2023-07-06T10:35:18.317Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[64,58] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-06T10:35:18.317Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,56] io.quarkus.deployment.util.WebJarUtil in io.quarkus.deployment.util has been deprecated and marked for removal<br/>[2023-07-06T10:35:18.317Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[68,66] copyResourcesForDevOrTest(io.quarkus.deployment.builditem.LiveReloadBuildItem,io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem,io.quarkus.deployment.builditem.LaunchModeBuildItem,io.quarkus.maven.dependency.ResolvedDependency,java.lang.String,boolean) in io.quarkus.deployment.util.WebJarUtil has been deprecated<br/>[2023-07-06T10:35:18.317Z] [WARNING] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/deployment/DevConsoleProcessor.java:[78,34] devConsoleHandler(java.lang.String,io.quarkus.runtime.ShutdownContext) in io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder has been deprecated<br/>[2023-07-06T10:35:18.317Z] [INFO] <br/>[2023-07-06T10:35:18.317Z] [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:18.317Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-07-06T10:35:18.317Z] [INFO] skip non existing resourceDirectory /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/src/test/resources<br/>[2023-07-06T10:35:18.317Z] [INFO] <br/>[2023-07-06T10:35:18.317Z] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:18.317Z] [INFO] No sources to compile<br/>[2023-07-06T10:35:18.317Z] [INFO] <br/>[2023-07-06T10:35:18.317Z] [INFO] --- maven-surefire-plugin:3.1.2:test (default-test) @ runtime-tools-quarkus-extension-deployment ---<br/>[2023-07-06T10:35:18.317Z] [INFO] No tests to run.<br/>[2023-07-06T10:35:18.317Z] [INFO] <br/>[2023-07-06T10:35:18.317Z] [INFO] --- maven-jar-plugin:3.1.0:jar [...]

2023-07-07 20:55 UTC, paulovmr requested changes
Hi @Sara4994 , great job! The code looks good, just two comments:

1) There is still this old dependency on trusty package: `"@kogito-tooling/kie-editors-standalone": "^0.10.0"`.

2) The `pnpm-lock.yaml` shouldn't be formatted like that. Please run a build on ui-packages and don't format it on the IDE.

2023-07-09 18:25 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1206` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1206/display/redirect

**Test results:**
- PASSED: 1616
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  2.481 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 21.256 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  4.903 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 16.011 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL :: Reporting SUCCESS [ 20.801 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [ 54.364 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Common ................... SUCCESS [  5.915 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.020 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 15.287 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [01:44 min]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:41 min]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:05 min]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:44 min]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:01 min]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index .... SUCCESS [  0.026 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common SUCCESS [  0.019 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Runtime SUCCESS [  4.741 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Common :: Deployment SUCCESS [  0.309 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory SUCCESS [  0.019 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Runtime SUCCESS [  0.291 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Deployment SUCCESS [  0.396 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests :: SW SUCCESS [ 23.375 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index In-memory :: Integration Tests :: Process SUCCESS [ 20.493 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL SUCCESS [  0.020 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Runtime SUCCESS [  0.270 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Deployment SUCCESS [  0.413 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests :: SW SUCCESS [ 26.825 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index PostgreSQL :: Integration Tests :: Process SUCCESS [ 23.834 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan SUCCESS [  0.021 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Runtime SUCCESS [  0.343 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Deployment SUCCESS [  0.566 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension SUCCESS [  0.018 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Extension SUCCESS [  4.332 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [ 14.953 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Serverless Workflow Quarkus Dev UI Extension :: Deployment SKIPPED<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: SW SKIPPED<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index Infinispan :: Integration Tests :: Process SUCCESS [ 26.173 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB SUCCESS [  0.023 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Runtime SUCCESS [  0.262 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Deployment SUCCESS [  0.408 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: SW SUCCESS [ 26.563 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Kogito Addons Quarkus Data Index MongoDB :: Integration Tests :: Process SUCCESS [ 19.552 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 54.427 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.019 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.215 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [ 13.762 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.019 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.019 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  2.821 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.018 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.200 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [ 31.701 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [ 44.634 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.184 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  4.441 s]<br/>[2023-07-09T18:25:13.372Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.278 s]<br/>[2023-07-09T18:25:13.372Z [...]

2023-07-13 12:50 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1212` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1212/display/redirect

**Test results:**
- PASSED: 2761
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1212/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testDeleteTimerCycle/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteTimerCycle</a></summary>
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
</details>

2023-07-17 18:50 UTC, paulovmr reviewed
Hi @Sara4994 , code LGTM! I'm doing some tests, this is what I found so far:

1) When running the `serverless-workflow-compensation-quarkus`, the first time I go in the Dev UI, click on "Workflow Instances", click on the "Workflow Definitions" tab, and click to start the workflow, nothing happens and there is a error in the console. If I switch screen and go back, it starts working.

2) Management console has that bug with the patternfly classes, might need the same fix as the Dev UI.

2023-07-18 06:03 UTC, Sara4994 commented
> Hi @Sara4994 , code LGTM! I'm doing some tests, this is what I found so far:
> 
> 1. When running the `serverless-workflow-compensation-quarkus`, the first time I go in the Dev UI, click on "Workflow Instances", click on the "Workflow Definitions" tab, and click to start the workflow, nothing happens and there is a error in the console. If I switch screen and go back, it starts working.
> 2. Management console has that bug with the patternfly classes, might need the same fix as the Dev UI.

Hi @paulovmr 

#2 Management Consoles looks fine here. 🤔 

<img width="1517" alt="Screenshot 2023-07-18 at 11 28 22 AM" src="https://github.com/kiegroup/kogito-apps/assets/40579476/9184635f-9eff-488c-a22d-98bae5b42a7a">

2023-07-18 07:28 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1224` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1798 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1224/display/redirect

**Test results:**
- PASSED: 2768
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/1224/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/>
</details>

2023-07-18 17:53 UTC, paulovmr approved these changes

2023-07-19 09:11 UTC, Sara4994 commented
Jenkins retest this

2023-07-19 18:07 UTC, merged