[incubator-kie-issues-711] Refactroing job service to allow collocated service for Quarkus
apache/incubator-kie-kogito-apps pull request #1925
Opened 2023-11-28 08:25 UTC by elguardian

issue : https://github.com/apache/incubator-kie-issues/issues/711

depends on :https://github.com/apache/incubator-kie-kogito-runtimes/pull/3295

2023-11-28 11:18 UTC, kie-ci3 commented
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/display/redirect

**Test results:**
- PASSED: 2032
- FAILED: 70

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.http.KogitoServiceRandomPortQuarkusHttpTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.kafka.KogitoServiceRandomPortQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.inmemory/ProcessDataIndexInMemoryIT/testProcessInstanceEvents/">org.kie.kogito.index.inmemory.ProcessDataIndexInMemoryIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.http.KogitoServiceRandomPortQuarkusHttpTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.http.KogitoServiceRandomPortQuarkusHttpTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.kafka.KogitoServiceRandomPortQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.http.KogitoServiceRandomPortQuarkusHttpTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.kafka.KogitoServiceRandomPortQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.postgresql/ProcessDataIndexPostgreSqlHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.http.KogitoServiceRandomPortQuarkusHttpTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index.postgresql/ProcessDataIndexPostgreSqlKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.quarkus.kafka.KogitoServiceRandomPortQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index/ProcessDataIndexOracleIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexOracleIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.index/ProcessDataIndexPostgreSqlIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexPostgreSqlIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.it.jobs/JobServiceLeaderIT/___/">org.kie.kogito.it.jobs.JobServiceLeaderIT.(?)</a></summary>
Could not find a valid Docker environment. Please see logs and check configuration
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/1/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/PR_check___Build_projects___callbackStateTimeoutsExceeded/">PR check / Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test r [...]

2023-11-29 13:02 UTC, kie-ci3 commented
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/display/redirect

**Test results:**
- PASSED: 2252
- FAILED: 49

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.http.DataIndexInfinispanHttpQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.kafka.DataIndexInfinispanQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.inmemory/ProcessDataIndexInMemoryIT/testProcessInstanceEvents/">org.kie.kogito.index.inmemory.ProcessDataIndexInMemoryIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.DataIndexInMemoryQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.http.DataIndexMongoDBHttpQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.kafka.DataIndexMongoDBQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.http.DataIndexOracleHttpQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.kafka.DataIndexOracleQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.postgresql/ProcessDataIndexPostgreSqlHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.http.DataIndexPostgreSqlHttpQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index.postgresql/ProcessDataIndexPostgreSqlKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.kafka.DataIndexPostgreSqlQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index/ProcessDataIndexOracleIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexOracleIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.index/ProcessDataIndexPostgreSqlIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexPostgreSqlIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.it.jobs/JobServiceLeaderIT/___/">org.kie.kogito.it.jobs.JobServiceLeaderIT.(?)</a></summary>
Container startup failed
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/2/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/PR_check___Build_projects___callbackStateTimeoutsExceeded/">PR check / Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTest [...]

2023-11-29 21:44 UTC, kie-ci3 commented
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/3/display/redirect

**Test results:**
- PASSED: 2830
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/3/testReport/org.kie.kogito.index.service/MongoDomainIndexingServiceIT/testConcurrentProcessInstanceIndex/">org.kie.kogito.index.service.MongoDomainIndexingServiceIT.testConcurrentProcessInstanceIndex</a></summary>
Assertion condition defined as a org.kie.kogito.index.service.AbstractIndexingServiceIT 1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/> within 30 seconds.
</details>

2023-11-30 17:29 UTC, kie-ci3 commented
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/5/display/redirect

**Test results:**
- PASSED: 2827
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/5/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/5/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/5/testReport/org.kie.kogito.index.service/MongoDomainIndexingServiceIT/testConcurrentProcessInstanceIndex/">org.kie.kogito.index.service.MongoDomainIndexingServiceIT.testConcurrentProcessInstanceIndex</a></summary>
Assertion condition defined as a org.kie.kogito.index.service.AbstractIndexingServiceIT 1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: PENDING<br/> within 30 seconds.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/5/testReport/org.kie.kogito.index.oracle.query/JobEntityQueryIT/testJobQuery/">org.kie.kogito.index.oracle.query.JobEntityQueryIT.testJobQuery</a></summary>
Error invoking subclass method
</details>

2023-12-05 14:17 UTC, tiagodolphine commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/json/JacksonConfiguration.java
> +            kogitoCustomModule.addDeserializer(ExactExpirationTime.class, new ExactExpirationTimeDeserializer());
The serializers related to `kogito-api` could be moved to the new addon for the collocated jobs-service, with an additional objectMapper customizer, this seems specific to the addon, and this way we keep the core of jobs-service as decoupled as possible from the runtimes internal APIs, wdyt?
c/c @wmedvede

2023-12-11 08:03 UTC, elguardian commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/json/JacksonConfiguration.java
> +            kogitoCustomModule.addDeserializer(ExactExpirationTime.class, new ExactExpirationTimeDeserializer());
there are many things in kogito api or kogito events api that, honestly job, user task and workflow engine should be in the same kogito-events-api or core as they are mandatory elements of the workflow engine (it cannot function without them). This is only used in the addon as for some reason the data being passes through kafka seems to be duplicated or changed depending on the end using it  (client/server)

I would go for this in first place and the discuss how to rearrange things after the user task app. (it will happen at some point after 9.1

2023-12-11 14:02 UTC, kie-ci3 commented
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/6/display/redirect

**Test results:**
- PASSED: 2842
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/6/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>

2023-12-14 15:02 UTC, kie-ci3 commented
**PR job** `#7` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/7/display/redirect

**Test results:**
- PASSED: 2842
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/7/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>

2023-12-22 17:40 UTC, kie-ci3 commented
**PR job** `#9` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/9/display/redirect

**Test results:**
- PASSED: 2843
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/9/testReport/org.kie.kogito.it.trusty/QuarkusTrustyExplainabilityEnd2EndIT/doTest/">org.kie.kogito.it.trusty.QuarkusTrustyExplainabilityEnd2EndIT.doTest</a></summary>
Container startup failed for image org.kie.kogito/integration-tests-trusty-service-quarkus:999-SNAPSHOT
</details>

2024-01-03 10:45 UTC, pefernan requested changes

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/job/DelegateJob.java
> +    private final JobEventPublisher jobStreams;
I'd rename `jobStreams` to `jobEventPublisher`

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/job/DelegateJob.java
> +    public DelegateJob(JobExecutorResolver executorResolver, JobEventPublisher jobStreams) {
same here

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/repository/impl/BaseReactiveJobRepository.java
> +    private JobEventPublisher jobStreams;
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/repository/impl/BaseReactiveJobRepository.java
> +    protected BaseReactiveJobRepository(Vertx vertx, JobEventPublisher jobStreams) {
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/repository/impl/InMemoryJobRepository.java
> +    public InMemoryJobRepository(Vertx vertx, JobEventPublisher jobStreams) {
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/scheduler/impl/TimerDelegateJobScheduler.java
> +    private JobEventPublisher jobStreams;
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/scheduler/impl/TimerDelegateJobScheduler.java
> +            JobEventPublisher jobStreams) {
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-common/src/test/java/org/kie/kogito/jobs/service/scheduler/impl/VertxTimerServiceSchedulerTest.java
> +    private JobEventPublisher jobStreams;
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-infinispan/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/InfinispanJobRepository.java
> +            JobEventPublisher jobStreams,
same

2024-01-03 10:45 UTC, pefernan commented on jobs-service/jobs-service-postgresql-common/src/main/java/org/kie/kogito/jobs/service/repository/postgresql/PostgreSqlJobRepository.java
> +    public PostgreSqlJobRepository(Vertx vertx, JobEventPublisher jobStreams, PgPool client,
same

2024-01-03 10:45 UTC, pefernan commented on data-index/kogito-addons-quarkus-data-index-persistence/kogito-addons-quarkus-data-index-persistence-common/runtime/.gitignore
> +/target/
I'd remove this file

2024-01-03 10:45 UTC, pefernan commented on data-index/kogito-addons-quarkus-data-index/kogito-addons-quarkus-data-index-common/runtime/.gitignore
> +/target/
remove

2024-01-04 16:22 UTC, kie-ci3 commented
**PR job** `#12` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/12/display/redirect

**Test results:**
- PASSED: 613
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/12/testReport/org.kie.kogito.persistence.oracle/OracleStorageServiceIT/testQuery_Equal/">org.kie.kogito.persistence.oracle.OracleStorageServiceIT.testQuery_Equal</a></summary>
Error invoking subclass method
</details>

2024-01-04 23:04 UTC, kie-ci3 commented
**PR job** `#13` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/13/display/redirect

**Test results:**
- PASSED: 2865
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/13/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.http.DataIndexOracleHttpQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/13/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/13/testReport/org.kie.kogito.index/ProcessDataIndexOracleIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexOracleIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>

2024-01-05 14:27 UTC, kie-ci3 commented
**PR job** `#14` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1925 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/14/display/redirect

**Test results:**
- PASSED: 2872
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1925/14/testReport/org.kie.kogito.swf.tools.custom.dashboard.impl/CustomDashboardStorageTest/testHotReloading/">org.kie.kogito.swf.tools.custom.dashboard.impl.CustomDashboardStorageTest.testHotReloading</a></summary>
Condition with org.kie.kogito.swf.tools.custom.dashboard.impl.CustomDashboardStorageTest was not fulfilled within 20 seconds.
</details>

2024-01-05 15:46 UTC, pefernan approved these changes

2024-01-05 20:46 UTC, martinweiler approved these changes
Great work @elguardian and @pefernan!

2024-01-08 09:10 UTC, pefernan commented
test failures are unrelated

2024-01-08 09:25 UTC, merged