KOGITO-2008: Configured common package to share react components
apache/incubator-kie-kogito-apps pull request #206
Opened 2020-05-01 06:34 UTC by Sara4994

This pull request intended to configure a common package in lerna monorepo to share components that are common in both management and task consoles.

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Atoms/BrandLogo/BrandLogo.tsx
> +// import { withRouter } from 'react-router-dom';
please remove comment out code

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +import aboutPageLogo from '../../../static/managementConsoleLogo.svg';
svg logo will be different for task console.

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +      trademark="Management Console is part of Kogito, an open source software released under the Apache Software License 2.0"
same here, _Management Console_ needs to be parametrized

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.css
> +  }
```suggestion
}
```

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +  const PageSkipToContent = (
please remove _SkipToContent_ as it caused issues regarding final build.

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +                  The management console could not access the server to display
```suggestion
                  The console could not access the server to display
```

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Organisms/PageLayout/PageLayout.css
> +  }
```suggestion
}
```

2020-05-05 03:51 UTC, cristianonicolai commented on packages/common/src/components/Organisms/PageLayout/PageLayout.tsx
> +      <p>Test</p>
should this be removed?

2020-05-05 05:31 UTC, Sara4994 commented on packages/common/src/components/Atoms/BrandLogo/BrandLogo.tsx
> +// import { withRouter } from 'react-router-dom';
done

2020-05-05 07:38 UTC, Sara4994 commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +import aboutPageLogo from '../../../static/managementConsoleLogo.svg';
done

2020-05-05 07:38 UTC, Sara4994 commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +      trademark="Management Console is part of Kogito, an open source software released under the Apache Software License 2.0"
done

2020-05-05 07:38 UTC, Sara4994 commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +  const PageSkipToContent = (
done

2020-05-05 07:38 UTC, Sara4994 commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.css
> +  }
done

2020-05-05 07:38 UTC, Sara4994 commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +                  The management console could not access the server to display
done

2020-05-05 07:39 UTC, Sara4994 commented on packages/common/src/components/Organisms/PageLayout/PageLayout.tsx
> +      <p>Test</p>
done

2020-05-05 07:39 UTC, Sara4994 commented on packages/common/src/components/Organisms/PageLayout/PageLayout.css
> +  }
done

2020-05-05 11:13 UTC, cristianonicolai commented on packages/common/package.json
> +    "@patternfly/react-core": "3.140.11",
please update versions according to https://github.com/kiegroup/kogito-apps/pull/195

2020-05-05 11:13 UTC, cristianonicolai commented on packages/common/package.json
> +    "*.{ts,tsx,js}": [
```suggestion
    "*.{ts,tsx}": [
```

2020-05-05 11:13 UTC, cristianonicolai commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +            {process.env.KOGITO_MANAGEMENTCONSOLE_VERSION}
```suggestion
            {process.env.KOGITO_APP_VERSION}
```

2020-05-05 11:13 UTC, cristianonicolai commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +              href="https://github.com/kiegroup/kogito-runtimes/wiki"
```suggestion
              href="https://docs.jboss.org/kogito/release/latest/html_single/"
```

2020-05-05 11:13 UTC, cristianonicolai commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +              https://github.com/kiegroup/kogito-runtimes/wiki
```suggestion
              https://docs.jboss.org/kogito/release/latest/html_single/
```

2020-05-05 11:13 UTC, cristianonicolai commented on packages/common/src/static/managementConsoleLogo.svg
> +<?xml version="1.0" encoding="utf-8"?>
management console logo shouldnt be in the common module.

2020-05-06 05:46 UTC, Sara4994 commented on packages/common/src/static/managementConsoleLogo.svg
> +<?xml version="1.0" encoding="utf-8"?>
done

2020-05-06 05:46 UTC, Sara4994 commented on packages/common/src/components/Molecules/AboutModalBox/AboutModalBox.tsx
> +              https://github.com/kiegroup/kogito-runtimes/wiki
done

2020-05-07 04:46 UTC, cristianonicolai commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +                  The console could not access the server to display content.
could we use `${process.env.KOGITO_APP_NAME}` in here as well?

2020-05-07 04:46 UTC, cristianonicolai commented on package.json
> +    "@patternfly/react-core": "3.153.13",
@Sara4994 arent these regular dependencies?

2020-05-07 04:49 UTC, cristianonicolai commented on packages/common/package.json
> +    "@apollo/react-hooks": "3.1.3",
@Sara4994 please also move all of these to root package.json

2020-05-07 12:08 UTC, Sara4994 commented on package.json
> +    "@patternfly/react-core": "3.153.13",
@cristianonicolai yes it is.. placed it there by mistake... now moved it into dependencies

2020-05-07 12:10 UTC, Sara4994 commented on packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +                  The console could not access the server to display content.
done

2020-05-07 12:57 UTC, Sara4994 commented on packages/common/package.json
> +    "@apollo/react-hooks": "3.1.3",
@cristianonicolai done

2020-05-08 03:41 UTC, cristianonicolai commented
@Sara4994 some issues I noticed:

Both brand logo ( Task Console and Management Console ) seem to big, I think @srambach had a css fix for that, which is missing now.
The app version is not displaying.
See both issues here:
![Selection_058](https://user-images.githubusercontent.com/570894/81367783-76285080-9131-11ea-9a66-44fe82eb2367.png)

On the generated runner jar, the kogito logo is not displaying in the about page:
![Selection_059](https://user-images.githubusercontent.com/570894/81367836-935d1f00-9131-11ea-8ddb-b17115b132c8.png)

2020-05-08 10:05 UTC, Sara4994 commented
> @Sara4994 some issues I noticed:
> 
> Both brand logo ( Task Console and Management Console ) seem to big, I think @srambach had a css fix for that, which is missing now.
> The app version is not displaying.
> See both issues here:
> ![Selection_058](https://user-images.githubusercontent.com/570894/81367783-76285080-9131-11ea-9a66-44fe82eb2367.png)
> 
> On the generated runner jar, the kogito logo is not displaying in the about page:
> ![Selection_059](https://user-images.githubusercontent.com/570894/81367836-935d1f00-9131-11ea-8ddb-b17115b132c8.png)

@cristianonicolai  all these issues are fixed now :+1:

2020-05-08 20:03 UTC, srambach commented on packages/task-console/src/index.tsx
> +ReactDOM.render(<BaseCommponent />, document.getElementById('root'));
"Component" only has one m in it - it's consistent several places in this PR as far as I can see but probably should be fixed to avoid future confusion.

2020-05-08 20:04 UTC, srambach commented on packages/task-console/src/components/Templates/PageLayoutComponent/PageLayoutComponent.tsx
> +      BrandAltText="Task Consol Logo"
Typo - "Task Console Logo"

2020-05-08 20:09 UTC, srambach commented on packages/task-console/src/components/Templates/PageLayoutComponent/PageLayoutComponent.tsx
> +        <NavItem isActive>TestOption-2</NavItem>
Are these placeholders or left over from an example?

2020-05-08 20:13 UTC, srambach commented on packages/management-console/src/components/Templates/PageLayouComponent/PageLayoutComponent.tsx
> +        BrandAltText="Task Consol Logo"
Typo "Task Console Logo"

2020-05-08 20:17 UTC, srambach commented on packages/management-console/src/components/Templates/BaseComponent/BaseComponent.tsx
> +import PageLayoutComponent from '../PageLayouComponent/PageLayoutComponent';
It looks like there is a typo in the spelling of the folder "PageLayoutComponent"

2020-05-08 20:28 UTC, srambach commented
I notice that some imports of the graphics have an initial capital letter and some don't. (Pascal case vs camel case) Is there a convention to follow?

2020-05-11 14:03 UTC, Sara4994 commented on packages/management-console/src/components/Templates/BaseComponent/BaseComponent.tsx
> +import PageLayoutComponent from '../PageLayouComponent/PageLayoutComponent';
@srambach done

2020-05-11 14:03 UTC, Sara4994 commented on packages/management-console/src/components/Templates/PageLayouComponent/PageLayoutComponent.tsx
> +        BrandAltText="Task Consol Logo"
done

2020-05-11 14:04 UTC, Sara4994 commented on packages/task-console/src/components/Templates/PageLayoutComponent/PageLayoutComponent.tsx
> +        <NavItem isActive>TestOption-2</NavItem>
@srambach it is left over as an example

2020-05-11 14:04 UTC, Sara4994 commented on packages/task-console/src/components/Templates/PageLayoutComponent/PageLayoutComponent.tsx
> +      BrandAltText="Task Consol Logo"
done

2020-05-11 14:05 UTC, Sara4994 commented on packages/task-console/src/index.tsx
> +ReactDOM.render(<BaseCommponent />, document.getElementById('root'));
@srambach it was a typo again.. corrected it. Thanks

2020-05-11 14:06 UTC, Sara4994 commented
> I notice that some imports of the graphics have an initial capital letter and some don't. (Pascal case vs camel case) Is there a convention to follow?

have made everything in camel case now.

2020-05-12 20:06 UTC, srambach commented
Are static images meant to be shared? If so, I see them duplicated in common and task-console.

2020-05-13 12:21 UTC, Sara4994 commented
> Are static images meant to be shared? If so, I see them duplicated in common and task-console.

@srambach removed duplicate svgs/pngs

2020-05-13 18:38 UTC, srambach approved these changes
Looks good as far as I can tell. 👍

2020-05-14 05:46 UTC, jstastny-cz requested changes

2020-05-14 05:46 UTC, jstastny-cz commented on package.json
> +    "cypress:run-common": "cypress run --project ./packages/common"
Does this make sense? Cypress tests require a running application, can you start something from the common package?

2020-05-14 05:46 UTC, jstastny-cz commented on packages/management-console/src/components/Templates/PageLayoutComponent/tests/__snapshots__/PageLayoutComponent.test.tsx.snap
> +      "version": "2.6.8",
Are you sure about this change? IMO we've recently moved from 2.6.8 -> local and now back?

2020-05-14 05:46 UTC, jstastny-cz commented on packages/management-console/src/components/Templates/PageLayoutComponent/tests/__snapshots__/PageLayoutComponent.test.tsx.snap
> +      "version": "2.6.8",
Yep, build fails because of this, IMO just rebase on master and the error should go away.

2020-05-14 05:46 UTC, jstastny-cz commented on packages/management-console/src/components/Templates/ProcessDetailsPage/tests/__snapshots__/ProcessDetailsPage.test.tsx.snap
> +      "version": "2.6.8",
Again - revert the change

2020-05-14 05:46 UTC, jstastny-cz commented on packages/task-console/tsconfig.json
> +    ],
Looking at this one and management-console tsconfig.json, there we have excluded 'node_modules' dir, is that required here too? I am not sure what the purpose there is.

2020-05-14 07:02 UTC, Sara4994 commented on package.json
> +    "cypress:run-common": "cypress run --project ./packages/common"
@jstastny-cz as suggested,removed cypress related files from packages/common

2020-05-14 07:02 UTC, Sara4994 commented on packages/management-console/src/components/Templates/PageLayoutComponent/tests/__snapshots__/PageLayoutComponent.test.tsx.snap
> +      "version": "2.6.8",
@jstastny-cz done

2020-05-14 07:03 UTC, Sara4994 commented on packages/management-console/src/components/Templates/ProcessDetailsPage/tests/__snapshots__/ProcessDetailsPage.test.tsx.snap
> +      "version": "2.6.8",
@jstastny-cz reverted :+1:

2020-05-14 07:03 UTC, jstastny-cz commented on packages/common/package.json
> +    "cypress:run": "cypress run",
Please remove those 2 lines with cypress scripts too.

2020-05-14 07:04 UTC, Sara4994 commented
@pefernan i have fixed build:prod issue now.

2020-05-14 07:06 UTC, Sara4994 commented on packages/common/package.json
> +    "cypress:run": "cypress run",
@jstastny-cz done

2020-05-14 09:54 UTC, manstis commented
Hi @cristianonicolai @Sara4994 we'd be looking at re-using the common components in trusty-ai (about modal etc). In my limited experience (of TypeScript) trying to re-use a local version of a dependency has been troublesum and led to "invalid use of hook" type errors. Can you advise a best practice to re-use this during development; other than depending on a published version (as trusty would then need to be one release behind `kiegroup`)?

@kelvah @danielezonca FYI.

2020-05-14 11:19 UTC, cristianonicolai commented
@manstis wouldn't that be another kogito app? meaning it could leave in the same repo... @Sara4994 you probably know more details about sharing a module outside our lerna setup, would that be possible?

2020-05-14 13:48 UTC, pefernan approved these changes
Guys, I've tested it locally and everything seems to work fine. +1 for me.

2020-05-14 15:39 UTC, Sara4994 commented
@cristianonicolai  @manstis right now, @kogito/common package is maintained as private. if we have to use these components outside lerna repo, as far as i know we would need to publish @kogito/common package into npm registry and then we can install that package(@kogito/common) as dependency same as how we install any other package from the registry.

2020-05-14 15:59 UTC, nmirasch approved these changes
works fine and looks good to me

2020-05-15 04:51 UTC, AjayJagan approved these changes
:+1:

2020-05-15 06:11 UTC, manstis commented
Thank-you @Sara4994, that was my understanding too which would mean other _consumers_ would have to depend on published artifacts (i.e. a version _behind_ the current; "trusty version N" would need to depend on, at best, "shared version N-1"). @cristianonicolai FYI, although trusty is a `kiegroup` development it does not and (probably) will not reside in 'kogito-apps`. Therefore the `leana` setup would not work (to build multi-module projects).

@danielezonca @kelvah FYI too.. it would appear re-use is not so straight forward. When we come to wanting to re-use these I guess they'll have to be a cross-team discussion.

2020-05-15 07:29 UTC, yzhao583 commented
@Sara4994 Thanks!

2020-05-15 07:30 UTC, yzhao583 approved these changes

2020-05-18 05:38 UTC, cristianonicolai approved these changes

2020-05-18 05:45 UTC, jstastny-cz approved these changes

2020-05-18 10:04 UTC, merged

2020-05-18 10:32 UTC, pefernan commented
yay!