KOGITO-556 - rest server for handling process instance error
apache/incubator-kie-kogito-apps pull request #23
Opened 2019-11-11 09:43 UTC by Sara4994

2019-11-11 10:18 UTC, cristianonicolai requested changes
@Sara4994 I believe it is missing the calls for skip and retry REST endpoints.

2019-11-11 10:18 UTC, cristianonicolai commented on packages/management-console/server/restServer.js
> +app.get('/management/process/:processId/instances/:processInstanceId/error', controller.showError)
how about retrigger and skip?
{processId}/instances/{processInstanceId}/retrigger
{processId}/instances/{processInstanceId}/skip

2019-11-11 10:18 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +    const result = await axios.get(`http://localhost:8090/management/process/${processId}/instances/${processInstanceId}/error`);
http://localhost:8090 should be replaced by the _endpoint_ attribute from the process instance.

2019-11-11 10:18 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            />: <Dropdown
actually, we dont have any actions now if not in error state. If in here should remove/hide kebab.

2019-11-13 06:23 UTC, cristianonicolai requested changes

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +              <DropdownItem key={1}>Abort</DropdownItem>,
Abort option can be removed entirely for now.

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            />: <Dropdown
the entire kebab could be hidden in this case.

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +  const [retryStatus, setretryStatus] = useState('');
```suggestion
  const [retryStatus, setRetryStatus] = useState('');
```

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/server/restServer.js
> +        res.send(error[0].skip)
we actually need that some of the request to fail, by that it needs to send a 401, 404, 500, 403 errors

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            title="Success"
```suggestion
            title="Skip operation"
```

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            Skip status : {skipStatus}
Process execution has successfully skipped node which was in error state.

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          title="Failed"
```suggestion
          title="Skip operation"
```

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Skip status : {skipStatus}
```suggestion
          Process execution failed to skip node which in error state. Message: {}
```

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            title="Success"
```suggestion
            title="Retry operation"
```

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            Retry status : {retryStatus}
```suggestion
            Process execution has successfully re executed node which was in error state.
```

2019-11-13 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Retry status : {retryStatus}
```suggestion
          Process execution failed to re executed node which is error state. Message {}
```

2019-11-13 06:24 UTC, cristianonicolai commented
@Sara4994 @AjayJagan there is also an issue to open the dropdown of the last item in table. See screenshot below. Should I create a specific JIRA for that?

![Selection_024](https://user-images.githubusercontent.com/570894/68738430-0c236880-0632-11ea-8baf-f6d2417a9db1.png)

2019-11-13 07:48 UTC, cristianonicolai commented
@Sara4994 also, when I click on retry or skip nothing happens.

2019-11-13 08:05 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Skip status : {skipStatus}
@mswiderski does that sounds accurate?

2019-11-13 08:06 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            Retry status : {retryStatus}
@mswiderski does that sounds accurate?

2019-11-13 08:06 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Retry status : {retryStatus}
@mswiderski same here.

2019-11-13 08:20 UTC, mswiderski commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Skip status : {skipStatus}
sounds good to me

2019-11-13 08:20 UTC, mswiderski commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            Retry status : {retryStatus}
sounds good to me

2019-11-13 08:21 UTC, mswiderski commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Retry status : {retryStatus}
sounds good, maybe just change `failed to re executed` to `failed to re execute`

2019-11-13 11:01 UTC, Sara4994 commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Retry status : {retryStatus}
added

2019-11-13 11:01 UTC, Sara4994 commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            Retry status : {retryStatus}
added

2019-11-13 11:01 UTC, Sara4994 commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +            title="Success"
added

2019-11-13 11:01 UTC, Sara4994 commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Skip status : {skipStatus}
added

2019-11-14 01:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +          Process execution failed to re executed node which is error state. Message {retryMessage}
```suggestion
          Process execution failed to re execute node which is error state. Message {retryMessage}
```

2019-11-14 01:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +      {skipAlertVisible && skipStatus === 'success' && (
@Sara4994 what if you define 3 variables: variant, title and message, that way you could have a single alert rendered?

2019-11-14 06:23 UTC, cristianonicolai requested changes

2019-11-14 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +      setAlertType('success');
```suggestion
      setAlertTitle('Skip operation');
      setAlertType('success');
```

2019-11-14 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +      setAlertType('danger');
```suggestion
      setAlertTitle('Skip operation');
      setAlertType('danger');
```

2019-11-14 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +      setAlertTitle('Skip operation');
```suggestion
      setAlertTitle('Retry operation');
```

2019-11-14 06:23 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +      setAlertTitle('Skip operation');
```suggestion
      setAlertTitle('Retry operation');
```

2019-11-14 13:19 UTC, cristianonicolai approved these changes

2019-11-14 13:36 UTC, AjayJagan approved these changes

2019-11-14 13:40 UTC, merged