KOGITO-2172 Implemented display data functionality for the Generic Task List Comp…
apache/incubator-kie-kogito-apps pull request #239
Opened 2020-05-28 23:22 UTC by yzhao583

[https://issues.redhat.com/browse/KOGITO-2172](https://issues.redhat.com/browse/KOGITO-2172)

Implemented display data functionality using PF4 Table component for Generic Task List Component. Here are the main functionalities for the DataTableComponent:

- Display data (an array of json object) passed in props.
- Users can decide the columns they want to show in the table by defining the "columns" (an array of string) prop; If there is no "columns" props defined, all properties of the "data" json object will be displayed.
-  Users can define custom "Loading" component and pass it to the table component in props, if there is a custom "Loading" component defined, it will be displayed when the table is loading status; Otherwise, the default "Loading" component is displayed.
- -  Users can define custom "Error" component and pass it to the table component in props, if there is a custom "Error" component defined, it will be displayed when the table is loading status; Otherwise, the default "Loading" component is displayed.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-05-29 10:16 UTC, jstastny-cz requested changes

2020-05-29 10:16 UTC, jstastny-cz commented on packages/task-console/src/components/Templates/DataTableContainer/__mocks__/DataTableContainer.tsx
> +const DataTableContainer = (): React.ReactElement => {
I would argue to keep the fact that it is a mock visible, what I am doing in other PR is to name the component as mock, in this case it would be MockedDataTableContainer wdyt? It's then apparent in snapshot that we actually don't expect the component to be rendered properly.

2020-05-29 10:16 UTC, jstastny-cz commented on packages/task-console/src/components/Templates/DataTableContainer/tests/DataTableContainer.test.tsx
> +        <MockedProvider>
For any mocks using MockedProvider we need to do additional steps to have nice snapshots (otherwise we get just empty-state component render even if we provide mocked data).
Here there are no values passed to the component, so I guess this test is for rendering the DataTableContainer with a DataTableComponent than is in 'empty-state'. So I see two options now:
* If we don't care about the DataTableComponent in the tests here, we should mock it IMO.
* If we care about DataTableComponent rendering we should also add test where the component would actually show some data.

But I assume option 1 is sufficient for testing this container, and given that you've already created mock for DataTableComponent, I would just mock it for this test.

2020-05-29 10:16 UTC, jstastny-cz commented on packages/task-console/src/components/Templates/DataTableContainer/tests/__snapshots__/DataTableContainer.test.tsx.snap
> +                  <DataTableComponent
In relation with comment on the test itself -> here would be the place in snapshot to see the mocked component.

2020-05-29 10:16 UTC, jstastny-cz commented on packages/task-console/src/components/Organisms/DataTableComponent/tests/DataTableComponent.test.tsx
> +    const wrapper = shallow(
IMO shallow does not actually run the graphql query like `mount` would. That's why the following snapshot is also just showing only the component with properties being passed, no children - which I would expect based on the mocked data passed in.

2020-05-29 10:16 UTC, jstastny-cz commented on packages/task-console/src/components/Organisms/DataTableComponent/__mocks__/DataTableComponent.tsx
> +const DataListComponent = (): React.ReactElement => {
I would call the component MockedDataList -> for the snapshots to apparently show that the component is actually mocked.

2020-05-29 10:16 UTC, jstastny-cz commented on packages/task-console/src/components/Organisms/DataTableComponent/tests/DataTableComponent.test.tsx
> +    const wrapper = shallow(
If you decide to use mount instead mind that the test needs to be async, I have a solution in my PR, where I just introduce another wrapper for such cases: `getWrapperAsync`, then the test would look like:
```
it('', async ()=> {
     const wrapper = await getWrapperAsync(....)
     expect(wrapper).toMatchSnapshot();
})
```
Reach out to me if needed.

2020-05-29 21:46 UTC, yzhao583 commented on packages/task-console/src/components/Organisms/DataTableComponent/__mocks__/DataTableComponent.tsx
> +const DataListComponent = (): React.ReactElement => {
Thanks! Will update.

2020-05-29 23:59 UTC, yzhao583 commented on packages/task-console/src/components/Templates/DataTableContainer/tests/DataTableContainer.test.tsx
> +        <MockedProvider>
@jstastny-cz Updated, Thanks.

2020-06-01 07:26 UTC, jstastny-cz approved these changes
LGTM, thanks.

2020-06-01 21:17 UTC, srambach commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
Two comments here. First, I think this is the fourth time we have .spinner-center and .error-text defined between the packages. We definitely need to think about how to share common CSS here.

Second, we need to establish some good naming practices for CSS classes. I have been using something close to `.kogito-packagename—block__element—modifier`. In the domain explorer, we’ve used this to solve the same problem of a too-wide table.
```
.kogito-management-console--domain-explorer__table-OverFlow {
overflow-y: auto;
}
```

2020-06-02 03:51 UTC, AjayJagan commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
Hello @yzhao583 , So there was a discussion on naming the components and there everyone feels that it would be better to remove the 'component' at the end of every components(for instance in this case just the DataTable). wdyt @cristianonicolai @Sara4994  @srambach . Other than that the PR looks awesome :)

2020-06-02 04:25 UTC, cristianonicolai commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +import SpinnerComponent from '../../Atoms/SpinnerComponent/SpinnerComponent';
@yzhao583, @Sara4994 is working on moving and renaming these components to the common module, maybe is worth if you guys sync for one PR after the other.

2020-06-02 04:25 UTC, cristianonicolai commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +        rowKey: JSON.stringify(rowData).substr(0, 20) // This is a walkaround to bypass the "id" cannot be included in "columns" issue
@yzhao583 I think on management console we end-up using a random uuid, maybe double check with @AjayJagan @Sara4994.

2020-06-02 04:25 UTC, cristianonicolai commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
+1 for dropping _Compoment_ from the naming. Also, @yzhao583 is this a Task specific table, do we want to maybe name for specifically or even keep as generic and move to the common module?

2020-06-02 11:14 UTC, pefernan approved these changes
Hey  @yzhao583 Your code works and looks great. I'd remove some unneeded comments but since this is an ongoing dev we can merge and remove later.

2020-06-02 11:14 UTC, pefernan commented on packages/task-console/src/components/Templates/DataTableContainer/DataTableContainer.tsx
> +  // const columns = [
I think this could be removed

2020-06-02 12:46 UTC, Sara4994 commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +        rowKey: JSON.stringify(rowData).substr(0, 20) // This is a walkaround to bypass the "id" cannot be included in "columns" issue
@yzhao583 you can use generate random key something like this "Math.random().toString()"

2020-06-02 12:47 UTC, Sara4994 commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +import SpinnerComponent from '../../Atoms/SpinnerComponent/SpinnerComponent';
@yzhao583 Now you can import "KogitoSpinner" component from @kogito-apps/common

2020-06-02 14:02 UTC, yzhao583 commented on packages/task-console/src/components/Organisms/DataTableComponent/tests/DataTableComponent.test.tsx
> +    const wrapper = shallow(
@jstastny-cz Updated, thanks

2020-06-02 14:02 UTC, yzhao583 commented on packages/task-console/src/components/Organisms/DataTableComponent/__mocks__/DataTableComponent.tsx
> +const DataListComponent = (): React.ReactElement => {
@jstastny-cz Updated, thanks

2020-06-02 14:08 UTC, yzhao583 commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
@srambach Thanks for the feedback. Really appreciate that! 

> Two comments here. First, I think this is the fourth time we have .spinner-center and .error-text defined between the packages. We definitely need to think about how to share common CSS here.
Yes, I totally agree we should define some common CSS class here so it can be shared. Could you please suggest how and where should we do that? Thanks.





> Second, we need to establish some good naming practices for CSS classes. I have been using something close to `.kogito-packagename—block__element—modifier`. In the domain explorer, we’ve used this to solve the same problem of a too-wide table.

This component it not only for Task Console, and maybe it is not only for KOGITO as well. So I assume using some general name may make more sense here? wdyt

2020-06-02 14:18 UTC, yzhao583 commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@AjayJagan Thanks for the feedback, really appreciate that! 


> So there was a discussion on naming the components and everyone feels that it would be better to remove the 'component' at the end of every components(for instance in this case just the DataTable)

Yes, I feel like removing 'component' in the name make more sense.

@cristianonicolai Thanks for the feedback, really appreciate that! 


> is this a Task specific table, do we want to maybe name for specifically or even keep as generic and move to the common module?

This is not only for Task Console, the goal here is to make a general Table Component. The reason I did not put it into the Common module is that I found there is also a similar Table Component in Domain Explorer module, and it has more functionalities, I am not sure which one should we put into the Common module. Any suggestion? Thanks

2020-06-02 14:19 UTC, yzhao583 commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +import SpinnerComponent from '../../Atoms/SpinnerComponent/SpinnerComponent';
@cristianonicolai @Sara4994 Thanks! I will update to use the component from the Common module.

2020-06-02 14:25 UTC, yzhao583 commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +        rowKey: JSON.stringify(rowData).substr(0, 20) // This is a walkaround to bypass the "id" cannot be included in "columns" issue
@cristianonicolai @Sara4994 I personally prefer the "uuid" solution, WDYT? And if we use "uuid" here, it may generate some headache when we do snapshot test, any suggestions? Appreciated!

2020-06-02 14:27 UTC, yzhao583 commented on packages/task-console/src/components/Templates/DataTableContainer/DataTableContainer.tsx
> +  // const columns = [
@pefernan Sorry, I just commented it out by mistake, we need that here, but thanks for the feedbacks! Appreciated!

2020-06-02 14:59 UTC, nmirasch approved these changes
Looks great, Thanks!

2020-06-02 15:03 UTC, AjayJagan approved these changes
:tada:

2020-06-03 02:33 UTC, cristianonicolai commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +        rowKey: JSON.stringify(rowData).substr(0, 20) // This is a walkaround to bypass the "id" cannot be included in "columns" issue
task id and process id, are actually uuid, to me that should be enough but again @Sara4994 @AjayJagan might know better the inner works.

2020-06-03 02:34 UTC, cristianonicolai commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@yzhao583, @Sara4994 is working on moving that component into the common module, perhaps we should wait to get that in first?

2020-06-03 05:06 UTC, Sara4994 commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +        rowKey: JSON.stringify(rowData).substr(0, 20) // This is a walkaround to bypass the "id" cannot be included in "columns" issue
@cristianonicolai for keys i would prefer Math.random(), but if we look for some other alternative there is something called nanoid().

2020-06-03 13:42 UTC, srambach commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
@yzhao583  
Since the overflow is on the data table in task console, then how about `.kogito-task-console--data-table--Overflow`? If at some point the data tables are combined into the common package, then they can share a class in common.
Do we need to set `overflow` here, or is `overflow-y` sufficient?

As for `.error-text` and `.spinner-center` - I don't even see them being used anywhere even though they are defined several times. Can they be removed?

2020-06-03 16:56 UTC, yzhao583 commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
@srambach Yes, you are right, the Data Table is in task console, but it maybe reused for by applications. And the reason to add overflow here is handle the case that there is too many columns.

I will remove the unused classes, thanks.

2020-06-03 17:01 UTC, pefernan commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@yzhao583 @cristianonicolai @Sara4994 I have one question, is both components overlapping? The goal of this PR is creating a _Table Component_, to be used in Task Console but ideally reusable for other purposes (maybe jobs or whatever we may need). If both of them have the same goal, should we modify the existing DE table @Sara4994's working on, to make it generic so we can adopt it in both modules? If not, to me +1 to merge is (maybe renaming it to avoid collisions) so we can continue working. WDYT?

2020-06-03 17:03 UTC, pefernan commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@yzhao583 @Sara4994 do you think it would be feasible to do it, that could save us a lot of time :-P

2020-06-04 05:23 UTC, cristianonicolai commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@pefernan I know its not ideal but we're focusing on moving domain explorer to common right now, it might be a few prs away see https://github.com/kiegroup/kogito-apps/pull/245 and https://github.com/kiegroup/kogito-apps/pull/242,  I think would be best if we concentrate the effort in the long term approach.

2020-06-04 07:40 UTC, pefernan commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@cristianonicolai so we should rename this so we can merge?

2020-06-04 18:00 UTC, srambach commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
@yzhao583 Great!  What other applications would this class be used in? Do you mean something outside of Kogito?

2020-06-04 19:37 UTC, yzhao583 commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
@srambach Yes, it could be. Although the main goal is build a Table Component for Task Console, there is also another goal that to make is reusable for other applications as well.

2020-06-04 20:02 UTC, srambach commented on packages/task-console/src/components/Templates/DataTableContainer/DataTable.css
> +}
OK, I see. I still feel that it would be best to namespace any classes we are adding. That way it will avoid potential conflicts and identify the source of the class for debugging.

2020-06-05 09:22 UTC, pefernan commented on packages/task-console/src/components/Organisms/DataTableComponent/DataTableComponent.tsx
> +const DataTableComponent: React.FC<IOwnProps> = ({
@cristianonicolai @yzhao583 @nmirasch why not merge this into the task-console, so @yzhao583 can continue working, and we may move it to commons when needed. In future developmens we'll have to be more synchronized.

2020-06-08 13:02 UTC, merged