KOGITO-2178 Implement customize column visibility functionality for the Generic T…
apache/incubator-kie-kogito-apps pull request #267
Opened 2020-06-12 02:48 UTC by yzhao583

…ask List Component

Jira: https://issues.redhat.com/browse/KOGITO-2178

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-06-15 08:31 UTC, pefernan requested changes
@yzhao583 code looks well but it seems that there's a conflict, would you mind rebasign?

thanks!

2020-06-16 01:52 UTC, yzhao583 commented
@pefernan Updated Thanks!

2020-06-16 02:13 UTC, cristianonicolai commented
@yzhao583 @pefernan @nmirasch  wouldn't this be something that could be reused across consoles?

2020-06-16 07:22 UTC, pefernan commented
@cristianonicolai yea, but since this won't be finished by devpreview 2 I asked @yzhao583 to add it on Task Console to keep the common module clean.

2020-06-16 08:55 UTC, pefernan approved these changes
Waiting for @jstastny-cz but I'd say +1

2020-06-16 11:27 UTC, jstastny-cz requested changes

2020-06-16 11:27 UTC, jstastny-cz commented on packages/task-console/src/components/Templates/DataTableContainer/tests/__snapshots__/DataTableContainer.test.tsx.snap
> +                      [Error: Network error: No more mocked responses for the query: query getUserTasksByStates($state: [String!]) {
here it seems like an error in test setup, or is the failure expected?

2020-06-16 11:27 UTC, jstastny-cz commented on packages/task-console/src/components/Templates/DataTableContainer/tests/__snapshots__/DataTableContainer.test.tsx.snap
> +                      [Error: Network error: No more mocked responses for the query: query getUserTasksByStates($state: [String!]) {
Probably due to not passing mocks to the MockedProvider.

2020-06-17 02:43 UTC, yzhao583 commented on packages/task-console/src/components/Templates/DataTableContainer/tests/__snapshots__/DataTableContainer.test.tsx.snap
> +                      [Error: Network error: No more mocked responses for the query: query getUserTasksByStates($state: [String!]) {
@jstastny-cz Updated. Thanks!

2020-06-18 13:09 UTC, jstastny-cz approved these changes

2020-06-18 20:07 UTC, yzhao583 commented
@cristianonicolai @pefernan @jstastny-cz Hi guys, is there anything else I need to fix? If not, can we merge this PR so we can move forward? Thanks!

2020-06-23 07:18 UTC, merged