KOGITO-1901: Manage columns enhancements
apache/incubator-kie-kogito-apps pull request #268
Opened 2020-06-13 14:52 UTC by Sara4994

Please enter the commit message for your changes. Lines starting

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-06-19 19:51 UTC, srambach commented
The refresh icon seems to cause the column management modal to appear. I don't think it should, and should probably not be part of the ManageColumns component since it's really independent of this.

2020-06-19 19:54 UTC, srambach commented on packages/common/src/components/Molecules/ManageColumns/ManageColumns.tsx
> +          id="table-column-management"
Please add `isCompact` here.

2020-06-22 21:42 UTC, srambach commented
If we have a Select All option, I think that we also need to be able to remove selection from all. I know this isn't in the Patternfly demo, but we have many more columns to select than are shown in the demo. Is it possible either to use the bulk selector as shown here https://www.patternfly.org/v4/documentation/react/demos/bulkselecttable#component-title, or really all that is needed is the checkbox for all as shown here https://www.patternfly.org/v4/documentation/react/demos/filtertabledemo
Adding a header row with the checkbox and "Column name" as the column name (somewhat ironically) would be fine in my opinion.

2020-06-22 21:47 UTC, srambach commented
Here is how I've modified it, for reference along with the code comments. 
![image](https://user-images.githubusercontent.com/19825616/85338538-73e73f00-b4b0-11ea-9de5-2552fa9d0ba6.png)

2020-06-23 13:12 UTC, srambach requested changes

2020-06-23 13:12 UTC, srambach commented on packages/common/src/components/Molecules/ManageColumns/ManageColumns.css
> +}
Please replace entire contents with that below to clean up the spacing and to use Patternfly spacer variables for consistent spacing. We should test with more than one level of expansion to make sure it still works. This relies on adding the classname `kogito-common--manage-columns__data-list` to the overall table, and a couple of corrections to the classnames also in ManageColumns.tsx
```
.kogito-common--manage-columns__data-list .pf-c-data-list__toggle {
    margin-left: calc(-1 * var(--pf-global--spacer--md));
}

.kogito-common--manage-columns__data-list-content:not(:last-of-type) {
    box-shadow: none;   
}

.kogito-common--manage-columns__data-list-content .pf-c-data-list__expandable-content-body{
    padding: 0px;   
}

.kogito-common--manage-columns__data-list-content .pf-c-data-list__expandable-content-body .pf-c-data-list__item-row {
    padding-left: calc( var(--pf-global--spacer--2xl) + var(--pf-global--spacer--lg));
}

.kogito-common--manage-columns__data-list-content .pf-c-data-list__cell {
    padding-left: var(--pf-global--spacer--md);
}
```

2020-06-23 13:12 UTC, srambach commented on packages/common/src/components/Molecules/ManageColumns/ManageColumns.tsx
> +                  className="kogito-common--Manage-columns__DataList-content"
Change to `kogito-common--manage-columns__data-list-content`

2020-06-23 13:12 UTC, srambach commented on packages/common/src/components/Molecules/ManageColumns/ManageColumns.tsx
> +                      className="kogito-common--Manage-columns__DataList-content"
Change to `kogito-common--manage-columns__data-list-content`

2020-06-23 13:12 UTC, srambach commented on packages/common/src/components/Molecules/ManageColumns/ManageColumns.tsx
> +          id="table-column-management"
Also, add `className="kogito-common--manage-columns__data-list"` to be able to target this list

2020-06-23 21:10 UTC, srambach commented
@Sara4994 I think the bulk selector on the column management modal is getting list bullets because it's within a `pf-c-content` block. Try moving it out of the modal description and down into the modal content where the list is. I think that should solve it.

2020-06-24 15:13 UTC, srambach commented
On the empty state, we need to change the wording "Select columns from the dropdown to see content" to something more like `Select [Manage Columns](url) to see content.`

2020-06-24 15:42 UTC, srambach commented
> @Sara4994 I think the bulk selector on the column management modal is getting list bullets because it's within a `pf-c-content` block. Try moving it out of the modal description and down into the modal content where the list is. I think that should solve it.

And then, let's either use a new class on the dropdown so that we don't increase specificity, and use one of our PF spacer variables. 
```
.kogito-common--manage-columns__dropdown {
    margin-bottom: var(--pf-global--spacer--md);
}
```

2020-06-29 13:13 UTC, cristianonicolai commented
@Sara4994 should this be closed in favour of https://github.com/kiegroup/kogito-apps/pull/298 ?

2020-06-29 23:50 UTC, Sara4994 commented
Opened a new one https://github.com/kiegroup/kogito-apps/pull/298. Closing this

2020-06-29 23:50 UTC, closed without merging