KOGITO-1139 Add node retrigger action in process instance timeline
apache/incubator-kie-kogito-apps pull request #283
Opened 2020-06-19 09:04 UTC by AjayJagan

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

description: a node can be retriggered from the timeline of process details page.

JIRA: https://issues.redhat.com/browse/KOGITO-1139

2020-06-22 10:19 UTC, nmirasch commented
jenkins please retest this

2020-06-23 07:06 UTC, AjayJagan commented
jenkins please retest this

2020-06-25 05:18 UTC, jstastny-cz requested changes

2020-06-25 05:18 UTC, jstastny-cz commented on ui-packages/packages/management-console/server/MockData/controllers.js
> +  callNodeRetrigger:(req,res)=>{
formatting is a bit off - mainly whitespace, please try to reformat

2020-06-25 05:18 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/ProcessDetailsPage/tests/ProcessDetailsPage.test.tsx
> +      .simulate('click');
should we validate what happened after the click?

2020-06-25 05:18 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/ProcessDetailsPage/tests/__snapshots__/ProcessDetailsPage.test.tsx.snap
> +                              <AngleRightIcon
please mock the react-icons in whole file

2020-06-25 05:18 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/ProcessDetailsPage/tests/__snapshots__/ProcessDetailsPage.test.tsx.snap
> +                        <svg
these svg fragments are from some button? could we mock it?

2020-06-25 05:18 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/utils/tests/Utils.test.tsx
> +      );
we're not checking here the outcome, IDK in this case maybe whether the mocked functions were invoked or sth like that.

2020-06-26 06:26 UTC, AjayJagan commented on ui-packages/packages/management-console/server/MockData/controllers.js
> +  callNodeRetrigger:(req,res)=>{
removed the whitespace

2020-06-26 06:27 UTC, AjayJagan commented on ui-packages/packages/management-console/src/utils/tests/Utils.test.tsx
> +      );
I have tested the title, type and the content being set

2020-06-26 10:41 UTC, AjayJagan commented
jenkins please retest this

2020-06-29 10:11 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/ProcessDetailsPage/tests/ProcessDetailsPage.test.tsx
> +jest.mock(
please mock the @kogito-apps/common as you'd do for any external package - not to rely on its inner folder structure here.
Like you did for @patternfly/react-icons:
```
jest.mock('@kogito-apps/common', () => ({
  ...jest.requireActual('@kogito-apps/common'),
  ProcessDescriptor: () => {
    return <MockedComponent />;
  },
  KogitoSpinner: () =>
.
.
.
}));
```

2020-06-29 10:11 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/ProcessDetailsPage/tests/ProcessDetailsPage.test.tsx
> +      .simulate('click');
should we click twice here?

2020-06-29 11:51 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Templates/ProcessDetailsPage/tests/ProcessDetailsPage.test.tsx
> +jest.mock(
changed now :)

2020-06-29 13:24 UTC, jstastny-cz requested changes

2020-06-29 13:24 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +        <Dropdown
this dropdown is the same as the on in following elseif branch, just a few strings change there. Can we derive a function and just keep the moving parts as arguments?

2020-06-29 13:24 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +        <Dropdown
Or maybe! create a separate component here? covering all the cases we have here in this function `processManagementKebabButtons` together with `onDropdownSelect` and `onKebabToggle`,... ?

2020-06-29 13:24 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      wrapper
So we're clicking twice here, right? first open, second close? Then I'd check also if the Dropdown was actually opened -> add a `isOpen` check after first click that would check expect `true`

2020-06-29 13:24 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      wrapper
check before here that the kebab was open by the onToggle invocation.

2020-06-29 13:24 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      .find(Dropdown)
please add at least comments with description on what we're acutally clicking (improves readability of test).

2020-06-29 13:24 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      .find(Dropdown)
Please see if we can test each step here -> each `onClick` invocation should IMO be followed by a `expect` unless there is a valid reason not to - each onClick IMO should have an influence on the DOM, so I expect this is not a case here and it is testable.

2020-06-30 05:30 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +        <Dropdown
Hey @jstastny-cz - I have converted the redundant code to a simple function . Please have a look

2020-06-30 06:40 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  onSuccessAction: (title: string, content: string) => void,
@AjayJagan I think _onSuccessAction_ you actually dont need any parameters. This method just called called so you know it operation succeed.

2020-06-30 06:40 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  onFailureAction: (title: string, content: string) => void
in here I would propose to only have a `message: string` as result so you can build the final content.

2020-06-30 06:40 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  nodeObject: any,
You can either pass the `id` as String or a `Pick<
    NodeInstance,
    'id'
  >`
Node name is not needed as message should be built in the calling method.

2020-06-30 06:40 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +      const tempKebabArray = [...kebabOpenArray];
you just call `onDropdownSelect id` from here?

2020-06-30 06:40 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Atoms/ErrorPopover/ErrorPopover.tsx
> +  onSuccessAction: (title: string, content: string) => void;
same here, would keep onSuccessAction as simple function and onFailureAction with a message string to be returned.

2020-06-30 08:29 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +        <Dropdown
converted to a simple function removing redundant code :)

2020-06-30 08:30 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      wrapper
as discussed I was not able to assert the isOpen properly .. let's investigate it more and do it in an incremental pr

2020-06-30 08:31 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      wrapper
as discussed I was not able to assert the isOpen properly .. let's investigate it more and do it in an incremental pr

2020-06-30 08:31 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      .find(Dropdown)
added the comments and placed the expect below each click for better readability

2020-06-30 09:02 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Atoms/ErrorPopover/ErrorPopover.tsx
> +  onSuccessAction: (title: string, content: string) => void;
@cristianonicolai - so do we need to have something like this for failure 'The node confirm travel failed to retirgger', or the real error message itself which looks something like - 'no such node found in the process instance'(checked using the swagger)

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +      const tempKebabArray = [...kebabOpenArray];
@AjayJagan ^

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +      onRetriggerFailure();
need to pass message here?

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  nodeObject: Pick<GraphQL.NodeInstance, 'id'>,
```suggestion
  node: Pick<GraphQL.NodeInstance, 'id'>,
```

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  processInstanceData: Pick<
```suggestion
  processInstance: Pick<
```

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +  const onRetriggerFailure = (): void => {
```suggestion
  const onRetriggerFailure = (name: String): void => {
```

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +  const onRetriggerSuccess = (): void => {
```suggestion
  const onRetriggerSuccess = (name: String): void => {
```

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +              onRetriggerSuccess,
```suggestion
              () => onRetriggerSuccess(node.name),
```

2020-06-30 15:21 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +              onRetriggerFailure
```suggestion
              () => onRetriggerFailurenode.name)
```

2020-06-30 15:31 UTC, AjayJagan commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +      onRetriggerFailure();
we show the name of the node that has failed to retrigger.. is that fine or should I get the error message and show it in the modal

2020-06-30 16:07 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +      const tempKebabArray = [...kebabOpenArray];
reused the function :)

2020-06-30 16:07 UTC, AjayJagan commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  processInstanceData: Pick<
changed

2020-06-30 16:07 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +  const onRetriggerFailure = (): void => {
changed

2020-06-30 16:07 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +  const onRetriggerSuccess = (): void => {
changed

2020-06-30 16:07 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +              onRetriggerSuccess,
changed

2020-06-30 16:08 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +              onRetriggerFailure
changed

2020-07-01 11:37 UTC, jstastny-cz requested changes

2020-07-01 11:37 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  };
We could reduce code repetition even more:
```suggestion
  const onAction = (type: string, title: string, content: string): void => {
    setTitleType(type);
    setModalTitle(title);
    setModalContent(content);
    handleModalToggle();
  }
  const onSuccessAction = (title: string, content: string): void => {
    onAction('success', title, content)
  };

  const onFailureAction = (title: string, content: string): void => {
    onAction('failure', title, content)
  };
```

2020-07-01 11:37 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +    );
Is this exactly the same as in ProcessListTableItems ? Can we extract the dropdownitems together with the actions to a separate component/s?

Conceptually in following lines:
Move dropdowns and their actions to a separate file, let's call Actions for now. Resulting would be: Actions.SkipDropdownItem, Actions.onSkipSuccess(), Actions.onSkipFailure(), Actions.RetryDropdownItem ...
then in `const dropdownItems` below we would be adding return [ <Actions.RetryDropdownItem/>, <Actions.SkipDropdownItem/> ] and the on-functions would be hidden in Actions.
But we would need probably to pass the functions to alter the modal from there ... or would moving the ProcessListModal to the new file help there? to have another component <Actions.ProcessListModal /> ...

I mean at least as a follow-up action ... wdyt?

2020-07-01 11:37 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      expect(handleNodeInstanceRetriggerSpy).toHaveBeenCalled();
can we add check for the result? probably checking if onRetriggerFailure() has been invoked ..... or check contents of the modal?

2020-07-01 13:38 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +    );
yeah I had similar idea, it starts to become evident that we would need another component here for the actions.

2020-07-01 13:39 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +    );
so do you want me to go with the same PR?

2020-07-01 13:41 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  };
changed as requested :)

2020-07-01 13:41 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/tests/ProcessDetailsTimeline.test.tsx
> +      expect(handleNodeInstanceRetriggerSpy).toHaveBeenCalled();
so now the modalContent is being checked as well

2020-07-01 14:04 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Organisms/ProcessDetailsTimeline/ProcessDetailsTimeline.tsx
> +    );
This can be done as a follow up ..
here is the JIRA link for that -> https://issues.redhat.com/browse/KOGITO-2608

2020-07-01 14:19 UTC, jstastny-cz approved these changes

2020-07-01 15:13 UTC, jstastny-cz commented
Code duplication removal planned as https://issues.redhat.com/browse/KOGITO-2608. Do you all agree?
@AjayJagan @cristianonicolai @Sara4994 @nmirasch

2020-07-02 00:49 UTC, srambach commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +      'Process execution has successfully re-executed node which was in error state.',
Should all these error messages be getting put into a separate file for i18n and ease of maintenance?
In other places, we say "The node [id] was..." Should we stick with that wording here? I.e. "The node [id] was successfully re-executed." Is it important that it was in an error state? Or that it is now (if it failed wouldn't it be assumed to be now in error?) @cristianonicolai

2020-07-02 04:10 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +      'Process execution has successfully re-executed node which was in error state.',
@srambach I agree we need to review i18n and consolidate these messages. @nmirasch could you open a JIRA for that?

Regarding this message in specific, I agree to make it more consistent so: _The node [id] was successfully re-executed._ looks good to me.

2020-07-02 06:44 UTC, nmirasch commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +      'Process execution has successfully re-executed node which was in error state.',
@cristianonicolai  @srambach  sure, here it is  https://issues.redhat.com/browse/KOGITO-2625

2020-07-02 10:14 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  const onAction = (title: string, content: string, type: string): void => {
type shouldnt be TitleType?
```suggestion
  const onAction = (title: string, content: string, type: TitleType): void => {
```

2020-07-02 10:14 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  node: Pick<GraphQL.NodeInstance, 'name'>,
you shouldn't receive a node here. The node endpoint for retrigger is a different one, already covered in `handleNodeInstanceRetrigger` method

2020-07-02 10:14 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +    'id' | 'nodes' | 'addons' | 'error' | 'serviceUrl' | 'processId' | 'state'
I think you only need `serviceUrl`, `processId`, `id` here

2020-07-02 10:14 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  node: Pick<GraphQL.NodeInstance, 'name'>,
you dont need node in here

2020-07-02 10:14 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +        node ? node.name : processInstance.processName,
do you need to pass name back? you already have this in the calling method?

2020-07-02 10:14 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +    'id' | 'processId' | 'serviceUrl' | 'state' | 'processName'
shouldn't need the name here, its available in the calling method.

2020-07-02 10:26 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +      onRetriggerFailure();
missing to pass the error message here?

2020-07-02 12:27 UTC, AjayJagan commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  node: Pick<GraphQL.NodeInstance, 'name'>,
removed

2020-07-02 12:28 UTC, AjayJagan commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +    'id' | 'nodes' | 'addons' | 'error' | 'serviceUrl' | 'processId' | 'state'
yes only passing that

2020-07-02 12:28 UTC, AjayJagan commented on ui-packages/packages/management-console/src/utils/Utils.tsx
> +  node: Pick<GraphQL.NodeInstance, 'name'>,
done

2020-07-02 12:28 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  const onAction = (title: string, content: string, type: string): void => {
changed

2020-07-02 15:11 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  // const onRetrySuccess = (name: string): void => {
please remove unsued code :)

2020-07-02 15:11 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Atoms/ErrorPopover/ErrorPopover.tsx
> +  onAction: (title: string, content: string, type: TitleType) => void;
@AjayJagan you can get these functions pushed back. If you have in here lets say:
`onRetryClick` and `onSkipClick`, then all popup and messages get centralized into `ProcessListTableItems`  wdyt?

2020-07-02 15:11 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  const onAction = (title: string, content: string, type: string): void => {
@AjayJagan could we have a more meaningful name for this function?

2020-07-02 15:54 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  // const onRetrySuccess = (name: string): void => {
done

2020-07-02 15:54 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +  const onAction = (title: string, content: string, type: string): void => {
renamed to onShowMessage as you suggested.

2020-07-02 15:54 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Atoms/ErrorPopover/ErrorPopover.tsx
> +  onAction: (title: string, content: string, type: TitleType) => void;
grouped those functions :)

2020-07-02 15:57 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +    type: string
```suggestion
    type: TitleType
```

2020-07-02 16:01 UTC, AjayJagan commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +    type: string
done :D

2020-07-02 16:27 UTC, srambach commented on ui-packages/packages/management-console/src/components/Molecules/ProcessListTableItems/ProcessListTableItems.tsx
> +      'Process execution has successfully re-executed node which was in error state.',
👍

2020-07-02 16:40 UTC, srambach approved these changes
Changes here look good.

2020-07-02 16:56 UTC, cristianonicolai approved these changes

2020-07-02 17:01 UTC, nmirasch approved these changes

2020-07-02 17:05 UTC, Sara4994 approved these changes

2020-07-02 19:26 UTC, cristianonicolai commented
jenkins please retest this

2020-07-03 03:15 UTC, merged