KOGITO-2431: Fixed snapshots related to DE
apache/incubator-kie-kogito-apps pull request #284
Opened 2020-06-19 14:34 UTC by Sara4994

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-06-22 10:12 UTC, jstastny-cz requested changes

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('Snapshot test with default props', async () => {
I would maybe keep this test as the only one that actually uses the patternfly table component and mock in the rest.

The goal is to make the snapshot shorter - this way we make sure that the component renders fine with default props and then in other snapshots just focus on the behavior (often it is emtpy-state vs. table rednered - but we don't need to see the contents of the table, it is enough to see that table component is being used)

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('Boolean assertions-false', async () => {
here I am still not clear on the description of the test, one is `Boolean assertions-false`, second `Boolean assertions-true` - what is the difference?

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('Boolean assertions-false', async () => {
Hum, the snapshots for the two tests are identical, just differ based on passed values (state `COMPLETED` vs. `PENDING` in one process instance). So unless there's some reason I am missing I would remove both the snapshots, cause they're identical also to `Snapshot test with default props`. If this is due to coverage - we might need to test differently - cause there's nothing interesting in the resulting snapshot.

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('check false value of isLoadingMore', async () => {
is empty-state in snapshot here expected?

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('check zero offset', async () => {
Should zero offset result in empty-state? Or needs the test to be fixed?

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/__snapshots__/DomainExplorer.test.tsx.snap
> +    <LoadMore
can we try mocking LoadMore too?

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/__snapshots__/DomainExplorer.test.tsx.snap
> +  <DataToolbar
Can we mock DataToolbar now?

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/DomainExplorerLandingPage/tests/__snapshots__/DomainExplorerLandingPage.test.tsx.snap
> +                      <AngleRightIcon
I think we can mock all the icons used here, it'll save some space in snapshots.

2020-06-22 10:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/DomainExplorerPage/tests/__snapshots__/DomainExplorerPage.test.tsx.snap
> +                      <AngleRightIcon
could we mock the icons to shorten the snapshot?

2020-06-22 11:35 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('check false value of isLoadingMore', async () => {
@jstastny-cz yes it is, as per the condition provided.

2020-06-22 11:35 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/__snapshots__/DomainExplorer.test.tsx.snap
> +    <LoadMore
this is done

2020-06-22 11:36 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('Boolean assertions-false', async () => {
This is made as one single snapshot tests all state values

2020-06-22 11:43 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +  it('check zero offset', async () => {
This is fixed, now it renders table not empty-state

2020-06-22 14:57 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/__snapshots__/DomainExplorer.test.tsx.snap
> +  <DataToolbar
This is done

2020-06-22 14:57 UTC, Sara4994 commented on ui-packages/packages/management-console/src/components/Templates/DomainExplorerLandingPage/tests/__snapshots__/DomainExplorerLandingPage.test.tsx.snap
> +                      <AngleRightIcon
Mocked Breadcrumb

2020-06-22 14:57 UTC, Sara4994 commented on ui-packages/packages/management-console/src/components/Templates/DomainExplorerPage/tests/__snapshots__/DomainExplorerPage.test.tsx.snap
> +                      <AngleRightIcon
Mocked Breadcrumb as suggested

2020-06-22 15:13 UTC, jstastny-cz requested changes
Just a typo in component name, otherwise looks great.

2020-06-22 15:13 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/DomainExplorer.test.tsx
> +const MockedDatToolbar = (): React.ReactElement => {
typo MockedDatToolbar -> MockedDataToolbar

2020-06-22 15:27 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/DomainExplorer.test.tsx
> +const MockedDatToolbar = (): React.ReactElement => {
Corrected :+1:

2020-06-22 15:32 UTC, jstastny-cz approved these changes

2020-06-22 16:55 UTC, nmirasch approved these changes

2020-06-23 05:00 UTC, AjayJagan approved these changes

2020-06-23 09:57 UTC, cristianonicolai approved these changes

2020-06-23 09:57 UTC, merged