KOGITO-580 - Task console bootstrap
apache/incubator-kie-kogito-apps pull request #30
Opened 2019-11-20 19:28 UTC by Sara4994

2019-11-20 23:57 UTC, cristianonicolai requested changes
@Sara4994 please  also take a look in the build error

2019-11-20 23:57 UTC, cristianonicolai commented on packages/task-console/src/index.html
> +    <title>Kogito - Management Console</title>
```suggestion
    <title>Kogito - Task Console</title>
```

2019-11-21 16:12 UTC, cristianonicolai commented
@Sara4994 I wonder if we could reuse some of these config files. I belive most settings will be common anyway so we could share it. It would avoid inconsistencies in the future.

2019-11-25 11:54 UTC, cristianonicolai reviewed
@Sara4994 could we also share the webpack files? seems like we can do import and these are not really different between apps, wdyt?

2019-11-25 11:54 UTC, cristianonicolai commented on Jenkinsfile
> +                            sh('yarn run init && yarn build:prod && yarn run lint')
shouldnt lint be part of build:prod instead?

2019-11-25 12:56 UTC, Sara4994 commented on Jenkinsfile
> +                            sh('yarn run init && yarn build:prod && yarn run lint')
@cristianonicolai moved lint as common one for both the apps. there is a script in package.json of lerna, which will check lint errors for the both application.

2019-11-25 17:17 UTC, cristianonicolai approved these changes

2019-11-26 02:48 UTC, AjayJagan approved these changes

2019-11-26 02:54 UTC, merged