KOGITO-1331: Domain Explorer filters
apache/incubator-kie-kogito-apps pull request #315
Opened 2020-07-07 05:41 UTC by Sara4994

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-07-09 10:52 UTC, Sara4994 commented
jenkins please retest this

2020-07-09 13:55 UTC, srambach commented
I'm wondering about the default view when you first come into the domain explorer - "metadata/processInstances/state:ACTIVE" is shown as the filter on a chip. "Clear all filters" does clear them - but normally I'd expect that sort of reset to take the user back to the initial state. I see value in the default if it's a shortcut for the user, but I'd also think the reset should go to the initial state. @kywalker-rh  @lclay2

2020-07-09 14:16 UTC, Sara4994 commented
@kywalker-rh @srambach I have a question too, For instance, i making selections on all 3 dropdowns or providing inputs to textinputs and clicking on Apply filter... At this point, dropdowns and textInputs should reset back to placeholder text..?

2020-07-09 14:34 UTC, srambach commented
Instead of defaulting to "Operator" when a new filter field is selected, is it better to just default to the first one?  (I understand that what the operators are is defined in the data, not the interface)
Should the operators be alphabetized, or left in the order they are?
@kywalker-rh @lclay2

2020-07-09 18:20 UTC, lclay2 commented
@srambach  It's difficult to weigh in without seeing it in action.

2020-07-10 20:14 UTC, srambach commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/DomainExplorerManageColumns.tsx
> +          where: { value: finalFilters, type: argument }
On line 595 down below, the `className="pf-u-m-md"` should be removed because it is causing too much space between the filter toolbar and chips.

2020-07-10 20:15 UTC, srambach commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.css
> +    margin-right: var(--pf-global--spacer--md)
Please be sure to pu a `;` at the end of each CSS line.

2020-07-13 06:23 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/DomainExplorerManageColumns.tsx
> +          where: { value: finalFilters, type: argument }
@srambach done, thanks

2020-07-13 06:23 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.css
> +    margin-right: var(--pf-global--spacer--md)
@srambach added :+1:

2020-07-14 12:27 UTC, Sara4994 commented
jenkins please retest this

2020-07-14 19:05 UTC, srambach commented
A few things:
- I see the filter button turn active before all parts of the filter are valid. 
- changing the operator sometimes removes or changes the value. This seems maybe to be when focus is on the text field and you go directly to the operator dropdown and change it.

2020-07-16 08:22 UTC, jstastny-cz requested changes

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  currentDomain,
can we sort the params alphabetically?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +    null,
again, can we sort?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/DomainExplorerTable.tsx
> +                  Selected filters has no data to display. Try other filters.
filters has -> fitlers have (or filter has)

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/DomainExplorerTable.tsx
> +              title="No filter applied"
do we want to end title and body with period since we start with capital letter?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +    const props = {
You can do here similarly to the test above:
* defining some common base props once (lets say containing `filterError: ''`)
* where needed important things can be overrided/added by `<DomainExplorerTable {...{...props, filterError:'some-error'}} />`

wdyt?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +    wrapper.update();
there's no check of the result

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +      ['onClick'](event);
we should probably check what happens after

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/__snapshots__/DomainExplorerTable.test.tsx.snap
> +                      <ExclamationTriangleIcon
please mock the icons

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/ServerErrors/ServerErrors.tsx
> +        <Bullseye>
to me this element seems duplicated in both cases. extract into a function or component and just wrap inside the pagesection when needed.

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +configure({ adapter: new Adapter() });
don't we have this somewhere in our common configuration?
I can see this in `config/Jest-config/test-setup.js` isn't that enough?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +  const mockuseApolloClient = () => {
mockuse -> mockUse

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    await Promise.resolve();
not that it would matter too much, just out of curiosity, can't we use getWrapperAsync() above and just check the snapshot after?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    await Promise.resolve();
we're resolving the promise now (I assume it is to wait for mount to wrap up) - so all the find() and simulate() were called while the components were still loading?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    // simulate on select prop on fields dropdown to make a selection
Shouldn't we verify what happened after each step?

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    // simulate on select prop on fields dropdown to make a selection
Again I would expect an `expect` after each such step.

2020-07-16 08:22 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/__snapshots__/DomainExplorerFilterOptions.test.tsx.snap
> +                <CaretDownIcon
we could mock the icon.

2020-07-16 10:25 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/__snapshots__/DomainExplorerFilterOptions.test.tsx.snap
> +                <CaretDownIcon
@jstastny-cz these Icon cant be mocked, since they are used inside PF component. So mocking this Icon will not make an effect on snapshots

2020-07-16 10:25 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/__snapshots__/DomainExplorerTable.test.tsx.snap
> +                      <ExclamationTriangleIcon
@jstastny-cz these Icon cant be mocked, since they are used inside PF component. So mocking this Icon will not make an effect on snapshots

2020-07-16 10:25 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/DomainExplorerTable.tsx
> +                  Selected filters has no data to display. Try other filters.
done

2020-07-16 11:11 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    await Promise.resolve();
getWrapperAsync does work nice in my test, so used mock instead

2020-07-16 13:10 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +    const props = {
modified :+1:

2020-07-16 13:11 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    await Promise.resolve();
actually this wasnt required on this line... so removed it.

2020-07-16 13:11 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    // simulate on select prop on fields dropdown to make a selection
done

2020-07-16 13:11 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    // simulate on select prop on fields dropdown to make a selection
done

2020-07-16 13:16 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerTable/tests/DomainExplorerTable.test.tsx
> +    wrapper.update();
added check

2020-07-16 16:27 UTC, jstastny-cz requested changes

2020-07-16 16:27 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    // const mGraphQLResponse = {
should be removed?

2020-07-16 16:27 UTC, jstastny-cz commented on ui-packages/packages/common/src/utils/tests/Utils.test.ts
> +    clearEmpties(obj);
should we check the object now?

2020-07-16 16:27 UTC, jstastny-cz commented on ui-packages/packages/common/src/utils/tests/Utils.test.ts
> +    clearEmpties(obj);
And please add tests with more cases

2020-07-16 16:27 UTC, jstastny-cz commented on ui-packages/packages/common/src/utils/tests/Utils.test.ts
> +    set(obj, keys, value);
we should check the outcome

2020-07-16 16:27 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/ServerErrors/tests/ServerErrors.test.tsx
> +    wrapper.update();
can we check what the click did?

2020-07-16 16:43 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    // const mGraphQLResponse = {
done

2020-07-16 16:43 UTC, Sara4994 commented on ui-packages/packages/common/src/utils/tests/Utils.test.ts
> +    set(obj, keys, value);
done

2020-07-16 16:46 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/ServerErrors/tests/ServerErrors.test.tsx
> +    wrapper.update();
done

2020-07-16 17:00 UTC, Sara4994 commented on ui-packages/packages/common/src/utils/tests/Utils.test.ts
> +    clearEmpties(obj);
done

2020-07-16 20:14 UTC, nmirasch commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/tests/__snapshots__/DomainExplorer.test.tsx.snap
> +  defaultFilter={
@Sara4994  we have to avoid use process instance stuff in common package to keep that to find other kind of assets. Wdyt?

2020-07-16 20:27 UTC, nmirasch commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const stateArray = [
@Sara4994 we have to avoid use process instance stuff in common package to keep that to find other kind of assets.
I think the generic part of the  domain explorer have to filter just by domain data, (thinking in reuse this component for other purposes)

2020-07-16 20:50 UTC, nmirasch commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const nullTypes = [
@Sara4994  could you find a better name for this?

2020-07-17 02:45 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const stateArray = [
+1 will be very hard to make it generic later on. I believe this can be avoided if you check that the attribute is of type enum. Then you can get the enum values from the schema itself.

2020-07-17 02:45 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/DomainExplorerManageColumns.tsx
> +  finalFilters: any;
would be possible to define the actual type here?

2020-07-17 02:45 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +  rememberedFilters: any;
please use specific types

2020-07-17 02:45 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +                        argument={argument}
It seems just a big dependency between these components, in high level, it should mostly get a domain that is needed to find out the schema object and have a method callback about when a new filter is applied

2020-07-17 04:31 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const nullTypes = [
changed :+1:

2020-07-17 04:38 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/DomainExplorerManageColumns.tsx
> +  finalFilters: any;
done

2020-07-17 09:38 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const stateArray = [
@cristianonicolai  i did try to get enum by having check, I got enum as type for field = state, operator = 'equal'. But in case of field = state, operator = 'in' type is provided as LIST. Thats the reason i had to keep those values in an array

2020-07-17 12:40 UTC, Sara4994 commented
jenkins please retest this

2020-07-17 18:19 UTC, srambach commented
Looks good 👍

2020-07-20 03:38 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const stateArray = [
the ProcessInstanceStateArgument defines _equal_ and _in_ as types, one is a single `ProcessInstanceState` and the other is and array of `ProcessInstanceState`. If the type is a list, should be possible to get the actual type. https://github.com/kiegroup/kogito-apps/blob/master/data-index/data-index-service/src/main/resources/schema.graphqls#L243

2020-07-21 06:42 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  const stateArray = [
@cristianonicolai @nmirasch as suggested handled using query to fetch enum

2020-07-21 06:44 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +                        argument={argument}
@cristianonicolai as discussed, removed query from ManageColumns component and some of its dependencies. Now query inside FilterOptions component works generic to handle manage columns and filters

2020-07-21 09:47 UTC, jstastny-cz reviewed
I have a few reservations regarding readability, please see respective comments.

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  // const stateArray = [];
please remove commented code

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +      typeName.type.kind === 'ENUM' ||
can we create a function returning boolean and name based on what it checks? It's not clear form the condition itself.

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +      typeName.type.kind === 'ENUM' ||
Maybe moving the whole logic into a separate function would help - and leave onSelect just to call the functions
```
const onSelect = event => {
    setSelectTypes(event.target.innerText);
    setIsFilterDropdownOpen(false);
    newlyAddedFunction(itemName:string);
}
```

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +    const parent = event.nativeEvent.target.parentElement.parentElement.getAttribute(
please also here - introduce a function whose name would be indicate the purpose and just call it from the onChange.

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  finalResult.unshift(rootElement);
this hits readability - does the invocation of unshift need to be here? I think it does not need to be in between the `const` definitions, right? Please move below all const definitions.

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  useEffect(() => {
please move useEffect hooks next to each other.

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +  };
What do you think of similar rewrite? (plus there's a typo in `validataScalarArgument`)
```
  const valueToValidate = (currentArgumentScalar) => {
    switch (currentArgumentScalar)
      case 'Boolean': return currentBoolean;
      case 'ArrayString': return selectedState;
      case 'stateSelection': return selectedState;
      case 'MultiSelection': return multiState;
      default: return textValue;
    }
  }
  const validataScalarArgument = (scalarType, objKeys) => {
    const value = valueToValidate(scalarType);
    let parentString = '';
    let chipText = '';
    typeParent &&
      typeParent.map(parent => (parentString = parentString + ' / ' + parent));
    parentString = parentString.substring(3);
    if (scalarType === 'ArrayString') {
      chipText = validateChip(parentString, selected, selectTypes, inputArray);
      let chipSelections = '';
      if (typeParent) {
        chipSelections = `${parentString} / ${selected}`;
      } else {
        chipSelections = selected;
      }
      checkChipArray(chipSelections, chipText);
      const tempArray = inputArray.split(',');
      set(obj, objKeys, tempArray);
    } else {
      chipText = validateChip(parentString, selected, selectTypes, value);
      let chipSelections = '';
      if (typeParent) {
        chipSelections = `${parentString} / ${selected}`;
      } else {
        chipSelections = selected;
      }
      checkChipArray(chipSelections, chipText);
      set(obj, objKeys, value);
    }
    setFinalFilters(() => {
      if (finalFilters.hasOwnProperty(typeParent)) {
        const te: any = Object.values(obj)[0];
        finalFilters[typeParent] = { ...finalFilters[typeParent], ...te };
        return finalFilters;
      } else {
        return { ...finalFilters, ...obj };
      }
    });
    setTypeParent('');
    setRunQuery(true);
  };

  const onApplyFilter = () => {
    let objKeys;
    if (typeParent.length > 0) {
      objKeys = `${typeParent},${selected},${selectTypes}`;
    } else {
      objKeys = `${selected},${selectTypes}`;
    }
    validataScalarArgument(currentArgumentScalar, objKeys);
  };
```

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/tests/DomainExplorerFilterOptions.test.tsx
> +    mockUseEffect();
why invoked twice here? to mock implementation twice?

2020-07-21 09:47 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/tests/DomainExplorerManageColumns.test.tsx
> +    const wrapper = mount(<DomainExplorerManageColumns {...{ ...props }} />);
we can keep just `{...props}` here when not overriding any value

2020-07-21 10:56 UTC, jstastny-cz approved these changes
I don't see anything wrong in the PR, seems rather complex, but that might be inevitable in this case.

2020-07-21 12:00 UTC, AjayJagan approved these changes
looks good to me

2020-07-22 07:02 UTC, nmirasch commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +      setFinalFilters({
@Sara4994  could we use here defaultfilter received as parameter?

2020-07-22 07:02 UTC, nmirasch commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +      setFilterChips(['metadata / processInstances / state: ACTIVE']);
@Sara4994  could we use here defaultChip received as parameter?

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +        setCurrentArgumentScalar('stateSelection');
this should be generic for any enum, could it be merged if the lines above?

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/DomainExplorerManageColumns.tsx
> +  setRunQuery: any;
please use more specific types

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +  rememberedFilters: object;
please use more specific types

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +                        argument={argument}
@Sara4994 thats good but still feels that the dependency between `DomainExplorer` and `DomainExplorerFilterOptions` is huge, based on the amount of arguments we have in here. Would be good if that could be avoided.

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/graphql/graphql.schema.json
> +            "name": "Travels",
@Sara4994 please dont include custom types in here. Please regenerate without deploying proto files to data index.

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/graphql/types.tsx
> +  export type Address = {
as mentioned, custom types should not be added to our types, please regenerate the graphql schema.

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/utils/Utils.ts
> +  const _obj = testObj;
feels like some magic going on here, maybe adding some comments to describe the goal of each of these methods and a more specific name could help to understand.

2020-07-23 06:03 UTC, cristianonicolai commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
please remove file from PR.

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +    'ProcessInstanceState',
do we still need to handle this, isnt enough to just handle as an enum?

2020-07-23 06:03 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +      const Query = query({
shouldnt be the parent component be the one responsible for sending the queries when the filters change?

2020-07-23 13:13 UTC, Sara4994 commented
jenkins please retest this

2020-07-23 13:53 UTC, Sara4994 commented on ui-packages/packages/common/src/graphql/types.tsx
> +  export type Address = {
done

2020-07-23 15:40 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +    'ProcessInstanceStateArgument',
do we need special handling for `ProcessInstanceStateArgument` ?

2020-07-23 15:40 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerManageColumns/DomainExplorerManageColumns.tsx
> +  enableRefresh: any;
please use specific type

2020-07-23 15:40 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +  rememberedFilters: object;
still mostly using any

2020-07-23 15:40 UTC, cristianonicolai commented on ui-packages/packages/common/src/components/Organisms/DomainExplorer/DomainExplorer.tsx
> +  const Query = query({
can you rename to something more meaningful, like `domainQuery` ?

2020-07-23 15:40 UTC, cristianonicolai commented on ui-packages/packages/common/src/utils/Utils.ts
> +// functio that removes single property from object
```suggestion
// function that removes single property from object
```

2020-07-23 15:40 UTC, cristianonicolai commented on ui-packages/packages/management-console/src/components/Templates/DomainExplorerPage/DomainExplorerPage.tsx
> +  finalFilters?: any;
use more specific types?

2020-07-23 16:52 UTC, Sara4994 commented on ui-packages/packages/common/src/components/Molecules/DomainExplorerFilterOptions/DomainExplorerFilterOptions.tsx
> +    'ProcessInstanceStateArgument',
yes it is required for now, to avoid below attributes on the first dropdown

input ProcessInstanceStateArgument {
    equal: ProcessInstanceState
    in: [ProcessInstanceState]
  }

2020-07-24 03:09 UTC, Sara4994 commented
Jenkins please retest this

2020-07-24 10:42 UTC, cristianonicolai approved these changes

2020-07-24 10:59 UTC, cristianonicolai commented
jenkins please retest this

2020-07-27 06:57 UTC, nmirasch commented
jenkins please retest this

2020-07-27 13:12 UTC, nmirasch approved these changes

2020-07-28 05:54 UTC, Sara4994 commented
jenkins please retest this

2020-07-28 10:28 UTC, Sara4994 commented
jenkins please retest this

2020-08-03 09:02 UTC, Sara4994 commented
jenkins please retest this

2020-08-03 14:14 UTC, merged