KOGITO-2750 - add explainability-core and explainability-integrationtests to kogito-apps
apache/incubator-kie-kogito-apps pull request #324
Opened 2020-07-15 09:48 UTC by tteofili

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-07-15 10:29 UTC, r00ta reviewed
Hi @tteofili thanks for the PR! I have some difficulties to review the pull request that is pretty big. And I have some high level questions about the main structure of the library (for example why is it handling the communication with the kogito-runtimes at a library level and not at a service level?). IIUC the api for the local explanability is 
```
T explain(Prediction prediction, BlackBoxModel model);
```
But I wonder if it's better to review the api of the library so to make it more flexible, for example leaving the consumer to decide how to implement the component that interacts with the kogito-runtime and so on. 
I wonder if it's better to split the pull request in smaller PRs, so that we can discuss and review the components properly, wdyt?

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-core/pom.xml
> +</project>
I think you have to refactor a bit this pom, the versions of the artifacts should be put in `kogito-runtimes/bom` as well as `properties` that are not already present in the parent poms

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
> +<?xml version="1.0"?>
Can you review this pom? the versions of the artifacts should be put in kogito-runtimes/bom as well as properties that are not already present in the parent poms

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +<?xml version="1.0"?>
Can you review this pom? the versions of the artifacts should be put in `kogito-runtimes/bom` as well as `properties` that are not already present in the parent poms

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +    <artifactId>kogito-apps</artifactId>
wrong parent

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
> +    <artifactId>kogito-apps</artifactId>
wrong parent

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-core/pom.xml
> +    <artifactId>kogito-apps</artifactId>
wrong parent

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +    <artifactId>kogito-apps</artifactId>
wrong parent

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +<?xml version="1.0"?>
Can you review this pom? the versions of the artifacts should be put in kogito-runtimes/bom as well as properties that are not already present in the parent poms

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-integrationtests/pom.xml
> +    <artifactId>kogito-apps</artifactId>
wrong parent

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
private static final

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/HttpHelper.java
> +}
Do we need this?

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/RemoteDMNModel.java
> +    }
I think this comes directly from the PoC and might not be what we will do for the stable implementation?

2020-07-15 10:29 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/RemoteDMNModel.java
> +public class RemoteDMNModel implements BlackBoxModel {
I personally would remove all the communication between services from this library and delegate it to the service, wdyt?

2020-07-15 11:53 UTC, tteofili commented
thanks @r00ta for your comments.
I understand your concerns regarding the big PR being a bit hard to review in a fine grained manner.
That is the reason why this PR is only about the `explainability-core` module (and its ITs) while the `explainability-service` is left untouched / empty.
One alternative might be to separate an `explainability-api` module out from `explainability-core` and me filing two separate PRs about them.
Generally speaking I agree on the fact that the communication between the library and the model would rather happen in the service.
And thanks about the suggested POM fixes.

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/pom.xml
> +    <surefire-plugin.version>2.22.1</surefire-plugin.version>
I think you should be able to inherit all these information from parent pom and if not we should move these properties there

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/pom.xml
> +    </dependencies>
Same for this

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/pom.xml
> +      <version>3.9</version>
Al dependency versions should be managed with `DependencyManagement` node in root pom (btw I think they are already defined so just try to remove the `version` as first

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +        logger.info("explanation time: {}ms", (end - start));
I think `debug` should be better

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +            if (!Type.NUMBER.equals(featureTypes.get(t))) {
Why don't add `NUMBER` to `switch` block and remove this addition `if`? Is it needed?

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +            }
What does this imply?

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +        logger.info("explanation time: {}ms", (end - start));
`debug`?

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/pom.xml
> +    </dependency>
:thinking: Are you sure about this dependency? I do not expect this library to depends on `kogito-api`. Maybe it is for `test`?

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +            return "";
Why this? This means that empty string and `null` are equivalent

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/DMNUtils.java
> +public class DMNUtils {
Can you review this class? It is named `DMN` but it is not using any DMN class at all. Is it maybe a generic data types utils class?

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/DecisionModelWrapper.java
> +public class DecisionModelWrapper implements BlackBoxModel {
What is this class? I do not expect any `DMN` specific class in this library expect as `test`

2020-07-15 13:12 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/HttpHelper.java
> +public class HttpHelper {
This should not be in the `core` (and in general we can leverage on `quarkus` features for that)

2020-07-15 15:22 UTC, r00ta reviewed
Some more comments

2020-07-15 15:22 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/kogito/explainability/explainability/integrationtests/dmn/LoanEligibilityDmnLimeExplainerTest.java
> +    @RepeatedTest(10)
Is this supposed to be not deterministic?

2020-07-15 15:22 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/kogito/explainability/explainability/integrationtests/dmn/LoanEligibilityDmnLimeExplainerTest.java
> +/*
Is there a specific reason why the integration tests are in separated modules? We might put them in the core and service modules and add the maven plugin to run them if they match a specific regex (like we are already doing for the trusty service and the data index) see here https://github.com/kiegroup/kogito-apps/blob/8516df2ef0e84d9a2bb55a165348f7e16cfd570c/data-index/data-index-service/pom.xml#L159

2020-07-15 15:22 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +        Collection<DataSeries> pdps = new LinkedList<>();
pdps?

2020-07-15 15:22 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +            throw new RuntimeException(e);
log?

2020-07-15 15:22 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
private static final?

2020-07-15 15:22 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/DataSeries.java
> +        assert x.length == y.length : "x and y lengths do not match";
I don't think `assert` is a good idea here :/ Throw an illegal argument exception (or my personal preference is anyway to use a factory if an exception can be raised)

2020-07-16 12:33 UTC, tteofili commented on explainability/explainability-core/pom.xml
> +</project>
I've removed all the `properties`, `dependencyManagement`, `repository` and `build` POM portions that are no longer required as inherited by kogito-apps parent.

2020-07-16 12:40 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/HttpHelper.java
> +}
I was not 100% sure about whether to bring this and `RemoteDMNModel` along in `kogito-apps` as they will most probably be replaced by a proper wiring to a `/predict` endpoint in kogito.
I realize it is actually best to have `explainability-core` to be completely model agnostic (see also other comments wrt other DMN related classes).

2020-07-16 12:40 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/RemoteDMNModel.java
> +    }
+1

2020-07-16 12:41 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/RemoteDMNModel.java
> +public class RemoteDMNModel implements BlackBoxModel {
+1

2020-07-16 12:41 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +            if (!Type.NUMBER.equals(featureTypes.get(t))) {
good point :) thanks

2020-07-16 12:42 UTC, tteofili commented on explainability/explainability-core/pom.xml
> +    </dependency>
we actually need it only in integration tests, hence moving it into `explainability-integrationtests-dmn`.

2020-07-16 12:42 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +            return "";
this is wrong, thanks for catching it :)

2020-07-16 12:43 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/DMNUtils.java
> +public class DMNUtils {
yes, this is used to convert `TypedData` into and from `PredictionInputs` and `PredictionOutputs`.
Anyway this stuff belongs to the `explanation-service` hence dropping it from the current PR.

2020-07-16 12:44 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/dmn/DecisionModelWrapper.java
> +public class DecisionModelWrapper implements BlackBoxModel {
see above, moving it to `explainability-integrationtests-dmn`.

2020-07-16 12:44 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/HttpHelper.java
> +public class HttpHelper {
+1

2020-07-16 12:47 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/kogito/explainability/explainability/integrationtests/dmn/LoanEligibilityDmnLimeExplainerTest.java
> +/*
the main reason to have them in separate modules is that dependencies needed to run `DMN` and `PMML` dependencies within the same JVM are not compatible, in the sense that they use two different and not compatible versions of drools (at least in the current state of `kie-pmml-new` vs `kogito-dmn`).

2020-07-16 12:49 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/src/test/java/org/kie/kogito/explainability/explainability/integrationtests/dmn/LoanEligibilityDmnLimeExplainerTest.java
> +    @RepeatedTest(10)
Such ITs are currently repeated as they used to be the first gate to stability of LIME explanations. 
Currently we also have other tests covering the stability parts.
However there's some non determinism in how LIME perturb features and hence the repeated test.
I am fine to move them to single execution tests.

2020-07-16 12:49 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +        Collection<DataSeries> pdps = new LinkedList<>();
**p**artial **d**ependency **p**lots.

2020-07-16 12:50 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +            throw new RuntimeException(e);
imho, as per the local case, we need to throw a `GlobalExplainabilityException`.

2020-07-16 12:50 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
+1

2020-07-16 12:50 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +        logger.info("explanation time: {}ms", (end - start));
+1

2020-07-16 12:51 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
+1

2020-07-16 12:53 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/DataSeries.java
> +        assert x.length == y.length : "x and y lengths do not match";
I do not expect this class to be instantiated by customers / external users therefore it should have a package level constructor, not `public`. The reason for using `assert` is that it's an internal check I put in place while I was developing the PDP implementation.
I'm fine to drop it anyway.

2020-07-16 13:41 UTC, tteofili commented
I think I have gone through all the comments from @danielezonca and @r00ta. 
Adding also @jiripetrlik as reviewer.

2020-07-16 15:16 UTC, r00ta reviewed
Some comments

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/pom.xml
> +      <version>3.9</version>
Move the version definition to `kogito-runtimes/bom/pom.xml`

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +     * get the input and output predictions transformed into a numerical training set
Don't shoot on me :) I'm not sure about the documentation policy of the project but I'd suggest to start always with capital letter and end the sentence with the dot (also for all the other classes). Do you have more info @jiripetrlik @danielezonca ?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/BlackBoxModel.java
> +public interface BlackBoxModel {
I wonder if `BlackBoxModel` is the most comprehensive name here, since this class is going to be extended by the consumer of the library and implement the mechanism to execute the prediction (in our case, the `BlackBoxModelImpl` would make http calls to the kogito-runtimes application so it's not just executing the model). For that reason, what about `PredictionProvider` or something like this?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +        return doubles;
Is this covering all the possible cases?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        // get the mean
I'd remove those comments since the method names are already clear. Keep only `force desired XYZ` ones

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +        return inputCognitiveChunks + outputCognitiveChunks > 0 ? 0.333 / (double) inputCognitiveChunks
Are the casts `(double)` needed?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +                    if (match) {
Check condition directly in the `if`?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            for (Output output : prediction.getOutput().getOutputs()) {
Is it possible that `pairs` or `prediction.getOutput().getOutputs()` are empty? if so, an exception is going to be raised because of `return 0/0`

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +            while (floss > 0.1 && e < 15) {
move constants to property so that it's clear what they are for?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/TestUtils.java
> +        int r = random.nextInt(12);
Even if the seed is fixed and these tests are deterministic, it is impossible to understand what are the features really tested by these tests. wdyt?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainerTest.java
> +        }
why?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DatasetEncoderTest.java
> +    private final static SecureRandom random = new SecureRandom();
Unit tests should be deterministic by definition, I would avoid using `random`

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +            features.add(TestUtils.getRandomFeature());
I would avoid using random in every tests (and all the other classes) even if the seed is set, wdyt?

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/model/FeatureFactoryTest.java
> +        assertEquals(number, feature.getValue().getUnderlyingObject());
Can you refactor the entire class so to remove duplicated code? For example moving `String name` to a property in the class and using a reusable method to do the assertions

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/DataUtilsTest.java
> +    private final static SecureRandom random = new SecureRandom();
random unit test

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +    private static final SecureRandom random = new SecureRandom();
random unit test

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +    private final static SecureRandom random = new SecureRandom();
random unit test

2020-07-16 15:16 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +      <version>1.9.2</version>
move version to `kogito-runtimes/bom`

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/LocalExplanationException.java
> +public class LocalExplanationException extends Exception {
Side note, in general it is better to use runtime exception because checked exceptions don't fit well with lambda/stream. I will let you decide what you prefer, it is just a comment :)

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +class DatasetEncoder {
Is there any reason why this class is not `public` (same question for the constructor and methods)?

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertTrue(v > 0);
Please consider to use `assertj` to replace this and other `assertTrue` based on simple expressions.
You can express condition logic directly in the assertion to obtain better error reporting
```java
assertThat(v).isPositive();
assertThat(v).isGreaterThanOrEqualTo(0);
```

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +      </exclusions>
This should not be needed any more

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +    </dependency>
Side note, this will be changed to proper `kogito-pmml` dependencies as soon as https://issues.redhat.com/browse/DROOLS-5491 will be merged. For now it is not a problem especially because they are `test` dependencies

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/GlobalExplanationException.java
> +public class GlobalExplanationException extends Exception {
Side note, in general it is better to use runtime exception because checked exceptions don't fit well with lambda/stream. I will let you decide what you prefer, it is just a comment :)

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
> +      <artifactId>kogito-scenario-simulation</artifactId>
Are you sure about this dependency? This is for `scesim` file runner so I expect you are looking for `kogito-dmn` or similar

2020-07-16 16:34 UTC, danielezonca commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +    <org.kie.version>7.40.0-SNAPSHOT</org.kie.version>
In Kogito we use `Final` external dependencies only. Btw we just updated master to `7.40.0.Final` so this property is not needed (use `version.org.kie7` https://github.com/kiegroup/kogito-runtimes/blob/master/pom.xml#L143 ).
We should only use `DependencyManagement` but PMML is not ported to Kogito yet so we have no proper dependency to use ( https://issues.redhat.com/browse/DROOLS-5491 ). I'm fine to stay with explicit dependencies in the meanwhile but please change the property as suggested

2020-07-16 16:38 UTC, danielezonca commented on explainability/explainability-core/pom.xml
> +      <version>3.9</version>
Wait: `kogito-bom` is for internal (aka `kogito-*`) dependencies while external dependencies are declared [here](https://github.com/kiegroup/kogito-runtimes/blob/master/pom.xml). Btw this dependency should be already inherited by other bom so try to remove the `version`

2020-07-16 16:40 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +     * get the input and output predictions transformed into a numerical training set
We do not have a proper policy so fine for me both upper or lower case. Usually we use upper case but no strong opinion

2020-07-16 16:42 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +        return inputCognitiveChunks + outputCognitiveChunks > 0 ? 0.333 / (double) inputCognitiveChunks
It is not needed because `0.333` is already floating point but I prefer to keep the cast to preserve floating point division even if we change `0.333` to `1` or similar

2020-07-16 16:44 UTC, danielezonca commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +      <version>1.9.2</version>
This is a really specific dependency used for test. I prefer to keep it declared here but please use a property instead of explicit version.

2020-07-16 17:48 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +     * get the input and output predictions transformed into a numerical training set
Ok, I would suggest to align all the docs so that the first letter is capital with a final dot

2020-07-17 08:23 UTC, tteofili commented on explainability/explainability-core/pom.xml
> +      <version>3.9</version>
correct, dropping the `version` just works :)

2020-07-17 09:04 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +        return doubles;
not _all_ possible cases yet.
Here're the ones I see:
- we could have a String representation of a vector, right now it is blindly converted into an arrays of 1s
- we could have a binary, a `ByteBuffer`, that could be parsed as a `double[]`
- etc.
It probably makes sense to have a `VectorValue` interface that users should leverage to define how a specific object is encoded/decoded into/from a `double[]`.

2020-07-17 09:05 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        // get the mean
ok

2020-07-17 09:18 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/model/FeatureFactoryTest.java
> +        assertEquals(number, feature.getValue().getUnderlyingObject());
sure, makes sense.

2020-07-17 09:47 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/DataUtilsTest.java
> +    private final static SecureRandom random = new SecureRandom();
good point, I'll remove the randomized parts.

2020-07-17 09:47 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +    private static final SecureRandom random = new SecureRandom();
good point, I'll remove the randomized parts.

2020-07-17 09:48 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +    private final static SecureRandom random = new SecureRandom();
randomization here is needed for a more functional test rather than unit test.
I'll move that stuff in a different (integration) test.

2020-07-17 09:48 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +      <version>1.9.2</version>
ok

2020-07-17 09:50 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +class DatasetEncoder {
it is expected to be used by `LimeExplainer` rather than users, hence the package local constructor and methods, similar to `SampleWeighter`.

2020-07-17 09:50 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertTrue(v > 0);
thanks for the suggestion, I'll do that.

2020-07-17 09:51 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +      </exclusions>
correct

2020-07-17 10:16 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/BlackBoxModel.java
> +public interface BlackBoxModel {
I had dropped the previous much overloaded `Model` in favor of `BlackBoxModel` because I wanted to highlight that the library is expected to work with any kind of model, regardless of implementation. 
`PredictionProvider` sounds good to me to highlight the fact that it is not necessarily a model instance (e.g. loaded in memory from disk), the only thing I am not sure is that, in its current state, it doesn't only provide predictions but also information about feature wise data distribution.
This leads to me to think that it might be useful to decouple the prediction API from the data distribution API, also because not all the _providers_ are also able to provide data distribution information.
So `PredictionProvider` will only have the `predict` API.

2020-07-17 11:07 UTC, jiripetrlik requested changes
Hello @tteofili, thank you for your PR.
I have some comments and suggestions in the review. Also it seems that Sonar cloud test coverage failed. It says "74.7% Coverage on New Code (is less than 80%)". As this is mostly the Java library with quite complicated logic implemented inside, I think it would be good if we reach at least requested 80% of test coverage.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/README.md
> + * Local Interpretable Model-Agnostic Explanations: a slightly modified version of the [LIME](https://arxiv.org/abs/1602.04938) algorithm (Ribeiro et al., 2016) for local explanations.
Can you please describe more what means "slightly modified"?

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/pom.xml
> +    <dependency>
Why do we need resteasy if this is a library and not app or addon?

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/GlobalExplainer.java
> + * @param <T>
Please describe T.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +    private static final int SERIES_LENGTH = 100;
Is it good to hard code series length? Is there any reason to not make this configurable?

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +    List<Pair<double[], Double>> getEncodedTrainingSet() {
Please also make methods of this class public.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                    break;
Shouldn't we throw exception or log something here?

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> + * - perturbing numerical features is done by sampling from a normal distribution centered around the value of the feature value associated with the prediction to be explained
Please split the line to make this comment more readable.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainerTest.java
> +        ;
Please remove.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DatasetEncoderTest.java
> +    void testEmptyDatasetEncoding() {
Please use public for test methods.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +
Please remove newlines.

2020-07-17 11:07 UTC, jiripetrlik commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        DataUtils.seed(4);
As many of tests in this lib are stochastic and results depend on random numbers generator I would suggest to create some logic which allows us to run these tests also with different seed. I mean to have fixed default value, but also possibility to change seed using some env. variable etc. This will allow us to test this lib more robust. I can for example do few runs with with different seed to see whether these methods are really robust or the results are within some tollerance. What do you think?

2020-07-17 11:07 UTC, jiripetrlik commented on pom.xml
> -    <module>explainability-service</module>
What is the reason to remove word "service"?

2020-07-17 11:19 UTC, danielezonca commented on pom.xml
> -    <module>explainability-service</module>
I think it is for the same reason we did it with `trusty` module: this module will contain a `core` library and a `service` module so it is probably to avoid a `explainable-service-service` module :)

2020-07-17 12:09 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/BlackBoxModel.java
> +public interface BlackBoxModel {
Makes sense to me

2020-07-17 12:11 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +        return doubles;
I'm a bit concerned about that because if the developer is using some dmn models (or whatever :) ) that we do not support, we are not catching the exception that is going to be raised here

2020-07-17 12:25 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        DataUtils.seed(4);
I have a quite strong opinion on using random in unit tests. If internally the library is using random, then I agree with @jiripetrlik that it's good to use different and fixed seeds during the initialization of the tests (and use a test factory to make it more clean from a code perspective). But I really think we should not generate random data upfront for our tests (for example in this class with `features.add(TestUtils.getRandomFeature());`), even if the seed is fixed because it's really impossible to understand what are the scenarios that are covered by the tests.

2020-07-17 14:01 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/LocalExplanationException.java
> +public class LocalExplanationException extends Exception {
ok

2020-07-17 14:02 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/GlobalExplanationException.java
> +public class GlobalExplanationException extends Exception {
ok

2020-07-17 14:03 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
> +      <artifactId>kogito-scenario-simulation</artifactId>
correct, `kogito-dmn` is the right one here.

2020-07-17 14:07 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +    <org.kie.version>7.40.0-SNAPSHOT</org.kie.version>
:+1:

2020-07-17 14:15 UTC, tteofili commented on pom.xml
> -    <module>explainability-service</module>
exactly @danielezonca

2020-07-17 14:16 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DatasetEncoderTest.java
> +    void testEmptyDatasetEncoding() {
this is no longer required since junit5 onwards.

2020-07-17 14:19 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +    private static final int SERIES_LENGTH = 100;
sure, I think it is ok to make it configurable.

2020-07-17 14:29 UTC, tteofili commented on explainability/explainability-core/pom.xml
> +    <dependency>
correct, it's not needed.

2020-07-17 14:30 UTC, tteofili commented on explainability/explainability-core/README.md
> + * Local Interpretable Model-Agnostic Explanations: a slightly modified version of the [LIME](https://arxiv.org/abs/1602.04938) algorithm (Ribeiro et al., 2016) for local explanations.
the main differences are highlighted in the javadoc of `LimeExplainer`.

2020-07-17 14:32 UTC, tteofili commented on explainability/explainability-core/README.md
> + * Local Interpretable Model-Agnostic Explanations: a slightly modified version of the [LIME](https://arxiv.org/abs/1602.04938) algorithm (Ribeiro et al., 2016) for local explanations.
> Hello @tteofili, thank you for your PR.
> I have some comments and suggestions in the review. Also it seems that Sonar cloud test coverage failed. It says "74.7% Coverage on New Code (is less than 80%)". As this is mostly the Java library with quite complicated logic implemented inside, I think it would be good if we reach at least requested 80% of test coverage.

agreed, I'll make sure the test coverage is good (and beyond 80%).

2020-07-17 14:41 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +    List<Pair<double[], Double>> getEncodedTrainingSet() {
`DatasetEncoder` is expected to be used by `LimeExplainer' only, hence the package level visibility of both class and methods.
Same as per class and constructor I think it's better not to make stuff `public` unless needed by consumers, as usually reducing the surface API is usually more expensive.

2020-07-17 15:24 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +        return doubles;
as far as I can see, the problem here is that we eventually do not correctly parse a vector feature, or skip parts of it.
The right fix here is a more thorough (and pluggable) encoding / decoding mechanism for vector values.
Note though that this is anyway an edge case where a model holds an entire vector into a single feature, whereas the good practice is to use a feature for each coordinate (value) in a vector (e.g. you have 100 numerical features for a 100-dimensional vector), which we correctly handle already.
I'll create a separate ticket for this purpose.

2020-07-20 10:24 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +        } else {
If trainingSet.isEmpty() is true this function is going to return 1. Is this the correct behaviour (even if atm the return value is never used)?

2020-07-21 08:00 UTC, r00ta commented
Hi @tteofili , there are still some open comments of the previous reviews. I still have to have a look at the implementation of LIME and the real content of the explainability, once the comments are resolved let me know and I'll have another round

2020-07-21 11:45 UTC, jiripetrlik commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        DataUtils.seed(4);
@r00ta Yes, completely agree with you. It is not good to have completely random unit tests. My suggestion was about possibility to simply change the seed for tests and try it also with different  seed if needed.

2020-07-21 14:32 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +        } else {
the initial value should be `NaN` instead of `1`, other than that the return value is used in tests to make sure it converges. 
I'll make sure to use it also inside `LimeExplainer` as a sanity check that the linear model is a good fit.

2020-07-21 15:03 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        DataUtils.seed(4);
I have dropped the randomization in all tests.
There's some randomness in the way LIME picks the feature to perturb, that has to be made fixed in tests via setting a random seed.

Also in general I agree with you, just note the randomization in tests that work on numeric and text data is sometimes useful in order to capture edge cases (btw that's what Apache Lucene does for example, see [1,2]) and strange combinations (e.g. wrt certain text encoding/locale scenarios) especially while developing a library (you have less control on what the user inputs to it).

[1] : https://labs.carrotsearch.com/randomizedtesting.html
[2] : https://www.youtube.com/watch?v=zD57QKzqdCw

2020-07-21 15:07 UTC, tteofili commented
@r00ta I think I've resolved all the comments mentioned so far, please go ahead with the rest of the review if / when you have time.

2020-07-21 18:26 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                    break;
@tteofili have a look at this please

2020-07-21 18:26 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> + * - perturbing numerical features is done by sampling from a normal distribution centered around the value of the feature value associated with the prediction to be explained
@tteofili have a look at this please

2020-07-21 18:26 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +        return inputCognitiveChunks + outputCognitiveChunks > 0 ? 0.333 / (double) inputCognitiveChunks
@tteofili have a look at this please

2020-07-21 18:27 UTC, r00ta commented on explainability/explainability-core/pom.xml
> +    <artifactId>kogito-apps</artifactId>
@tteofili have a look at this please

2020-07-21 18:29 UTC, r00ta reviewed
> @r00ta I think I've resolved all the comments mentioned so far, please go ahead with the rest of the review if / when you have time.

Some of them are still open, I've tagged you on some of them now

2020-07-21 19:25 UTC, danielezonca commented
@tteofili 
Please pay attention to hidden comments :)

2020-07-22 07:24 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            for (Output output : prediction.getOutput().getOutputs()) {
theoretically this is possible, although not really plausible in reality, but nevertheless I think it's worth guarding against possible 0 by 0 division, thanks!

2020-07-22 07:41 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                    break;
after having thought about this I think `UNDEFINED` should be handled the same way as non text, non numeric features, hence moving it so that it's handled by `encodeEquals` method.

2020-07-22 07:44 UTC, tteofili commented
thanks @r00ta  @danielezonca , also the hidden ones should be resolved by now.

2020-07-22 12:40 UTC, r00ta reviewed
Some comments in the meanwhile.. I'm at 26/74 files :) Now I need a break, I'll finish the review later hopefully

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/pom.xml
> +    </dependency>
Is this needed?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                case NUMBER:
What about a refactoring like 
```
    private List<List<Double>> getColumnData(List<PredictionInput> perturbedInputs) {
        List<List<Double>> columnData = new LinkedList<>();

        for (int t = 0; t < targetInput.getFeatures().size(); t++) {
            Feature originalFeature = targetInput.getFeatures().get(t);
            switch (originalFeature.getType()) {
```
so that we avoid to open a stream and iterate on `targetInput`

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                    featureValue = Arrays.binarySearch(perturbedWords, word) >= 0 ? 1d : 0d;
What's the gain of sorting and then using a binary search? this thing is going to be `O(nlogn)` instead of `O(n)` with a simple linear scan

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +            PredictionInput targetInput = DataUtils.linearizeInputs(List.of(originalInput)).get(0);
There might be models without inputs, `get(0)` without checks on the size is dangerous

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +    public Saliency explain(Prediction prediction, PredictionProvider model) {
This method is pretty big, would it be possible to refactor it with some private methods so that it's clear what are the steps that the algorithm is making? If this does not make sense to you, ignore it.

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                    int tries = 3;
make this configurable?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +        List<FeatureImportance> saliencies = new LinkedList<>();
Why linkedlist?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                        if (tries == 0 || separableDataset) {
why do we add the perturbed inputs/outputs if `tries == 0`? at the end if `separableDataset` is false this operation is without effects

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                    }
what about a refactoring like 
```
                    for (int tries = MAX_RETRY; tries > 0; tries--){
                        List<PredictionInput> perturbed = getPerturbedInputs(originalInput, noOfInputFeatures, noOfSamples);
                        List<PredictionOutput> perturbedOutputs = model.predict(perturbed);

                        Value<?> fv = currentOutput.getValue();

                        int finalO = o;
                        rawClassesBalance = perturbedOutputs.stream().map(p -> p.getOutputs().get(finalO)).map(output -> (Type.NUMBER
                                .equals(output.getType())) ? output.getValue().asNumber() : (((output.getValue().getUnderlyingObject() == null
                                && fv.getUnderlyingObject() == null) || (output.getValue().getUnderlyingObject() != null && output.getValue().asString().equals(fv.asString()))) ? 1d : 0d))
                                .collect(Collectors.groupingBy(Double::doubleValue, Collectors.counting()));
                        logger.debug("raw samples per class: {}", rawClassesBalance);

                        if (rawClassesBalance.size() > 1) {
                            Long max = rawClassesBalance.values().stream().max(Long::compareTo).orElse(1L);
                            if ((double) max / (double) perturbed.size() < 0.99) {
                                separableDataset = true;
                                classification = rawClassesBalance.size() == 2;
                                perturbedInputs.addAll(perturbed);
                                predictionOutputs.addAll(perturbedOutputs);
                            } 
                        } 
                    }
``` ?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                            weights[i] += linearModel.getWeights()[i] / (double) actualOutputs.size();
cast not needed

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                            weights[i] += linearModel.getWeights()[i] / (double) actualOutputs.size();
`
weights = Arrays.stream(linearModel.getWeights()).map(x -> x / actualOutputs.size()).toArray();
`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +        } catch (Exception e) {
I don't 100% like big `try/catch(Exception)` 'cause it means we don't really control what is going on there, is there a specify reason why we have to catch everything?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/SampleWeighter.java
> +                d -> DataUtils.euclideanDistance(x, d)).map(d -> DataUtils.exponentialSmoothingKernel(d, 0.75 *
Move to constant?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Feature.java
> +     * the name of the feature
Capital (and in the following methods) : )

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/FeatureDistribution.java
> +     * get minimum value for this feature
Capital

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/model/FeatureFactoryTest.java
> +class FeatureFactoryTest {
Could you add a test for complex nested (more than 1 level) structures created with `newCompositeFeature`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/PredictionProvider.java
> +     * perform a batch of predictions, given a batch of inputs.
capital

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/PredictionProviderMetadata.java
> +     * fetch the data distribution associated to this model
capital

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Type.java
> +    CURRENCY("currency");
Are these the build types we support atm right? I know the explainability applies to all the models, but we also have to consider that we have to target DMN and its types to properly perturb the inputs. 
afaik there are a couple of fancy build in types like "years and months duration" that we will have to support as well. I'm not saying we should support all of them now in this PR, but it might be good to create a ticket for that to keep track. wdyt? cc @danielezonca

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +            doubles = (double[]) underlyingObject;
why not using `underlyingObject  instanceof double[]` ?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +                }
why can it fail with an Exception?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static void seed(long seed) {
rename to `setSeed`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +            double g = 1d / (1d + random.nextInt(10));
why is it bounded to `10`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        m = m / (double) data.length;
cast not needed

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                String newStringValue;
Initialize to `""` so that you can skip the assignments at lines 186 and 189?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        }
This is going to remove **at max** 2 words, is this intended?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        }
If `stringValue` ends with " ", an exception is going to be raised by `random.nextInt(0)` at line 179. Could you fix it and add a test?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                double v = DataUtils.generateData(0, 1, noOfSamples)[pickIdx];
can you rename `v`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                double ov = feature.getValue().asNumber();
rename `ov`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                f = FeatureFactory.newCurrencyFeature(featureName, Currency.getInstance(Locale.getDefault()));
Not sure if it's the comment that is not aligned with the actual implementation, but Locale.getDefault is not going to return always EUR

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                break;
Not sure if I get it, but if the input was already MIDNIGHT this is not going to perturb the data right?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        Arrays.sort(names);
Same as in another comment: we don't need to sort, this is slower than a linear search for this particular use case

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        List<String> matchingWords = Arrays.stream(names).map(n -> n.contains(" (") ? n.substring(0, n.indexOf(" (")) : "").filter(words::contains).collect(Collectors.toList());
Why do we look for " ("?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                }
Same comments above

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        int idx = random.nextInt(values.length - 1);
with this the last value of the array is always excluded

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        int idx = random.nextInt(values.length - 1);
An exception is going to be raised if the array is composed by only one element, can you also add a test for that?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +
Is this the hamming distance? afaik if the two strings have different lenght then it is not defined

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        return Math.exp(-Math.pow(x, 2) / 2) / Math.sqrt(3.14);
`Math.PI`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +            double[] doubles = generateData(random.nextDouble(), random.nextDouble(), 1000);
why `1000`?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        List<Feature> flattenedFeatures = new LinkedList<>();
why linkedlist?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +}
What about all the other supported types? can you add a test using for example `Boolean` and other?

2020-07-22 12:40 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +     * measure the explainability of an explanation as per paper "Towards Quantification of Explainability in Explainable
capital

2020-07-22 12:49 UTC, tteofili commented on explainability/explainability-core/pom.xml
> +    </dependency>
no, correct. thanks!

2020-07-22 13:37 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                    featureValue = Arrays.binarySearch(perturbedWords, word) >= 0 ? 1d : 0d;
agreed

2020-07-22 13:51 UTC, r00ta reviewed
Here the other comments. My main concern is about type handling, because I see that in many places we have switches over the types and implement logic there. I wonder if the support for all the declared types in Types.java is really complete and tested. Once these new comments are resolved, I'll have a deeper look at this part

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +}
With the current implementation ` ExplainabilityMetrics.classificationFidelity(pairs);` always returns `0` for these inputs, if this is what it was intended to be tested, can you assert that it's equal to zero?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +}
There are no meaningful tests for this method, if this is intended to be public and exposed by the library can you add some?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            impact += DataUtils.hammingDistance(original.getValue().asString(), modified.getValue().asString());
are these comparable? any link to the paper/documentation?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +            while ((Double.isNaN(finalLoss) || finalLoss > GOOD_LOSS_THRESHOLD) && e < MAX_NO_EPOCHS) {
use a `do/while` to remove `(Double.isNaN(finalLoss)` that is used just to get in the loop for the first time?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +    private double checkFinite(double diff) {
the name of the method is a bit misleading, rename to `checkAndHandleInfinite`?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/TestUtils.java
> +    }
Why do we need a mock here? `Feature` and `Value` do not have any real dependency to be mocked

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertTrue(topFeatures.get(2).getScore() < topFeatures.get(0).getScore() * 10);
why these checks?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertThat(v).isGreaterThanOrEqualTo(0);
This is false only if an exception is raised. Is this what was intended to be checked?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertThat(v).isGreaterThanOrEqualTo(0);
same as above

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertThat(v).isGreaterThanOrEqualTo(0);
same as above

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertThat(v).isGreaterThanOrEqualTo(0);
same as above

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        PredictionInput input = mock(PredictionInput.class);
These POJOs do not have any business logic, is there a specific reason why `mock` is used?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Output.java
> +     * get the output name
capital

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/DataUtilsTest.java
> +    }
Is it possible to set the seed here so that the test is somehow deterministic? As @jiripetrlik suggested, It might be good to test with different seeds. 
The same for all the following tests

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +        assertThat(linearModel.fit(trainingSet)).isLessThan(1d);
Isnt't' always true (if there are no Exceptions)?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +        assertThat(linearModel.fit(trainingSet)).isLessThan(1d);
Isnt't' always true (if there are no Exceptions)?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
> +      <version>${project.version}</version>
Please declare the modules in the kogito-bom and remove `<version>${project.version}</version>`

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +      <version>${project.version}</version>
move to kogito bom and remove version

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +      <version>${project.version}</version>
move to kogito bom and remove version

2020-07-22 13:51 UTC, r00ta commented on pom.xml
> -    <module>explainability-service</module>
Could you update the parent of explainability/explainability-service/pom.xml with the new one?

2020-07-22 13:51 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/global/pdp/PartialDependencePlotExplainer.java
> +    public Collection<PartialDependenceGraph> explain(PredictionProvider model, PredictionProviderMetadata metadata) {
Add a link to documentation?

2020-07-22 13:55 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +            PredictionInput targetInput = DataUtils.linearizeInputs(List.of(originalInput)).get(0);
there shouldn't be predictions without inputs as well as there shouldn't be inputs without features, that wouldn't make much sense.
Anyway I'll add some checks to avoid ugly exceptions in case of malformed inputs.

2020-07-22 14:18 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                case NUMBER:
ok

2020-07-22 14:22 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                    int tries = 3;
in general, why not, my only concern is giving trying not letting users shoot in their feet by giving them too much flexibility in the configuration :) anyway I think a reasonable default would work, so yes.

2020-07-22 15:22 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                        if (tries == 0 || separableDataset) {
prior to throwing an `Exception`, when the dataset is not easily separable the impl used to try to train linear classifier anyway. I'll fix it.

2020-07-22 15:25 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +        List<FeatureImportance> saliencies = new LinkedList<>();
because prior to linearizing the inputs/features we don't know how many items the `List` will contain and hence using e.g. an `ArrayList` with a fixed size constructor is not possible.

2020-07-23 06:34 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +    public Saliency explain(Prediction prediction, PredictionProvider model) {
I have abstracted the dataset encoding and sample weighting responsibilities in different classes exactly because of that, let me see if I can refactor more portions of the method body in private methods or separate classes.

2020-07-23 06:41 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                    }
sounds good, I'd only add a `break` statement in the "succeeding" block to avoid always running the whole cycle three times.

2020-07-23 06:44 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                            weights[i] += linearModel.getWeights()[i] / (double) actualOutputs.size();
sounds good

2020-07-23 06:45 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/SampleWeighter.java
> +                d -> DataUtils.euclideanDistance(x, d)).map(d -> DataUtils.exponentialSmoothingKernel(d, 0.75 *
ok

2020-07-23 06:58 UTC, danielezonca commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Type.java
> +    CURRENCY("currency");
Here the idea is simplify the integration of an external "engine" with explainable-service: instead of just accept plain array of `double` and ask to do all the conversion on engine side we will support a richer set of data types.
I am not sure about how far we want to go with this and we need to find a tradeoff: it is always possible to add a new type or manually convert the value.
In general I agree we should try to support all builtin DMN types so feel free to create a ticket to track missing types

2020-07-23 07:28 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/model/FeatureFactoryTest.java
> +class FeatureFactoryTest {
sure :)

2020-07-23 09:34 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +        } catch (Exception e) {
apart personal taste I think it's good to carefully consider expected failures only, I'll drop the generic `try/catch(Exception)` block.

2020-07-23 09:39 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Type.java
> +    CURRENCY("currency");
when coming with this initial set of types to support I have looked at some DMN models as well as trying to think what generally makes sense or is commonly used in ML models in terms of features. Any possible enrichment to the supported data types is welcome I'd say.

2020-07-23 10:01 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/model/Value.java
> +                }
because `asNumber' throws a `NumberFormatException` if the `underlyingObject` cannot be parsed as a number. Maybe a good idea is to make `asNumber` return `NaN` in such cases and avoid throwing `NFE`.

2020-07-23 10:49 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +            double g = 1d / (1d + random.nextInt(10));
to generate data less prune to underflow, `100` or `1000` would be fine as well though.

2020-07-23 10:57 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        }
this is one of those very sensitive parameters in LIME, I think it's worth opening an investigation issue to assess a good default; this setting was the result of my experiments with our models, but it's worth investigating a bit more.

2020-07-23 11:16 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        }
I've created FAI-236 to handle this.

2020-07-23 11:34 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        }
ok

2020-07-23 11:37 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                f = FeatureFactory.newCurrencyFeature(featureName, Currency.getInstance(Locale.getDefault()));
yes, the comment is wrong, as that depends on the machine the code is running actually.

2020-07-23 11:39 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                break;
correct

2020-07-23 12:45 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +
correct, I'll fix it.

2020-07-23 12:47 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        List<Feature> flattenedFeatures = new LinkedList<>();
same as before

2020-07-23 12:51 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +            double[] doubles = generateData(random.nextDouble(), random.nextDouble(), 1000);
good point, I've made it configurable.

2020-07-23 12:52 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +}
the other supported types do not have to be _linearized_, I'll add tests.

2020-07-23 13:23 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +}
this is tested in `ExplainabilityMetricsTest`, I'll add more tests there and in ITs.

2020-07-23 13:36 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            impact += DataUtils.hammingDistance(original.getValue().asString(), modified.getValue().asString());
this is the Gower distance `d_c(x_c) + lambda*d_n(x_n)` (in which the `lambda` parameter is equals to `1`) where `x_c` are categorical / text values whereas `x_n` are numeric values in an vector `x` holding mixed types of data.
The idea is to measure how far the outputs end up when you mask the most important features, if your explanation is good, most influential features will produce very different results (with respect to the original), when masked.
I'll try to find back the link to this specific paper / literature.

2020-07-23 13:37 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/LinearModel.java
> +            while ((Double.isNaN(finalLoss) || finalLoss > GOOD_LOSS_THRESHOLD) && e < MAX_NO_EPOCHS) {
no please, `do/while` no.

2020-07-23 13:39 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/TestUtils.java
> +    }
in order to avoid depending on `FeatureFactory` which may have bugs itself.

2020-07-23 13:41 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertTrue(topFeatures.get(2).getScore() < topFeatures.get(0).getScore() * 10);
because that particular model simply lets one fixed input feature be passed as the output, all other features should have way low importance, when compared with the top one.

2020-07-23 14:50 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        PredictionInput input = mock(PredictionInput.class);
to avoid unnecessary boiler plate code as this is a test for an empty prediction.

2020-07-23 14:54 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/DataUtilsTest.java
> +    }
I've opened FAI-237 for this and other tests requiring test with multiple different seeds.

2020-07-23 14:56 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +        assertThat(linearModel.fit(trainingSet)).isLessThan(1d);
nope, this happens also with an empty dataset, and I think it is good to define the expectation here, regardless of the actual implementation internal behaviour.

2020-07-23 14:57 UTC, tteofili commented on pom.xml
> -    <module>explainability-service</module>
sure

2020-07-27 12:41 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-pmml/pom.xml
> +      <version>${project.version}</version>
https://github.com/kiegroup/kogito-runtimes/pull/653

2020-07-27 12:41 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-opennlp/pom.xml
> +      <version>${project.version}</version>
https://github.com/kiegroup/kogito-runtimes/pull/653

2020-07-27 12:41 UTC, tteofili commented on explainability/explainability-integrationtests/explainability-integrationtests-dmn/pom.xml
> +      <version>${project.version}</version>
https://github.com/kiegroup/kogito-runtimes/pull/653

2020-07-27 12:48 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        List<String> matchingWords = Arrays.stream(names).map(n -> n.contains(" (") ? n.substring(0, n.indexOf(" (")) : "").filter(words::contains).collect(Collectors.toList());
this is suboptimal, I know, but the reason why this happens is because LIME creates word level text features from a full text feature by splitting the text at whitespaces, the `name` of such features becomes `word (feature-name)`.

2020-07-27 14:38 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        List<String> matchingWords = Arrays.stream(names).map(n -> n.contains(" (") ? n.substring(0, n.indexOf(" (")) : "").filter(words::contains).collect(Collectors.toList());
as a side note, this and other feature processing functions will be better structured in a dedicated API in [FAI-238](https://issues.redhat.com/browse/FAI-238).

2020-07-28 09:03 UTC, r00ta reviewed
Hi @tteofili , thanks for the changes! A major comment about the type handling and a possible refactoring that we might do in another ticket. Some other minor comments on the classes that have been modified in the last commits

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +            }
A comment on the type handling: at the moment in some parts of the pull request there are some logics around the types. All those logics are handled with a `switch` statement: I think that it would be much much easier to read and expecially maintain if we go for a strategy pattern. If a new type comes in, we just add a class instead of adding a case in all the switches (with the risk of missing some of them).
Since this pr is big and the refactoring might not be trivial, we might do that in another ticket if you @tteofili @danielezonca @jiripetrlik think it makes sense.

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                    break;
Add default case and handle the unsupported case?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +                .map(d -> (d - threshold < 1e-3) ? 1d : 0d).collect(Collectors.toList());
move threshold to constant?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +    private static final Logger logger = LoggerFactory.getLogger(LimeExplainer.class);
minor thing: all caps letters?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                             */
which code block is this comment referring to?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                            logger.debug("raw samples per class: {}", rawClassesBalance);
can you intent/split this line? it's a bit hard to read/understand

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                                if ((double) max / (double) perturbedInputs.size() < 0.99) {
move to constant?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/SampleWeighter.java
> +    }
indent/split?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static double[] generateData(double mean, double stdDeviation, int size) {
Just for my understanding: what is the difference of sampling from a normal distribution and this procedure?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        newStringValue = String.join(" ", words);
If I'm not wrong, if `stringValue.endswith(' ') == true` this piece of code will throw an exception since `1/2 = 0` and `random.nextInt(0)` will throw an `IllegalArgumentException` or something. Can you add a test for that if this is correct?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                f = FeatureFactory.newCurrencyFeature(featureName, Currency.getInstance(Locale.getDefault()));
Just for my understanding: this line of code does not ensure that the feature is perturbed right? Should we create a ticket to investigate and improve the perturbation of such types?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    }
Check if the strings have different length?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +            for (int i = 0; i < Math.min(x.length, y.length); i++) {
`Math.min` not needed anymore

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        }
Same as above for hamming distance?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertTrue(topFeatures.get(2).getScore() < topFeatures.get(0).getScore() * 10);
Following the discussion of the previous comment ` all other features should have way low importance, when compared with the top one.`, wouldn't it be better to check the percentage here? In theory these checks might pass if `topFeatures.get(1).getScore() == topFeatures.get(0).getScore()`, which is not the expected behaviour iiuc

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertThat(v).isGreaterThan(0);
this is always `true`, isn't it? Same for all the following tests

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeExplainerTest.java
> +        }
`Assertions.assertThrows(LocalExplanationException.class, () -> limeExplainer.explain(prediction, model));` ?

2020-07-28 09:03 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeStabilityTest.java
> +    }
refactor so to remove duplicated code?

2020-07-28 10:09 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/DatasetEncoder.java
> +            }
sure, that's what I proposed as well in another comment above, I've created [FAI-238](https://issues.redhat.com/browse/FAI-238) to track that.

2020-07-28 10:11 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java
> +                             */
it refers to: https://github.com/tteofili/kogito-apps/blob/KOGITO-2750/explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/lime/LimeExplainer.java#L123-L157

I realize there's an indent issue, I'll fix it.

2020-07-28 10:26 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static double[] generateData(double mean, double stdDeviation, int size) {
there's no difference, in fact that is used exactly for sampling from a standard normal distribution in https://github.com/tteofili/kogito-apps/blob/KOGITO-2750/explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java#L216

2020-07-28 11:15 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static double[] generateData(double mean, double stdDeviation, int size) {
Ok, since there is no difference wdyt @tteofili  if we change it to something like
```
Random r = new Random();
double sample = r.nextGaussian()*targetStandardDeviation+targetMean;
```
?

2020-07-28 12:25 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +        }
sure

2020-07-28 12:38 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static double[] generateData(double mean, double stdDeviation, int size) {
the current code is slightly more accurate with respect to `r.nextGaussian()*targetStandardDeviation+targetMean`, not sure why it is the case but there's a difference in precision wrt to desired `mean` and `stdDev` of the generated data of 1e-6 (with current code) vs 1e-2 (with `r.nextGaussian()*targetStandardDeviation+targetMean`).
So if it is not a problem, I'd prefer to keep the current code (slightly slower but more precise).

2020-07-28 12:49 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                f = FeatureFactory.newCurrencyFeature(featureName, Currency.getInstance(Locale.getDefault()));
yes, agreed.

2020-07-28 13:19 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertTrue(topFeatures.get(2).getScore() < topFeatures.get(0).getScore() * 10);
hmm, now I realize the check is wrong, thanks for pointing it out, I'll fix it.

2020-07-28 13:23 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/DummyModelsLimeExplainerTest.java
> +        assertThat(v).isGreaterThan(0);
no, it can be `0 when dropping features has no effect in the model prediction output. 
If the impact it's greater than `0` it means that the drop of the top `k` features caused some change in the output.

2020-07-28 13:57 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +                        newStringValue = String.join(" ", words);
I think this is guarded by `!words.isEmpty()`, anyway there're tests for such text features at https://github.com/tteofili/kogito-apps/blob/KOGITO-2750/explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/DataUtilsTest.java#L155-L197

2020-07-28 16:17 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static double[] generateData(double mean, double stdDeviation, int size) {
Hi @tteofili , I've called `generateData(0, 10, 500)` and I've plotted the data, but it does not look a gaussian: it's not symmetric at all. 
![Screenshot from 2020-07-28 18-12-43](https://user-images.githubusercontent.com/18282531/88692146-086f3d80-d0fe-11ea-8c06-fac9db2d635d.png)

If it's important that we sample from a normal distribution maybe it's better to go for ` r.nextGaussian()*targetStandardDeviation+targetMean` even if the noise is bigger than the other method, because at least we sample from a normal distribution. If the distribution is not that important as the mean and the std deviation, forget my comments. 
btw, what is the size of the sample you are generating for your comparison?

2020-07-28 16:18 UTC, r00ta commented
Hi @tteofili , I left another comment in https://github.com/kiegroup/kogito-apps/pull/324#discussion_r461706452 even if it's closed

2020-07-29 12:22 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/DataUtils.java
> +    public static double[] generateData(double mean, double stdDeviation, int size) {
both are important for the numerical data perturbation procedure, hence I would mix them together, by generating the initial values of`double[]` with `r.nextGaussian()*targetStandardDeviation+targetMean` and then adjusting `mean` and `stdDeviation` with the current procedure.

2020-07-29 15:50 UTC, danielezonca approved these changes
Thanks for you PR, approving :+1:

2020-07-29 18:29 UTC, r00ta reviewed
Hi @tteofili , just few minor comments on the new code

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            }
If the two strings have different length then the impact is just `1`? Is this correct?

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            impact += 0.5 * DataUtils.euclideanDistance(new double[]{original.getScore()}, new double[]{modified.getScore()});
Why 0.5?

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/TestUtils.java
> +        return f;
Isnt't better to directly instantiate a `Feature` object without a mock?

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeStabilityTest.java
> +        assertTrue(topFeature);
This is checking that the last `entry.getValue()` is `>= 0.9` right? Isnt't better to rewrite it?

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +        assertThat(v).isBetween(0d, 1d);
This is always true unless `ExplainabilityMetrics.classificationFidelity` throws an exception. If this is the intended check, could you use `assertDoesNotThrow`?

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +        assertThat(v).isBetween(0d, 1d);
This is always true unless `ExplainabilityMetrics.classificationFidelity` throws an exception. If this is the intended check, could you use `assertDoesNotThrow`?

2020-07-29 18:29 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +        assertEquals(Arrays.toString(new double[size]), Arrays.toString(linearModel.getWeights()));
`assertArrayEquals(new double[size], linearModel.getWeights());` or check that all the elements are zero?

2020-07-30 07:38 UTC, jiripetrlik approved these changes

2020-07-30 09:28 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/TestUtils.java
> +        return f;
`Feature` constructor is package local to prevent users to instantiate them themselves while possibly messing up `Types ` and `Values` (e.g. `Type.BOOLEAN` and `new Value<Double>(1d)`).
`Feature` creation is exposed via `FeatureFactory` however I prefer to not depend on the `FeatureFactory` impl in the tests, as that might hide some bugs iteself.

2020-07-30 09:32 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/lime/LimeStabilityTest.java
> +        assertTrue(topFeature);
the proper check is that at least one entry matches the condition, hence yes, I'll fix it.

2020-07-30 09:35 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +        assertThat(v).isBetween(0d, 1d);
the above assertion is meant to check that the value returned by `ExplainabilityMetrics.classificationFidelity` is in the expected range of values, which I think is correct. If it throws an `Exception` that would be an unexpected behaviour and the test should go in error instead of failing.

2020-07-30 09:35 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +        assertThat(v).isBetween(0d, 1d);
same as above.

2020-07-30 09:37 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/LinearModelTest.java
> +        assertEquals(Arrays.toString(new double[size]), Arrays.toString(linearModel.getWeights()));
the former, correct, thanks.

2020-07-30 10:00 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            }
I am struggling at finding the original paper where I had found this `impact` definition, I'll keep digging...
Anyway the idea is similar to the one described in [this paper](https://arxiv.org/pdf/1910.07387.pdf) where the impact is `1` when either the output without the important features is different from the original one or when its score has changed by at least `0.5` (in a `0..1` range), except that instead of having a discrete impact we to calculate the distance between the changed/original output values and between changed/original scores, giving more weight to a changed output than to a changed score (hence the 0.5 on score).
In case the (`hamming`) distance cannot be computed (e.g. when their lengths differ) it's just set to `1` if the output value changed.

2020-07-30 10:01 UTC, tteofili commented on explainability/explainability-core/src/main/java/org/kie/kogito/explainability/utils/ExplainabilityMetrics.java
> +            impact += 0.5 * DataUtils.euclideanDistance(new double[]{original.getScore()}, new double[]{modified.getScore()});
see above comment

2020-07-30 11:17 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +        assertThat(v).isBetween(0d, 1d);
Hi @tteofili , I'm more referring to the fact that `ExplainabilityMetrics.classificationFidelity` returns *always* a number between 0 and 1 by contract, regardless the inputs (could you double check?). Meaning that we can change the implementation of `ExplainabilityMetrics.classificationFidelity` and this test completely and this test would anyway pass. That's why I was wondering if the real check is `assertDoesNotThrow`, since this is the only way for this test to fail.

2020-07-30 11:48 UTC, r00ta approved these changes
Hi @tteofili , thanks for the changes! 
Once the comments are resolved it looks good to me. 
I don't remember what we have discussed about the integration tests, but isnt't better to include them in the explainability-service or somewhere else in the future? If it makes sense to you, feel free to create a ticket for that so that we keep track

2020-07-30 12:39 UTC, tteofili commented
> Hi @tteofili , thanks for the changes!
> Once the comments are resolved it looks good to me.
> I don't remember what we have discussed about the integration tests, but isnt't better to include them in the explainability-service or somewhere else in the future? If it makes sense to you, feel free to create a ticket for that so that we keep track

as of today they have their own submodule `explainability-integrationtests` that only depend on `explainability-core`; the idea there is to have them act as quality gates for the core library, then most probably we must have integration tests for `explainability-service` that check explaining a kogito app running DMN / PMML models work properly.
So at the moment I'd keep them as they are and then create a ticket for creating ITs (or adapting the current ones) that cover generating explanations at a service level.

2020-07-30 13:09 UTC, tteofili commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/utils/ExplainabilityMetricsTest.java
> +        assertThat(v).isBetween(0d, 1d);
ok, done ;)

2020-07-30 16:18 UTC, merged