Kogito 2828 - catch exceptions in event processing to avoid global stop
apache/incubator-kie-kogito-apps pull request #342
Opened 2020-07-23 16:50 UTC by r00ta

While I was working on other messaging stuff I had the chance to experiment this ticket herehttps://issues.redhat.com/browse/KOGITO-2828 . 

If there is an exception during the processing of the event the entire even loop is stopped, and no events are consumed anymore. It's good to surround the processing catching all the exceptions to avoid the global stop of the messaging system in case something bad happens. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2020-07-23 16:51 UTC, r00ta commented on trusty/trusty-service/src/test/java/org/kie/kogito/trusty/service/messaging/TraceEventConsumerIT.java
> +public class TraceEventConsumerIT {
I've moved the old content of this class to `TraceEventConsumerInfinispanIT` since it's an integration test that uses also infinispan.

2020-07-23 16:52 UTC, r00ta commented on trusty/trusty-service/src/test/java/org/kie/kogito/trusty/service/messaging/TraceEventConsumerIT.java
> +        verify(trustyService, times(2)).storeDecision(any(String.class), any(Decision.class));
This is the new test that checks that both events are processed. With the old implementation only the first one was processed

2020-07-24 14:03 UTC, jiripetrlik requested changes
Please improve test coverage. It seems that we have only  about 33 % code coverage of a new code.

2020-07-27 09:51 UTC, r00ta commented
> Please improve test coverage. It seems that we have only about 33 % code coverage of a new code.

Hi @jiripetrlik , should be ok now

2020-07-28 12:42 UTC, jiripetrlik approved these changes
@r00ta 
Thank you for adding missing tests! Looks good to me.

2020-07-29 12:38 UTC, danielezonca approved these changes

2020-07-29 12:40 UTC, merged