WIP: KOGITO-2721: Update to latest Patternfly version
apache/incubator-kie-kogito-apps pull request #361
Opened 2020-08-03 13:37 UTC by nmirasch

Jira related : https://issues.redhat.com/browse/KOGITO-2721

2020-08-04 16:16 UTC, jstastny-cz requested changes
Generally looks good, majority of ouia-related changes in snapshots is inflicted by the change in PF4 handling of ouia attributes (rendered by default).

I have a few reservations though, especially in terms of using patternfly's OUIAProps and related functions. They're PF4 specific as can be seen in resulting snapshots, I'd keep usage of our OUIAUtils instead where we have more room to tweak those.

2020-08-04 16:16 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Atoms/EndpointLink/EndpointLink.tsx
> +import {Button, getOUIAProps, OUIAProps} from '@patternfly/react-core';
I would keep our OUIAUtils implementation - the patternfly one adds a `PF4-` selector to the component type and it's not necessary, plus will limit the places that need to be changed.

2020-08-04 16:16 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Atoms/KogitoEmptyState/tests/__snapshots__/KogitoEmptyState.test.tsx.snap
> +                data-ouia-component-id={0}
those additions are expected - PF4 turned OUIA on by default, so the components that support it will have similar snapshots.

2020-08-04 16:16 UTC, jstastny-cz commented on ui-packages/packages/common/src/components/Molecules/ServerUnavailable/ServerUnavailable.tsx
> +        <Avatar src={userImage} alt="Kogito Logo" />
indent right?

2020-08-04 16:16 UTC, jstastny-cz commented on ui-packages/packages/common/src/utils/OuiaUtils.ts
> +  return ouiaAttribute( 'data-ouia-component-id', ouiaId);
for all the removed function arguments also please remove the lines in documentation for the function.

2020-08-07 12:46 UTC, AjayJagan approved these changes
+1

2020-08-07 15:43 UTC, Sara4994 approved these changes

2020-08-10 04:42 UTC, cristianonicolai commented
@jstastny-cz good to merge?

2020-08-10 06:25 UTC, jstastny-cz approved these changes
LGTM

2020-08-10 09:05 UTC, merged