[KOGITO-3297] Bump CloudEvents api to 2.x
apache/incubator-kie-kogito-apps pull request #450
Opened 2020-09-08 20:24 UTC by ruromero

Related to https://github.com/kiegroup/kogito-runtimes/pull/750
Fix https://issues.redhat.com/browse/KOGITO-3297

Signed-off-by: ruromero <rromerom@redhat.com>

2020-09-08 20:54 UTC, ricardozanini approved these changes

2020-09-09 08:48 UTC, evacchi approved these changes

2020-09-14 09:49 UTC, ruromero commented
jenkins retest this

2020-09-14 11:03 UTC, danielezonca commented on trusty/trusty-service/src/main/java/org/kie/kogito/trusty/service/messaging/BaseEventConsumer.java
> +    protected abstract void handleCloudEvent(final CloudEvent cloudEvent);
What about refactor `getCloudEventType()` to return `TypeReference<E>`?
`ObjectMapper` can be specified as constructor parameter and then you can move deserialization logic here and isolate business logic for subclasses like:
```java
    protected abstract void internalHandleCloudEvent(final CloudEvent cloudEvent, final E payload);

    protected abstract void handleCloudEvent(final CloudEvent cloudEvent) {
        final E payload;
        try {
            payload = mapper.readValue(cloudEvent.getData(), getCloudEventType());
        } catch (IOException e) {
            LOG.error("Unable to deserialize CloudEvent data as " + getCloudEventType().getName(), e);
            return;
        }
        if (event == null) {
            LOG.error("Received CloudEvent with id {} from {} with empty data", cloudEvent.getId(), cloudEvent.getSource());
            return;
        }

        LOG.debug("Received CloudEvent with id {} from {}", cloudEvent.getId(), cloudEvent.getSource());

        internalHandleCloudEvent(cloudEvent, payload);
    }
```

2020-09-14 11:03 UTC, danielezonca commented on trusty/trusty-service/src/main/java/org/kie/kogito/trusty/service/messaging/incoming/ExplainabilityResultConsumer.java
>      public ExplainabilityResultConsumer(TrustyService service) {
Please do not mix injection on field and on constructor: move all the injection to constructor

2020-09-14 11:03 UTC, danielezonca commented on trusty/trusty-service/src/main/java/org/kie/kogito/trusty/service/messaging/incoming/ModelEventConsumer.java
>      @Inject
Please do not mix injection on field and on constructor: move all the injection to constructor

2020-09-14 11:03 UTC, danielezonca commented on trusty/trusty-service/src/main/java/org/kie/kogito/trusty/service/messaging/incoming/TraceEventConsumer.java
>      @Inject
Please do not mix injection on field and on constructor: move all the injection to constructor

2020-09-14 20:01 UTC, ruromero commented on trusty/trusty-service/src/main/java/org/kie/kogito/trusty/service/messaging/BaseEventConsumer.java
> +    protected abstract void handleCloudEvent(final CloudEvent cloudEvent);
Done, thanks for the suggestion

2020-09-14 20:07 UTC, danielezonca approved these changes
Thanks for your PR, approving 👍

2020-09-14 22:17 UTC, ricardozanini commented
@danielezonca I also need this PR merged, but it looks like it's failing in the CI. I was incapable to see why, tough day. Can you take a look tomorrow? After a good night of sleep I'll look also.

2020-09-14 22:18 UTC, ricardozanini commented
/jenkins test

2020-09-16 07:15 UTC, danielezonca commented
jenkins retest this please

2020-09-16 09:23 UTC, danielezonca commented
@ruromero 
Can you please have a look to failed tests?
`testEvaluateTrafficViolation – org.kie.dmn.kogito.quarkus.tracing.LoanEligibilityTest` fails with 
```bash
2020-09-16 04:12:54,840 INFO [io.sma.rea.mes.provider] (main) SRMSG00209: Initializing mediators
2020-09-16 04:12:54,918 ERROR [io.sma.rea.mes.provider] (main) SRMSG00212: Unable to initialize mediator: org.kie.kogito.tracing.decision.QuarkusModelEventEmitter#getEventPublisher: java.lang.NoClassDefFoundError: io/cloudevents/rw/CloudEventAttributesWriter
at io.cloudevents.jackson.JsonFormat.getCloudEventJacksonModule(JsonFormat.java:102)
```

`org.acme.travel.CloudEventListenerTest – org.acme.travel.CloudEventListenerTest` fails with
```bash
[error]: Build step org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.IllegalStateException: src/main/java/org/kie/kogito/app/CloudEventListenerResource.java (7:40) : cannot find symbol
symbol: class CloudEventConverter
location: package org.kie.kogito.events.knative.ce
src/main/java/org/kie/kogito/app/CloudEventListenerResource.java (27:13) : cannot find symbol
symbol: class RestEasyHttpRequestConverter
location: class org.kie.kogito.app.CloudEventListenerResource
src/main/java/org/kie/kogito/app/CloudEventListenerResource.java (27:69) : cannot find symbol
symbol: class RestEasyHttpRequestConverter
```
```

2020-09-16 09:35 UTC, ruromero commented
@danielezonca yes I'm still working on it. I'm having trouble with the objectMapper.

2020-09-21 19:41 UTC, ruromero commented
jenkins retest this

2020-09-21 20:57 UTC, ricardozanini requested changes
LGTM @kostola @manstis do you mind taking a look? I should merge it tomorrow if nothing goes wrong.

2020-09-21 20:57 UTC, ricardozanini approved these changes

2020-09-21 20:59 UTC, ricardozanini approved these changes

2020-09-23 14:27 UTC, merged