KOGITO-3557 - Enable keycloak on trusty-ui
apache/incubator-kie-kogito-apps pull request #477
Opened 2020-10-06 14:38 UTC by r00ta

JIRA: https://issues.redhat.com/browse/KOGITO-3557

This PR aims to enable keycloak on trusty-ui service. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2020-10-07 08:55 UTC, Sgitario requested changes
I made some comments about the usage of the @TestProfile annotation (I didn't request any changes about it, just raise some questions).
However, the native compilation is failing and that's why I requested changes.
Also, I've added @nmirasch as reviewer as she has lot of knowledge about this.
Thanks!

2020-10-07 08:55 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/KeycloakTrustyUIServiceIT.java
> +@TestProfile(KeycloakTrustyUIServiceIT.ITKeycloakProfile.class)
In the rest of the tests, we use the @QuarkusTestResource annotation like this:

```java
@QuarkusTestResource(KeycloakQuarkusTestResource.class)
```

As far I could see, the main difference between @TestProfile and @QuarkusTestResource is that @TestProfile is isolated to the running test suite where @QuarkusTestResource is per package (having this annotation affects all the tests). For me, I would prefer to having it per test suite using @TestProfile, but there are two problems:
- It does not allow having multiple test profiles (to specify what resources the test needs individually). Therefore, to use it, we would need to create a profile class in every single test (or module)
- This annotation is not supported by native tests

Did you use this annotation for some other reason? I would prefer all the tests use the same things to have expected behaviour. What do you think about this?

2020-10-07 08:55 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/KeycloakTrustyUIServiceIT.java
> +        public Map<String, String> getConfigOverrides() {
We don't need to implement this method.

2020-10-07 08:55 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/KeycloakTrustyUIServiceIT.java
> +        public Set<Class<?>> getEnabledAlternatives() {
We don't need to implement this method.

2020-10-07 08:55 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/NativeStaticContentTestIT.java
> +public class NativeStaticContentTestIT extends StaticContentTest {
The native profile is failing. If I run this:

```
mvn clean install -Pnative
```

It fails because the uberJar is not true. I need to add this plugin in the native maven profile:

```xml
<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-maven-plugin</artifactId>
  <configuration>
    <uberJar>true</uberJar>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>native-image</goal>
      </goals>
      <configuration>
        <additionalBuildArgs>--allow-incomplete-classpath</additionalBuildArgs>
      </configuration>
    </execution>
  </executions>
</plugin>
```

And also remove the "quarkus.package.type":

```xml
<properties>
   <quarkus.package.type>native</quarkus.package.type>
</properties>
```

2020-10-07 08:55 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/NativeStaticContentTestIT.java
>  @NativeImageTest
The native maven profile is not running this test. For enabling it, I followed the same conventions as in Kogito Examples and then the test failed:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.kie.kogito.NativeStaticContentTestIT
Executing [/home/jcarvaja/sources/kogito/kogito-apps/trusty-ui/target/trusty-ui-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8080, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8080, -Dquarkus.log.file.path=target/target/quarkus.log]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-07 10:47:27,852 ERROR [io.qua.application] (main) Failed to start application (with profile prod): io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: META-INF/resources/index.html
	at io.vertx.core.file.impl.FileSystemImpl$16.perform(FileSystemImpl.java:865)
```

Also, the Keycloak resource is not starting because of native test is not compatible with @TestProfile (see [here](https://github.com/quarkusio/quarkus/pull/11150)). Therefore, we would need to annotate this class using:

```
@QuarkusTestResource(KeycloakQuarkusTestResource.class)
```

2020-10-07 09:09 UTC, r00ta commented on trusty-ui/src/test/java/org/kie/kogito/KeycloakTrustyUIServiceIT.java
> +@TestProfile(KeycloakTrustyUIServiceIT.ITKeycloakProfile.class)
Hi @Sgitario , I used `TestProfile` because of this issue https://github.com/quarkusio/quarkus/issues/9854 . 
Basically when using `@QuarkusTestResource`, it's used for all Quarkus tests that don't specify a `@TestProfile` -> since we have another `QuarkusTest`, the keycloak container is started but it fails because it is not configured.

2020-10-07 09:11 UTC, r00ta commented on trusty-ui/src/test/java/org/kie/kogito/NativeStaticContentTestIT.java
>  @NativeImageTest
Same as above, if we use `QuarkusTestResource` we have to choose betwen testing keycloak and the other Quarkus Tests

2020-10-07 09:12 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/KeycloakTrustyUIServiceIT.java
> +@TestProfile(KeycloakTrustyUIServiceIT.ITKeycloakProfile.class)
This bit is resolved if we use the annotation this way:

```
@QuarkusTestResource(KeycloakQuarkusTestResource.Conditional.class)
```

This way the test resource will only be executed if there are some properties. See more here: https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-test-utils

2020-10-08 10:04 UTC, nmirasch commented on trusty-ui/src/main/resources/application.properties
> +%keycloak.quarkus.oidc.credentials.secret=secret
@r00ta There is something I miss here  in the oidc configuration to let keycloak manage the login page 
%keycloak.quarkus.oidc.application-type=web-app

2020-10-20 12:30 UTC, r00ta commented on trusty-ui/src/main/resources/application.properties
> +%keycloak.quarkus.oidc.credentials.secret=secret
Hi @nmirasch , thanks for the tip! I've updated the file, could you please double check if everything is ok for you?

2020-10-20 12:31 UTC, r00ta commented on trusty-ui/src/test/java/org/kie/kogito/KeycloakTrustyUIServiceIT.java
> +@TestProfile(KeycloakTrustyUIServiceIT.ITKeycloakProfile.class)
Hi @Sgitario , thank you very much for the tip! I've updated the tests, could you please double check if everything looks good to you?

2020-10-21 12:40 UTC, Sgitario requested changes

2020-10-21 12:40 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/NativeStaticContentTestIT.java
> +public class NativeStaticContentTestIT extends StaticContentTest {
This test is still not being executed when using the native maven profile.

2020-10-23 16:03 UTC, nmirasch commented on trusty-ui/src/main/resources/application.properties
> +%keycloak.quarkus.oidc.credentials.secret=secret
@r00ta this configuration looks good now and work fine.
Just one more thing from my side, if you have any plan to add some instructions at README.md file about create the keycloak docker container, maybe would be a good idea to reuse other predefined client like 'kogito-console-quarkus' that is ready to work at 8380 and comes with the predefined kogito-realm.json  or just add this new id to https://github.com/kiegroup/kogito-apps/blob/47d51dcb1dfe684e01efb950b5df9c1d83e05ac5/config/kogito-realm.json

2020-10-27 10:53 UTC, r00ta commented on trusty-ui/src/test/java/org/kie/kogito/NativeStaticContentTestIT.java
> +public class NativeStaticContentTestIT extends StaticContentTest {
Hi @Sgitario , sorry for the late reply. I think the native tests are failing also on master for the management console and the trusty-ui projects, I'm wondering if we can tackle the fix in another pull request. wdyt? With the current pom the  `NativeStaticContentTestIT` is excluded, otherwise it would fail

2020-10-27 11:30 UTC, Sgitario commented on trusty-ui/src/test/java/org/kie/kogito/NativeStaticContentTestIT.java
> +public class NativeStaticContentTestIT extends StaticContentTest {
Fine with me.

2020-10-27 11:30 UTC, Sgitario approved these changes

2020-11-10 13:51 UTC, r00ta commented on trusty-ui/src/main/resources/application.properties
> +%keycloak.quarkus.oidc.credentials.secret=secret
Hi @nmirasch , I apologize for the very late reply. This PR went out of my radar :/ I've updated the trusty-ui readme with the same instructions that we suggest in the task-console and the management console. Let me know if this is ok for you

2020-11-12 14:16 UTC, nmirasch commented on trusty-ui/src/main/resources/application.properties
> +%keycloak.quarkus.oidc.credentials.secret=secret
@r00ta all fine

2020-11-12 14:16 UTC, nmirasch approved these changes

2020-11-16 13:42 UTC, danielezonca approved these changes

2020-11-16 13:43 UTC, r00ta commented
Jenkins retest this please

2020-11-16 17:45 UTC, danielezonca commented
Jenkins retest this please

2020-11-16 20:47 UTC, danielezonca commented
jenkins retest this please

2020-11-23 07:58 UTC, r00ta commented
jenkins retest this please

2020-11-23 11:04 UTC, merged