KOGITO-3118 Infinispan 11 upgrade
apache/incubator-kie-kogito-apps pull request #495
Opened 2020-10-21 07:13 UTC by cristianonicolai

2020-10-22 02:58 UTC, cristianonicolai commented
jenkins please retest this

2020-10-27 03:13 UTC, cristianonicolai commented
jenkins please retest this

2020-10-27 09:58 UTC, radtriste approved these changes

2020-10-27 11:06 UTC, ricardozanini approved these changes

2020-10-27 11:34 UTC, tiagodolphine approved these changes

2020-10-27 13:59 UTC, MarianMacik approved these changes

2020-10-27 13:59 UTC, MarianMacik commented on data-index/data-index-service/data-index-service-infinispan/src/main/resources/META-INF/kogito-cache-default.xml
>    <cache-container statistics="true" shutdown-hook="DEFAULT">
Just an idea, shouldn't we upgrade also schema version in the xml? Currently it is 10.0.

Side question - this XML is used as a basic configuration for Infinispan instance that Data Index uses? I wonder why we don't have something similar for kogito runtime service by default, probably because we need more flexibility from the user in Kogito Runtime??

2020-10-27 15:37 UTC, cristianonicolai commented on data-index/data-index-service/data-index-service-infinispan/src/main/resources/META-INF/kogito-cache-default.xml
>    <cache-container statistics="true" shutdown-hook="DEFAULT">
@MarianMacik just updated the schema version. As for the configuration XML, correct that is used for these different services, including data index. The reason is there is because indexing must be enabled, otherwise it restricts some of our searching capabilities. As opposed to runtimes, where we use it as a simple key-value store, so default config from Infinispan is fine. We can look into doing something like this for runtimes if there is some specific need.

2020-10-27 15:38 UTC, cristianonicolai commented
@danielezonca any impact of this in the trusty service?

2020-10-27 19:22 UTC, danielezonca approved these changes

2020-10-27 19:26 UTC, danielezonca requested changes
Sorry I forgot this file
https://github.com/kiegroup/kogito-apps/blob/master/trusty/trusty-storage/trusty-storage-infinispan/src/main/resources/META-INF/decision.proto
I think it should be updated too @kostola can you please double check?

2020-10-28 08:58 UTC, kostola commented
The [Upgrading Infinispan 11.0 document](https://infinispan.org/docs/stable/titles/upgrading/upgrading.html) says:

> It is now required to annotate a field that requires sorting with @SortableField, both for embedded and remote queries.

In the Trusty storage protobuf definition, the only field we're currently sorting by (`Decision.executionTimestamp`) is already annotated with `@SortableField` ([link](https://github.com/kiegroup/kogito-apps/blob/0f49bdabc5a1b10fd91e8342f0e9f6c06e6032d0/trusty/trusty-storage/trusty-storage-infinispan/src/main/resources/META-INF/decision.proto#L18)).

Imho that file is ok at the moment. We may add the annotation to other fields in the future in case we need to sort by them.

@cristianonicolai and @MarianMacik what do you think?

2020-10-28 09:09 UTC, danielezonca approved these changes
@kostola 
Ok thanks for the verification, I think we are fine to proceed :+1:

2020-10-28 09:10 UTC, r00ta approved these changes

2020-10-28 11:58 UTC, kostola approved these changes

2020-10-28 12:34 UTC, merged