KOGITO-441
apache/incubator-kie-kogito-apps pull request #5
Opened 2019-10-24 06:37 UTC by AjayJagan

connected with data-index-service
changed the route paths
resolved bugs in ListDetails and ProcessDetails

2019-10-24 07:59 UTC, Sara4994 submitted a review, later dismissed

2019-10-24 08:04 UTC, cristianonicolai requested changes

2019-10-24 08:04 UTC, cristianonicolai commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +  //   const GET_CHILD_INSTANCES = gql`
this could be removed

2019-10-24 08:04 UTC, cristianonicolai commented on packages/management-console/src/index.tsx
> +  uri: "http://localhost:8180/graphql"
perhaps use some sort of configuration instead.

2019-10-24 15:26 UTC, cristianonicolai reviewed
overall looks good just a comment regarding the json data file for the mock server.

2019-10-24 15:26 UTC, cristianonicolai commented on packages/management-console/server/server.js
> +    id: 'a1e139d5-4e77-48c9-84ae-34578e904e5a',
@AjayJagan can we skip the replacement of double quotes on this file? Otherwise, we will have to reformat it every time we copy data from index service.

2019-10-25 03:07 UTC, AjayJagan commented on packages/management-console/server/server.js
> +    id: 'a1e139d5-4e77-48c9-84ae-34578e904e5a',
@cristianonicolai  sure. Will make the changes and push it

2019-10-25 05:47 UTC, cristianonicolai approved these changes

2019-10-25 05:47 UTC, merged