KOGITO-3616: Job management section
apache/incubator-kie-kogito-apps pull request #503
Opened 2020-10-26 09:34 UTC by Sara4994

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-10-27 05:14 UTC, AjayJagan approved these changes
LGTM

2020-10-27 09:01 UTC, nmirasch commented
@Sara4994 Looks good to me (even it seems there is some missing snapshot update), maybe we can put this pr as Draft and include the commit on the next list of jobs PR that have to come. Regarding doesn't make sense merge this independently. Maybe @jstastny-cz could take a look here to see how the things are moving on, even this is the first step throw that new section. Wdyt?

2020-10-29 15:45 UTC, nmirasch reviewed
I

2020-10-29 15:45 UTC, nmirasch commented on ui-packages/packages/common/src/graphql/queries.tsx
>        lastUpdate
@Sara4994 Here I miss expirationTime

2020-10-29 15:45 UTC, nmirasch commented on ui-packages/packages/common/src/graphql/types.tsx
> -        expirationTime
@Sara4994 I guess this is related with the previous comment

2020-10-29 15:45 UTC, nmirasch commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +  const handleCancelAction = (id): void => {
@Sara4994 we are repeating code here that we already have in JobActionsKebab. We need to reuse as much as possible in order to unify and maintain consistency.

2020-10-30 06:19 UTC, Sara4994 commented on ui-packages/packages/common/src/graphql/queries.tsx
>        lastUpdate
expirationTime was added twice on that query so removed one, here is the query
  Jobs(where: { processInstanceId: { equal: $processInstanceId } }) {
      id
      processId
      processInstanceId
      rootProcessId
      status
      expirationTime
      priority
      callbackEndpoint
      repeatInterval
      repeatLimit
      scheduledId
      retries
      lastUpdate
      endpoint
    }
  }

2020-10-30 06:19 UTC, Sara4994 commented on ui-packages/packages/common/src/graphql/types.tsx
> -        expirationTime
@nmirasch same... expirationTime was added twice on that query

2020-10-30 07:46 UTC, nmirasch commented on ui-packages/packages/common/src/graphql/queries.tsx
>        lastUpdate
@Sara4994 true, well done then! Sorry, I miss that too

2020-10-30 12:12 UTC, jstastny-cz requested changes

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/server/server.js
> +      if(Object.keys(args).length> 0) {
whitespace formatting.

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +interface actionsMeta {
I would suggest capital initial letter in interface names.

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +        setModalContent(`The job: ${job.id} is cancelled successfully`);
cancelled -> canceled to be in sync

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Atoms/JobActionsKebab/JobActionsKebab.tsx
>    const handleCancelAction = (): void => {
cancelled -> canceled

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +  const handleCancelAction = (id): void => {
+1 to that

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +          jobType = 'editable';
Maybe initial capital letter to be in sync with `Non-editable` below?

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +      {rows.length > 0 && (
filtering is not planned / implemented right now, correct? Meaning - rows are all data there's here, it's not dependent on some sort of filtering?

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/tests/JobsManagementTable.test.tsx
> +jest.mock('axios');
mock also Date.now, I've seen some time sensitive items in the component definition.

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/JobsManagementPage/JobsManagementPage.tsx
> +              description: `There are no jobs associated with any process instance`,
maybe add a period in the end of sentences started with capital letters?

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/JobsManagementPage/JobsManagementPage.tsx
> +    <div {...componentOuiaProps(ouiaId, 'JobsManagementPage', ouiaSafe)}>
```suggestion
    <div {...componentOuiaProps(ouiaId, 'JobsManagementPage', ouiaSafe?ouiaSafe:!isLoading())}>
```

2020-10-30 12:12 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/JobsManagementPage/tests/JobsManagementPage.test.tsx
> +    window.location = location;
Is it certain that this will happen on test failure? I think some sort of before/after method hooks would be better place for this.

2020-10-30 12:35 UTC, Sara4994 commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +      {rows.length > 0 && (
@jstastny-cz  Filtering will be the next PR

2020-10-30 13:11 UTC, Sara4994 commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/JobsManagementTable.tsx
> +  const handleCancelAction = (id): void => {
after 1.0 release we will remove JobActionsKebab component and will use patternfly approach to display kebab on table.

2020-10-30 13:17 UTC, jstastny-cz requested changes

2020-10-30 13:17 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Templates/JobsManagementPage/JobsManagementPage.tsx
> +        ouiaSafe ? ouiaSafe : loading
```suggestion
        ouiaSafe ? ouiaSafe : !loading
```

2020-10-30 13:17 UTC, jstastny-cz commented on ui-packages/packages/management-console/src/components/Organisms/JobsManagementTable/tests/JobsManagementTable.test.tsx
> +jest.mock('axios');
I think you've added it in the test for page.

2020-10-30 15:01 UTC, jstastny-cz approved these changes

2020-10-30 15:36 UTC, nmirasch approved these changes

2020-10-30 16:36 UTC, merged