Jobs management pagination
apache/incubator-kie-kogito-apps pull request #565
Opened 2020-12-09 13:28 UTC by Sara4994

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2021-01-04 12:15 UTC, jstastny-cz requested changes
I think the general approach should be different.

2021-01-04 12:15 UTC, jstastny-cz commented on ui-packages/packages/common/src/graphql/graphql.schema.json
> +            "name": "Travels",
Why are the domain-specific terms like Travels, Visa, etc mentioned in common package? The query should be generalized imo and the actual domain passed as argument.

2021-01-04 12:15 UTC, jstastny-cz commented on ui-packages/packages/common/src/graphql/graphql.schema.json
> +        "name": "Flight",
again, should not be here.

2021-01-04 12:15 UTC, jstastny-cz commented on ui-packages/packages/common/src/graphql/types.tsx
> +    TravelsAdded: Travels;
Should not be handled like this - Travels, Visa, Deals are domain-specific, whereas Job and UserTask are general entities. I think this is not correct approach to take.

2021-01-05 08:59 UTC, Sara4994 commented
@jstastny-cz yep that's my bad, corrected both the files. Thanks

2021-01-05 11:03 UTC, jstastny-cz commented
@Sara4994 seems to work fine in dev mode, but there's one snapshot test failure, please check.

2021-01-05 11:40 UTC, Sara4994 commented
jenkins retest this please

2021-01-07 07:26 UTC, AjayJagan approved these changes
:+1:

2021-01-12 09:33 UTC, Sara4994 commented
jenkins retest this please

2021-01-12 15:35 UTC, jstastny-cz approved these changes

2021-01-12 17:03 UTC, nmirasch approved these changes

2021-01-13 07:37 UTC, merged