KOGITO-4310 - JIT DMN accepts base64 encoded dmn models
apache/incubator-kie-kogito-apps pull request #617
Opened 2021-01-29 16:40 UTC by r00ta

JIRA: KOGITO-4310

JIRA: https://issues.redhat.com/browse/KOGITO-4310

This PR aims to accept base64 encoded DMN models on the jit endpoints.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2021-01-29 17:46 UTC, tarilabs approved these changes
thank you :+1

2021-01-31 09:59 UTC, tarilabs requested changes

2021-01-31 09:59 UTC, tarilabs commented on jitexecutor/jitexecutor-dmn/src/main/java/org/kie/kogito/jitexecutor/dmn/api/SchemaResource.java
> +        DMNModel dmnModel = modelFromXML(Base64Utils.decode(payload));
sorry for "changing my mind" but I noticed this only now.
Why do we need to base64 a normal REST payload of type `application/xml` ?

2021-01-31 09:59 UTC, tarilabs commented on jitexecutor/jitexecutor-dmn/src/main/java/org/kie/kogito/jitexecutor/dmn/utils/Base64Utils.java
> +    }
```suggestion
    }
    
    private Base64Utils() {
        // not allowed for util class.
    }
```

2021-01-31 09:59 UTC, tarilabs commented on jitexecutor/jitexecutor-dmn/src/main/java/org/kie/kogito/jitexecutor/dmn/utils/Base64Utils.java
> +    }
this should avoid SonarCloud complaints 👍

2021-02-01 08:17 UTC, r00ta commented on jitexecutor/jitexecutor-dmn/src/main/java/org/kie/kogito/jitexecutor/dmn/api/SchemaResource.java
> +        DMNModel dmnModel = modelFromXML(Base64Utils.decode(payload));
Thanks for the catch @tarilabs ! Fixed

2021-02-01 09:31 UTC, tarilabs commented on jitexecutor/jitexecutor-dmn/src/main/java/org/kie/kogito/jitexecutor/dmn/api/SchemaResource.java
> +        DMNModel dmnModel = modelFromXML(Base64Utils.decode(payload));
This was a REST endpoint taking XML.
Imho, it should still be a REST for XML input, JSON output.
REST is simple and I would keep it as it was previous this PR.

2021-02-01 09:56 UTC, r00ta commented on jitexecutor/jitexecutor-dmn/src/main/java/org/kie/kogito/jitexecutor/dmn/api/SchemaResource.java
> +        DMNModel dmnModel = modelFromXML(Base64Utils.decode(payload));
Ok, reverted

2021-02-01 15:20 UTC, r00ta commented
Not needed anymore as discussed on gchat

2021-02-01 15:20 UTC, closed without merging