KOGITO-1229 list redesign
apache/incubator-kie-kogito-apps pull request #72
Opened 2020-02-24 06:22 UTC by AjayJagan

- added icons to states

2020-02-24 11:39 UTC, cristianonicolai approved these changes

2020-02-24 12:18 UTC, Sara4994 approved these changes

2020-02-26 15:33 UTC, cristianonicolai commented on packages/management-console/server/MockData/types.js
> -    PENDING
The actual enum is upper case on Data Index, changing here will probably break the query, see https://github.com/kiegroup/kogito-apps/blob/master/data-index/data-index-service/src/main/resources/schema.graphqls#L73

2020-02-26 18:53 UTC, srambach commented on packages/management-console/server/MockData/types.js
> -    PENDING
I have CSS Magic... we can still display it as "Pending" even if it comes in as "PENDING" by using `text-transform: capitalize;` on that element when we put it into the list. 🧙‍♀️

2020-02-27 05:28 UTC, AjayJagan commented on packages/management-console/src/components/Molecules/DataToolbarComponent/Datatoolbar.css
> +}
Hey @srambach - I tried adding text-transform:capitalize , but it was still showing every letter in caps. So I did this work around. I am still trying to figure it out, if I am not successful ,please help me out :)

2020-03-02 21:56 UTC, srambach commented
@AjayJagan it's coming into a better shape :) @cristianonicolai 
- All status icons should be default (black) color except for completed (green) and error (red) as those are.
- Spacing of the Apply Filter button is off (I'll comment on the line to fix)
- The name linked to details beside the external icon linked to the endpoint application needs to be addressed. My comments are in the PR I made to your branch. Hopefully there is a name of the endpoint that we could use as text? If not, another option would be to move that to the kebab. But we need to know a little more about how it's used to say for sure - but the details link next to just the external link icon going to the endpoint cannot stay. :-)  https://github.com/AjayJagan/kogito-apps/pull/2

2020-03-02 21:59 UTC, srambach commented
OK, I guess it won't let me comment on the line - in DataToolbarComponent.tsx, you can remove the `variant="filter-group"` on line 134:
```
 <DataToolbarGroup variant="filter-group">
```
That's intended to remove the space between multiple filter dropdowns, but the button should be spaced normally.

2020-03-03 04:23 UTC, AjayJagan commented
> @AjayJagan it's coming into a better shape :) @cristianonicolai
> 
> * All status icons should be default (black) color except for completed (green) and error (red) as those are.
> * Spacing of the Apply Filter button is off (I'll comment on the line to fix)
> * The name linked to details beside the external icon linked to the endpoint application needs to be addressed. My comments are in the PR I made to your branch. Hopefully there is a name of the endpoint that we could use as text? If not, another option would be to move that to the kebab. But we need to know a little more about how it's used to say for sure - but the details link next to just the external link icon going to the endpoint cannot stay. :-)  [AjayJagan#2](https://github.com/AjayJagan/kogito-apps/pull/2)
I have removed the variant = filter groups and changed the color's of the status.
The only thing that's pending is the endpoint. @cristianonicolai  can you please tell us what should be done regarding that
![image](https://user-images.githubusercontent.com/36824134/75742769-a2d87a00-5d34-11ea-8a02-a914b8da03a4.png)

2020-03-05 13:54 UTC, srambach commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +              </DataListCell>,
How about using this to solve the problem of the external icon by itself? And then we also talked about only putting it on the parent, can you do that?
```
              <DataListCell key={1}>
                <Link to={'/ProcessInstances/' + processInstanceData.id} className="pf-u-mr-sm">
                    <strong>{processInstanceData.processName} </strong>
                </Link>
                <Link to={`${processInstanceData.endpoint}/management/processes/${processInstanceData.processId}/instances/${processInstanceData.id}`} target="_blank">
                  Endpoint <ExternalLinkAltIcon />
                </Link>
              </DataListCell>,
```
@AjayJagan @cristianonicolai

2020-03-06 03:22 UTC, AjayJagan commented on packages/management-console/src/components/Molecules/DataListItemComponent/DataListItemComponent.tsx
> +              </DataListCell>,
yep, displaying it only on the parent is possible. awaiting @cristianonicolai response.

2020-03-06 19:23 UTC, srambach approved these changes
I like the endpoint link. Can you make it go to a new tab? @AjayJagan  @cristianonicolai 
Otherwise, approved! Thanks.

2020-03-09 03:45 UTC, AjayJagan commented
> I like the endpoint link. Can you make it go to a new tab? @AjayJagan @cristianonicolai
> Otherwise, approved! Thanks.

Done :+1:

2020-03-11 06:02 UTC, cristianonicolai commented
@AjayJagan noticed a few things:

- Can you add a mock process with status complete so we can check the UI?
- @srambach  Should the popover close when we click elsewhere? Otherwise we endup with an overlay like in the screenshot below.
- Should buttons in the popover be aligned to the right side? Do we need a close button there?
![Selection_032](https://user-images.githubusercontent.com/570894/76386899-54208500-63b1-11ea-8867-2e86b05530c1.png)
- In the process details page, error state is not showing up
![Selection_033](https://user-images.githubusercontent.com/570894/76387040-afeb0e00-63b1-11ea-8701-f72a2ece87a8.png)

2020-03-11 06:08 UTC, cristianonicolai commented on packages/management-console/server/server.js
> -  '/management/processes/:processId/instances/:processInstanceId',
the endpoint was correct, method should be DELETE.

2020-03-11 06:08 UTC, cristianonicolai commented on packages/management-console/src/components/Organisms/ProcessDetails/ProcessDetails.tsx
> +      case 'ACTIVE':
would it help to use the TypseScript enum here?

2020-03-11 06:09 UTC, cristianonicolai requested changes
see previous comments

2020-03-12 09:30 UTC, AjayJagan commented on packages/management-console/server/server.js
> -  '/management/processes/:processId/instances/:processInstanceId',
This change is made in KOGITO 789

2020-03-12 12:21 UTC, cristianonicolai commented on packages/management-console/server/server.js
> -  '/management/processes/:processId/instances/:processInstanceId',
perhaps just revert the change here then.

2020-03-13 06:56 UTC, AjayJagan commented on packages/management-console/server/server.js
> -  '/management/processes/:processId/instances/:processInstanceId',
done :)

2020-03-14 02:07 UTC, cristianonicolai reviewed
@AjayJagan we also need to show the error popup on the process details page, when status is in error.

2020-03-14 02:07 UTC, cristianonicolai commented on packages/management-console/server/server.js
> -  '/management/processes/:processId/instances/:processInstanceId',
sorry but still showing _/abort_, I guess the idea was to just revert the change on this line.

2020-03-14 03:37 UTC, AjayJagan commented
> @AjayJagan we also need to show the error popup on the process details page, when status is in error.

@cristianonicolai  we were adding a view error along with the process management in process details page, So I thought we had to add the pop up instead of the view error. (because the pop contains Skip and Retry which are related to process management)

2020-03-15 13:48 UTC, cristianonicolai commented
@AjayJagan we can review the details page in another commit, just revert the change in the abort endpoint and we should be good ti go with this PR.

2020-03-16 01:38 UTC, cristianonicolai approved these changes

2020-03-16 01:39 UTC, merged