KOGITO-4969: Jobs panel and process diagram migration
apache/incubator-kie-kogito-apps pull request #792
Opened 2021-05-03 07:15 UTC by Sara4994

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-05-04 09:03 UTC, pefernan requested changes
Some changes to be done but great job!

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/apis/apis.tsx
> +// import React from 'react';
remove if not neded

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/channel/ProcessDetails/tests/ProcessDetailsGatewayApi.test.ts
> +  //   it('initialLoad', () => {
Do we need this??

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/management-console-webapp/src/channel/ProcessDetails/tests/ProcessDetailsQueries.test.ts
> + * Copyright 2021 Red Hat, Inc. and/or its affiliates.
double header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/JobActionsKebab/JobActionsKebab.tsx
> +import React, { useState } from 'react';
missing header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/JobActionsKebab/__mocks__/JobActionsKebab.tsx
> +import React from 'react';
missing header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/JobsPanel/JobsPanel.tsx
> +import React, { useState, useEffect } from 'react';
missing header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/JobsPanel/__mocks__/JobsPanel.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/JobsPanel/tests/JobsPanel.test.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/ProcessDetailsErrorModal/ProcessDetailsErrorModal.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/ProcessDetailsErrorModal/__mocks__/ProcessDetailsErrorModal.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/ProcessDetailsErrorModal/tests/ProcessDetailsErrorModal.test.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/ProcessDiagram/tests/ProcessDiagram.test.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/envelope/components/ProcessDiagram/ProcessDiagram.tsx
> +import React from 'react';
header

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-list/src/envelope/components/ProcessListTable/ProcessListTable.tsx
> +              <Link
Change link to a PF button

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/api/mocks/MockedProcessDetailsDriver.ts
> +/*
move this mocks folder inside a test to avoid issues on `mgmt-console-webapp`

2021-05-04 09:03 UTC, pefernan commented on ui-packages/packages/process-details/src/api/index.ts
> +export * from './mocks/MockedProcessDetailsDriver';
Since this are mocks for testing purposes I wouldn't export it here.

2021-05-04 19:40 UTC, closed without merging

2021-05-05 17:23 UTC, AjayJagan commented on ui-packages/packages/management-console-webapp/src/channel/ProcessList/ProcessListGatewayApi.ts
> +    // this.activeProcess = process;
maybe remove comment here