FAI-500: Duplicate counterfactual result id created for final result
apache/incubator-kie-kogito-apps pull request #887
Opened 2021-06-14 13:58 UTC by ruivieira

[FAI-500](https://issues.redhat.com/browse/FAI-500):

The final result from the CF search was sharing the same `id` with the last intermediate result. Since the `id` is used for other logic (such as storage key) this can cause errors.
The final result now has a freshly generated unique `id` to avoid this conflict.
Relevant unit test added to check last intermediate result has a different `id` than final result.

> Many thanks for submitting your Pull Request :heart:! 
> 
> Please make sure that your PR meets the following requirements:
> 
> - [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
> - [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
> - [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
> - [x] Pull Request contains link to the JIRA issue
> - [x] Pull Request contains link to any dependent or related Pull Request
> - [x] Pull Request contains description of the issue
> - [x] Pull Request does not include fixes for issues other than the main ticket
> 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-06-17 22:53 UTC, ruivieira commented
Jenkins retest this please

2021-06-21 09:53 UTC, manstis commented
@ruivieira Is this ready to be converted to a _real_ PR?

2021-06-22 07:43 UTC, manstis approved these changes
One minor comment; otherwise LGTM.

2021-06-22 07:43 UTC, manstis commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals(executionIds.get(0), executionId);
IDK if it's worth also asserting that `executionIds.size() == 1` since the related assertions depend on there being only one entry (and there should only be one entry, but you're using a `List` so knowing there _is_ only one entry requires an understanding of the implementation of the `CounterfactualExplainer`).

2021-06-22 07:49 UTC, r00ta requested changes

2021-06-22 07:49 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
Actually this is not checking that the `executionsIds` list does not contain any duplicate, is it? 

Consider 
```java
List<Integer> list = List.of(1, 1, 1);
List<Integer> distinctInts = list.stream().distinct().collect(Collectors.toList());
```
then `distinctInts = [1]`.

2021-06-22 07:50 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
Yes, good catch! It should clearly be `assertEquals((int) executionIds.stream().distinct().count(), executionIds.size())`.

2021-06-22 07:53 UTC, manstis commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
`[1,2]` would pass that check too.

2021-06-22 07:54 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals(executionIds.get(0), executionId);
Good point. It should _at least_ have one element (in order to have a "last" intermediate).

2021-06-22 07:57 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
@manstis That would be OK for checking all intermediate `id`s are different, no? I think the problem is that the goal of the test could be clearer :)

2021-06-22 08:02 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals(executionIds.get(0), executionId);
Wrong comment, apologies. I thought this comment was referring to the intermediated `id`s. I will add the above check, thanks!

2021-06-22 08:05 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
I wrongly thought the above comment was about the intermediate `id`s, apologies.
Given it is about the `executionIds`, the expectation is that they would all be the same for all intermediate results, is that correct @manstis, @r00ta?

2021-06-22 08:38 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals(executionIds.get(0), executionId);
As per the discussion offline I'll add the check on the `executionIds` size, thanks.

2021-06-22 08:39 UTC, ruivieira commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
Hi @r00ta, thanks for the comment. The goal is to test the opposite actually, that all `executionIds` are the same.

2021-06-22 08:51 UTC, r00ta commented on explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java
> +        assertEquals((int) executionIds.stream().distinct().count(), 1);
Super, thanks @ruivieira

2021-06-22 08:51 UTC, r00ta approved these changes

2021-06-22 09:43 UTC, danielezonca approved these changes

2021-06-23 12:57 UTC, ruivieira commented
Jenkins retest this please

2021-06-24 10:35 UTC, ruivieira commented
Jenkins retest this please

2021-06-24 11:33 UTC, jiripetrlik approved these changes
LGTM

2021-06-24 13:36 UTC, ruivieira commented
Jenkins retest this please

2021-06-25 09:06 UTC, manstis commented
SonarCloud is complaining about test coverage of a line that has had parenthesis removed (due to a code smell).

Merging.

2021-06-25 09:06 UTC, merged