KOGITO-5410 Disable Failing Native Image tests on kogito-apps
apache/incubator-kie-kogito-apps pull request #903
Opened 2021-06-24 08:49 UTC by evacchi

2021-06-24 08:55 UTC, evacchi commented
jenkins run native

2021-06-24 09:28 UTC, tarilabs reviewed
I'm not sure this are "randomic failures" hence if this is a good idea to disable it, as it might be a symptom some NI generation is actually breaking?

2021-06-24 09:47 UTC, danielezonca commented
I agree that it looks strange to disable all of them, @evacchi is it a regression introduced by quarkus 2.0 update?

2021-06-24 12:01 UTC, evacchi commented
@danielezonca @tarilabs it's been broken on master for a while; I only discovered it recently as I was running the native build on this PR https://github.com/kiegroup/kogito-runtimes/pull/1277 and it seemed an unrelated failure. I am disabling them because as they are they are only masking other possible issues. We can disable the native build entirely if that is what you mean. I have created tickets for tracking the issue in follow ups.

I can only assume it's been broken for a while https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/kogito/job/nightly/job/master/job/kogito-native/

unfortunately there were other broken native tests on runtimes that probably masked it on apps see https://github.com/kiegroup/kogito-runtimes/pull/1379

2021-06-24 12:48 UTC, tarilabs commented
This https://github.com/kiegroup/kogito-apps/pull/907 should fix Native test for the JIT Runner.
Thanks for reporting.

2021-06-28 08:39 UTC, tarilabs requested changes
ref https://github.com/kiegroup/kogito-apps/commit/8f0f6e7eeb7e52025b47e5074dbb2e45731973db

2021-06-28 08:39 UTC, tarilabs commented on jitexecutor/jitexecutor-runner/src/test/java/org/kie/kogito/jitexecutor/runner/NativeJITDMNResourceIT.java
> +@Disabled("KOGITO-5409 JIT Executor Native Image tests fail")
```suggestion
```

2021-06-28 08:39 UTC, tarilabs commented on jitexecutor/jitexecutor-runner/src/test/java/org/kie/kogito/jitexecutor/runner/NativeOneOfEachTypeIT.java
> +@Disabled("KOGITO-5409 JIT Executor Native Image tests fail")
```suggestion
```

2021-06-28 08:39 UTC, tarilabs commented on jitexecutor/jitexecutor-runner/src/test/java/org/kie/kogito/jitexecutor/runner/NativeSchemaResourceIT.java
> +@Disabled("KOGITO-5409 JIT Executor Native Image tests fail")
```suggestion
```

2021-06-28 08:39 UTC, tarilabs commented on jitexecutor/jitexecutor-runner/src/test/java/org/kie/kogito/jitexecutor/runner/NativeValidatorResourceIT.java
> +@Disabled("KOGITO-5409 JIT Executor Native Image tests fail")
```suggestion
```

2021-06-30 14:43 UTC, evacchi commented
@tiagodolphine this disables the test -- if that's ok I can merge it, unless you want to take a look already

2021-07-05 11:14 UTC, tiagodolphine approved these changes
It's fine for me, TBF I'm not even sure we need native build for job-service, if that's the case we could remove the native tests.

2021-07-08 06:49 UTC, evacchi commented
jenkins run native

2021-07-08 06:49 UTC, evacchi commented
Jenkins retest this

2021-08-02 07:41 UTC, evacchi commented
Jenkins retest this

2021-08-02 07:42 UTC, evacchi commented
jenkins run nativex

2021-08-09 12:04 UTC, evacchi commented
jenkins run native

2021-08-09 13:43 UTC, evacchi commented
Jenkins retest this

2021-08-12 09:36 UTC, evacchi commented
there are some further native tests breaking now, needs further investigation?

2021-09-18 05:44 UTC, closed without merging