KOGITO-5541 Quarkus DEV UI: Form Service
apache/incubator-kie-kogito-apps pull request #972
Opened 2021-08-02 13:16 UTC by bxf12315

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-08-03 17:51 UTC, paulovmr requested changes
@bxf12315 Looking good, made two small comments, and would it be possible to add some tests? Specially for the storage. Thanks!

2021-08-03 17:51 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/FormsService.java
> +    public Response UpdateFormContent(@PathParam("formName") String formName, String formContent) {
```suggestion
    public Response updateFormContent(@PathParam("formName") String formName, String formContent) {
```

2021-08-03 17:51 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/model/FormConfiguration.java
> +    private static String RECOURCES_KEY = "resources";
```suggestion
    private static String RESOURCES_KEY = "resources";
```

2021-08-03 17:53 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/impl/FormsStorageImpl.java
> +        return null;
Why is this returning null?

2021-08-03 17:57 UTC, paulovmr requested changes

2021-08-03 17:57 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/FormsService.java
> +            return Response.ok(storage.getFormContent(formName).toString()).build();
Probably good to apply some regex filter in the `formName` to avoid path traversal.

2021-08-03 17:57 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/FormsService.java
> +            storage.updateFormContent(formContent, formName);
Probably good to apply some regex filter in the `formName` to avoid path traversal.

2021-08-05 03:18 UTC, bxf12315 commented
@paulovmr updated

2021-08-05 09:35 UTC, bxf12315 commented
Jenkins retest this

2021-08-10 03:04 UTC, bxf12315 commented
Jenkins retest this

2021-08-10 06:48 UTC, bxf12315 commented
Jenkins retest this

2021-08-11 19:35 UTC, paulovmr requested changes

2021-08-11 19:35 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/FormsService.java
> +            System.out.println("getFormContent getFormContent getFormContent getFormContent : " + formName);
```suggestion

```

2021-08-11 19:35 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/impl/FormsStorageImpl.java
> +        LOGGER.info("form's files path is {0}", formsFolder.toString());
THis is causing a `NullPointerException` when the `formsFolder` is `null`.

2021-08-11 19:35 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/FormsService.java
> +        } catch (Exception e) {
Could you add a catch for `FileNotFoundException` and return `404` please?

2021-08-11 19:35 UTC, paulovmr commented on runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension/src/main/java/org/kie/kogito/runtime/tools/quarkus/extension/runtime/forms/impl/FormsStorageImpl.java
> +            formInfoMap.put(FilenameUtils.removeExtension(file.getName()),
Maybe better to only add the form to the list if the config file exists, otherwise it could appear in the list but not be acessible.

2021-08-12 08:59 UTC, bxf12315 commented
@paulovmr updated

2021-08-16 12:55 UTC, paulovmr approved these changes

2021-08-16 14:21 UTC, paulovmr commented
Jenkins retest this

2021-08-17 05:45 UTC, AjayJagan commented
Jenkins retest this

2021-08-17 09:48 UTC, AjayJagan commented
Jenkins retest this

2021-08-17 12:19 UTC, paulovmr commented
Jenkins retest this

2021-08-18 04:50 UTC, AjayJagan commented
jenkins please retest this

2021-08-18 04:50 UTC, AjayJagan commented
jenkins retest apps

2021-08-19 13:25 UTC, merged